import Theorems.Thm_StickyKakeya4_native_compatible_plane_variation
import Theorems.Thm_StickyKakeya4_native_actual_projected_grain_count

set_option autoImplicit false
#print axioms NativeActualProjectedGrainCount.actual_node_grain_count
#print axioms NativeActualProjectedGrainCount.actual_projection_minimum_lower
#print axioms NativeActualProjectedGrainCount.cap_mul_raw_vertices_le
#print axioms NativeActualProjectedGrainCount.grainWidth
#print axioms NativeActualProjectedGrainCount.grainWidth_pos
#print axioms NativeActualProjectedGrainCount.predecessorProduct
#print axioms NativeActualProjectedGrainCount.projectionLabel
#print axioms NativeActualProjectedGrainCount.restricted_node_grain_count
#print axioms NativeActualProjectedGrainCount.taggedLabel
#print axioms NativeActualProjectedGrainCount.tagged_same_label_near
#print axioms NativeActualProjectedGrainCount.transverseCost
#print axioms NativeActualProjectedGrainCount.transverseCost_pos
#print axioms NativeCompatiblePlaneVariation.compatible_installed_span_variation
#print axioms NativeCompatiblePlaneVariation.installed_word_coarsens
#print axioms NativeCompatiblePlaneVariation.matching_word_span_variation
