import Theorems.Thm_StickyKakeya4_native_grain_height_projection_direct

#print axioms NativeGrainHeightProjectionDirect.coordinates_norm
#print axioms NativeGrainHeightProjectionDirect.infDist_sub_smul_le
#print axioms NativeGrainHeightProjectionDirect.physical_difference_decomposition
#print axioms NativeGrainHeightProjectionDirect.unchanged_quotient_difference
#print axioms NativeGrainHeightProjectionDirect.raw_mesh_times_ancestor
#print axioms NativeGrainHeightProjectionDirect.ancestor_height_gap
#print axioms NativeGrainHeightProjectionDirect.mixed_vertex_ancestor
