import Theorems.Thm_StickyKakeya4_native_common_direction_phase_geometry
import Theorems.Thm_StickyKakeya4_native_common_direction_phase_menu
import Theorems.Thm_StickyKakeya4_native_generic_query_rank
import Theorems.Thm_StickyKakeya4_native_generic_reference_data
import Theorems.Thm_StickyKakeya4_native_generic_reference_queries
import Theorems.Thm_StickyKakeya4_native_generic_reference_rank
import Theorems.Thm_StickyKakeya4_native_generic_reference_second_stage
import Theorems.Thm_StickyKakeya4_native_generic_squared_grain_selection
import Theorems.Thm_StickyKakeya4_native_source_third_XY_bundle
import Theorems.Thm_StickyKakeya4_native_third_XY_construction
import Theorems.Thm_StickyKakeya4_native_third_XY_source_data

set_option autoImplicit false
#print axioms NativeCommonDirectionPhaseGeometry.front_equation
#print axioms NativeCommonDirectionPhaseGeometry.original_intercept_difference
#print axioms NativeCommonDirectionPhaseGeometry.physical_cell_gap
#print axioms NativeCommonDirectionPhaseGeometry.physical_height_bound
#print axioms NativeCommonDirectionPhaseGeometry.physical_intercept_spread
#print axioms NativeCommonDirectionPhaseGeometry.scalar_intercept_spread
#print axioms NativeCommonDirectionPhaseGeometry.source_front_error
#print axioms NativeCommonDirectionPhaseMenu.dyadic_phase_cap
#print axioms NativeCommonDirectionPhaseMenu.dyadic_sigma
#print axioms NativeCommonDirectionPhaseMenu.dyadic_source_error
#print axioms NativeCommonDirectionPhaseMenu.full_R_representative_readback
#print axioms NativeCommonDirectionPhaseMenu.original_parent_mem_menu
#print axioms NativeCommonDirectionPhaseMenu.original_phase_cap
#print axioms NativeCommonDirectionPhaseMenu.phaseMenu
#print axioms NativeCommonDirectionPhaseMenu.phaseMenu_card
#print axioms NativeCommonDirectionPhaseMenu.same_angle_original_slope
#print axioms NativeGenericQueryRank.HasQueriedRankSelection
#print axioms NativeGenericQueryRank.exists_query_depth_cutoff
#print axioms NativeGenericReferenceData.factor_pos
#print axioms NativeGenericReferenceData.global_near
#print axioms NativeGenericReferenceQueries.HasQuerySecondStageCore
#print axioms NativeGenericReferenceQueries.decode_second_stage_queries
#print axioms NativeGenericReferenceRank.HasRankSelection
#print axioms NativeGenericReferenceRank.exists_rank_selection_cutoff
#print axioms NativeGenericReferenceSecondStage.HasRetainedRankSelection
#print axioms NativeGenericReferenceSecondStage.HasSecondStageCore
#print axioms NativeGenericReferenceSecondStage.exists_second_stage_cutoff
#print axioms NativeGenericSquaredGrainSelection.select_squared_grain_second_stage
#print axioms NativeSourceThirdXYBundle.exists_source_third_XY_bundle
#print axioms NativeThirdXYConstruction.construct_third_XY_data
#print axioms NativeThirdXYSourceData.HasThirdXYSourceData
