import Theorems.Thm_StickyKakeya4_native_actual_tuple_plane_transfer
import Theorems.Thm_StickyKakeya4_native_iterated_projection_grains
import Theorems.Thm_StickyKakeya4_native_quantized_projection_grains
import Theorems.Thm_StickyKakeya4_native_span_coefficient_power
import Theorems.Thm_StickyKakeya4_native_squared_grain_queries

set_option autoImplicit false
#print axioms NativeActualTuplePlaneTransfer.actual_chain_plane_transfer
#print axioms NativeActualTuplePlaneTransfer.chain_span_finrank
#print axioms NativeActualTuplePlaneTransfer.exists_global_plane_representatives
#print axioms NativeIteratedProjectionGrains.iterated_grain_count
#print axioms NativeIteratedProjectionGrains.minimumFiber_attained
#print axioms NativeIteratedProjectionGrains.native_chain_grain_count
#print axioms NativeQuantizedProjectionGrains.grain_count_computed
#print axioms NativeQuantizedProjectionGrains.grain_count_mul
#print axioms NativeQuantizedProjectionGrains.infDist_le_normal_norm
#print axioms NativeQuantizedProjectionGrains.label
#print axioms NativeQuantizedProjectionGrains.label_mem_box_of_near
#print axioms NativeQuantizedProjectionGrains.minimumFiber
#print axioms NativeQuantizedProjectionGrains.normal
#print axioms NativeQuantizedProjectionGrains.normal_norm_le_of_near
#print axioms NativeQuantizedProjectionGrains.representative
#print axioms NativeQuantizedProjectionGrains.representative_label
#print axioms NativeQuantizedProjectionGrains.representative_mem
#print axioms NativeQuantizedProjectionGrains.representatives_cover
#print axioms NativeQuantizedProjectionGrains.same_label_near
#print axioms NativeQuantizedProjectionGrains.vertexLabel
#print axioms NativeSpanCoefficientPower.coefficientCost_le_power
#print axioms NativeSquaredGrainQueries.pairedQueries
#print axioms NativeSquaredGrainQueries.pairedQueries_short
#print axioms NativeSquaredGrainQueries.pairedQueries_uniformities
#print axioms NativeSquaredGrainQueries.pairedQueries_valid
#print axioms NativeSquaredGrainQueries.pairedQueries_vertex
#print axioms NativeSquaredGrainQueries.paired_query_count
#print axioms NativeSquaredGrainQueries.phaseDepth
#print axioms NativeSquaredGrainQueries.phaseDepth_bounds
#print axioms NativeSquaredGrainQueries.phase_inverse_le_square
#print axioms NativeSquaredGrainQueries.short_fine_scale_ratio
#print axioms NativeSquaredGrainQueries.squared_scale_identity
#print axioms NativeSquaredGrainQueries.stopping_depth_cap
