import Theorems.Thm_StickyKakeya4_native_retained_fine_pair_density
import Theorems.Thm_StickyKakeya4_native_spatial_parent_count
import Theorems.Thm_StickyKakeya4_native_parent_grain_incidence_cleanup

set_option autoImplicit false
#print axioms NativeParentGrainIncidenceCleanup.cutEdges
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_card
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_grain_image
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_points
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_subset
#print axioms NativeParentGrainIncidenceCleanup.exists_cleaned_parent
#print axioms NativeParentGrainIncidenceCleanup.exists_mixed_dense_core
#print axioms NativeParentGrainIncidenceCleanup.mixedFiber
#print axioms NativeParentGrainIncidenceCleanup.mixedLabel
#print axioms NativeParentGrainIncidenceCleanup.mixedVertices
#print axioms NativeParentGrainIncidenceCleanup.mixed_fiber_geometry
#print axioms NativeParentGrainIncidenceCleanup.mixed_fiber_vertex_cap
#print axioms NativeParentGrainIncidenceCleanup.mixed_label_count
#print axioms NativeParentGrainIncidenceCleanup.parent_mixed_fiber_eq
#print axioms NativeRetainedFinePairDensity.density_cross
#print axioms NativeRetainedFinePairDensity.finePairCount
#print axioms NativeRetainedFinePairDensity.full_mass_eq_pair_count
#print axioms NativeRetainedFinePairDensity.pairDensityConstant
#print axioms NativeRetainedFinePairDensity.pairDensityConstant_pos
#print axioms NativeRetainedFinePairDensity.source_fine_pair_density
#print axioms NativeSpatialParentCount.fine_pair_count_in_raw_cell
#print axioms NativeSpatialParentCount.parent_count_le_pair_count
#print axioms NativeSpatialParentCount.raw_point_count_le_one
#print axioms NativeSpatialParentCount.source_global_subset_upper
#print axioms NativeSpatialParentCount.source_spatial_parent_count
