import Theorems.Thm_StickyKakeya4_native_raw_point_global_profiles

#print axioms NativeRawPointGlobalProfiles.global_shadow_multiplicity_upper
#print axioms NativeRawPointGlobalProfiles.global_shadow_multiplicity_lower
#print axioms NativeRawPointGlobalProfiles.global_shadow_bounds_of_conditional
#print axioms NativeRawPointGlobalProfiles.original_shading_mass_lower
#print axioms NativeRawPointGlobalProfiles.all_depth_raw_point_profile
#print axioms NativeRawPointGlobalProfiles.raw_point_count_mono
#print axioms NativeRawPointGlobalProfiles.retained_raw_point_lower
#print axioms NativeRawPointGlobalProfiles.source_hereditary_conditional_upper
