import Theorems.Thm_StickyKakeya4_native_finite_point_coherence
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_incidence
import Theorems.Thm_StickyKakeya4_native_saturated_point_angular_lower
import Theorems.Thm_StickyKakeya4_native_sharp_X_cap_cancellation
import Theorems.Thm_StickyKakeya4_native_sharp_reference_angular_upper

set_option autoImplicit false
#print axioms NativeFinitePointCoherence.cell_offset_image
#print axioms NativeFinitePointCoherence.lift
#print axioms NativeFinitePointCoherence.lift_card
#print axioms NativeFinitePointCoherence.lift_fiber
#print axioms NativeFinitePointCoherence.pointWeight
#print axioms NativeFinitePointCoherence.select_original_point_fibers
#print axioms NativeFinitePointCoherence.support_mass
#print axioms NativeFinitePointCoherence.weighted_finite_selection
#print axioms NativeReferenceXYGridIncidence.dyadic_original_edge_rawPoint
#print axioms NativeReferenceXYGridIncidence.frame
#print axioms NativeReferenceXYGridIncidence.frame_dist_le
#print axioms NativeReferenceXYGridIncidence.frame_infDist_le
#print axioms NativeReferenceXYGridIncidence.frame_injective
#print axioms NativeReferenceXYGridIncidence.frame_line_formula
#print axioms NativeReferenceXYGridIncidence.framed_retained_original_incidence
#print axioms NativeReferenceXYGridIncidence.original_edge_rawPoint
#print axioms NativeReferenceXYGridIncidence.original_edge_rawPoint_three_rho
#print axioms NativeReferenceXYGridIncidence.point_quotient_reconstruction
#print axioms NativeReferenceXYGridIncidence.retained_original_rawPoint_incidence
#print axioms NativeSaturatedPointAngularLower.saturated_multiplicity_lower
#print axioms NativeSaturatedPointAngularLower.saturated_reference_point_angular_lower
#print axioms NativeSaturatedPointAngularLower.saturated_refined_multiplicity_lower
#print axioms NativeSharpReferenceAngularUpper.angular_menu_mono
#print axioms NativeSharpReferenceAngularUpper.exists_actual_reference_angular_upper
#print axioms NativeSharpReferenceAngularUpper.reference_population
#print axioms NativeSharpXCapCancellation.cross_cap_cancellation
