import Theorems.Thm_StickyKakeya4_native_original_point_saturation
import Theorems.Thm_StickyKakeya4_native_post_graph_slice_forget
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_native
import Theorems.Thm_StickyKakeya4_native_saturated_mixed_grain_core

set_option autoImplicit false
#print axioms NativeOriginalPointSaturation.Saturated
#print axioms NativeOriginalPointSaturation.nodeCut_saturation
#print axioms NativeOriginalPointSaturation.original_fiber_eq
#print axioms NativeOriginalPointSaturation.point_uniformity
#print axioms NativeOriginalPointSaturation.quotient_saturation
#print axioms NativeOriginalPointSaturation.same_point_mixed
#print axioms NativeOriginalPointSaturation.saturated_filter
#print axioms NativeOriginalPointSaturation.saturated_graph_quotient_heights
#print axioms NativeOriginalPointSaturation.saturated_selected
#print axioms NativeOriginalPointSaturation.translated_heights_saturation
#print axioms NativePostGraphSliceForget.curve_cleanup_forget
#print axioms NativePostGraphSliceForget.curve_retained_forget
#print axioms NativePostGraphSliceForget.curve_stage_forget
#print axioms NativePostGraphSliceForget.height_core_with_forget
#print axioms NativePostGraphSliceForget.profiles_forget
#print axioms NativeRetainedSliceBudgetNative.exists_actual_native_retained_budget
#print axioms NativeSaturatedMixedGrainCore.HasMixedSaturation
#print axioms NativeSaturatedMixedGrainCore.HasPointSaturation
#print axioms NativeSaturatedMixedGrainCore.SaturatedMaps
#print axioms NativeSaturatedMixedGrainCore.exists_automatic_saturated_core
#print axioms NativeSaturatedMixedGrainCore.exists_saturated_mixed_dense_core
#print axioms NativeSaturatedMixedGrainCore.exists_simultaneous_saturated_core
#print axioms NativeSaturatedMixedGrainCore.source_saturated_mixed_grain_core
