import Theorems.Thm_StickyKakeya4_native_fixed_source_reference
set_option autoImplicit false
#print axioms NativeFixedSourceReference.fixed_balanced_configuration
#print axioms NativeFixedSourceReference.fixed_two_scale_configuration
#print axioms NativeFixedSourceReference.fixed_middle_two_scale_extra_configuration
#print axioms NativeFixedSourceReference.fixed_all_two_scale_extra_configuration
#print axioms NativeFixedSourceReference.exists_fixed_source_reference
#print axioms NativeFixedSourceReference.union_pos_of_shading_lower
#print axioms NativeFixedSourceReference.native_near_of_volume_bounds
#print axioms NativeFixedSourceReference.exists_reference_from_volume_bounds
