import Theorems.Thm_StickyKakeya4_native_prescribed_parent_menu_configuration

#print axioms NativePrescribedParentMenuConfiguration.HasPrescribedHorizontalStage
#print axioms NativePrescribedParentMenuConfiguration.callerRelations
#print axioms NativePrescribedParentMenuConfiguration.prescribed_stage_with_horizontal_menu
#print axioms NativePrescribedParentMenuConfiguration.exists_prescribed_parent_menu_configuration
#print axioms NativePrescribedParentMenuConfiguration.prescribed_horizontal_stage_forget
