import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_selection

#print axioms NativeWeightedGrainQuotientSelection.grain
#print axioms NativeWeightedGrainQuotientSelection.chosen
#print axioms NativeWeightedGrainQuotientSelection.selected
#print axioms NativeWeightedGrainQuotientSelection.chosen_spec
#print axioms NativeWeightedGrainQuotientSelection.selected_subset
#print axioms NativeWeightedGrainQuotientSelection.selected_grain
#print axioms NativeWeightedGrainQuotientSelection.selected_grain_nonempty
#print axioms NativeWeightedGrainQuotientSelection.selected_grain_image
#print axioms NativeWeightedGrainQuotientSelection.local_mass_retention
#print axioms NativeWeightedGrainQuotientSelection.mass_retention
#print axioms NativeWeightedGrainQuotientSelection.card_retention_ceil
#print axioms NativeWeightedGrainQuotientSelection.local_card_retention
