import Theorems.Thm_StickyKakeya4_native_actual_offset_menu
import Theorems.Thm_StickyKakeya4_native_post_graph_slice_stage
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_source

set_option autoImplicit false
#print axioms NativeActualOffsetMenu.actual_offset_count
#print axioms NativeActualOffsetMenu.angular_cell_local_difference
#print axioms NativePostGraphSliceStage.HasPostGraphRetainedHistory
#print axioms NativePostGraphSliceStage.HasPostGraphStage
#print axioms NativePostGraphSliceStage.PostGraphCleanupData
#print axioms NativePostGraphSliceStage.stage_with_post_graph_slice
#print axioms NativeRetainedSliceBudgetSource.actualRetainedConstant
#print axioms NativeRetainedSliceBudgetSource.actualRetainedConstant_le
#print axioms NativeRetainedSliceBudgetSource.actual_quotient_test
#print axioms NativeRetainedSliceBudgetSource.quotientTolerance
#print axioms NativeRetainedSliceBudgetSource.quotientTolerance_bounds
