import Theorems.Thm_StickyKakeya4_native_parent_direction_difference
import Theorems.Thm_StickyKakeya4_native_halo_count_transfer

set_option autoImplicit false
#print axioms NativeHaloCountTransfer.multiplicity_transfer
#print axioms NativeHaloCountTransfer.relation_card_mul_le
#print axioms NativeHaloCountTransfer.rows_card_mul_le_of_menu
#print axioms NativeParentDirectionDifference.difference_near_submodule
#print axioms NativeParentDirectionDifference.incident_difference_near_horizontal
#print axioms NativeParentDirectionDifference.parent_normalized_horizontal_difference
#print axioms NativeParentDirectionDifference.subspace_infDist_smul
