import Theorems.Thm_StickyKakeya4_native_fine_weighted_coarse_core
import Theorems.Thm_StickyKakeya4_native_fine_weighted_coarse_cutoff
import Theorems.Thm_StickyKakeya4_native_mass_reference_coarse_selection
set_option autoImplicit false
#print axioms NativeFineWeightedCoarseCore.fineCapacity
#print axioms NativeFineWeightedCoarseCore.colorCost
#print axioms NativeFineWeightedCoarseCore.pruneCost
#print axioms NativeFineWeightedCoarseCore.fineCapacity_pos
#print axioms NativeFineWeightedCoarseCore.colorCost_pos
#print axioms NativeFineWeightedCoarseCore.pruneCost_pos
#print axioms NativeFineWeightedCoarseCore.color_weight_retention
#print axioms NativeFineWeightedCoarseCore.pruned_weight_retention
#print axioms NativeFineWeightedCoarseCore.normalized_pruning_charge
#print axioms NativeFineWeightedCoarseCore.same_Q_selection
#print axioms NativeFineWeightedCoarseCore.actual_shading_from_fine_weights
#print axioms NativeFineWeightedCoarseCore.same_Q_native_input
#print axioms NativeFineWeightedCoarseCutoff.exists_uniform_cutoff
#print axioms NativeFineWeightedCoarseCutoff.effective_power
#print axioms NativeFineWeightedCoarseCutoff.exists_effective_cutoff
#print axioms NativeFineWeightedCoarseCutoff.two_output_power_readback
#print axioms NativeFineWeightedCoarseCutoff.two_output_lower_bounds
#print axioms NativeFineWeightedCoarseCutoff.ordered_two_output_parameters
#print axioms NativeFineWeightedCoarseCutoff.exists_two_output_cutoff
#print axioms NativeMassReferenceCoarseSelection.same_reference_coarse_selection_of_mass
