import Theorems.Thm_StickyKakeya4_native_incident_affine_anchor_geometry

#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_sub
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_mem_heightKernel
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_norm
#print axioms NativeIncidentAffineAnchorGeometry.normalCoordinates
#print axioms NativeIncidentAffineAnchorGeometry.coordinates_normal_sub_matrix
#print axioms NativeIncidentAffineAnchorGeometry.coordinates_norm_le
#print axioms NativeIncidentAffineAnchorGeometry.anchorTube
#print axioms NativeIncidentAffineAnchorGeometry.anchorTube_mem
#print axioms NativeIncidentAffineAnchorGeometry.exists_incident_affine_anchors
