import Theorems.Thm_StickyKakeya4_native_compatible_weighted_retention
import Theorems.Thm_StickyKakeya4_native_tagged_packet_fiber_iteration

set_option autoImplicit false
#print axioms NativeCompatibleWeightedRetention.RetainedFamily
#print axioms NativeCompatibleWeightedRetention.cancel_terminal_scale
#print axioms NativeCompatibleWeightedRetention.combinedLoss
#print axioms NativeCompatibleWeightedRetention.combinedLoss_budget
#print axioms NativeCompatibleWeightedRetention.delta_loss_lower
#print axioms NativeCompatibleWeightedRetention.denominator_power
#print axioms NativeCompatibleWeightedRetention.exact_retention_from_numerator
#print axioms NativeCompatibleWeightedRetention.exists_rank_retention_cutoff
#print axioms NativeCompatibleWeightedRetention.exists_uniform_weak_retention
#print axioms NativeCompatibleWeightedRetention.from_master_and_actual_cost
#print axioms NativeCompatibleWeightedRetention.menuCost
#print axioms NativeCompatibleWeightedRetention.menuCost_pos
#print axioms NativeCompatibleWeightedRetention.retainedFamily_mono
#print axioms NativeCompatibleWeightedRetention.retainedFraction
#print axioms NativeCompatibleWeightedRetention.retainedFraction_closed_form
#print axioms NativeTaggedPacketFiberIteration.actual_chain_lower_bound
#print axioms NativeTaggedPacketFiberIteration.fixed_node_cap
#print axioms NativeTaggedPacketFiberIteration.layers
#print axioms NativeTaggedPacketFiberIteration.layers_antitone
#print axioms NativeTaggedPacketFiberIteration.nodeVertices
#print axioms NativeTaggedPacketFiberIteration.nodeVertices_mono
#print axioms NativeTaggedPacketFiberIteration.node_minimum_lower
#print axioms NativeTaggedPacketFiberIteration.node_vertex_predecessors
#print axioms NativeTaggedPacketFiberIteration.packet_predecessor_geometry
#print axioms NativeTaggedPacketFiberIteration.step_vertex_count
