import Theorems.Thm_StickyKakeya4_native_source_parent_grain_cleanup
import Theorems.Thm_StickyKakeya4_native_middle_grain_parent_budget
import Theorems.Thm_StickyKakeya4_native_scheduled_pair_parent_transfer
import Theorems.Thm_StickyKakeya4_native_uniform_retention_transfer

set_option autoImplicit false
#print axioms NativeMiddleGrainParentBudget.absorb_error_constant
#print axioms NativeMiddleGrainParentBudget.actual_middle_error
#print axioms NativeMiddleGrainParentBudget.actual_middle_parent_direction
#print axioms NativeMiddleGrainParentBudget.actual_test_radius_lower
#print axioms NativeMiddleGrainParentBudget.coefficient_power_bound
#print axioms NativeMiddleGrainParentBudget.errorConstant
#print axioms NativeMiddleGrainParentBudget.exists_uniform_cutoff
#print axioms NativeMiddleGrainParentBudget.grainDepth_middle
#print axioms NativeMiddleGrainParentBudget.middleDepth
#print axioms NativeMiddleGrainParentBudget.middleIndex
#print axioms NativeMiddleGrainParentBudget.middle_depth_bounds
#print axioms NativeMiddleGrainParentBudget.middle_query_readback
#print axioms NativeMiddleGrainParentBudget.middle_scale_bounds
#print axioms NativeMiddleGrainParentBudget.middle_scale_root_bound
#print axioms NativeMiddleGrainParentBudget.normalizedError
#print axioms NativeMiddleGrainParentBudget.normalized_error_le_scale
#print axioms NativeMiddleGrainParentBudget.normalized_error_power
#print axioms NativeMiddleGrainParentBudget.parent_direction_from_error
#print axioms NativeScheduledPairParentTransfer.coarse_pair_over_fine_card_le
#print axioms NativeScheduledPairParentTransfer.diagonal_pair_fiber_eq
#print axioms NativeScheduledPairParentTransfer.diagonal_pair_uniformity
#print axioms NativeScheduledPairParentTransfer.diagonal_parent_uniformity
#print axioms NativeScheduledPairParentTransfer.fine_pair_determines_parent
#print axioms NativeScheduledPairParentTransfer.parent_fine_pair_fiber_eq
#print axioms NativeScheduledPairParentTransfer.parent_fine_pair_uniformity
#print axioms NativeSourceParentGrainCleanup.cancel_depth_and_taxes
#print axioms NativeSourceParentGrainCleanup.density_cap_cancellation
#print axioms NativeSourceParentGrainCleanup.mixed_vertex_cross
#print axioms NativeSourceParentGrainCleanup.parentGrainConstant
#print axioms NativeSourceParentGrainCleanup.source_parent_grain_cleanup
#print axioms NativeUniformRetentionTransfer.finite_menu_retention_cross
#print axioms NativeUniformRetentionTransfer.image_card_le_mul_of_fiber_images
#print axioms NativeUniformRetentionTransfer.retained_image_card
#print axioms NativeUniformRetentionTransfer.retained_image_multiplicity
#print axioms NativeUniformRetentionTransfer.uniform_subset_card_cross
