import Theorems.Thm_StickyKakeya4_native_compact_source_coordinate_caps_draft_2218
set_option autoImplicit false
#print axioms NativeCompactSourceCoordinateCapsDraft2218.compact_tube_point_norm
#print axioms NativeCompactSourceCoordinateCapsDraft2218.original_cell_center_norm
#print axioms NativeCompactSourceCoordinateCapsDraft2218.native_height_count
#print axioms NativeCompactSourceCoordinateCapsDraft2218.packed_tangent_grid_count
#print axioms NativeCompactSourceCoordinateCapsDraft2218.packed_fine_X_count
