import Theorems.Thm_StickyKakeya4_native_normalized_population_admission_budget
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_caps
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_local
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_cutoff
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_final
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_ad

set_option autoImplicit false
#print axioms NativeNormalizedPopulationAdmissionBudget.exists_original_population_admission_cutoff
#print axioms NativeNormalizedPopulationAdmissionBudget.local_scale_root
#print axioms NativeNormalizedPopulationAdmissionBudget.pay_local_root
#print axioms NativeNormalizedPopulationAdmissionBudget.populationValue
#print axioms NativeNormalizedPopulationAdmissionBudget.population_from_original_mass
#print axioms NativeReferenceXYGridCaps.filtered_image_points
#print axioms NativeReferenceXYGridCaps.fine_forward_capacity
#print axioms NativeReferenceXYGridCaps.fine_inverse_capacity
#print axioms NativeReferenceXYGridCaps.forward_capacity
#print axioms NativeReferenceXYGridCaps.inverse_capacity
#print axioms NativeReferenceXYGridCaps.lift_incidence_capacity
#print axioms NativeReferenceXYGridLocal.floor_center_error
#print axioms NativeReferenceXYGridLocal.grid_ball_pair
#print axioms NativeReferenceXYGridLocal.inBox
#print axioms NativeReferenceXYGridLocal.local_inverse_cover
#print axioms NativeRetainedSliceBudgetCutoff.exists_extra_cutoff
#print axioms NativeRetainedSliceBudgetCutoff.exists_third_budget_cutoffs
#print axioms NativeRetainedSliceBudgetCutoff.extraCutoff
#print axioms NativeRetainedSliceBudgetCutoff.extraCutoff_pays
#print axioms NativeRetainedSliceBudgetCutoff.extraCutoff_pos
#print axioms NativeRetainedSliceBudgetFinal.actual_retained_constant_le_power
#print axioms NativeRetainedSliceBudgetFinal.exists_initial_parameters
#print axioms NativeRetainedSliceBudgetFinal.source_eta_allowance
#print axioms NativeTwoMapRetainedSliceAD.all_radius_bounds
