import Theorems.Thm_StickyKakeya4_native_spatial_angular_geometry

set_option autoImplicit false
set_option warningAsError true
set_option maxRecDepth 4096
set_option maxHeartbeats 3600000

noncomputable section
namespace NativeSpatialShadowPointMenu
open Classical Finset StickyKakeya4 NativeCommonCubicalMesh NativeCubicalIncidenceCounts
open NativeOriginalParentSelection NativeOriginalCellChartGeometry NativeOriginalPaddedCells
open NativeLocalParentPhysicalMap NativeCoarsePointMultiplicity NativeCoarseShadingCapacity
open NativeSpatialAngularGeometry

lemma cellIndex_mem_box {width : ℝ} (hw : 0 < width) (x y : E4) (K : ℕ)
    (H : ∀v,|x v-y v| ≤ (K:ℝ)*width) :
    wzDyadicCellIndex width x∈integerBox 4 (K+1) (wzDyadicCellIndex width y) := by
  apply Fintype.mem_piFinset.mpr
  intro v
  apply floor_mem_interval
  rw [←sub_div,abs_div,abs_of_pos hw]
  exact (div_le_iff₀ hw).mpr (H v)

/-- The common physical contraction is controlled by a literal ORIGINAL
spatial cube, with no representative or output-input hypothesis. -/
lemma physical_cube_close {n : ℕ} (D : FiniteScaleSource n) (a : ℝ)
    (M : ℕ) (hM : 0 < M) (k l : Index)
    (hcell : spatialLabel D M k=spatialLabel D M l) (v : Fin 4) :
    |NativeLocalParentPhysicalMap.physicalMap D a 1 (0,0) (cellCenter (mesh D) k) v-
      NativeLocalParentPhysicalMap.physicalMap D a 1 (0,0) (cellCenter (mesh D) l) v| ≤ (32/(M:ℝ))/2 := by
  rw [physicalMap_zero_sub,abs_div,abs_of_pos (by norm_num : (0:ℝ)<512)]
  calc
    _ ≤ (64/(M:ℝ))/512 := div_le_div_of_nonneg_right
      (spatial_coordinate_close D M hM k l hcell v) (by norm_num)
    _ = (1/8:ℝ)/(M:ℝ) := by ring
    _ ≤ 16/(M:ℝ) := div_le_div_of_nonneg_right (by norm_num) (by positivity)
    _ = _ := by ring

/-- All actual full-shadow point labels generated by original incidences
inside one spatial64/M cube lie in one fixed7^4-cell menu. -/
theorem spatial_point_image_card {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i)∈Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (M B : ℕ) (hM : 0 < M) (hscale : (M:ℝ)*D.thickness ≤ 1)
    (hmesh : (B:ℝ)*D.thickness/128=32/(M:ℝ))
    (rep : Parent → Fin n) (F : Finset (Fin n × Index)) (hF : F⊆incidences original)
    (hrep : ∀z∈F,parentLabel D a M (rep (parentLabel D a M z.1))=parentLabel D a M z.1)
    (q : Index) (hspace : ∀z∈F,spatialLabel D M z.2=q) :
    (F.image (pointLabel D a M B rep)).card ≤ 2401 := by
  by_cases hne : F.Nonempty
  · obtain ⟨z0,hz0⟩ := hne
    let anchor := NativeLocalParentPhysicalMap.physicalMap D a 1 (0,0) (cellCenter (mesh D) z0.2)
    let box := integerBox 4 3 (wzDyadicCellIndex (32/(M:ℝ)) anchor)
    have hsub : F.image (pointLabel D a M B rep) ⊆ box := by
      intro p hp
      obtain ⟨z,hz,rfl⟩ := mem_image.mp hp
      unfold pointLabel projectedLabel
      rw [hmesh]
      apply cellIndex_mem_box (by positivity) _ anchor 2
      intro v
      have hfront := projected_front_near_physical h original horiginal ha M hM hscale
        z.1 (rep (parentLabel D a M z.1)) z.2
        ((mem_incidences original z.1 z.2).mp (hF hz)) (hrep z hz) v
      have hphysical := physical_cube_close D a M hM z.2 z0.2
        ((hspace z hz).trans (hspace z0 hz0).symm) v
      have hh := (abs_sub_le
        (frontPoint D a (0,0) (rep (parentLabel D a M z.1)) z.2 v)
        (NativeLocalParentPhysicalMap.physicalMap D a 1 (0,0) (cellCenter (mesh D) z.2) v) (anchor v)).trans
          (add_le_add hfront hphysical)
      norm_num only [Nat.cast_ofNat]
      nlinarith
    exact (card_le_card hsub).trans_eq (integerBox_card 4 3 _)
  · rw [not_nonempty_iff_eq_empty.mp hne]
    simp

end NativeSpatialShadowPointMenu
