import Theorems.Thm_StickyKakeya4_native_actual_post_graph_slice
import Theorems.Thm_StickyKakeya4_native_actual_reference_W_physical
import Theorems.Thm_StickyKakeya4_native_normalized_cell_angular_menu
import Theorems.Thm_StickyKakeya4_native_normalized_cell_reverse_menu
import Theorems.Thm_StickyKakeya4_native_normalized_cell_source_angular
import Theorems.Thm_StickyKakeya4_native_normalized_cell_source_upper
import Theorems.Thm_StickyKakeya4_native_offset_angular_geometry
import Theorems.Thm_StickyKakeya4_native_offset_menu_count
import Theorems.Thm_StickyKakeya4_native_original_point_angular_lower
import Theorems.Thm_StickyKakeya4_native_post_graph_slice_data
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_maps
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_menus
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_metric
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_points
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_algebra
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_costs
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget_extra
import Theorems.Thm_StickyKakeya4_native_sharp_parent_graph_configuration
import Theorems.Thm_StickyKakeya4_native_sharp_parent_graph_data
import Theorems.Thm_StickyKakeya4_native_sharp_parent_graph_forget
import Theorems.Thm_StickyKakeya4_native_translated_slice_grain_join
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_join
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_labels
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_radius
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_upper

set_option autoImplicit false
#print axioms NativeActualPostGraphSlice.attach_actual_post_graph_slice
#print axioms NativeActualReferenceWPhysical.geometric_incidence_residual
#print axioms NativeActualReferenceWPhysical.local_front_graph
#print axioms NativeActualReferenceWPhysical.local_front_phase_error
#print axioms NativeActualReferenceWPhysical.original_column_residual
#print axioms NativeActualReferenceWPhysical.position
#print axioms NativeActualReferenceWPhysical.position_coordinate_error
#print axioms NativeNormalizedCellAngularMenu.angularCell
#print axioms NativeNormalizedCellAngularMenu.angularMenu
#print axioms NativeNormalizedCellAngularMenu.angular_menu_le_degree
#print axioms NativeNormalizedCellAngularMenu.angular_readback
#print axioms NativeNormalizedCellAngularMenu.original_angular_menu_upper
#print axioms NativeNormalizedCellAngularMenu.relativeAngle
#print axioms NativeNormalizedCellReverseMenu.physical_cell_mem_reverse
#print axioms NativeNormalizedCellReverseMenu.reverseMenu
#print axioms NativeNormalizedCellReverseMenu.reverseMenu_card
#print axioms NativeNormalizedCellSourceAngular.exists_source_angular_upper
#print axioms NativeNormalizedCellSourceUpper.exists_source_normalized_degree_upper
#print axioms NativeNormalizedCellSourceUpper.source_native_from_population
#print axioms NativeOffsetAngularGeometry.incident_offsets_close
#print axioms NativeOffsetAngularGeometry.matrix_action_general
#print axioms NativeOffsetAngularGeometry.quotient_difference
#print axioms NativeOffsetMenuCount.exists_coherent_offset_core
#print axioms NativeOffsetMenuCount.geometric_offset_count
#print axioms NativeOffsetMenuCount.offset_count_from_point_menus
#print axioms NativeOffsetMenuCount.pairImage
#print axioms NativeOffsetMenuCount.right_fiber_card
#print axioms NativeOriginalPointAngularLower.angular_global_readback
#print axioms NativeOriginalPointAngularLower.original_point_angular_lower
#print axioms NativeOriginalPointAngularLower.pointMenu
#print axioms NativeOriginalPointAngularLower.pointMenu_card
#print axioms NativeOriginalPointAngularLower.translateAngle
#print axioms NativeOriginalPointAngularLower.translateAngle_injective
#print axioms NativePostGraphSliceData.HasHeightCoreWith
#print axioms NativePostGraphSliceData.HasPostGraphParentProfiles
#print axioms NativePostGraphSliceData.HasTranslatedSliceData
#print axioms NativeReferenceXYGridMaps.coarseXY
#print axioms NativeReferenceXYGridMaps.coarseXY_x
#print axioms NativeReferenceXYGridMaps.coarseXY_y
#print axioms NativeReferenceXYGridMaps.euclidean_coord_bound
#print axioms NativeReferenceXYGridMaps.floor_neighbor
#print axioms NativeReferenceXYGridMaps.pxy
#print axioms NativeReferenceXYGridMaps.pxy_height
#print axioms NativeReferenceXYGridMaps.quotient_nodeSlope
#print axioms NativeReferenceXYGridMaps.same_floor_abs
#print axioms NativeReferenceXYGridMenus.coarseIndex_one
#print axioms NativeReferenceXYGridMenus.coarseXY_one
#print axioms NativeReferenceXYGridMenus.forward_menu
#print axioms NativeReferenceXYGridMenus.inverse_menu
#print axioms NativeReferenceXYGridMenus.pref_neighbor_of_old_dist
#print axioms NativeReferenceXYGridMenus.vectorBox
#print axioms NativeReferenceXYGridMenus.vectorBox_card
#print axioms NativeReferenceXYGridMenus.xyBox
#print axioms NativeReferenceXYGridMenus.xyBox_card
#print axioms NativeReferenceXYGridMetric.old_dist_le_raw
#print axioms NativeReferenceXYGridMetric.old_dist_of_coarse_XY
#print axioms NativeReferenceXYGridMetric.old_dist_of_coordinate_bounds
#print axioms NativeReferenceXYGridMetric.old_height_gap
#print axioms NativeReferenceXYGridMetric.raw_dist_le_old
#print axioms NativeReferenceXYGridMetric.raw_dist_of_coarse_pref
#print axioms NativeReferenceXYGridMetric.raw_height_gap
#print axioms NativeReferenceXYGridPoints.coarseIndex
#print axioms NativeReferenceXYGridPoints.coarseIndex_height
#print axioms NativeReferenceXYGridPoints.coarseIndex_spatial
#print axioms NativeReferenceXYGridPoints.coarse_pref_spatial
#print axioms NativeReferenceXYGridPoints.floor_div_scale
#print axioms NativeReferenceXYGridPoints.heightMesh
#print axioms NativeReferenceXYGridPoints.heightMesh_eq
#print axioms NativeReferenceXYGridPoints.heightMesh_pos
#print axioms NativeReferenceXYGridPoints.mu
#print axioms NativeReferenceXYGridPoints.mu_phase
#print axioms NativeReferenceXYGridPoints.mu_pos
#print axioms NativeReferenceXYGridPoints.oldPoint
#print axioms NativeReferenceXYGridPoints.original_phase_rounding
#print axioms NativeReferenceXYGridPoints.physical_rounding
#print axioms NativeReferenceXYGridPoints.pref
#print axioms NativeReferenceXYGridPoints.prefMesh
#print axioms NativeReferenceXYGridPoints.prefMesh_eq
#print axioms NativeReferenceXYGridPoints.prefMesh_pos
#print axioms NativeReferenceXYGridPoints.pref_height
#print axioms NativeReferenceXYGridPoints.pref_height_floor
#print axioms NativeReferenceXYGridPoints.pref_spatial
#print axioms NativeReferenceXYGridPoints.rawPoint
#print axioms NativeReferenceXYGridPoints.rho
#print axioms NativeReferenceXYGridPoints.rho_pos
#print axioms NativeReferenceXYGridPoints.sigma
#print axioms NativeReferenceXYGridPoints.sigma_pos
#print axioms NativeRetainedSliceBudgetAlgebra.quotientCost
#print axioms NativeRetainedSliceBudgetAlgebra.quotientCost_le
#print axioms NativeRetainedSliceBudgetAlgebra.quotientCost_pos
#print axioms NativeRetainedSliceBudgetAlgebra.retained_constant_le_reference
#print axioms NativeRetainedSliceBudgetCosts.rank_parent_retention_power
#print axioms NativeRetainedSliceBudgetCosts.third_core_parent_cost
#print axioms NativeRetainedSliceBudgetExtra.extraCoefficient
#print axioms NativeRetainedSliceBudgetExtra.extraConstant
#print axioms NativeRetainedSliceBudgetExtra.extraConstant_one_le
#print axioms NativeRetainedSliceBudgetExtra.extra_coefficient_bound
#print axioms NativeRetainedSliceBudgetExtra.graphCost_pos
#print axioms NativeRetainedSliceBudgetExtra.squared_loss
#print axioms NativeSharpParentGraphConfiguration.HasSharpCurveParentRetainedHistory
#print axioms NativeSharpParentGraphConfiguration.HasSharpCurveParentStage
#print axioms NativeSharpParentGraphConfiguration.SharpCurveParentFinalCleanupData
#print axioms NativeSharpParentGraphConfiguration.exists_sharp_parent_graph_configuration
#print axioms NativeSharpParentGraphConfiguration.half_depth_eq_depth
#print axioms NativeSharpParentGraphConfiguration.middleSelected
#print axioms NativeSharpParentGraphConfiguration.middle_selected_depth
#print axioms NativeSharpParentGraphConfiguration.sharp_stage_with_parent_graph
#print axioms NativeSharpParentGraphData.HasParentHeightCore
#print axioms NativeSharpParentGraphData.HasSharpCurveParentProfiles
#print axioms NativeSharpParentGraphData.attach_sharp_parent_graph
#print axioms NativeSharpParentGraphData.sharp_curve_parent_profiles_forget
#print axioms NativeSharpParentGraphForget.curve_cleanup_forget
#print axioms NativeSharpParentGraphForget.curve_parent_profiles_forget
#print axioms NativeSharpParentGraphForget.curve_retained_forget
#print axioms NativeSharpParentGraphForget.curve_stage_forget
#print axioms NativeTranslatedSliceGrainJoin.construct_translated_slice_grain
#print axioms NativeTwoMapRetainedSliceJoin.height_card_le_of_class_bounds
#print axioms NativeTwoMapRetainedSliceJoin.height_image_cap
#print axioms NativeTwoMapRetainedSliceJoin.menu_classes_all_radius64
#print axioms NativeTwoMapRetainedSliceLabels.append_div
#print axioms NativeTwoMapRetainedSliceLabels.coarse
#print axioms NativeTwoMapRetainedSliceLabels.encode
#print axioms NativeTwoMapRetainedSliceLabels.encode_coarse
#print axioms NativeTwoMapRetainedSliceLabels.encode_height
#print axioms NativeTwoMapRetainedSliceLabels.encode_injective
#print axioms NativeTwoMapRetainedSliceLabels.encode_left
#print axioms NativeTwoMapRetainedSliceLabels.encode_right
#print axioms NativeTwoMapRetainedSliceLabels.encoded_fiber_eq
#print axioms NativeTwoMapRetainedSliceLabels.encoded_uniformity
#print axioms NativeTwoMapRetainedSliceLabels.image_encode_card
#print axioms NativeTwoMapRetainedSliceRadius.all_radius_bounds64
#print axioms NativeTwoMapRetainedSliceUpper.retained_class_upper
