from pathlib import Path
import json,hashlib,tarfile,shutil
w=Path('/workspace/shared/sticky-recovery-20261006');cache=w/'project-cache-20261006T2057';check=w/'cache-import-check-20261006T2057/status.json';d=json.loads(check.read_text());assert d['state']=='passed' and d['artifact_count']==974
out=Path('/workspace/scratch/5f2524fd4117/cache-delivery-20261006T2120');out.mkdir(exist_ok=False);name='4dstickykakeya-verified-cache974-20261006T2057.tar.gz';archive=out/name
with tarfile.open(archive,'w:gz',compresslevel=6) as tf:tf.add(cache,arcname=cache.name);tf.add(check,arcname='CACHE_IMPORT_VALIDATION.json')
raw=archive.read_bytes();parts=[]
for i,start in enumerate(range(0,len(raw),18000000),1):
 p=out/(name+f'.part{i:02d}');data=raw[start:start+18000000];p.write_bytes(data);parts.append({'file_name':p.name,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
manifest={'archive_file_name':name,'archive_bytes':len(raw),'archive_sha256':hashlib.sha256(raw).hexdigest(),'artifact_count':974,'source_commit_at_snapshot':json.loads((cache/'CACHE_MANIFEST.json').read_text())['project_commit'],'compiler_and_dependency_pins':'inside CACHE_MANIFEST.json and lake-manifest.json','validation_finished_utc':d['finished_utc'],'parts':parts,'scope':'Complete hash-verified project import closure, independently imported from cache-only path. Reuse is not a fresh source compilation. Pair with a compatible source/history bundle.'}
(out/'CACHE974_REASSEMBLY.json').write_text(json.dumps(manifest,indent=2)+'\n')
(out/'CACHE974_RESTORE_README.txt').write_text('This is an optional acceleration cache, not a replacement for proof sources.\n\n1. Restore the compatible project source/history bundle.\n2. Concatenate part01, part02, ... in numerical order to recreate '+name+'.\n3. Check every part SHA256 and the whole archive SHA256 in CACHE974_REASSEMBLY.json.\n4. Extract into an independent directory. Verify the exact Lean compiler, all dependency pins, all canonical source and olean hashes, and the complete import closure in CACHE_MANIFEST.json before reusing.\n5. Reusing these artifacts is cache restoration, not a new proof build. Their validation completed '+d['finished_utc']+'.\n\nEach part is at most18000000 bytes for the attachment limit. The original archive and its hash remain authoritative. The original dimension-four theorem is not completed by these cache files.\n')
files=[out/x['file_name'] for x in parts]+[out/'CACHE974_REASSEMBLY.json',out/'CACHE974_RESTORE_README.txt']
request={'uploads':[{'local_path':str(p),'purpose':'create_library_file','library_artifact_type':'other'} for p in files]};(w/'CACHE974_UPLOAD_REQUEST.json').write_text(json.dumps(request,indent=2)+'\n');(w/'CACHE974_PACKAGE.json').write_text(json.dumps(dict(manifest,directory=str(out)),indent=2)+'\n');print(json.dumps({'archive_bytes':len(raw),'archive_sha256':manifest['archive_sha256'],'parts':len(parts),'upload_files':len(files)}))
