import Theorems.Thm_StickyKakeya4_native_actual_dimension_range_configuration
import Theorems.Thm_StickyKakeya4_native_anisotropic_column_menus
import Theorems.Thm_StickyKakeya4_native_raw_shadow_pair_comparison
import Theorems.Thm_StickyKakeya4_native_anisotropic_column_capacity

set_option autoImplicit false
#print axioms NativeActualDimensionRangeConfiguration.exists_actual_dimension_range_configuration
#print axioms NativeActualDimensionRangeConfiguration.extremalExponent_le_two
#print axioms NativeAnisotropicColumnCapacity.column_height_fiber_card_le
#print axioms NativeAnisotropicColumnCapacity.column_vertices_card_le
#print axioms NativeAnisotropicColumnCapacity.column_vertices_card_le_mul
#print axioms NativeAnisotropicColumnCapacity.dyadic_column_vertices_card_le
#print axioms NativeAnisotropicColumnCapacity.dyadic_height_eq
#print axioms NativeAnisotropicColumnCapacity.heightMenu
#print axioms NativeAnisotropicColumnCapacity.heightMenu_card
#print axioms NativeAnisotropicColumnCapacity.same_column_height_mem_menu
#print axioms NativeAnisotropicColumnCapacity.same_column_same_height_mem_halo
#print axioms NativeAnisotropicColumnMenus.columnHalo_symm
#print axioms NativeAnisotropicColumnMenus.columnHalo_trans
#print axioms NativeAnisotropicColumnMenus.same_column_height_close
#print axioms NativeAnisotropicColumnMenus.same_column_same_height_spatial_close
#print axioms NativeAnisotropicColumnMenus.same_floor_width_close
#print axioms NativeAnisotropicColumnMenus.same_raw_column_mem_halo
#print axioms NativeRawShadowPairComparison.image_multiplicity_le_of_card_bounds
#print axioms NativeRawShadowPairComparison.pair_image_card_le_of_point_comparison
#print axioms NativeRawShadowPairComparison.pair_image_card_of_constant
#print axioms NativeRawShadowPairComparison.rawPair
#print axioms NativeRawShadowPairComparison.same_R_full_source_multiplicity_comparison
#print axioms NativeRawShadowPairComparison.same_R_multiplicity_comparison
#print axioms NativeRawShadowPairComparison.same_R_pair_image_card_comparison
