import Theorems.Thm_StickyKakeya4_native_anisotropic_column_capacity

#print axioms NativeAnisotropicColumnCapacity.heightMenu
#print axioms NativeAnisotropicColumnCapacity.heightMenu_card
#print axioms NativeAnisotropicColumnCapacity.same_column_height_mem_menu
#print axioms NativeAnisotropicColumnCapacity.same_column_same_height_mem_halo
#print axioms NativeAnisotropicColumnCapacity.column_height_fiber_card_le
#print axioms NativeAnisotropicColumnCapacity.column_vertices_card_le
#print axioms NativeAnisotropicColumnCapacity.column_vertices_card_le_mul
#print axioms NativeAnisotropicColumnCapacity.dyadic_height_eq
#print axioms NativeAnisotropicColumnCapacity.dyadic_column_vertices_card_le
