import Theorems.Thm_StickyKakeya4_native_configured_lower_quotient_readback
set_option autoImplicit false
#print axioms NativeConfiguredLowerQuotientReadback.lowerQuotient
#print axioms NativeConfiguredLowerQuotientReadback.graphGrid_quotient
#print axioms NativeConfiguredLowerQuotientReadback.coarse_height_readback
#print axioms NativeConfiguredLowerQuotientReadback.point_quotient_readback
#print axioms NativeConfiguredLowerQuotientReadback.lowerQuotient_dist
#print axioms NativeConfiguredLowerQuotientReadback.key_center_dist_of_same_coarse_height
#print axioms NativeConfiguredLowerQuotientReadback.key_center_dist_of_same_old_height
