import Theorems.Thm_StickyKakeya4_actual_slope_source_bounds

#check @StickyKakeya4.ActualSlopeSource.horizontalProjection_heightPoint
#check @StickyKakeya4.ActualSlopeSource.norm_northGraphIntercept_le_twice_offset
#check @StickyKakeya4.ActualSlopeSource.compact_offset_bound
#check @StickyKakeya4.ActualSlopeSource.sourceMeasure_intercept_le_twice_offset_bound
#check @StickyKakeya4.ActualSlopeSource.sourceMeasure_intercept_bound_of_compact
#check @StickyKakeya4.ActualSlopeSource.intercept_bound_of_compact_front_support
#check @StickyKakeya4.ActualSlopeSource.compact_full_direction_actual_slope_source_bounded

#print axioms StickyKakeya4.ActualSlopeSource.horizontalProjection_heightPoint
#print axioms StickyKakeya4.ActualSlopeSource.norm_northGraphIntercept_le_twice_offset
#print axioms StickyKakeya4.ActualSlopeSource.compact_offset_bound
#print axioms StickyKakeya4.ActualSlopeSource.sourceMeasure_intercept_le_twice_offset_bound
#print axioms StickyKakeya4.ActualSlopeSource.sourceMeasure_intercept_bound_of_compact
#print axioms StickyKakeya4.ActualSlopeSource.intercept_bound_of_compact_front_support
#print axioms StickyKakeya4.ActualSlopeSource.compact_full_direction_actual_slope_source_bounded
