import Theorems.Thm_StickyKakeya4_actual_residual_phase_localization

set_option autoImplicit false

#print axioms StickyKakeya4.ActualResidualPhaseLocalization.exists_comparable_dyadic_radius
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.indexedCenters
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.indexedCenters_mem
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.indexedCenters_separated
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.indexedCenters_cover_ae
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.actual_phase_ball_mass_le
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.actual_phaseBlock_mass_toReal_le
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.reference_lower_mass_le_phaseBlock
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.angular_scale_cubic_normalization_cost
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.angular_scale_localized_density
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.normalized_restriction_scaled_ball_bound
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.localize_actual_shell_in_reference_nets
#print axioms StickyKakeya4.ActualResidualPhaseLocalization.sticky_datum_exists_uniform_actual_shell_localization
