import Theorems.Thm_StickyKakeya4_actual_residual_cycle_witness

#check @StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight
#check @StickyKakeya4.ActualResidualCycleWitness.measurable_oldGraphWeight
#check @StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_le_one
#check @StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_pos_support
#check @StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_diagonal
#check @StickyKakeya4.ActualResidualCycleWitness.oldGraph_mass_eq_fixed_angle_residual_content
#check @StickyKakeya4.ActualResidualCycleWitness.pairTime
#check @StickyKakeya4.ActualResidualCycleWitness.measurable_pairTime
#check @StickyKakeya4.ActualResidualCycleWitness.canonical_old_time_bounds
#check @StickyKakeya4.ActualResidualCycleWitness.pairTime_swap
#check @StickyKakeya4.ActualResidualCycleWitness.cycleVertices
#check @StickyKakeya4.ActualResidualCycleWitness.cycleIntercepts
#check @StickyKakeya4.ActualResidualCycleWitness.cycleTimes
#check @StickyKakeya4.ActualResidualCycleWitness.cycleTimes_zero
#check @StickyKakeya4.ActualResidualCycleWitness.measurable_cycleVertices
#check @StickyKakeya4.ActualResidualCycleWitness.measurable_cycleIntercepts
#check @StickyKakeya4.ActualResidualCycleWitness.measurable_cycleTimes
#check @StickyKakeya4.ActualResidualCycleWitness.contact_norm_reverse
#check @StickyKakeya4.ActualResidualCycleWitness.cycle_contact_errors
#check @StickyKakeya4.ActualResidualCycleWitness.cycle_fresh_times_mem
#check @StickyKakeya4.ActualResidualCycleWitness.timeLabelKernel
#check @StickyKakeya4.ActualResidualCycleWitness.timeLabelKernel_isMarkov
#check @StickyKakeya4.ActualResidualCycleWitness.timedWitnessMeasure
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_original
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_times
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_old_time
#check @StickyKakeya4.ActualResidualCycleWitness.vertex_witness_contact_errors
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_contact_errors
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_observable
#check @StickyKakeya4.ActualResidualCycleWitness.determinantCut
#check @StickyKakeya4.ActualResidualCycleWitness.measurableSet_determinantCut
#check @StickyKakeya4.ActualResidualCycleWitness.cycle_times_near_old_time
#check @StickyKakeya4.ActualResidualCycleWitness.old_time_cell_contact_bound
#check @StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines
#check @StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines_mem
#check @StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines_secant
#check @StickyKakeya4.ActualResidualCycleWitness.timed_selector_contact_errors
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_fresh_times_mem
#check @StickyKakeya4.ActualResidualCycleWitness.timed_witness_four_distinct

#print axioms StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurable_oldGraphWeight
#print axioms StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_le_one
#print axioms StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_pos_support
#print axioms StickyKakeya4.ActualResidualCycleWitness.oldGraphWeight_diagonal
#print axioms StickyKakeya4.ActualResidualCycleWitness.oldGraph_mass_eq_fixed_angle_residual_content
#print axioms StickyKakeya4.ActualResidualCycleWitness.pairTime
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurable_pairTime
#print axioms StickyKakeya4.ActualResidualCycleWitness.canonical_old_time_bounds
#print axioms StickyKakeya4.ActualResidualCycleWitness.pairTime_swap
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleVertices
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleIntercepts
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleTimes
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleTimes_zero
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurable_cycleVertices
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurable_cycleIntercepts
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurable_cycleTimes
#print axioms StickyKakeya4.ActualResidualCycleWitness.contact_norm_reverse
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycle_contact_errors
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycle_fresh_times_mem
#print axioms StickyKakeya4.ActualResidualCycleWitness.timeLabelKernel
#print axioms StickyKakeya4.ActualResidualCycleWitness.timeLabelKernel_isMarkov
#print axioms StickyKakeya4.ActualResidualCycleWitness.timedWitnessMeasure
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_original
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_times
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_old_time
#print axioms StickyKakeya4.ActualResidualCycleWitness.vertex_witness_contact_errors
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_contact_errors
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_observable
#print axioms StickyKakeya4.ActualResidualCycleWitness.determinantCut
#print axioms StickyKakeya4.ActualResidualCycleWitness.measurableSet_determinantCut
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycle_times_near_old_time
#print axioms StickyKakeya4.ActualResidualCycleWitness.old_time_cell_contact_bound
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines_mem
#print axioms StickyKakeya4.ActualResidualCycleWitness.cycleMarkedLines_secant
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_selector_contact_errors
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_fresh_times_mem
#print axioms StickyKakeya4.ActualResidualCycleWitness.timed_witness_four_distinct
