import Theorems.Thm_StickyKakeya4_affine_focus_energy_escape

#print axioms StickyKakeya4.AffineFocusEnergyEscape.measurable_affineFocusIntercept
#print axioms StickyKakeya4.AffineFocusEnergyEscape.lineResidual_reference_root
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_collision_line_localization
#print axioms StickyKakeya4.AffineFocusEnergyEscape.rootTimeCollision_mass_le_line_potential
#print axioms StickyKakeya4.AffineFocusEnergyEscape.goodSourceTime_pair_sublevel_le_of_potential_bound
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_pair_sublevel_power
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_finite_pair_energy
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_finite_front_energy
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_original_front_frostman
#print axioms StickyKakeya4.AffineFocusEnergyEscape.affine_focus_original_front_dimH_eq_four
#print axioms StickyKakeya4.AffineFocusEnergyEscape.original_spacetime_map_eq_of_ae_affine_focus
#print axioms StickyKakeya4.AffineFocusEnergyEscape.original_front_dimH_eq_four_of_ae_affine_focus
#print axioms StickyKakeya4.AffineFocusEnergyEscape.original_goodSourceTime_map_eq_of_ae_affine_focus
#print axioms StickyKakeya4.AffineFocusEnergyEscape.original_finite_front_energy_of_ae_affine_focus
#print axioms StickyKakeya4.AffineFocusEnergyEscape.original_front_frostman_of_ae_affine_focus
