import Theorems.Thm_StickyKakeya4_common_target_star_kernel

#check @StickyKakeya4.FourDistinctSources.measure_triple_event_eq_ofReal_tripleProbability
#check @StickyKakeya4.FourDistinctSources.measure_fourDistinct_eq_ofReal
#check @StickyKakeya4.FourDistinctSources.measure_fourDistinct_ge_half_of_normalizedWeights
#check @StickyKakeya4.FourDistinctSources.measure_fourDistinct_ge_half_of_ennreal_weights
#check @StickyKakeya4.FourDistinctSources.measure_fourDistinct_toReal_ge_half_of_ennreal_weights
#check @StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.atom_density
#check @StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.weighted_ratio_ae
#check @StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.index_partition
#check @StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.total_target_density
#check @StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.conditional_index_ratio_ae
#check @StickyKakeya4.CommonTargetStarKernel.targetOccurrence
#check @StickyKakeya4.CommonTargetStarKernel.targetOccurrence_isFinite
#check @StickyKakeya4.CommonTargetStarKernel.targetOccurrence_fst
#check @StickyKakeya4.CommonTargetStarKernel.source_cut_joint_le
#check @StickyKakeya4.CommonTargetStarKernel.target_le_selector_source_mass
#check @StickyKakeya4.CommonTargetStarKernel.source_piece_genuine
#check @StickyKakeya4.CommonTargetStarKernel.normalized_target_le_selector
#check @StickyKakeya4.CommonTargetStarKernel.boundedWeight
#check @StickyKakeya4.CommonTargetStarKernel.measurable_boundedWeight
#check @StickyKakeya4.CommonTargetStarKernel.boundedWeight_le_one
#check @StickyKakeya4.CommonTargetStarKernel.boundedWeight_density
#check @StickyKakeya4.CommonTargetStarKernel.sourceWeight
#check @StickyKakeya4.CommonTargetStarKernel.sourceWeight_density
#check @StickyKakeya4.CommonTargetStarKernel.sourceWeight_target_density
#check @StickyKakeya4.CommonTargetStarKernel.occurrenceFiber
#check @StickyKakeya4.CommonTargetStarKernel.occurrenceFiber_isMarkov
#check @StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_disintegration
#check @StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_graph_ae
#check @StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_same_target
#check @StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_graph_on_positive_weight
#check @StickyKakeya4.CommonTargetStarKernel.indexMeasure
#check @StickyKakeya4.CommonTargetStarKernel.indexKernel
#check @StickyKakeya4.CommonTargetStarKernel.indexKernel_apply
#check @StickyKakeya4.CommonTargetStarKernel.indexKernel_isMarkov
#check @StickyKakeya4.CommonTargetStarKernel.indexKernel_singleton
#check @StickyKakeya4.CommonTargetStarKernel.indexKernel_ae_nonzero
#check @StickyKakeya4.CommonTargetStarKernel.occurrenceFamily
#check @StickyKakeya4.CommonTargetStarKernel.occurrenceFamily_isMarkov
#check @StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel
#check @StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_isMarkov
#check @StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_index
#check @StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_index_mass
#check @StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_ae
#check @StickyKakeya4.CommonTargetStarKernel.tripleOccurrenceKernel
#check @StickyKakeya4.CommonTargetStarKernel.tripleOccurrenceKernel_isMarkov
#check @StickyKakeya4.CommonTargetStarKernel.starExtension
#check @StickyKakeya4.CommonTargetStarKernel.star_extension_original
#check @StickyKakeya4.CommonTargetStarKernel.single_fresh_stationary
#check @StickyKakeya4.CommonTargetStarKernel.triple_fiber_first
#check @StickyKakeya4.CommonTargetStarKernel.triple_fiber_second
#check @StickyKakeya4.CommonTargetStarKernel.triple_fiber_third
#check @StickyKakeya4.CommonTargetStarKernel.star_fresh_stationary
#check @StickyKakeya4.CommonTargetStarKernel.star_all_fresh_stationary
#check @StickyKakeya4.CommonTargetStarKernel.star_cut_fresh_le
#check @StickyKakeya4.CommonTargetStarKernel.star_extension_genuine
#check @StickyKakeya4.CommonTargetStarKernel.star_extension_common_target
#check @StickyKakeya4.CommonTargetStarKernel.starSuccess
#check @StickyKakeya4.CommonTargetStarKernel.measurableSet_starSuccess
#check @StickyKakeya4.CommonTargetStarKernel.stationary_fiber_distinct_probability
#check @StickyKakeya4.CommonTargetStarKernel.restrict_source_compProd
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_le_full
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_original_le
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_original_ge_half
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_fresh_le
#check @StickyKakeya4.CommonTargetStarKernel.source_index_genuine
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_genuine
#check @StickyKakeya4.CommonTargetStarKernel.retainedStar_four_distinct_physical_sources
#check @StickyKakeya4.CommonTargetStarKernel.selector_cut_retainedStar_original_ge_half
#check @StickyKakeya4.CommonTargetStarKernel.selector_cut_retainedStar_mass_ge_quarter

#print axioms StickyKakeya4.FourDistinctSources.measure_triple_event_eq_ofReal_tripleProbability
#print axioms StickyKakeya4.FourDistinctSources.measure_fourDistinct_eq_ofReal
#print axioms StickyKakeya4.FourDistinctSources.measure_fourDistinct_ge_half_of_normalizedWeights
#print axioms StickyKakeya4.FourDistinctSources.measure_fourDistinct_ge_half_of_ennreal_weights
#print axioms StickyKakeya4.FourDistinctSources.measure_fourDistinct_toReal_ge_half_of_ennreal_weights
#print axioms StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.atom_density
#print axioms StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.weighted_ratio_ae
#print axioms StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.index_partition
#print axioms StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.total_target_density
#print axioms StickyKakeya4.CommonTargetStarKernel.ConditionalIndexDensity.conditional_index_ratio_ae
#print axioms StickyKakeya4.CommonTargetStarKernel.targetOccurrence
#print axioms StickyKakeya4.CommonTargetStarKernel.targetOccurrence_isFinite
#print axioms StickyKakeya4.CommonTargetStarKernel.targetOccurrence_fst
#print axioms StickyKakeya4.CommonTargetStarKernel.source_cut_joint_le
#print axioms StickyKakeya4.CommonTargetStarKernel.target_le_selector_source_mass
#print axioms StickyKakeya4.CommonTargetStarKernel.source_piece_genuine
#print axioms StickyKakeya4.CommonTargetStarKernel.normalized_target_le_selector
#print axioms StickyKakeya4.CommonTargetStarKernel.boundedWeight
#print axioms StickyKakeya4.CommonTargetStarKernel.measurable_boundedWeight
#print axioms StickyKakeya4.CommonTargetStarKernel.boundedWeight_le_one
#print axioms StickyKakeya4.CommonTargetStarKernel.boundedWeight_density
#print axioms StickyKakeya4.CommonTargetStarKernel.sourceWeight
#print axioms StickyKakeya4.CommonTargetStarKernel.sourceWeight_density
#print axioms StickyKakeya4.CommonTargetStarKernel.sourceWeight_target_density
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrenceFiber
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrenceFiber_isMarkov
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_disintegration
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_graph_ae
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_same_target
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrence_fiber_graph_on_positive_weight
#print axioms StickyKakeya4.CommonTargetStarKernel.indexMeasure
#print axioms StickyKakeya4.CommonTargetStarKernel.indexKernel
#print axioms StickyKakeya4.CommonTargetStarKernel.indexKernel_apply
#print axioms StickyKakeya4.CommonTargetStarKernel.indexKernel_isMarkov
#print axioms StickyKakeya4.CommonTargetStarKernel.indexKernel_singleton
#print axioms StickyKakeya4.CommonTargetStarKernel.indexKernel_ae_nonzero
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrenceFamily
#print axioms StickyKakeya4.CommonTargetStarKernel.occurrenceFamily_isMarkov
#print axioms StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel
#print axioms StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_isMarkov
#print axioms StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_index
#print axioms StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_index_mass
#print axioms StickyKakeya4.CommonTargetStarKernel.taggedOccurrenceKernel_ae
#print axioms StickyKakeya4.CommonTargetStarKernel.tripleOccurrenceKernel
#print axioms StickyKakeya4.CommonTargetStarKernel.tripleOccurrenceKernel_isMarkov
#print axioms StickyKakeya4.CommonTargetStarKernel.starExtension
#print axioms StickyKakeya4.CommonTargetStarKernel.star_extension_original
#print axioms StickyKakeya4.CommonTargetStarKernel.single_fresh_stationary
#print axioms StickyKakeya4.CommonTargetStarKernel.triple_fiber_first
#print axioms StickyKakeya4.CommonTargetStarKernel.triple_fiber_second
#print axioms StickyKakeya4.CommonTargetStarKernel.triple_fiber_third
#print axioms StickyKakeya4.CommonTargetStarKernel.star_fresh_stationary
#print axioms StickyKakeya4.CommonTargetStarKernel.star_all_fresh_stationary
#print axioms StickyKakeya4.CommonTargetStarKernel.star_cut_fresh_le
#print axioms StickyKakeya4.CommonTargetStarKernel.star_extension_genuine
#print axioms StickyKakeya4.CommonTargetStarKernel.star_extension_common_target
#print axioms StickyKakeya4.CommonTargetStarKernel.starSuccess
#print axioms StickyKakeya4.CommonTargetStarKernel.measurableSet_starSuccess
#print axioms StickyKakeya4.CommonTargetStarKernel.stationary_fiber_distinct_probability
#print axioms StickyKakeya4.CommonTargetStarKernel.restrict_source_compProd
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_le_full
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_original_le
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_original_ge_half
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_fresh_le
#print axioms StickyKakeya4.CommonTargetStarKernel.source_index_genuine
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_genuine
#print axioms StickyKakeya4.CommonTargetStarKernel.retainedStar_four_distinct_physical_sources
#print axioms StickyKakeya4.CommonTargetStarKernel.selector_cut_retainedStar_original_ge_half
#print axioms StickyKakeya4.CommonTargetStarKernel.selector_cut_retainedStar_mass_ge_quarter
