import Theorems.Thm_StickyKakeya4_contact_cycle_rigidity

#print axioms StickyKakeya4.ContactCycleRigidity.edgeMatrix_det_eq_anchored
#print axioms StickyKakeya4.ContactCycleRigidity.sum_edges_eq_zero
#print axioms StickyKakeya4.ContactCycleRigidity.time_difference_system
#print axioms StickyKakeya4.ContactCycleRigidity.residual_sum_norm_le
#print axioms StickyKakeya4.ContactCycleRigidity.residual_sum_coordinate_le
#print axioms StickyKakeya4.ContactCycleRigidity.old_times_cluster
#print axioms StickyKakeya4.ContactCycleRigidity.old_times_pairwise_cluster
#print axioms StickyKakeya4.ContactCycleRigidity.edgeMatrix_bound_of_direction_bound
#print axioms StickyKakeya4.ContactCycleRigidity.graphSlope_maps_frame
#print axioms StickyKakeya4.ContactCycleRigidity.scalar_graph_error_identity
#print axioms StickyKakeya4.ContactCycleRigidity.reference_residual_frame_le
#print axioms StickyKakeya4.ContactCycleRigidity.graphSlope_scalar_error_le
#print axioms StickyKakeya4.ContactCycleRigidity.scalar_graph_time_coherence
#print axioms StickyKakeya4.ContactCycleRigidity.graphSlope_scalar_error_quadratic
#print axioms StickyKakeya4.ContactCycleRigidity.old_times_in_scalar_label_packet
#print axioms StickyKakeya4.ContactCycleRigidity.old_edges_collide_at_scalar_label
