import Theorems.Thm_StickyKakeya4_original_good_graph_cap_fraction
import Theorems.Thm_StickyKakeya4_native_original_cap_fraction_budget
import Theorems.Thm_StickyKakeya4_native_a2_critical_tube_family
import Theorems.Thm_StickyKakeya4_original_critical_cap_parameter_transfer
import Theorems.Thm_StickyKakeya4_original_two_projection_cartesian
import Theorems.Thm_StickyKakeya4_original_two_projection_cover
import Theorems.Thm_StickyKakeya4_original_two_projection_real_graph
import Theorems.Thm_StickyKakeya4_original_height_log_budget

#print axioms OriginalGoodGraphCapFraction.original_good_graph_external_cap_charge
#print axioms OriginalGoodGraphCapFraction.original_good_graph_cap_fraction
#print axioms NativeOriginalCapFractionBudget.exists_native_original_cap_fraction_budget
#print axioms NativeA2CriticalTubeFamily.exists_uniform_original_critical_tube_family
#print axioms OriginalCriticalCapParameterTransfer.original_critical_cap_population
#print axioms OriginalCriticalCapParameterTransfer.original_critical_cap_coarse_exponent
#print axioms OriginalTwoProjectionCartesian.same_scalar_code_close
#print axioms OriginalTwoProjectionCartesian.two_projection_distance
#print axioms OriginalTwoProjectionCartesian.original_code_fiber_card
#print axioms OriginalTwoProjectionCartesian.graph_subset_product
#print axioms OriginalTwoProjectionCartesian.original_graph_witness
#print axioms OriginalTwoProjectionCartesian.original_query_graph_mass
#print axioms OriginalTwoProjectionCartesian.small_projections_cartesian_density
#print axioms OriginalTwoProjectionCartesian.projection_linear_identity
#print axioms OriginalTwoProjectionCartesian.synthetic_projection_error
#print axioms OriginalTwoProjectionCover.perturbed_floor_image_card
#print axioms OriginalTwoProjectionCover.original_query_synthetic_cover
#print axioms OriginalTwoProjectionCover.weights_le_of_transverse
#print axioms OriginalTwoProjectionCover.original_transverse_query_cover
#print axioms OriginalTwoProjectionRealGraph.realPoint_injective
#print axioms OriginalTwoProjectionRealGraph.real_graph_card
#print axioms OriginalTwoProjectionRealGraph.real_alphabet_card
#print axioms OriginalTwoProjectionRealGraph.real_graph_subset_product
#print axioms OriginalTwoProjectionRealGraph.real_alphabet_separated
#print axioms OriginalTwoProjectionRealGraph.real_alphabet_unit_box
#print axioms OriginalTwoProjectionRealGraph.real_graph_original_witness
#print axioms OriginalTwoProjectionRealGraph.rounded_linearValue_realPoint
#print axioms OriginalTwoProjectionRealGraph.real_query_cover
#print axioms OriginalTwoProjectionRealGraph.original_query_collision_energy
#print axioms OriginalHeightLogBudget.original_height_level_count_log_envelope
#print axioms OriginalHeightLogBudget.exists_original_height_budget_cutoff
#print axioms OriginalHeightLogBudget.exists_original_source_budget_cutoff
