import Theorems.Thm_StickyKakeya4_energy_dimension

#check StickyKakeya4.EnergyDimension.exists_supported_frostman_probability_of_finite_energy
#check StickyKakeya4.EnergyDimension.le_dimH_of_supported_finite_energy
#print axioms StickyKakeya4.EnergyDimension.ball_mass_le_potential
#print axioms StickyKakeya4.EnergyDimension.restrict_ball_growth_of_bounded_potential
#print axioms StickyKakeya4.EnergyDimension.exists_bounded_potential_piece
#print axioms StickyKakeya4.EnergyDimension.exists_supported_frostman_probability_of_finite_energy
#print axioms StickyKakeya4.EnergyDimension.le_dimH_of_supported_finite_energy

#check StickyKakeya4.EnergyDimension.hasFrontFrostmanMeasures_of_supported_finite_energies
#check StickyKakeya4.EnergyDimension.dimH_ge_four_of_supported_finite_energies
#print axioms StickyKakeya4.EnergyDimension.exists_bounded_measurable_piece
#print axioms StickyKakeya4.EnergyDimension.hasFrontFrostmanMeasures_of_supported_finite_energies
#print axioms StickyKakeya4.EnergyDimension.dimH_ge_four_of_supported_finite_energies

#print axioms StickyKakeya4.EnergyDimension.measurable_inverseDistancePotential
