import Theorems.Thm_StickyKakeya4_exact_packing_reference_piece

#print axioms StickyKakeya4.upperMinkowskiDim_mono
#print axioms StickyKakeya4.upperMinkowskiDim_closure_le
#print axioms StickyKakeya4.upperMinkowskiDim_closure
#print axioms StickyKakeya4.coveringNumber_union_le_add
#print axioms StickyKakeya4.upperMinkowskiDim_union_le_max
#print axioms StickyKakeya4.upperMinkowskiDim_accumulate_le
#print axioms StickyKakeya4.compact_countable_cover_extract_small_loss
#print axioms StickyKakeya4.compact_countable_constraints_extract_small_loss
#print axioms StickyKakeya4.compact_packingDim_lt_extract_small_loss_piece
#print axioms StickyKakeya4.compact_packingDim_le_three_extract_exact_piece
#print axioms StickyKakeya4.compact_packingDim_le_three_extract_positive_exact_piece
#print axioms StickyKakeya4.packing_carrier_extract_exact_small_loss_piece
#print axioms StickyKakeya4.packing_carrier_extract_exact_fraction_piece

#check StickyKakeya4.compact_packingDim_lt_extract_small_loss_piece
#check StickyKakeya4.compact_packingDim_le_three_extract_exact_piece
#check StickyKakeya4.compact_packingDim_le_three_extract_positive_exact_piece
#check StickyKakeya4.packing_carrier_extract_exact_small_loss_piece
#check StickyKakeya4.packing_carrier_extract_exact_fraction_piece
