import Theorems.Thm_StickyKakeya4_filtration_capacity_budget

#print axioms StickyKakeya4.FiltrationCapacityBudget.gainConstant_pos
#print axioms StickyKakeya4.FiltrationCapacityBudget.entropyRemainder_nonneg
#print axioms StickyKakeya4.FiltrationCapacityBudget.gain_le_entropyRemainder
#print axioms StickyKakeya4.FiltrationCapacityBudget.potential_nonneg
#print axioms StickyKakeya4.FiltrationCapacityBudget.node_growth_budget
#print axioms StickyKakeya4.FiltrationCapacityBudget.node_growth_budget_of_subcapacity
#print axioms StickyKakeya4.FiltrationCapacityBudget.node_growth_budget_log_capacity
#print axioms StickyKakeya4.FiltrationCapacityBudget.sum_child_values
#print axioms StickyKakeya4.FiltrationCapacityBudget.finite_tree_growth_budget
#print axioms StickyKakeya4.FiltrationCapacityBudget.finite_tree_growth_budget_of_subcapacity
#print axioms StickyKakeya4.FiltrationCapacityBudget.finite_tree_growth_budget_log_capacity
