import Theorems.Thm_StickyKakeya4_finite_transverse_menu_growth

#print axioms FiniteTransverseMenuGrowth.card_le_real_mul_of_fibers
#print axioms FiniteTransverseMenuGrowth.same_floor_abs_sub_le
#print axioms FiniteTransverseMenuGrowth.floor_fiber_card_le
#print axioms FiniteTransverseMenuGrowth.interval_population
#print axioms FiniteTransverseMenuGrowth.scalar_coefficient_control
#print axioms FiniteTransverseMenuGrowth.first_fixed_second_injective
#print axioms FiniteTransverseMenuGrowth.scalar_endpoint_fiber
#print axioms FiniteTransverseMenuGrowth.scalar_fixed_angle_growth
#print axioms FiniteTransverseMenuGrowth.scalar_menu_growth
#print axioms FiniteTransverseMenuGrowth.planar_line_ne_top
#print axioms FiniteTransverseMenuGrowth.planar_line_richness_of_subspaces
#print axioms FiniteTransverseMenuGrowth.planar_frozen_paths
#print axioms FiniteTransverseMenuGrowth.scalar_infDist_bot
#print axioms FiniteTransverseMenuGrowth.scalar_menu_growth_from_subspaces
#print axioms FiniteTransverseMenuGrowth.two_step_coordinate_error
#print axioms FiniteTransverseMenuGrowth.planar_menu_growth
