import Theorems.Thm_StickyKakeya4_finite_voronoi_real_ad_coarsening
set_option autoImplicit false
set_option warningAsError true
#print axioms FiniteVoronoiRealADCoarsening.scaled_bounds_of_ADBounds
#print axioms FiniteVoronoiRealADCoarsening.ADBounds_of_scaled_bounds
#print axioms FiniteVoronoiRealADCoarsening.cluster_scaled_population_bounds
#print axioms FiniteVoronoiRealADCoarsening.cluster_population_bounds
#print axioms FiniteVoronoiRealADCoarsening.subfamily_scaled_population_bounds
#print axioms FiniteVoronoiRealADCoarsening.global_scaled_card_le
#print axioms FiniteVoronoiRealADCoarsening.coarse_scaled_ball_bounds
#print axioms FiniteVoronoiRealADCoarsening.coarse_ADBounds
#print axioms FiniteVoronoiRealADCoarsening.exists_AD_coarsening
