import Theorems.Thm_StickyKakeya4_fixed_time_heavy_families

#print axioms StickyKakeya4.FixedTimeHeavyFamilies.exists_heavy_bush_of_slice_cover
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.positive_remainder_contains_fixed_time_heavy_piece
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.exists_disjoint_fixed_time_heavy_exhaustion
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.exists_finite_fixed_time_heavy_retention
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.ae_fixed_time_heavy_families
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.exists_fixed_time_heavy_families
#print axioms StickyKakeya4.FixedTimeHeavyFamilies.sticky_deficit_exists_common_time_whole_parent_heavy_bush_families
