import Theorems.Thm_StickyKakeya4_fixed_angle_terminal_vanishing

#check StickyKakeya4.FixedAngleTerminalVanishing.root_strict_band_eq_zero_of_ae
#check StickyKakeya4.FixedAngleTerminalVanishing.root_directionBand_eq_zero
#check StickyKakeya4.FixedAngleTerminalVanishing.root_compl_directionBand_eq_univ
#check StickyKakeya4.FixedAngleTerminalVanishing.root_compl_directionBand_le_iff
#check StickyKakeya4.FixedAngleTerminalVanishing.terminal_mass_eq_zero_of_fixed_angle
#check StickyKakeya4.FixedAngleTerminalVanishing.terminal_eq_zero_of_fixed_angle
#check StickyKakeya4.FixedAngleTerminalVanishing.terminal_mass_eq_zero_of_same_cap

#print axioms StickyKakeya4.FixedAngleTerminalVanishing.root_strict_band_eq_zero_of_ae
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.root_directionBand_eq_zero
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.root_compl_directionBand_eq_univ
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.root_compl_directionBand_le_iff
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.terminal_mass_eq_zero_of_fixed_angle
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.terminal_eq_zero_of_fixed_angle
#print axioms StickyKakeya4.FixedAngleTerminalVanishing.terminal_mass_eq_zero_of_same_cap
