import Theorems.Thm_StickyKakeya4_global_terminal_band

#check StickyKakeya4.GlobalTerminalBand.sum_le_of_disjoint_restrictions
#check StickyKakeya4.GlobalTerminalBand.sum_map_le_map_of_sum_le
#check StickyKakeya4.GlobalTerminalBand.terminal_mass_le_root_band
#check StickyKakeya4.GlobalTerminalBand.product_band_le_of_ball_bound
#check StickyKakeya4.GlobalTerminalBand.terminal_mass_le_cubic
#check StickyKakeya4.GlobalTerminalBand.terminal_mass_le_cubic_with_reversal
#check StickyKakeya4.GlobalTerminalBand.terminal_mass_le_quadratic

#print axioms StickyKakeya4.GlobalTerminalBand.sum_le_of_disjoint_restrictions
#print axioms StickyKakeya4.GlobalTerminalBand.sum_map_le_map_of_sum_le
#print axioms StickyKakeya4.GlobalTerminalBand.terminal_mass_le_root_band
#print axioms StickyKakeya4.GlobalTerminalBand.mem_directionBand_of_same_cap
#print axioms StickyKakeya4.GlobalTerminalBand.band_support_of_cap_support
#print axioms StickyKakeya4.GlobalTerminalBand.product_band_le_of_ball_bound
#print axioms StickyKakeya4.GlobalTerminalBand.product_band_le_cubic
#print axioms StickyKakeya4.GlobalTerminalBand.terminal_mass_le_product_band
#print axioms StickyKakeya4.GlobalTerminalBand.terminal_mass_le_cubic
#print axioms StickyKakeya4.GlobalTerminalBand.terminal_mass_le_cubic_with_reversal
#print axioms StickyKakeya4.GlobalTerminalBand.terminal_mass_le_quadratic
