import Theorems.Thm_StickyKakeya4_independent_flag_separation

#check @StickyKakeya4.IndependentFlagSeparation.freshExtension
#check @StickyKakeya4.IndependentFlagSeparation.fresh_labels_rectangle
#check @StickyKakeya4.IndependentFlagSeparation.fresh_extension_original
#check @StickyKakeya4.IndependentFlagSeparation.fresh_extension_observable
#check @StickyKakeya4.IndependentFlagSeparation.disintegrated_fresh_original
#check @StickyKakeya4.IndependentFlagSeparation.fresh_extension_genuine
#check @StickyKakeya4.IndependentFlagSeparation.restricted_fresh_genuine
#check @StickyKakeya4.IndependentFlagSeparation.restricted_original_apply
#check @StickyKakeya4.IndependentFlagSeparation.restricted_original_le
#check @StickyKakeya4.IndependentFlagSeparation.le_restricted_original
#check @StickyKakeya4.IndependentFlagSeparation.complement_original_ge
#check @StickyKakeya4.IndependentFlagSeparation.closeNormals
#check @StickyKakeya4.IndependentFlagSeparation.measurableSet_closeNormals
#check @StickyKakeya4.IndependentFlagSeparation.close_normals_fiber_le
#check @StickyKakeya4.IndependentFlagSeparation.close_original_le
#check @StickyKakeya4.IndependentFlagSeparation.separated_original_ge
#check @StickyKakeya4.IndependentFlagSeparation.separated_normals_ae
#check @StickyKakeya4.IndependentFlagSeparation.separated_mass_ge
#check @StickyKakeya4.IndependentFlagSeparation.separated_mass_pos
#check @StickyKakeya4.IndependentFlagSeparation.close_observable_le
#check @StickyKakeya4.IndependentFlagSeparation.separated_observable_ge
#check @StickyKakeya4.IndependentFlagSeparation.endpoint_normal_law_separation

#print axioms StickyKakeya4.IndependentFlagSeparation.freshExtension
#print axioms StickyKakeya4.IndependentFlagSeparation.fresh_labels_rectangle
#print axioms StickyKakeya4.IndependentFlagSeparation.fresh_extension_original
#print axioms StickyKakeya4.IndependentFlagSeparation.fresh_extension_observable
#print axioms StickyKakeya4.IndependentFlagSeparation.disintegrated_fresh_original
#print axioms StickyKakeya4.IndependentFlagSeparation.fresh_extension_genuine
#print axioms StickyKakeya4.IndependentFlagSeparation.restricted_fresh_genuine
#print axioms StickyKakeya4.IndependentFlagSeparation.restricted_original_apply
#print axioms StickyKakeya4.IndependentFlagSeparation.restricted_original_le
#print axioms StickyKakeya4.IndependentFlagSeparation.le_restricted_original
#print axioms StickyKakeya4.IndependentFlagSeparation.complement_original_ge
#print axioms StickyKakeya4.IndependentFlagSeparation.closeNormals
#print axioms StickyKakeya4.IndependentFlagSeparation.measurableSet_closeNormals
#print axioms StickyKakeya4.IndependentFlagSeparation.close_normals_fiber_le
#print axioms StickyKakeya4.IndependentFlagSeparation.close_original_le
#print axioms StickyKakeya4.IndependentFlagSeparation.separated_original_ge
#print axioms StickyKakeya4.IndependentFlagSeparation.separated_normals_ae
#print axioms StickyKakeya4.IndependentFlagSeparation.separated_mass_ge
#print axioms StickyKakeya4.IndependentFlagSeparation.separated_mass_pos
#print axioms StickyKakeya4.IndependentFlagSeparation.close_observable_le
#print axioms StickyKakeya4.IndependentFlagSeparation.separated_observable_ge
#print axioms StickyKakeya4.IndependentFlagSeparation.endpoint_normal_law_separation
