import Theorems.Thm_StickyKakeya4_line_tube_inverse_potential

#print axioms StickyKakeya4.LineTubeInversePotential.local_residual_tube_cover
#print axioms StickyKakeya4.LineTubeInversePotential.local_residual_tube_mass_le
#print axioms StickyKakeya4.LineTubeInversePotential.cubic_le_interpolated
#print axioms StickyKakeya4.LineTubeInversePotential.tube_le_interpolated
#print axioms StickyKakeya4.LineTubeInversePotential.local_residual_tube_mass_le_power
#print axioms StickyKakeya4.LineTubeInversePotential.inverse_integral_le_of_power_sublevel
#print axioms StickyKakeya4.LineTubeInversePotential.root_distance_pos_ae
#print axioms StickyKakeya4.LineTubeInversePotential.affine_residual_tube_inverse_potential_le
#print axioms StickyKakeya4.LineTubeInversePotential.residual_tube_inverse_potential_le
#print axioms StickyKakeya4.LineTubeInversePotential.exists_uniform_line_tube_inverse_potential
#print axioms StickyKakeya4.LineTubeInversePotential.exists_uniform_affine_line_tube_inverse_potential
