import Theorems.Thm_StickyKakeya4_literal_affine_fiber_coordinates

#print axioms LiteralAffineFiberCoordinates.actual_affine_graph
#print axioms LiteralAffineFiberCoordinates.timeCoord_dist
#print axioms LiteralAffineFiberCoordinates.timeCoord_injective
#print axioms LiteralAffineFiberCoordinates.normalCoord_as_time
#print axioms LiteralAffineFiberCoordinates.normalCoord_injective
#print axioms LiteralAffineFiberCoordinates.timeCoord_close_iff
#print axioms LiteralAffineFiberCoordinates.normalCoord_close_iff
#print axioms LiteralAffineFiberCoordinates.fiber_time_injOn
#print axioms LiteralAffineFiberCoordinates.fiberCoordinates_card
#print axioms LiteralAffineFiberCoordinates.quotientCoordinates_card
#print axioms LiteralAffineFiberCoordinates.fiberCoordinates_ball_card
#print axioms LiteralAffineFiberCoordinates.quotientCoordinates_ball_card
#print axioms LiteralAffineFiberCoordinates.actual_working_ball_bounds
#print axioms LiteralAffineFiberCoordinates.actual_global_vertex_card
#print axioms LiteralAffineFiberCoordinates.global_quotient_from_fibers
#print axioms LiteralAffineFiberCoordinates.fiberAt_normalCoord
#print axioms LiteralAffineFiberCoordinates.actual_image_eq_graph_fibers
