import Theorems.Thm_StickyKakeya4_low_intercept_entropy_escape

#check StickyKakeya4.LowInterceptEntropyEscape.HasLowInterceptEntropy
#check StickyKakeya4.LowInterceptEntropyEscape.physical_ball_mass_le_of_coveringNumber
#check StickyKakeya4.LowInterceptEntropyEscape.sourceFrontMeasure_global_ball_bound
#check StickyKakeya4.LowInterceptEntropyEscape.frontProbability_global_ball_bound
#check StickyKakeya4.LowInterceptEntropyEscape.front_dimH_eq_four_of_low_intercept_entropy

#print axioms StickyKakeya4.LowInterceptEntropyEscape.centeredInterceptImage
#print axioms StickyKakeya4.LowInterceptEntropyEscape.HasLowInterceptEntropy
#print axioms StickyKakeya4.LowInterceptEntropyEscape.fiber_mass_le_finite_cover
#print axioms StickyKakeya4.LowInterceptEntropyEscape.physical_ball_mass_le_finite_cover
#print axioms StickyKakeya4.LowInterceptEntropyEscape.geometricConstant
#print axioms StickyKakeya4.LowInterceptEntropyEscape.geometricConstant_ne_top
#print axioms StickyKakeya4.LowInterceptEntropyEscape.physical_ball_mass_le_card_mul_fourth_power
#print axioms StickyKakeya4.LowInterceptEntropyEscape.physical_ball_mass_le_of_coveringNumber
#print axioms StickyKakeya4.LowInterceptEntropyEscape.sourceFrontMeasure_global_ball_bound
#print axioms StickyKakeya4.LowInterceptEntropyEscape.frontProbability
#print axioms StickyKakeya4.LowInterceptEntropyEscape.sourceFrontMeasure_mass_ne_zero
#print axioms StickyKakeya4.LowInterceptEntropyEscape.frontProbability_isProbability
#print axioms StickyKakeya4.LowInterceptEntropyEscape.frontProbability_global_ball_bound
#print axioms StickyKakeya4.LowInterceptEntropyEscape.frontProbability_supported
#print axioms StickyKakeya4.LowInterceptEntropyEscape.front_frostman_of_low_intercept_entropy
#print axioms StickyKakeya4.LowInterceptEntropyEscape.front_dimH_eq_four_of_low_intercept_entropy
