import Theorems.Thm_StickyKakeya4_markov_endpoint_preservation

#check @StickyKakeya4.MarkovEndpointPreservation.extension_fst
#check @StickyKakeya4.MarkovEndpointPreservation.extension_endpoint
#check @StickyKakeya4.MarkovEndpointPreservation.extension_mass
#check @StickyKakeya4.MarkovEndpointPreservation.submeasure_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.restriction_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.density_le
#check @StickyKakeya4.MarkovEndpointPreservation.fractional_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.fractional_extension_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.sum_subrestrictions_le
#check @StickyKakeya4.MarkovEndpointPreservation.sum_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.sum_extensions_endpoint_le
#check @StickyKakeya4.MarkovEndpointPreservation.root_density_le_product
#check @StickyKakeya4.MarkovEndpointPreservation.root_extension_endpoint_eq
#check @StickyKakeya4.MarkovEndpointPreservation.root_extension_endpoint_le_product
#check @StickyKakeya4.MarkovEndpointPreservation.root_submeasure_endpoint_le_product
#check @StickyKakeya4.MarkovEndpointPreservation.root_disjoint_subrestrictions_endpoint_le_product

#print axioms StickyKakeya4.MarkovEndpointPreservation.extension_fst
#print axioms StickyKakeya4.MarkovEndpointPreservation.extension_endpoint
#print axioms StickyKakeya4.MarkovEndpointPreservation.extension_mass
#print axioms StickyKakeya4.MarkovEndpointPreservation.submeasure_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.restriction_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.density_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.fractional_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.fractional_extension_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.sum_subrestrictions_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.sum_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.sum_extensions_endpoint_le
#print axioms StickyKakeya4.MarkovEndpointPreservation.root_density_le_product
#print axioms StickyKakeya4.MarkovEndpointPreservation.root_extension_endpoint_eq
#print axioms StickyKakeya4.MarkovEndpointPreservation.root_extension_endpoint_le_product
#print axioms StickyKakeya4.MarkovEndpointPreservation.root_submeasure_endpoint_le_product
#print axioms StickyKakeya4.MarkovEndpointPreservation.root_disjoint_subrestrictions_endpoint_le_product
