import Theorems.Thm_StickyKakeya4_moving_focus_energy_escape

#print axioms StickyKakeya4.MovingFocusEnergyEscape.measurable_movingFocusIntercept
#print axioms StickyKakeya4.MovingFocusEnergyEscape.measurableSet_goodFocusTimes
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_le
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_isFiniteMeasure
#print axioms StickyKakeya4.MovingFocusEnergyEscape.good_time_fiber_volume_ge
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_mass_ge
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_ne_zero
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_collision_line_localization
#print axioms StickyKakeya4.MovingFocusEnergyEscape.measurableSet_rootTimeCollision
#print axioms StickyKakeya4.MovingFocusEnergyEscape.rootTimeCollision_mass_eq
#print axioms StickyKakeya4.MovingFocusEnergyEscape.rootTimeCollision_mass_le_line_potential
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_pair_sublevel_le_root_collisions
#print axioms StickyKakeya4.MovingFocusEnergyEscape.goodSourceTime_pair_sublevel_le_of_potential_bound
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_pair_sublevel_power
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_finite_pair_energy
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_finite_front_energy
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_original_front_frostman
#print axioms StickyKakeya4.MovingFocusEnergyEscape.moving_focus_original_front_dimH_eq_four
#print axioms StickyKakeya4.MovingFocusEnergyEscape.original_spacetime_map_eq_of_ae_moving_focus
#print axioms StickyKakeya4.MovingFocusEnergyEscape.original_front_dimH_eq_four_of_ae_moving_focus
#print axioms StickyKakeya4.MovingFocusEnergyEscape.original_goodSourceTime_map_eq_of_ae_moving_focus
#print axioms StickyKakeya4.MovingFocusEnergyEscape.original_finite_front_energy_of_ae_moving_focus
#print axioms StickyKakeya4.MovingFocusEnergyEscape.original_front_frostman_of_ae_moving_focus
