import Theorems.Thm_StickyKakeya4_native_a2_dilated_caller

#print axioms NativeA2DilatedCaller.dilated_native_weak_radial_graph
#print axioms NativeA2DilatedCaller.exists_uniform_dilated_native_weak_radial_graph_threshold
