import Theorems.Thm_StickyKakeya4_native_literal_scalar_bounds

#print axioms NativeLiteralScalarBounds.AllRealBounds.scalar_fibers
#print axioms NativeLiteralScalarBounds.AllRealBounds.scalar_quotient
