import Theorems.Thm_StickyKakeya4_native_tangent_grid_coarsening

#print axioms NativeTangentGridCoarsening.scalar_interval_grid_card
#print axioms NativeTangentGridCoarsening.scalar_filtered_interval_grid_card
#print axioms NativeTangentGridCoarsening.planar_rectangle_grid_card
#print axioms NativeTangentGridCoarsening.planar_filtered_rectangle_grid_card
#print axioms NativeTangentGridCoarsening.coarse_floor_interval
#print axioms NativeTangentGridCoarsening.scalar_coarse_fiber_card
#print axioms NativeTangentGridCoarsening.planar_coarse_fiber_card
#print axioms NativeTangentGridCoarsening.image_card_le_real_mul_of_fiber_images
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening_add_two
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening_add_two
#print axioms NativeTangentGridCoarsening.ratio_add_two_le_three
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening_chain
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening_chain
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening
#print axioms NativeTangentGridCoarsening.scalar_centered_grid_card
#print axioms NativeTangentGridCoarsening.planar_centered_grid_card
#print axioms NativeTangentGridCoarsening.scalar_injective_grid_centered_card
#print axioms NativeTangentGridCoarsening.planar_injective_grid_centered_card
