import Theorems.Thm_StickyKakeya4_original_shading_center_profile
import Theorems.Thm_StickyKakeya4_original_shading_box_profile
import Theorems.Thm_StickyKakeya4_original_profiled_coarse_shadings
import Theorems.Thm_StickyKakeya4_native_original_shading_width_cutoff
import Theorems.Thm_StickyKakeya4_original_dense_family_cap
import Theorems.Thm_StickyKakeya4_native_original_tube_family_caller
import Theorems.Thm_StickyKakeya4_original_densest_fiber_retention
import Theorems.Thm_StickyKakeya4_native_original_densest_scale_decay
import Theorems.Thm_StickyKakeya4_native_original_coarse_tube_family
import Theorems.Thm_StickyKakeya4_original_window_physical_cells
import Theorems.Thm_StickyKakeya4_native_original_window_kt
import Theorems.Thm_StickyKakeya4_native_scheduled_scale_selection
import Theorems.Thm_StickyKakeya4_native_scheduled_height_population
import Theorems.Thm_StickyKakeya4_original_robust_kaufman_image

#print axioms OriginalShadingCenterProfile.original_shaded_center_ball_count
#print axioms OriginalShadingCenterProfile.original_shaded_center_frostman
#print axioms OriginalShadingCenterProfile.original_shading_coefficient_one_le
#print axioms OriginalShadingBoxProfile.original_common_box_euclidean
#print axioms OriginalShadingBoxProfile.original_half_box_lift
#print axioms OriginalShadingBoxProfile.original_half_common_box_euclidean
#print axioms OriginalShadingBoxProfile.original_half_box_profile_from_centers
#print axioms OriginalProfiledCoarseShadings.original_shading_half_box_frostman
#print axioms OriginalProfiledCoarseShadings.exists_original_profiled_coarse_shadings
#print axioms NativeOriginalShadingWidthCutoff.exists_native_shading_width_cutoff
#print axioms OriginalDenseFamilyCap.original_dense_external_cap
#print axioms OriginalDenseFamilyCap.normalize_original_dense_cap
#print axioms NativeOriginalTubeFamilyCaller.exists_native_original_tube_family_threshold
#print axioms OriginalDensestFiberRetention.selected_original_fibers_le_population_square
#print axioms OriginalDensestFiberRetention.original_pair_mass_after_coarse_selection
#print axioms NativeOriginalDensestScaleDecay.original_densest_scale_decay
#print axioms NativeOriginalDensestScaleDecay.exists_original_densest_scale_cutoff
#print axioms NativeOriginalCoarseTubeFamily.exists_native_original_coarse_family_threshold
#print axioms OriginalWindowPhysicalCells.physical_cells_rectangle
#print axioms OriginalWindowPhysicalCells.same_x_window_physical_cells
#print axioms OriginalWindowPhysicalCells.original_phase_over_x_cell
#print axioms OriginalWindowPhysicalCells.original_phase_first_fiber
#print axioms NativeOriginalWindowKT.actual_window_first_fiber
#print axioms NativeOriginalWindowKT.actual_window_KT
#print axioms NativeOriginalWindowKT.actual_window_projection_KT
#print axioms NativeScheduledScaleSelection.scheduledScale_eq_pow
#print axioms NativeScheduledScaleSelection.scheduledScale_integer
#print axioms NativeScheduledScaleSelection.exists_scheduled_scale_above
#print axioms NativeScheduledScaleSelection.scheduled_law_at_selected
#print axioms NativeScheduledScaleSelection.exists_scheduled_scale_with_laws
#print axioms NativeScheduledHeightPopulation.normalizedGraph_eq_common_scaling
#print axioms NativeScheduledHeightPopulation.actual_labels_KT
#print axioms NativeScheduledHeightPopulation.selected_labels_KT
#print axioms NativeScheduledHeightPopulation.selected_height_mass_exact
#print axioms NativeScheduledHeightPopulation.selected_height_mass
#print axioms NativeScheduledHeightPopulation.scheduled_representative_error
#print axioms NativeScheduledHeightPopulation.scheduled_error_ratio
#print axioms NativeScheduledHeightPopulation.selected_population_at_nearby_mesh
#print axioms NativeScheduledHeightPopulation.exists_dyadic_selected_population
#print axioms NativeScheduledHeightPopulation.exists_scheduled_actual_B_population
#print axioms NativeScheduledHeightPopulation.scheduled_field_error
#print axioms NativeScheduledHeightPopulation.paper_scheduled_field_error
#print axioms NativeScheduledHeightPopulation.scheduled_graph_envelope
#print axioms NativeScheduledHeightPopulation.enclosing_schedule_fits_common_scaling
#print axioms NativeScheduledHeightPopulation.selected_scheduled_graph_envelope
#print axioms OriginalRobustKaufmanImage.dense_intersection
#print axioms OriginalRobustKaufmanImage.floor_image_lower
#print axioms OriginalRobustKaufmanImage.original_robust_kaufman_image
