import Theorems.Thm_StickyKakeya4_native_scalar_cover_ad
import Theorems.Thm_StickyKakeya4_native_planar_cover_lemma53
import Theorems.Thm_StickyKakeya4_native_euclidean_cover_input
import Theorems.Thm_StickyKakeya4_native_quarter_square_cover_source
import Theorems.Thm_StickyKakeya4_native_weighted_point_populations
import Theorems.Thm_StickyKakeya4_native_slice_grid_geometry
import Theorems.Thm_StickyKakeya4_native_original_slice_population
import Theorems.Thm_StickyKakeya4_native_original_slice_ball_population
import Theorems.Thm_StickyKakeya4_vector_graph_collision_energy
import Theorems.Thm_StickyKakeya4_vector_labelled_energy_bin
import Theorems.Thm_StickyKakeya4_vector_integer_bin_real_bsg
import Theorems.Thm_StickyKakeya4_vector_whole_fiber_lift
import Theorems.Thm_StickyKakeya4_vector_product_cover
import Theorems.Thm_StickyKakeya4_vector_bin_selection_tools
import Theorems.Thm_StickyKakeya4_graph_weighted_original_fiber_bin
import Theorems.Thm_StickyKakeya4_vector_graph_weighted_rounding
import Theorems.Thm_StickyKakeya4_vector_original_graph_bsg
import Theorems.Thm_StickyKakeya4_original_annular_graph_deletion
import Theorems.Thm_StickyKakeya4_original_annular_off_root_mass
import Theorems.Thm_StickyKakeya4_native_annular_parameter_budget
import Theorems.Thm_StickyKakeya4_native_original_off_root_mass
import Theorems.Thm_StickyKakeya4_native_original_step2_caller
import Theorems.Thm_StickyKakeya4_original_retained_tube_ball_profile
import Theorems.Thm_StickyKakeya4_native_quarter_scale_parameters
import Theorems.Thm_StickyKakeya4_original_angular_exponent_range
import Theorems.Thm_StickyKakeya4_bounded_original_angle_tube_transfer
import Theorems.Thm_StickyKakeya4_original_two_hop_class_tube_transfer
import Theorems.Thm_StickyKakeya4_radial_angle_periodic_cover
import Theorems.Thm_StickyKakeya4_original_radial_sine_geometry
import Theorems.Thm_StickyKakeya4_radial_angle_bin_incidence
import Theorems.Thm_StickyKakeya4_original_angular_tube_incidence
import Theorems.Thm_StickyKakeya4_original_angular_class_population
import Theorems.Thm_StickyKakeya4_original_angular_pruning_from_physical
import Theorems.Thm_StickyKakeya4_native_dyadic_mesh_selection
import Theorems.Thm_StickyKakeya4_native_original_cutoff_selection
import Theorems.Thm_StickyKakeya4_native_planar_abc_to_bsg
import Theorems.Thm_StickyKakeya4_original_euclidean_affine_avoidance
import Theorems.Thm_StickyKakeya4_original_two_hop_pair_family
import Theorems.Thm_StickyKakeya4_native_quarter_balanced_mesh
import Theorems.Thm_StickyKakeya4_native_planar_abc_fixed_exponent

#print axioms NativeScalarCoverAD.cell_capacity
#print axioms NativeScalarCoverAD.card_le_capacity_mul_image
#print axioms NativeScalarCoverAD.point_AD_to_cover_AD
#print axioms NativeScalarCoverAD.literal_to_cover
#print axioms NativeScalarCoverAD.nearly_literal_to_cover
#print axioms NativePlanarCoverLemma53.relative_dyadic_mesh
#print axioms NativePlanarCoverLemma53.native_quarter_square_cover_lemma53
#print axioms NativeEuclideanCoverInput.packingBound_pos
#print axioms NativeEuclideanCoverInput.inputConstant_ge_one
#print axioms NativeEuclideanCoverInput.euclidean_injective
#print axioms NativeEuclideanCoverInput.cell_capacity
#print axioms NativeEuclideanCoverInput.subset_card_le_cover
#print axioms NativeEuclideanCoverInput.quarter_square_euclidean_diameter
#print axioms NativeEuclideanCoverInput.native_AD_of_euclidean_cover_AD
#print axioms NativeQuarterSquareCoverSource.fixed_factor_absorption
#print axioms NativeQuarterSquareCoverSource.point_AD_mono_constant
#print axioms NativeQuarterSquareCoverSource.quarter_square_cover_source_alignment
#print axioms NativeWeightedPointPopulations.projectedWeight_pos
#print axioms NativeWeightedPointPopulations.projectedWeight_mass_preimage
#print axioms NativeWeightedPointPopulations.degree_eq_projectedWeight
#print axioms NativeWeightedPointPopulations.projected_class_mass
#print axioms NativeWeightedPointPopulations.cardinality_uniform_of_weighted_degrees
#print axioms NativeSliceGridGeometry.mem_cylinder_iff
#print axioms NativeSliceGridGeometry.mem_gridBall_iff
#print axioms NativeSliceGridGeometry.cylinder_subset_gridBall
#print axioms NativeSliceGridGeometry.abs_ediv_sub_ediv_le_one
#print axioms NativeSliceGridGeometry.coarseSpatial_mem_box_of_mem_gridBall
#print axioms NativeSliceGridGeometry.gridBall_coarseSpatial_card_le_27
#print axioms NativeSliceGridGeometry.gridBall_card_le_27_mul_cylinder
#print axioms NativeSliceGridGeometry.gridBall_card_comparable
#print axioms NativeOriginalSlicePopulation.originalPullback_subset
#print axioms NativeOriginalSlicePopulation.originalPullback_fiber
#print axioms NativeOriginalSlicePopulation.originalPullback_mass
#print axioms NativeOriginalSlicePopulation.originalPullback_bins
#print axioms NativeOriginalSlicePopulation.originalPullback_subset_kept
#print axioms NativeOriginalSlicePopulation.originalPullback_support
#print axioms NativeOriginalSlicePopulation.originalPullback_sum
#print axioms NativeOriginalSlicePopulation.originalPullback_degree
#print axioms NativeOriginalSlicePopulation.originalWeight_pos
#print axioms NativeOriginalSlicePopulation.originalWeight_total
#print axioms NativeOriginalSlicePopulation.refine_original_incidence_labels
#print axioms NativeOriginalSliceBallPopulation.original_slice_ball_population
#print axioms VectorGraphCollisionEnergy.same_planar_grid_close
#print axioms VectorGraphCollisionEnergy.graph_grid_collisions_near
#print axioms VectorGraphCollisionEnergy.original_graph_cover_near_energy
#print axioms VectorGraphCollisionEnergy.original_ABC_cover_near_energy
#print axioms VectorLabelledEnergyBin.labelled_integer_collisions_le
#print axioms VectorLabelledEnergyBin.labelled_planar_near_energy_le_fortynine
#print axioms VectorLabelledEnergyBin.exists_vector_energy_preserving_bin
#print axioms VectorLabelledEnergyBin.exists_vector_graph_energy_bin
#print axioms VectorIntegerBinRealBSG.synthesis_injective
#print axioms VectorIntegerBinRealBSG.real_grid_card
#print axioms VectorIntegerBinRealBSG.real_grid_separated
#print axioms VectorIntegerBinRealBSG.collisions_image_card
#print axioms VectorIntegerBinRealBSG.integer_energy_le_original_near
#print axioms VectorIntegerBinRealBSG.integer_bin_planar_dyadic_bsg
#print axioms VectorWholeFiberLift.selectedPairs_subset
#print axioms VectorWholeFiberLift.selectedPairs_image
#print axioms VectorWholeFiberLift.selectedPairs_whole_fiber
#print axioms VectorWholeFiberLift.selectedPairs_fiber_sum
#print axioms VectorWholeFiberLift.selectedPairs_weighted_mass
#print axioms VectorWholeFiberLift.selectedPairs_relative_mass
#print axioms VectorWholeFiberLift.selectedPairs_original_mass
#print axioms VectorProductCover.rounded_grid_add_scalar
#print axioms VectorProductCover.roundPoint_grid_add
#print axioms VectorProductCover.roundPoint_grid_triple
#print axioms VectorProductCover.grid_triple_rounding
#print axioms VectorProductCover.actual_product_triple_cover
#print axioms VectorBinSelectionTools.selectedCodes_subset
#print axioms VectorBinSelectionTools.selectedCodes_image
#print axioms VectorBinSelectionTools.selectedCodes_card
#print axioms VectorBinSelectionTools.integer_addEnergy_cap
#print axioms VectorBinSelectionTools.normalized_bin_density
#print axioms VectorBinSelectionTools.rounded_point_box_four
#print axioms VectorBinSelectionTools.coupled_bin_grid_box
#print axioms GraphWeightedOriginalFiberBin.graphPiece_product
#print axioms GraphWeightedOriginalFiberBin.collisions_mono
#print axioms GraphWeightedOriginalFiberBin.exists_graph_weighted_energy_bin
#print axioms VectorGraphWeightedRounding.original_graph_cover_grid_energy
#print axioms VectorGraphWeightedRounding.graph_grid_collisions_near_graph
#print axioms VectorGraphWeightedRounding.rounded_graph_collisions_card
#print axioms VectorGraphWeightedRounding.original_graph_cover_rounded_energy
#print axioms VectorGraphWeightedRounding.exists_vector_graph_energy_bin
#print axioms VectorOriginalGraphBSG.dyadic_half_le_one
#print axioms VectorOriginalGraphBSG.original_vector_graph_dyadic_bsg
#print axioms VectorOriginalGraphBSG.original_product_value_box
#print axioms VectorOriginalGraphBSG.original_ABC_dyadic_bsg
#print axioms OriginalAnnularGraphDeletion.physical_pair_tube_swap
#print axioms OriginalAnnularGraphDeletion.bad_pair_graph_card
#print axioms OriginalAnnularGraphDeletion.native_original_annular_graph_deletion
#print axioms OriginalAnnularOffRootMass.annular_scales_card
#print axioms OriginalAnnularOffRootMass.original_distance_annulus_cover
#print axioms OriginalAnnularOffRootMass.original_near_root_card
#print axioms NativeAnnularParameterBudget.native_annular_loss_power
#print axioms NativeAnnularParameterBudget.native_annular_top_power
#print axioms NativeAnnularParameterBudget.original_inner_ball_budget
#print axioms NativeAnnularParameterBudget.exists_original_menu_power_cutoff
#print axioms NativeOriginalOffRootMass.native_original_off_root_half
#print axioms NativeOriginalStep2Caller.exists_native_original_step2_threshold
#print axioms OriginalRetainedTubeBallProfile.retained_original_wide_tube_ball_profile
#print axioms NativeQuarterScaleParameters.exists_small_power_cutoff
#print axioms NativeQuarterScaleParameters.quarter_representative_buffer
#print axioms NativeQuarterScaleParameters.quarter_error_buffer
#print axioms NativeQuarterScaleParameters.quarter_affine_source_buffer
#print axioms NativeQuarterScaleParameters.projection_scalar_budget
#print axioms NativeQuarterScaleParameters.exists_projection_resolution_and_scales
#print axioms NativeQuarterScaleParameters.exists_quarter_parameter_cutoff
#print axioms NativeQuarterScaleParameters.fraction_exponent_choice
#print axioms NativeQuarterScaleParameters.exists_original_eta_region
#print axioms NativeQuarterScaleParameters.absorb_original_fraction_loss
#print axioms NativeQuarterScaleParameters.fixed_upper_exponent
#print axioms OriginalAngularExponentRange.original_angular_card_upper
#print axioms OriginalAngularExponentRange.original_angular_exponent_lt_two
#print axioms OriginalAngularExponentRange.uniform_angular_mesh_cost
#print axioms BoundedOriginalAngleTubeTransfer.original_complex_norm_le_two_scale
#print axioms BoundedOriginalAngleTubeTransfer.original_physical_weighted_sine
#print axioms BoundedOriginalAngleTubeTransfer.original_bounded_same_root_support_transfer
#print axioms OriginalTwoHopClassTubeTransfer.original_two_hop_angle_support_transfer
#print axioms OriginalTwoHopClassTubeTransfer.original_reverse_forward_class_support_transfer
#print axioms RadialAnglePeriodicCover.small_sine_five_intervals
#print axioms OriginalRadialSineGeometry.original_scale_le_complex_norm
#print axioms OriginalRadialSineGeometry.original_sine_residual_identity
#print axioms OriginalRadialSineGeometry.physical_tube_small_sine
#print axioms RadialAngleBinIncidence.separated_bins_small_sine_card
#print axioms RadialAngleBinIncidence.native_small_sine_bin_card
#print axioms OriginalAngularTubeIncidence.original_point_tube_incidence
#print axioms OriginalAngularTubeIncidence.original_point_tube_incidence_euclidean
#print axioms OriginalAngularClassPopulation.root_original_angle_population
#print axioms OriginalAngularClassPopulation.original_forward_class_population
#print axioms OriginalAngularPruningFromPhysical.original_reverse_class_population
#print axioms OriginalAngularPruningFromPhysical.exists_original_angular_core
#print axioms NativeDyadicMeshSelection.exists_nearby_dyadic_mesh
#print axioms NativeDyadicMeshSelection.balanced_dyadic_mesh
#print axioms NativeDyadicMeshSelection.original_KT_at_finer_mesh
#print axioms NativeDyadicMeshSelection.original_mass_at_nearby_mesh
#print axioms NativeDyadicMeshSelection.error_ratio_at_nearby_mesh
#print axioms NativeDyadicMeshSelection.exists_balanced_nearby_dyadic_mesh
#print axioms NativeDyadicMeshSelection.exists_dyadic_original_population
#print axioms NativeOriginalCutoffSelection.exists_native_mesh_cutoff
#print axioms NativeOriginalCutoffSelection.quarter_angular_packing_budget
#print axioms NativeOriginalCutoffSelection.exists_quarter_mesh_and_packing_cutoff
#print axioms NativePlanarABCToBSG.actual_output_grid_eq
#print axioms NativePlanarABCToBSG.actual_planar_input_dyadic_bsg
#print axioms NativePlanarABCToBSG.original_density_cover_ratio
#print axioms OriginalEuclideanAffineAvoidance.length2_le_twice_norm
#print axioms OriginalEuclideanAffineAvoidance.original_euclidean_avoidance_sup
#print axioms OriginalEuclideanAffineAvoidance.quarter_original_euclidean_affine_cap
#print axioms OriginalTwoHopPairFamily.mem_two_hop_pairs
#print axioms OriginalTwoHopPairFamily.original_two_hop_pair_count
#print axioms OriginalTwoHopPairFamily.original_two_hop_pair_support
#print axioms NativeQuarterBalancedMesh.balanced_quarter_mesh_bounds
#print axioms NativeQuarterBalancedMesh.exists_balanced_quarter_dyadic
#print axioms NativeQuarterBalancedMesh.native_strip_width
#print axioms NativeQuarterBalancedMesh.native_line_fraction
#print axioms NativeQuarterBalancedMesh.native_power_loss
#print axioms NativeQuarterBalancedMesh.original_B_mass_at_balanced_projection
#print axioms NativePlanarABCFixedExponent.actual_angular_constant_ge_one
#print axioms NativePlanarABCFixedExponent.exists_fixed_exponent_data
#print axioms NativePlanarABCFixedExponent.exists_zeta_exponent_data
