import Theorems.Thm_StickyKakeya4_original_three_dimensional_band_geometry
import Theorems.Thm_StickyKakeya4_original_three_dimensional_direction_grid
import Theorems.Thm_StickyKakeya4_original_three_dimensional_heavy_slabs
import Theorems.Thm_StickyKakeya4_original_three_dimensional_heavy_slice_graph
import Theorems.Thm_StickyKakeya4_original_three_dimensional_unit_slabs
import Theorems.Thm_StickyKakeya4_native_original_chart_metric
import Theorems.Thm_StickyKakeya4_native_original_parent_count
import Theorems.Thm_StickyKakeya4_native_compact_chart_reach
import Theorems.Thm_StickyKakeya4_native_compact_carrier_count
import Theorems.Thm_StickyKakeya4_native_compact_parent_retention
import Theorems.Thm_StickyKakeya4_native_dense_original_parent
import Theorems.Thm_StickyKakeya4_native_compact_parent_exponent
import Theorems.Thm_StickyKakeya4_native_original_shading_density
import Theorems.Thm_StickyKakeya4_native_dense_source_refinement
import Theorems.Thm_StickyKakeya4_original_scalar_collision_mass
import Theorems.Thm_StickyKakeya4_original_terminal_scalar_collision_geometry
import Theorems.Thm_StickyKakeya4_native_scalar_collision_window
import Theorems.Thm_StickyKakeya4_original_triple_query_counts
import Theorems.Thm_StickyKakeya4_original_transverse_query_selection
import Theorems.Thm_StickyKakeya4_original_native_transverse_queries
import Theorems.Thm_StickyKakeya4_original_cartesian_query_family
import Theorems.Thm_StickyKakeya4_original_global_projection_multiplicity
import Theorems.Thm_StickyKakeya4_original_critical_population_range
import Theorems.Thm_StickyKakeya4_native_original_compact_family_parameters
import Theorems.Thm_StickyKakeya4_native_a2_critical_tube_family
import Theorems.Thm_StickyKakeya4_native_original_shading_slack
import Theorems.Thm_StickyKakeya4_native_original_length_two_a3_data
import Theorems.Thm_StickyKakeya4_original_height_vertex_density
import Theorems.Thm_StickyKakeya4_original_terminal_collision_source_costs
import Theorems.Thm_StickyKakeya4_gkz_original_ratio_gap
import Theorems.Thm_StickyKakeya4_gkz_original_gap_energy
import Theorems.Thm_StickyKakeya4_gkz_original_gap_gain
import Theorems.Thm_StickyKakeya4_gkz_original_gap_population_gain
import Theorems.Thm_StickyKakeya4_native_original_complete_budget

#print axioms OriginalThreeDimensionalBandGeometry.root_abs_le_two
#print axioms OriginalThreeDimensionalBandGeometry.rounded_root_error
#print axioms OriginalThreeDimensionalBandGeometry.rounded_normal_band
#print axioms OriginalThreeDimensionalBandGeometry.rounded_normal_in_grid
#print axioms OriginalThreeDimensionalDirectionGrid.free_grid_value
#print axioms OriginalThreeDimensionalDirectionGrid.free_grid_mass
#print axioms OriginalThreeDimensionalDirectionGrid.normal_grid_card
#print axioms OriginalThreeDimensionalDirectionGrid.original_pair_band_mass
#print axioms OriginalThreeDimensionalHeavySlabs.own_slab_contains_band
#print axioms OriginalThreeDimensionalHeavySlabs.original_nonheavy_partner_bound
#print axioms OriginalThreeDimensionalHeavySlabs.original_nonheavy_pair_bound
#print axioms OriginalThreeDimensionalHeavySliceGraph.original_bad_incidence_double_count
#print axioms OriginalThreeDimensionalHeavySliceGraph.original_bad_incidence_bound
#print axioms OriginalThreeDimensionalHeavySliceGraph.original_heavy_slice_graph
#print axioms OriginalThreeDimensionalHeavySliceGraph.original_power_heavy_slice_graph
#print axioms OriginalThreeDimensionalUnitSlabs.normal_length_one_le
#print axioms OriginalThreeDimensionalUnitSlabs.original_normal_coefficients_unit
#print axioms OriginalThreeDimensionalUnitSlabs.original_slab_in_unit_slab
#print axioms OriginalThreeDimensionalUnitSlabs.retained_direction_original_slab
#print axioms NativeOriginalChartMetric.carrier_coordinate_le
#print axioms NativeOriginalChartMetric.slope_sub_le
#print axioms NativeOriginalChartMetric.shiftedIntercept_sub_le
#print axioms NativeOriginalParentCount.le_chartReach
#print axioms NativeOriginalParentCount.neighbours_card
#print axioms NativeOriginalParentCount.floor_neighbour
#print axioms NativeOriginalParentCount.parentLabel_mem_neighbours
#print axioms NativeOriginalParentCount.parent_count
#print axioms NativeCompactChartReach.height_offset_le_of_mark
#print axioms NativeCompactChartReach.chartReach_le_of_marks
#print axioms NativeCompactChartReach.compact_uniform_chartReach
#print axioms NativeCompactCarrierCount.compact_carrier_card_bound
#print axioms NativeCompactParentRetention.parent_count_real
#print axioms NativeCompactParentRetention.parent_bound_of_source_count
#print axioms NativeCompactParentRetention.compact_parent_bound
#print axioms NativeDenseOriginalParent.exists_mass_and_density
#print axioms NativeDenseOriginalParent.sum_parentIncidences
#print axioms NativeDenseOriginalParent.sum_backbones
#print axioms NativeDenseOriginalParent.exists_dense_parent
#print axioms NativeCompactParentExponent.compact_dense_parent_retention
#print axioms NativeOriginalShadingDensity.source_incidence_density
#print axioms NativeOriginalShadingDensity.dense_parent_density
#print axioms NativeOriginalShadingDensity.exists_source_density_cutoff
#print axioms NativeDenseSourceRefinement.refinement_tube_density
#print axioms NativeDenseSourceRefinement.original_readback_tubes
#print axioms NativeDenseSourceRefinement.dense_source_slice_population
#print axioms OriginalScalarCollisionMass.scalar_terminal_image_bound
#print axioms OriginalScalarCollisionMass.vertices_eq_original_incidence_image
#print axioms OriginalScalarCollisionMass.original_collision_label_card
#print axioms OriginalScalarCollisionMass.original_eighth_power_count
#print axioms OriginalScalarCollisionMass.original_incidence_population_collision_mass
#print axioms OriginalScalarCollisionMass.scalar_original_collision_mass
#print axioms OriginalScalarCollisionMass.original_point_degree_fiber_card
#print axioms OriginalScalarCollisionMass.original_point_degrees_total
#print axioms OriginalTerminalScalarCollisionGeometry.scalar_terminal_gap
#print axioms OriginalTerminalScalarCollisionGeometry.scalar_terminal_fiber_cap
#print axioms OriginalTerminalScalarCollisionGeometry.scalar_witness_phase_relation
#print axioms OriginalTerminalScalarCollisionGeometry.scalar_witness_grain_drift
#print axioms OriginalTerminalScalarCollisionGeometry.scalar_graph_edge_grid_relation
#print axioms NativeScalarCollisionWindow.exists_scalar_original_phase_window_graph
#print axioms OriginalTripleQueryCounts.query_eq
#print axioms OriginalTripleQueryCounts.sum_queries_eq_degrees
#print axioms OriginalTripleQueryCounts.degree_cube
#print axioms OriginalTripleQueryCounts.sum_triple_queries
#print axioms OriginalTripleQueryCounts.original_query_cubic_mass
#print axioms OriginalTransverseQuerySelection.triple_query_card_le
#print axioms OriginalTransverseQuerySelection.pair_weight_upper
#print axioms OriginalTransverseQuerySelection.close_pair_weight_bound
#print axioms OriginalTransverseQuerySelection.exists_transverse_pair_with_common_mass
#print axioms OriginalTransverseQuerySelection.triple_query_eq_inter
#print axioms OriginalTransverseQuerySelection.exists_original_transverse_common_queries
#print axioms OriginalNativeTransverseQueries.away_two_card
#print axioms OriginalNativeTransverseQueries.exists_native_transverse_common_queries
#print axioms OriginalNativeTransverseQueries.weights_lower_of_three_transverse
#print axioms OriginalCartesianQueryFamily.real_alphabet_mono
#print axioms OriginalCartesianQueryFamily.real_graph_mono
#print axioms OriginalCartesianQueryFamily.exists_original_cartesian_query_family
#print axioms OriginalGlobalProjectionMultiplicity.selected_fiber_eq
#print axioms OriginalGlobalProjectionMultiplicity.exists_original_global_projection_multiplicity
#print axioms OriginalCriticalPopulationRange.original_query_population_upper
#print axioms OriginalCriticalPopulationRange.exists_original_population_upper_cutoff
#print axioms OriginalCriticalPopulationRange.original_effective_family_exponent
#print axioms NativeOriginalCompactFamilyParameters.exists_original_compact_family_parameter_cutoff
#print axioms NativeA2CriticalTubeFamily.exists_uniform_original_critical_tube_family
#print axioms NativeOriginalShadingSlack.original_coarse_coefficient_bound
#print axioms NativeOriginalShadingSlack.exists_original_coarse_shading_slack
#print axioms NativeOriginalShadingSlack.original_coarse_profile_with_slack
#print axioms NativeOriginalLengthTwoA3Data.exists_uniform_original_length_two_family
#print axioms OriginalHeightVertexDensity.original_height_vertex_fiber
#print axioms OriginalHeightVertexDensity.incidences_le_height_vertices
#print axioms OriginalHeightVertexDensity.original_average_height_density
#print axioms OriginalHeightVertexDensity.boxed_original_height_density
#print axioms OriginalHeightVertexDensity.interval_original_height_density
#print axioms OriginalTerminalCollisionSourceCosts.scalar_label_loss_square
#print axioms OriginalTerminalCollisionSourceCosts.source_loss_power
#print axioms OriginalTerminalCollisionSourceCosts.original_collision_alpha_source_lower
#print axioms OriginalTerminalCollisionSourceCosts.scalar_collision_mass_at_source_power
#print axioms GKZOriginalRatioGap.original_ratio_mem
#print axioms GKZOriginalRatioGap.zero_one_mem_of_original_gap
#print axioms GKZOriginalRatioGap.gap_forces_close_denominator
#print axioms GKZOriginalRatioGap.grid_collision_forces_close_denominator
#print axioms GKZOriginalGapEnergy.original_gap_collision_energy
#print axioms GKZOriginalGapGain.cutoff_ratios_mono
#print axioms GKZOriginalGapGain.original_gap_image_gain
#print axioms GKZOriginalGapPopulationGain.original_gap_population_gain
#print axioms NativeOriginalCompleteBudget.original_exponent_order
#print axioms NativeOriginalCompleteBudget.original_power_le_budget
#print axioms NativeOriginalCompleteBudget.original_loss_cube_le_budget
#print axioms NativeOriginalCompleteBudget.actual_shared_mesh_ratios
#print axioms NativeOriginalCompleteBudget.exists_original_complete_budget
