import Theorems.Thm_StickyKakeya4_parent_all_real_tube_control
import Theorems.Thm_StickyKakeya4_working_scale_profile_budget
import Theorems.Thm_StickyKakeya4_normalized_quantized_patches
import Theorems.Thm_StickyKakeya4_literal_affine_fiber_coordinates
import Theorems.Thm_StickyKakeya4_real_scalar_ad_interpolation
import Theorems.Thm_StickyKakeya4_actual_scalar_ad_profiles
import Theorems.Thm_StickyKakeya4_native_original_parent_assembly
import Theorems.Thm_StickyKakeya4_native_parent_refinement
import Theorems.Thm_StickyKakeya4_native_selected_parent_preparation
import Theorems.Thm_StickyKakeya4_native_angular_cost_bound
import Theorems.Thm_StickyKakeya4_native_interpolation_cost_bound
import Theorems.Thm_StickyKakeya4_native_parameter_constants
import Theorems.Thm_StickyKakeya4_native_reference_cost_bounds
import Theorems.Thm_StickyKakeya4_native_common_envelope
import Theorems.Thm_StickyKakeya4_native_alignment_scale_separation
import Theorems.Thm_StickyKakeya4_native_alignment_parameter_budget
import Theorems.Thm_StickyKakeya4_native_envelope_growth
import Theorems.Thm_StickyKakeya4_native_source_size_bounds
import Theorems.Thm_StickyKakeya4_native_absorbed_source_envelope
import Theorems.Thm_StickyKakeya4_native_original_parent_union
import Theorems.Thm_StickyKakeya4_full_normalized_scalar_ad
import Theorems.Thm_StickyKakeya4_native_ambient_ad_geometry
import Theorems.Thm_StickyKakeya4_full_normalized_ambient_ad
import Theorems.Thm_StickyKakeya4_native_normalized_parent_output
import Theorems.Thm_StickyKakeya4_native_original_alignment_geometry
import Theorems.Thm_StickyKakeya4_native_original_ad_alignment
import Theorems.Thm_StickyKakeya4_native_literal_scalar_bounds
import Theorems.Thm_StickyKakeya4_native_uniform_output_bounds
import Theorems.Thm_StickyKakeya4_native_top_scale_selection
import Theorems.Thm_StickyKakeya4_native_final_original_alignment
import Theorems.Thm_StickyKakeya4_native_paper_alignment_scales
import Theorems.Thm_StickyKakeya4_native_literal_aligned_set
import Theorems.Thm_StickyKakeya4_native_planar_lemma53
import Theorems.Thm_StickyKakeya4_original_physical_tube_scale_selection
import Theorems.Thm_StickyKakeya4_original_densest_tube_control
import Theorems.Thm_StickyKakeya4_native_radial_densest_graph
import Theorems.Thm_StickyKakeya4_original_radial_near_diagonal
import Theorems.Thm_StickyKakeya4_native_radial_scale_consequences

#print axioms ParentAllRealTubeControl.local_moved_tube_le_profile
#print axioms ParentAllRealTubeControl.stopped_parent_long_tube
#print axioms ParentAllRealTubeControl.wide_parent_grid_card
#print axioms ParentAllRealTubeControl.stopped_parent_all_real_tube
#print axioms ParentAllRealTubeControl.normalized_parent_all_real_tube
#print axioms ParentAllRealTubeControl.quantized_chart_parent_trace_bound
#print axioms WorkingScaleProfileBudget.adjacent_gap_lower
#print axioms WorkingScaleProfileBudget.old_length_le_adjacent
#print axioms WorkingScaleProfileBudget.working_ratio
#print axioms WorkingScaleProfileBudget.working_ratio_lower
#print axioms WorkingScaleProfileBudget.old_ratio_le_working_ratio
#print axioms WorkingScaleProfileBudget.old_profile_power_le
#print axioms WorkingScaleProfileBudget.stopped_loss_le_adjacent
#print axioms NormalizedQuantizedPatches.affine_eq_smul
#print axioms NormalizedQuantizedPatches.affine_dist
#print axioms NormalizedQuantizedPatches.affine_euclidean_dist
#print axioms NormalizedQuantizedPatches.normalized_quantized_proximity
#print axioms NormalizedQuantizedPatches.normalized_image_separation
#print axioms NormalizedQuantizedPatches.exact_normalized_mesh
#print axioms NormalizedQuantizedPatches.normalized_parent_coordinates
#print axioms LiteralAffineFiberCoordinates.actual_affine_graph
#print axioms LiteralAffineFiberCoordinates.timeCoord_dist
#print axioms LiteralAffineFiberCoordinates.timeCoord_injective
#print axioms LiteralAffineFiberCoordinates.normalCoord_as_time
#print axioms LiteralAffineFiberCoordinates.normalCoord_injective
#print axioms LiteralAffineFiberCoordinates.timeCoord_close_iff
#print axioms LiteralAffineFiberCoordinates.normalCoord_close_iff
#print axioms LiteralAffineFiberCoordinates.fiber_time_injOn
#print axioms LiteralAffineFiberCoordinates.fiberCoordinates_card
#print axioms LiteralAffineFiberCoordinates.quotientCoordinates_card
#print axioms LiteralAffineFiberCoordinates.fiberCoordinates_ball_card
#print axioms LiteralAffineFiberCoordinates.quotientCoordinates_ball_card
#print axioms LiteralAffineFiberCoordinates.actual_working_ball_bounds
#print axioms LiteralAffineFiberCoordinates.actual_global_vertex_card
#print axioms LiteralAffineFiberCoordinates.global_quotient_from_fibers
#print axioms LiteralAffineFiberCoordinates.fiberAt_normalCoord
#print axioms LiteralAffineFiberCoordinates.actual_image_eq_graph_fibers
#print axioms RealScalarADInterpolation.ballCount_mono
#print axioms RealScalarADInterpolation.ballCount_nonneg
#print axioms RealScalarADInterpolation.scalePower_eq
#print axioms RealScalarADInterpolation.real_ball_interpolation
#print axioms RealScalarADInterpolation.top_scale_extension
#print axioms ActualScalarADProfiles.parent_time_labels_close
#print axioms ActualScalarADProfiles.fiberBall_top_eq
#print axioms ActualScalarADProfiles.fiber_ballCount_eq
#print axioms ActualScalarADProfiles.quotient_ballCount_eq
#print axioms ActualScalarADProfiles.normalized_full_ball_interpolation
#print axioms ActualScalarADProfiles.fiber_real_ball_bounds
#print axioms ActualScalarADProfiles.quotient_real_ball_bounds
#print axioms NativeOriginalParentAssembly.chartPosition_injective
#print axioms NativeOriginalParentAssembly.chartPosition_mem
#print axioms NativeOriginalParentAssembly.chartPosition_grid_card
#print axioms NativeOriginalParentAssembly.chartPosition_same_cell
#print axioms NativeOriginalParentAssembly.parent_subset
#print axioms NativeOriginalParentAssembly.parent_chart_span
#print axioms NativeOriginalParentAssembly.parent_chart_diameter
#print axioms NativeOriginalParentAssembly.parent_image_subset
#print axioms NativeOriginalParentAssembly.physical_contacts
#print axioms NativeParentRefinement.quantizer_cap_total
#print axioms NativeParentRefinement.density_lower_from_parent_mass
#print axioms NativeParentRefinement.refine_parent
#print axioms NativeSelectedParentPreparation.exists_original_AD_selection
#print axioms NativeAngularCostBound.gap_le_floor_add_one
#print axioms NativeAngularCostBound.actual_angular_menu_le_extent
#print axioms NativeAngularCostBound.angularBudget_le_root
#print axioms NativeAngularCostBound.angularCost_le_extent_root
#print axioms NativeInterpolationCostBound.real_interpolation_cost_upper
#print axioms NativeInterpolationCostBound.full_interpolation_cost_upper
#print axioms NativeParameterConstants.density_cost_expand
#print axioms NativeParameterConstants.column_cost_expand
#print axioms NativeParameterConstants.spatial_squared
#print axioms NativeParameterConstants.spatial_times_K_sq
#print axioms NativeReferenceCostBounds.spatial_cost_upper
#print axioms NativeReferenceCostBounds.ad_cost_upper
#print axioms NativeReferenceCostBounds.column_cost_upper
#print axioms NativeReferenceCostBounds.density_cost_upper
#print axioms NativeReferenceCostBounds.stopped_loss_le_output_extent
#print axioms NativeCommonEnvelope.productBound_eq_envelope
#print axioms NativeCommonEnvelope.profileCoefficient_ge_one
#print axioms NativeCommonEnvelope.profileBound_ge_one
#print axioms NativeCommonEnvelope.ambientBound_ge_one
#print axioms NativeCommonEnvelope.columnBound_ge_one
#print axioms NativeCommonEnvelope.tubeBound_ge_one
#print axioms NativeCommonEnvelope.densityBound_ge_one
#print axioms NativeCommonEnvelope.interpolationBound_ge_one
#print axioms NativeCommonEnvelope.comparisonBound_ge_one
#print axioms NativeCommonEnvelope.refinementCost_ge_one
#print axioms NativeCommonEnvelope.retentionCost_ge_one
#print axioms NativeCommonEnvelope.fixedCoefficient_nonneg
#print axioms NativeCommonEnvelope.actual_cost_bounds
#print axioms NativeCommonEnvelope.retention_le_comparison_density
#print axioms NativeCommonEnvelope.product_dominates_comparison_density
#print axioms NativeCommonEnvelope.product_dominates_tube
#print axioms NativeAlignmentScaleSeparation.top_bracket_lower
#print axioms NativeAlignmentScaleSeparation.root_of_nat_power
#print axioms NativeAlignmentScaleSeparation.original_delta_output_separation
#print axioms NativeAlignmentParameterBudget.exists_nat_budget
#print axioms NativeAlignmentParameterBudget.exists_choice
#print axioms NativeAlignmentParameterBudget.absorb_common_envelope
#print axioms NativeEnvelopeGrowth.powers_expand
#print axioms NativeEnvelopeGrowth.envelope_le_growth
#print axioms NativeEnvelopeGrowth.output_extent_lower
#print axioms NativeSourceSizeBounds.inv_delta_le_pow
#print axioms NativeSourceSizeBounds.source_card_le_inv_cube
#print axioms NativeSourceSizeBounds.source_card_le_pow
#print axioms NativeSourceSizeBounds.radix_four_le
#print axioms NativeSourceSizeBounds.card_le_radix_pow
#print axioms NativeSourceSizeBounds.radix_le_four_root
#print axioms NativeSourceSizeBounds.radix_le_dyadic
#print axioms NativeSourceSizeBounds.K_pow_eighteen_le
#print axioms NativeSourceSizeBounds.rank_le_linear
#print axioms NativeSourceSizeBounds.epoch_factor_le
#print axioms NativeSourceSizeBounds.epoch_factor_real_le
#print axioms NativeSourceSizeBounds.index_card_real_one_le
#print axioms NativeSourceSizeBounds.epoch_cost_one_le
#print axioms NativeSourceSizeBounds.epoch_cost_real_one_le
#print axioms NativeAbsorbedSourceEnvelope.source_envelope_absorbed
#print axioms NativeOriginalParentUnion.originalPullback_image
#print axioms NativeOriginalParentUnion.originalPullback_subset
#print axioms NativeOriginalParentUnion.originalPullback_card
#print axioms NativeOriginalParentUnion.glue_parent_subsets
#print axioms NativeOriginalParentUnion.isolate_labelled_parents
#print axioms NativeOriginalParentUnion.Selection.retain_original_points
#print axioms FullNormalizedScalarAD.fiber_normalized_AD
#print axioms FullNormalizedScalarAD.quotient_normalized_AD
#print axioms NativeAmbientADGeometry.rawPoint_injective
#print axioms NativeAmbientADGeometry.rawPoint_close_iff
#print axioms NativeAmbientADGeometry.actualPoint_injective
#print axioms NativeAmbientADGeometry.image_ball_card
#print axioms NativeAmbientADGeometry.rawPoint_ball_card
#print axioms NativeAmbientADGeometry.raw_close_imp_actual_close
#print axioms NativeAmbientADGeometry.actual_close_imp_raw_close
#print axioms FullNormalizedAmbientAD.realInterpolationLoss_ge_one
#print axioms FullNormalizedAmbientAD.raw_ball_le_actual
#print axioms FullNormalizedAmbientAD.actual_ball_le_raw
#print axioms FullNormalizedAmbientAD.raw_real_ball_bounds
#print axioms FullNormalizedAmbientAD.ambient_normalized_AD
#print axioms NativeNormalizedParentOutput.refined_parent_all_real_bounds
#print axioms NativeOriginalAlignmentGeometry.refined_parent_near_graph
#print axioms NativeOriginalADAlignment.exists_original_AD_near_alignment
#print axioms NativeLiteralScalarBounds.AllRealBounds.scalar_fibers
#print axioms NativeLiteralScalarBounds.AllRealBounds.scalar_quotient
#print axioms NativeUniformOutputBounds.lower_count_absorption
#print axioms NativeUniformOutputBounds.raw_power_eq
#print axioms NativeUniformOutputBounds.AllRealBounds.to_uniform
#print axioms NativeUniformOutputBounds.majorant_products
#print axioms NativeUniformOutputBounds.AllRealBounds.to_uniform_majorants
#print axioms NativeUniformOutputBounds.UniformBounds.mono
#print axioms NativeTopScaleSelection.exists_top_scale
#print axioms NativeTopScaleSelection.deltaThreshold_pos
#print axioms NativeTopScaleSelection.choose_top_scale
#print axioms NativeTopScaleSelection.exists_delta0
#print axioms NativeFinalOriginalAlignment.exists_dyadic_original_near_alignment
#print axioms NativeFinalOriginalAlignment.exists_original_near_alignment
#print axioms NativeFinalOriginalAlignment.original_AD_near_alignment
#print axioms NativePaperAlignmentScales.retained_subset
#print axioms NativePaperAlignmentScales.retained_card
#print axioms NativePaperAlignmentScales.retained_nonempty
#print axioms NativePaperAlignmentScales.originalBall_eq_localBall
#print axioms NativePaperAlignmentScales.originalBall_nonempty
#print axioms NativePaperAlignmentScales.normalization_apply
#print axioms NativePaperAlignmentScales.normalized_localBall
#print axioms NativePaperAlignmentScales.normalized_localBall_bounded
#print axioms NativePaperAlignmentScales.output_scale_facts
#print axioms NativePaperAlignmentScales.output_mesh_identity
#print axioms NativePaperAlignmentScales.retention_in_output_mesh
#print axioms NativePaperAlignmentScales.retained_delta_power
#print axioms NativePaperAlignmentScales.output_scales_dyadic
#print axioms NativeLiteralAlignedSet.ballCount_eq_carrierBall
#print axioms NativeLiteralAlignedSet.quotient_fiber_nonempty
#print axioms NativeLiteralAlignedSet.normalizedImage_eq_vertex_image
#print axioms NativeLiteralAlignedSet.normalizedImage_euclidean_eq
#print axioms NativeLiteralAlignedSet.uniform_ambient_AD
#print axioms NativeLiteralAlignedSet.of_nearGraph_uniform
#print axioms NativeLiteralAlignedSet.nearGraph_source_bounded
#print axioms NativeLiteralAlignedSet.nearly_of_nearGraph_uniform
#print axioms NativePlanarLemma53.nearAlignment_to_original_points
#print axioms NativePlanarLemma53.native_planar_lemma53
#print axioms NativePlanarLemma53.quarter_square_diameter
#print axioms NativePlanarLemma53.native_quarter_square_lemma53
#print axioms OriginalPhysicalTubeScaleSelection.physical_tube_mono
#print axioms OriginalPhysicalTubeScaleSelection.original_tube_card_bounds
#print axioms OriginalPhysicalTubeScaleSelection.dyadic_radius_cover
#print axioms OriginalPhysicalTubeScaleSelection.chosen_scale_spec
#print axioms OriginalPhysicalTubeScaleSelection.exists_original_densest_graph_bin
#print axioms OriginalDensestTubeControl.scale_menu_bounds
#print axioms OriginalDensestTubeControl.original_larger_width_control
#print axioms OriginalDensestTubeControl.original_violation_forces_large_score
#print axioms NativeRadialDensestGraph.exists_original_dyadic_mesh
#print axioms NativeRadialDensestGraph.exists_native_densest_original_graph
#print axioms OriginalRadialNearDiagonal.original_separation_radius
#print axioms OriginalRadialNearDiagonal.remove_original_near_diagonal
#print axioms NativeRadialScaleConsequences.selected_scale_upper
#print axioms NativeRadialScaleConsequences.original_reciprocal_width_control
