import Theorems.Thm_StickyKakeya4_native_separated_fractional_patches

#print axioms NativeSeparatedFractionalPatches.pairPoint_dist
#print axioms NativeSeparatedFractionalPatches.pairPoint_injective
#print axioms NativeSeparatedFractionalPatches.pairPoint_realized
#print axioms NativeSeparatedFractionalPatches.pairPoint_quantized
#print axioms NativeSeparatedFractionalPatches.quantized_coordinate_movement
#print axioms NativeSeparatedFractionalPatches.quantized_euclidean_movement
#print axioms NativeSeparatedFractionalPatches.exists_separated_source_residue
#print axioms NativeSeparatedFractionalPatches.quantized_image_proximity
#print axioms NativeSeparatedFractionalPatches.isolate_original_parent_patches
#print axioms NativeSeparatedFractionalPatches.exists_native_separated_fractional_refinement
