import Theorems.Thm_StickyKakeya4_no_frostman_uniform_hairbrush

#print axioms StickyKakeya4.NoFrostmanUniformHairbrush.exact_contact_eq_affine_focus
#print axioms StickyKakeya4.NoFrostmanUniformHairbrush.exact_hairbrush_null_of_front_dimH_ne_four
#print axioms StickyKakeya4.NoFrostmanUniformHairbrush.uniform_hairbrush_decay_of_front_dimH_ne_four
#print axioms StickyKakeya4.NoFrostmanUniformHairbrush.sticky_datum_exists_actual_uniform_hairbrush_decay
#check StickyKakeya4.NoFrostmanUniformHairbrush.sticky_datum_exists_actual_uniform_hairbrush_decay
