import Theorems.Thm_StickyKakeya4_normalized_target_growth

#print axioms StickyKakeya4.NormalizedTargetGrowth.targetDensity_lower
#print axioms StickyKakeya4.NormalizedTargetGrowth.normalized_measure_le_old_measure
#print axioms StickyKakeya4.NormalizedTargetGrowth.normalized_positive_implies_old_positive
#print axioms StickyKakeya4.NormalizedTargetGrowth.multiplicity_le_card
#print axioms StickyKakeya4.NormalizedTargetGrowth.finite_normalized_measure
#print axioms StickyKakeya4.NormalizedTargetGrowth.normalized_low_support_growth
#print axioms StickyKakeya4.NormalizedTargetGrowth.layer_free_growth_or_positive_old_star
#print axioms StickyKakeya4.NormalizedTargetGrowth.stationary_atom_le
#print axioms StickyKakeya4.NormalizedTargetGrowth.stationary_four_distinct_probability_ge_half
#print axioms StickyKakeya4.NormalizedTargetGrowth.stationary_ennreal_four_distinct_probability_ge_half
