import Theorems.Thm_StickyKakeya4_north_slope_direction_density

set_option autoImplicit false

#print axioms StickyKakeya4.ActualSlopeSource.northSlopeLift_norm_le_two
#print axioms StickyKakeya4.ActualSlopeSource.northSlopeDirection_fourth_ge_half_of_norm_le_one
#print axioms StickyKakeya4.ActualSlopeSource.northSlopeDirection_inverse_dist_le_six_mul
#print axioms StickyKakeya4.ActualSlopeSource.northSlopeDirection_cap_preimage_subset_ball
#print axioms StickyKakeya4.ActualSlopeSource.northSlopeDirection_map_ball_le_cubic
#print axioms StickyKakeya4.ActualSlopeSource.exists_northSlopeDirection_cubic_density

#check StickyKakeya4.ActualSlopeSource.northSlopeDirection_map_ball_le_cubic
#check StickyKakeya4.ActualSlopeSource.exists_northSlopeDirection_cubic_density
