import Theorems.Thm_StickyKakeya4_old_neighbor_disintegration

#check @StickyKakeya4.OldNeighborDisintegration.oldNeighbor
#check @StickyKakeya4.OldNeighborDisintegration.oldNeighbor_isMarkov
#check @StickyKakeya4.OldNeighborDisintegration.old_neighbor_disintegration
#check @StickyKakeya4.OldNeighborDisintegration.old_neighbor_mass
#check @StickyKakeya4.OldNeighborDisintegration.old_neighbor_rectangle
#check @StickyKakeya4.OldNeighborDisintegration.labeled_old_endpoint_eq
#check @StickyKakeya4.OldNeighborDisintegration.labeled_old_observable_eq
#check @StickyKakeya4.OldNeighborDisintegration.root_source_density
#check @StickyKakeya4.OldNeighborDisintegration.root_isFinite
#check @StickyKakeya4.OldNeighborDisintegration.root_source_le_scaled
#check @StickyKakeya4.OldNeighborDisintegration.root_source_le
#check @StickyKakeya4.OldNeighborDisintegration.rootOldNeighbor
#check @StickyKakeya4.OldNeighborDisintegration.rootOldNeighbor_isMarkov
#check @StickyKakeya4.OldNeighborDisintegration.root_disintegration
#check @StickyKakeya4.OldNeighborDisintegration.root_degree_disintegration
#check @StickyKakeya4.OldNeighborDisintegration.root_labeled_endpoint_eq
#check @StickyKakeya4.OldNeighborDisintegration.root_labeled_endpoint_le_product

#print axioms StickyKakeya4.OldNeighborDisintegration.oldNeighbor
#print axioms StickyKakeya4.OldNeighborDisintegration.oldNeighbor_isMarkov
#print axioms StickyKakeya4.OldNeighborDisintegration.old_neighbor_disintegration
#print axioms StickyKakeya4.OldNeighborDisintegration.old_neighbor_mass
#print axioms StickyKakeya4.OldNeighborDisintegration.old_neighbor_rectangle
#print axioms StickyKakeya4.OldNeighborDisintegration.labeled_old_endpoint_eq
#print axioms StickyKakeya4.OldNeighborDisintegration.labeled_old_observable_eq
#print axioms StickyKakeya4.OldNeighborDisintegration.root_source_density
#print axioms StickyKakeya4.OldNeighborDisintegration.root_isFinite
#print axioms StickyKakeya4.OldNeighborDisintegration.root_source_le_scaled
#print axioms StickyKakeya4.OldNeighborDisintegration.root_source_le
#print axioms StickyKakeya4.OldNeighborDisintegration.rootOldNeighbor
#print axioms StickyKakeya4.OldNeighborDisintegration.rootOldNeighbor_isMarkov
#print axioms StickyKakeya4.OldNeighborDisintegration.root_disintegration
#print axioms StickyKakeya4.OldNeighborDisintegration.root_degree_disintegration
#print axioms StickyKakeya4.OldNeighborDisintegration.root_labeled_endpoint_eq
#print axioms StickyKakeya4.OldNeighborDisintegration.root_labeled_endpoint_le_product
