import Theorems.Thm_StickyKakeya4_gkz_finite_halving_net
import Theorems.Thm_StickyKakeya4_gkz_finite_gap_dichotomy
import Theorems.Thm_StickyKakeya4_gkz_original_ratio_dichotomy
import Theorems.Thm_StickyKakeya4_gkz_original_dense_ratio_selection
import Theorems.Thm_StickyKakeya4_gkz_original_short_denominator_energy
import Theorems.Thm_StickyKakeya4_gkz_original_large_denominator_energy
import Theorems.Thm_StickyKakeya4_gkz_original_dense_energy
import Theorems.Thm_StickyKakeya4_gkz_original_dense_gain
import Theorems.Thm_StickyKakeya4_gkz_original_bounded_gap_coefficients
import Theorems.Thm_StickyKakeya4_gkz_original_linear_expansion
import Theorems.Thm_StickyKakeya4_native_original_height_vertices
import Theorems.Thm_StickyKakeya4_native_source_height_density
import Theorems.Thm_StickyKakeya4_native_scheduled_quarter_geometry
import Theorems.Thm_StickyKakeya4_original_incidence_height_population
import Theorems.Thm_StickyKakeya4_native_scheduled_uniform_abc_input
import Theorems.Thm_StickyKakeya4_original_retained_incidence_degree
import Theorems.Thm_StickyKakeya4_native_original_ancestor_pruning
import Theorems.Thm_StickyKakeya4_native_compact_ancestor_budget
import Theorems.Thm_StickyKakeya4_native_original_pruned_mass
import Theorems.Thm_StickyKakeya4_native_pruning_mass_budget
import Theorems.Thm_StickyKakeya4_native_dyadic_pruning_cutoff
import Theorems.Thm_StickyKakeya4_native_pruned_power_constants
import Theorems.Thm_StickyKakeya4_native_compact_dyadic_source
import Theorems.Thm_StickyKakeya4_native_compact_pruned_parameters
import Theorems.Thm_StickyKakeya4_native_compact_ancestor_regularity
import Theorems.Thm_StickyKakeya4_native_dyadic_parent_cells
import Theorems.Thm_StickyKakeya4_native_compact_occupied_ancestors
import Theorems.Thm_StickyKakeya4_native_original_slope_cube_packing
import Theorems.Thm_StickyKakeya4_original_three_dimensional_unit_normals
import Theorems.Thm_StickyKakeya4_original_three_dimensional_cap_coordinates
import Theorems.Thm_StickyKakeya4_original_three_dimensional_tube_slab
import Theorems.Thm_StickyKakeya4_original_three_dimensional_slice_maximizer
import Theorems.Thm_StickyKakeya4_original_three_dimensional_tube_cover
import Theorems.Thm_StickyKakeya4_original_three_dimensional_tube_frostman
import Theorems.Thm_StickyKakeya4_original_three_dimensional_small_slice_branch
import Theorems.Thm_StickyKakeya4_native_three_dimensional_small_slice

#print axioms GKZFiniteHalvingNet.original_unit_interval_approximation
#print axioms GKZFiniteHalvingNet.gridPoint_left
#print axioms GKZFiniteHalvingNet.gridPoint_right
#print axioms GKZFiniteHalvingNet.original_dyadic_net
#print axioms GKZFiniteGapDichotomy.original_net_floor_count
#print axioms GKZFiniteGapDichotomy.original_gap_or_dense
#print axioms GKZOriginalRatioDichotomy.original_distant_pair
#print axioms GKZOriginalRatioDichotomy.original_ratio_gap_or_dense
#print axioms GKZOriginalDenseRatioSelection.exists_original_light_window
#print axioms GKZOriginalDenseRatioSelection.exists_original_light_ratio
#print axioms GKZOriginalShortDenominatorEnergy.original_short_denominator_energy
#print axioms GKZOriginalLargeDenominatorEnergy.original_collision_ratio_close
#print axioms GKZOriginalLargeDenominatorEnergy.original_large_denominator_energy
#print axioms GKZOriginalDenseEnergy.exists_original_dense_energy
#print axioms GKZOriginalDenseGain.exists_original_dense_image_gain
#print axioms GKZOriginalBoundedGapCoefficients.original_bounded_ratio_gap_or_dense
#print axioms GKZOriginalLinearExpansion.original_linear_expansion_alternative
#print axioms NativeOriginalHeightVertices.mem_pointTube
#print axioms NativeOriginalHeightVertices.pointTube_card
#print axioms NativeOriginalHeightVertices.pointTube_tubes
#print axioms NativeOriginalHeightVertices.height_index_eq
#print axioms NativeOriginalHeightVertices.floor_height
#print axioms NativeOriginalHeightVertices.pointsAt_bound
#print axioms NativeOriginalHeightVertices.heights_bound
#print axioms NativeOriginalHeightVertices.original_height_vertex_density
#print axioms NativeSourceHeightDensity.actual_source_height_vertex_density
#print axioms NativeScheduledQuarterGeometry.scheduled_quarter_bounds
#print axioms NativeScheduledQuarterGeometry.scheduled_quarter_balanced_bounds
#print axioms NativeScheduledQuarterGeometry.exists_scheduled_quarter_dyadic_cutoff
#print axioms NativeScheduledQuarterGeometry.scheduled_angular_exponent_lt_two
#print axioms OriginalIncidenceHeightPopulation.original_vertices_subset_product
#print axioms OriginalIncidenceHeightPopulation.original_incidence_height_product
#print axioms OriginalIncidenceHeightPopulation.original_fine_height_mass
#print axioms OriginalIncidenceHeightPopulation.original_fine_height_mass_of_global_density
#print axioms NativeScheduledUniformABCInput.exists_scheduled_source_uniform_ABC
#print axioms OriginalRetainedIncidenceDegree.retained_original_aggregate_degree
#print axioms OriginalRetainedIncidenceDegree.scalar_collision_mass_with_degree_retention
#print axioms OriginalRetainedIncidenceDegree.collision_source_exponent_with_degree_retention
#print axioms OriginalRetainedIncidenceDegree.scalar_collision_source_power_after_refinement
#print axioms NativeOriginalAncestorPruning.original_parent_pruning
#print axioms NativeCompactAncestorBudget.active_scale_budget
#print axioms NativeCompactAncestorBudget.cell_target_charge
#print axioms NativeCompactAncestorBudget.compact_original_ancestor_pruning
#print axioms NativeOriginalPrunedMass.volumeConstant_pos
#print axioms NativeOriginalPrunedMass.tube_volume_upper
#print axioms NativeOriginalPrunedMass.shadingMass_upper
#print axioms NativeOriginalPrunedMass.shadingMass_ne_top
#print axioms NativeOriginalPrunedMass.shadingMass_partition
#print axioms NativeOriginalPrunedMass.tubeMass_le_total
#print axioms NativeOriginalPrunedMass.retained_shading_density
#print axioms NativeOriginalPrunedMass.retained_convexWolff
#print axioms NativePruningMassBudget.deleted_card_le
#print axioms NativePruningMassBudget.source_tube_density_lower
#print axioms NativePruningMassBudget.removed_mass_small
#print axioms NativePruningMassBudget.half_card_of_loss_budget
#print axioms NativeDyadicPruningCutoff.dyadic_depth_log
#print axioms NativeDyadicPruningCutoff.exists_dyadic_pruning_cutoff
#print axioms NativePrunedPowerConstants.exponent_coefficient
#print axioms NativePrunedPowerConstants.retained_density_power
#print axioms NativePrunedPowerConstants.retained_CW_power
#print axioms NativeCompactDyadicSource.compact_original_dyadic_source
#print axioms NativeCompactPrunedParameters.compact_pruned_parameter_source
#print axioms NativeCompactAncestorRegularity.dyadic_parent_scale
#print axioms NativeCompactAncestorRegularity.compact_original_ancestor_regularization
#print axioms NativeDyadicParentCells.floor_dyadic_ancestor
#print axioms NativeDyadicParentCells.parent_ancestor_eq
#print axioms NativeDyadicParentCells.image_parent_fiber_eq_descendants
#print axioms NativeDyadicParentCells.dyadic_fine_scale
#print axioms NativeDyadicParentCells.finest_cell_occupancy
#print axioms NativeDyadicParentCells.descendants_card_comparison
#print axioms NativeCompactOccupiedAncestors.compact_original_occupied_ancestors
#print axioms NativeOriginalSlopeCubePacking.original_slope_eq_north
#print axioms NativeOriginalSlopeCubePacking.normalize_original_slope
#print axioms NativeOriginalSlopeCubePacking.direction_dist_le_eight_slope_dist
#print axioms NativeOriginalSlopeCubePacking.direction_dist_le_eight_slope_norm
#print axioms NativeOriginalSlopeCubePacking.slopeGrid_injOn
#print axioms NativeOriginalSlopeCubePacking.slopeGrid_mem_gridBox
#print axioms NativeOriginalSlopeCubePacking.gridBox_card_le
#print axioms NativeOriginalSlopeCubePacking.original_cube_card_le
#print axioms NativeOriginalSlopeCubePacking.original_cube_card_le_add_one
#print axioms NativeOriginalSlopeCubePacking.original_cube_card_le_ratio
#print axioms NativeOriginalSlopeCubePacking.native_cube_card_le_ratio
#print axioms NativeOriginalSlopeCubePacking.backbone_slope_cube
#print axioms NativeOriginalSlopeCubePacking.native_backbone_card_le
#print axioms NativeOriginalSlopeCubePacking.native_retained_parent_card_le
#print axioms OriginalThreeDimensionalUnitNormals.original_unit_normal_square
#print axioms OriginalThreeDimensionalUnitNormals.original_unit_normal_dot
#print axioms OriginalThreeDimensionalUnitNormals.unit_normal_chart_injective
#print axioms OriginalThreeDimensionalUnitNormals.original_normal_label_count
#print axioms OriginalThreeDimensionalUnitNormals.retained_actual_unit_normals
#print axioms OriginalThreeDimensionalUnitNormals.original_unit_normal_heavy_witness
#print axioms OriginalThreeDimensionalCapCoordinates.actual_grid_coefficients
#print axioms OriginalThreeDimensionalCapCoordinates.actual_normal_length_le_five
#print axioms OriginalThreeDimensionalCapCoordinates.original_normal_cap_coordinates
#print axioms OriginalThreeDimensionalTubeSlab.original_coordinate_le_distance
#print axioms OriginalThreeDimensionalTubeSlab.exists_original_large_coordinate
#print axioms OriginalThreeDimensionalTubeSlab.original_affine_parameter_bound
#print axioms OriginalThreeDimensionalTubeSlab.original_physical_tube_in_unit_slab
#print axioms OriginalThreeDimensionalTubeSlab.retained_heavy_slab_contains_original_tube
#print axioms OriginalThreeDimensionalSliceMaximizer.original_physical_tube3_mono
#print axioms OriginalThreeDimensionalSliceMaximizer.original_slice_annular_half_mass
#print axioms OriginalThreeDimensionalSliceMaximizer.exists_original_slice_maximizer_with_boundary
#print axioms OriginalThreeDimensionalTubeCover.original_tube_coordinate_fiber_diameter
#print axioms OriginalThreeDimensionalTubeCover.exists_original_tube_ball_centers
#print axioms OriginalThreeDimensionalTubeFrostman.original_tube_two_frostman_count
#print axioms OriginalThreeDimensionalTubeFrostman.original_rich_tube_scale_bound
#print axioms OriginalThreeDimensionalTubeFrostman.exists_original_rich_tube_scale_cutoff
#print axioms OriginalThreeDimensionalSmallSliceBranch.exists_original_concentrated_slice_radius
#print axioms NativeThreeDimensionalSmallSlice.exists_uniform_original_slice_contraction
#print axioms NativeThreeDimensionalSmallSlice.exists_native_original_small_slice_threshold
