import Theorems.Thm_StickyKakeya4_original_three_dimensional_energy_slice_witness
import Theorems.Thm_StickyKakeya4_original_three_dimensional_marked_slice_witness
import Theorems.Thm_StickyKakeya4_original_three_dimensional_marked_endpoint_carrier
import Theorems.Thm_StickyKakeya4_original_planar_tube_pair_count
import Theorems.Thm_StickyKakeya4_original_planar_tube_energy
import Theorems.Thm_StickyKakeya4_original_planar_tube_parameters
import Theorems.Thm_StickyKakeya4_original_planar_tube_chart
import Theorems.Thm_StickyKakeya4_original_tube_core_reinforcement
import Theorems.Thm_StickyKakeya4_original_planar_chart_tube_energy
import Theorems.Thm_StickyKakeya4_original_planar_core_richness
import Theorems.Thm_StickyKakeya4_original_three_dimensional_slab_projection
import Theorems.Thm_StickyKakeya4_original_finite_cell_weights
import Theorems.Thm_StickyKakeya4_original_three_dimensional_projection_cells
import Theorems.Thm_StickyKakeya4_original_three_dimensional_weighted_planar_projection
import Theorems.Thm_StickyKakeya4_original_three_dimensional_planar_box_projection
import Theorems.Thm_StickyKakeya4_original_three_dimensional_marked_planar_core
import Theorems.Thm_StickyKakeya4_original_three_dimensional_planar_tube_projection
import Theorems.Thm_StickyKakeya4_original_three_dimensional_planar_tube_lift
import Theorems.Thm_StickyKakeya4_original_three_dimensional_physical_core_richness
import Theorems.Thm_StickyKakeya4_original_three_dimensional_nonconcentrated_row_mass
import Theorems.Thm_StickyKakeya4_original_three_dimensional_chosen_slice_tube
import Theorems.Thm_StickyKakeya4_native_original_bounded_nonconcentrated_rows
import Theorems.Thm_StickyKakeya4_original_three_dimensional_native_reinforcement_budget
import Theorems.Thm_StickyKakeya4_native_fixed_compact_normalized_near_height
import Theorems.Thm_StickyKakeya4_native_fixed_compact_multiplicity
import Theorems.Thm_StickyKakeya4_native_uniform_multiplicity_restriction
import Theorems.Thm_StickyKakeya4_native_original_slice_restriction
import Theorems.Thm_StickyKakeya4_native_incidence_multiplicity_tower
import Theorems.Thm_StickyKakeya4_native_coarse_slope_occupancy
import Theorems.Thm_StickyKakeya4_original_height_window_macro_cells
import Theorems.Thm_StickyKakeya4_original_literal_macro_slice_upper
import Theorems.Thm_StickyKakeya4_original_whole_macro_window
import Theorems.Thm_StickyKakeya4_original_literal_dense_macro_height
import Theorems.Thm_StickyKakeya4_native_coarse_backbone_density
import Theorems.Thm_StickyKakeya4_original_polynomial_coefficient_grid
import Theorems.Thm_StickyKakeya4_original_tensor_coefficient_collision
import Theorems.Thm_StickyKakeya4_original_tensor_coefficient_permutation
import Theorems.Thm_StickyKakeya4_original_tensor_quadratic_caps
import Theorems.Thm_StickyKakeya4_original_tensor_projection_pairs
import Theorems.Thm_StickyKakeya4_original_high_dimensional_projection_energy
import Theorems.Thm_StickyKakeya4_original_tensor_projection_selection
import Theorems.Thm_StickyKakeya4_native_padded_phase_pullback
import Theorems.Thm_StickyKakeya4_native_same_parent_source_selection
import Theorems.Thm_StickyKakeya4_original_literal_macro_height_budget

#print axioms OriginalThreeDimensionalEnergySliceWitness.exists_original_energy_regular_slice_witness
#print axioms OriginalThreeDimensionalMarkedSliceWitness.exists_original_marked_slice_witness
#print axioms OriginalThreeDimensionalMarkedEndpointCarrier.original_graph_on_endpoint_carrier
#print axioms OriginalThreeDimensionalMarkedEndpointCarrier.original_endpoint_carrier_subset
#print axioms OriginalThreeDimensionalMarkedEndpointCarrier.original_marked_endpoints_raw_slab
#print axioms OriginalThreeDimensionalMarkedEndpointCarrier.original_endpoint_full_potential
#print axioms OriginalPlanarTubePairCount.original_planar_two_point_cell_count
#print axioms OriginalPlanarTubeEnergy.original_planar_square_sum_swap
#print axioms OriginalPlanarTubeEnergy.original_planar_tube_square_energy
#print axioms OriginalPlanarTubeEnergy.original_projected_inverse_distance
#print axioms OriginalPlanarTubeEnergy.original_slab_tube_square_energy
#print axioms OriginalPlanarTubeParameters.original_pair_slope_bound
#print axioms OriginalPlanarTubeParameters.original_pair_graph_endpoints
#print axioms OriginalPlanarTubeParameters.original_graph_value_rounding
#print axioms OriginalPlanarTubeParameters.original_pair_cell_slope
#print axioms OriginalPlanarTubeParameters.original_pair_strip_in_cell
#print axioms OriginalPlanarTubeParameters.original_cell_in_pair_strip
#print axioms OriginalPlanarTubeParameters.original_pair_endpoints_in_cell
#print axioms OriginalPlanarTubeParameters.original_chart_distance
#print axioms OriginalPlanarTubeParameters.exists_original_pair_chart
#print axioms OriginalPlanarTubeChart.exists_original_common_planar_chart
#print axioms OriginalPlanarTubeChart.original_chart_cell_slope
#print axioms OriginalTubeCoreReinforcement.original_core_pair_fiber
#print axioms OriginalTubeCoreReinforcement.original_rich_family_count
#print axioms OriginalTubeCoreReinforcement.original_core_rich_graph
#print axioms OriginalPlanarChartTubeEnergy.original_chart_coordinate_bounds
#print axioms OriginalPlanarChartTubeEnergy.original_chart_slab_tube_square_energy
#print axioms OriginalPlanarCoreRichness.exists_original_core_rich_planar_graph
#print axioms OriginalThreeDimensionalSlabProjection.frameCoordinate_eq_repr
#print axioms OriginalThreeDimensionalSlabProjection.distance3_eq_euclidean
#print axioms OriginalThreeDimensionalSlabProjection.distance2_squared
#print axioms OriginalThreeDimensionalSlabProjection.frame_distance_squared
#print axioms OriginalThreeDimensionalSlabProjection.projected_distance_le
#print axioms OriginalThreeDimensionalSlabProjection.slab_normal_difference
#print axioms OriginalThreeDimensionalSlabProjection.original_slab_distance_comparison
#print axioms OriginalThreeDimensionalSlabProjection.original_projected_coordinate_bounds
#print axioms OriginalThreeDimensionalSlabProjection.frameCoordinate_orthogonalFoot
#print axioms OriginalThreeDimensionalSlabProjection.orthogonalFoot_on_plane
#print axioms OriginalThreeDimensionalSlabProjection.project_orthogonalFoot
#print axioms OriginalThreeDimensionalSlabProjection.distance_to_orthogonalFoot
#print axioms OriginalFiniteCellWeights.pointWeight_nonneg
#print axioms OriginalFiniteCellWeights.pairWeight_nonneg
#print axioms OriginalFiniteCellWeights.point_mass_readback
#print axioms OriginalFiniteCellWeights.pair_mass_readback
#print axioms OriginalFiniteCellWeights.point_subset_mass_readback
#print axioms OriginalFiniteCellWeights.pair_subset_mass_readback
#print axioms OriginalFiniteCellWeights.pairFiber_subset_product
#print axioms OriginalFiniteCellWeights.pairWeight_le_pointWeight_product
#print axioms OriginalFiniteCellWeights.original_pair_occupied_endpoints
#print axioms OriginalFiniteCellWeights.original_graph_weighted_density
#print axioms OriginalThreeDimensionalProjectionCells.distance2_triangle
#print axioms OriginalThreeDimensionalProjectionCells.distance2_comm
#print axioms OriginalThreeDimensionalProjectionCells.distance2_le_abs_add
#print axioms OriginalThreeDimensionalProjectionCells.abs_coordinate_le_distance2
#print axioms OriginalThreeDimensionalProjectionCells.floor_anchor_error
#print axioms OriginalThreeDimensionalProjectionCells.original_projected_cell_error
#print axioms OriginalThreeDimensionalProjectionCells.original_cell_anchor_bounds
#print axioms OriginalThreeDimensionalProjectionCells.cellAnchor_separated
#print axioms OriginalThreeDimensionalProjectionCells.project_linePoint
#print axioms OriginalThreeDimensionalProjectionCells.original_cell_weighted_frostman
#print axioms OriginalThreeDimensionalWeightedPlanarProjection.exists_original_weighted_planar_projection
#print axioms OriginalThreeDimensionalPlanarBoxProjection.boxDistance_le_distance2
#print axioms OriginalThreeDimensionalPlanarBoxProjection.distance2_le_two_boxDistance
#print axioms OriginalThreeDimensionalPlanarBoxProjection.original_slab_box_distance_comparison
#print axioms OriginalThreeDimensionalPlanarBoxProjection.original_projected_pair_separation
#print axioms OriginalThreeDimensionalPlanarBoxProjection.original_cell_weighted_box_frostman
#print axioms OriginalThreeDimensionalMarkedPlanarCore.original_slice_energyBudget_pos
#print axioms OriginalThreeDimensionalMarkedPlanarCore.original_profile_coefficient_formula
#print axioms OriginalThreeDimensionalMarkedPlanarCore.original_enlarged_slice_unit_slab
#print axioms OriginalThreeDimensionalMarkedPlanarCore.same_floor_strict_difference
#print axioms OriginalThreeDimensionalMarkedPlanarCore.same_cell_projected_box_distance_lt
#print axioms OriginalThreeDimensionalMarkedPlanarCore.original_slab_pair_cell_labels_distinct
#print axioms OriginalThreeDimensionalMarkedPlanarCore.exists_original_marked_weighted_planar_core
#print axioms OriginalThreeDimensionalPlanarTubeProjection.chart_distance2
#print axioms OriginalThreeDimensionalPlanarTubeProjection.chart_linePoint
#print axioms OriginalThreeDimensionalPlanarTubeProjection.chart_project_linePoint
#print axioms OriginalThreeDimensionalPlanarTubeProjection.chart_projected_distance_le
#print axioms OriginalThreeDimensionalPlanarTubeProjection.chart_projected_coordinate_bounds
#print axioms OriginalThreeDimensionalPlanarTubeProjection.frameCoordinate_linePoint
#print axioms OriginalThreeDimensionalPlanarTubeProjection.frame_distance_le_tangent_normal
#print axioms OriginalThreeDimensionalPlanarTubeProjection.original_pair_affine_graph
#print axioms OriginalThreeDimensionalPlanarTubeProjection.original_pair_tube_scalar_strip
#print axioms OriginalThreeDimensionalPlanarTubeProjection.original_pair_tube_cell_projection
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_raw_pair_chart_gap
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_raw_width_le_expanded
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_graph_horizontal_witness
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_graph_tangent_error
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_graph_parameter_bound
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_affine_normal_lift_error
#print axioms OriginalThreeDimensionalPlanarTubeLift.original_projected_cell_tube_lifts
#print axioms OriginalThreeDimensionalPhysicalCoreRichness.original_raw_projected_pair_ne
#print axioms OriginalThreeDimensionalPhysicalCoreRichness.exists_original_physical_core_rich_graph
#print axioms OriginalThreeDimensionalNonconcentratedRowMass.original_outside_row_label_count
#print axioms OriginalThreeDimensionalNonconcentratedRowMass.original_nonconcentrated_row_mass
#print axioms OriginalThreeDimensionalNonconcentratedRowMass.original_small_slice_row_population
#print axioms OriginalThreeDimensionalChosenSliceTube.original_chosen_slice_contains_tube
#print axioms OriginalThreeDimensionalChosenSliceTube.original_slice_ceiling_identity
#print axioms OriginalThreeDimensionalChosenSliceTube.exists_original_slice_mass_power_cutoff
#print axioms OriginalThreeDimensionalChosenSliceTube.original_chosen_slice_relative_tube_gain
#print axioms NativeOriginalBoundedNonconcentratedRows.exists_original_bounded_nonconcentrated_rows_cutoff
#print axioms OriginalThreeDimensionalNativeReinforcementBudget.original_selected_ratio_reinforcement_budget
#print axioms OriginalThreeDimensionalNativeReinforcementBudget.exists_original_native_reinforcement_cutoff
#print axioms NativeFixedCompactNormalizedNearHeight.exists_normalized_near_extremizer_with_height
#print axioms NativeFixedCompactMultiplicity.massConstant_pos
#print axioms NativeFixedCompactMultiplicity.total_shading_upper
#print axioms NativeFixedCompactMultiplicity.fixed_compact_multiplicity_upper
#print axioms NativeFixedCompactMultiplicity.exists_matched_normalized_source
#print axioms NativeUniformMultiplicityRestriction.projectedWeight_mono
#print axioms NativeUniformMultiplicityRestriction.projectedWeight_total
#print axioms NativeUniformMultiplicityRestriction.uniform_point_mass_bound
#print axioms NativeUniformMultiplicityRestriction.subset_weighted_mass_cross
#print axioms NativeUniformMultiplicityRestriction.weighted_card_cross
#print axioms NativeUniformMultiplicityRestriction.selected_restriction_multiplicity
#print axioms NativeUniformMultiplicityRestriction.exists_restriction_control
#print axioms NativeOriginalSliceRestriction.original_slice_ball_population_with_restriction
#print axioms NativeOriginalSliceRestriction.original_slice_population_with_multiplicity_and_restriction
#print axioms NativeIncidenceMultiplicityTower.coarse_support
#print axioms NativeIncidenceMultiplicityTower.coarse_parents
#print axioms NativeIncidenceMultiplicityTower.parent_nonempty
#print axioms NativeIncidenceMultiplicityTower.coarse_parent_card
#print axioms NativeIncidenceMultiplicityTower.coarse_card_sum
#print axioms NativeIncidenceMultiplicityTower.fine_card_sum
#print axioms NativeIncidenceMultiplicityTower.multiplicity_le_parent_upper
#print axioms NativeIncidenceMultiplicityTower.exists_parent_multiplicity_product
#print axioms NativeIncidenceMultiplicityTower.source_multiplicity_real
#print axioms NativeIncidenceMultiplicityTower.actual_original_parent_product
#print axioms NativeCoarseSlopeOccupancy.occupied_slope_cell_bound
#print axioms NativeCoarseSlopeOccupancy.original_dyadic_slope_occupancy
#print axioms NativeCoarseSlopeOccupancy.compact_original_slope_occupancy
#print axioms OriginalHeightWindowMacroCells.actual_union_grain_image
#print axioms OriginalHeightWindowMacroCells.fixed_height_x_cell_count
#print axioms OriginalHeightWindowMacroCells.original_window_macro_grid_mass
#print axioms OriginalLiteralMacroSliceUpper.original_grain_ball_grid_upper
#print axioms OriginalLiteralMacroSliceUpper.original_macro_grain_grid_upper
#print axioms OriginalLiteralMacroSliceUpper.original_macro_height_point_upper
#print axioms OriginalWholeMacroWindow.actual_macro_readback
#print axioms OriginalWholeMacroWindow.actual_grain_fiber_readback
#print axioms OriginalLiteralDenseMacroHeight.exists_original_macro_with_height_population
#print axioms NativeCoarseBackboneDensity.incidence_tubes_subset_backbone
#print axioms NativeCoarseBackboneDensity.full_backbone_coarse_density
#print axioms NativeCoarseBackboneDensity.original_full_backbone_density
#print axioms OriginalPolynomialCoefficientGrid.grid_card
#print axioms OriginalPolynomialCoefficientGrid.grid_bounds
#print axioms OriginalPolynomialCoefficientGrid.original_coefficient_interval_count
#print axioms OriginalPolynomialCoefficientGrid.coefficient_mesh_choice
#print axioms OriginalTensorCoefficientCollision.original_first_coordinate_interval
#print axioms OriginalTensorCoefficientCollision.original_tensor_first_collision
#print axioms OriginalTensorCoefficientPermutation.original_coefficient_permutation_card
#print axioms OriginalTensorCoefficientPermutation.original_tensor_coordinate_collision
#print axioms OriginalTensorCoefficientPermutation.original_tensor_small_mesh_collision
#print axioms OriginalTensorCoefficientPermutation.original_tensor_two_box_collision
#print axioms OriginalTensorQuadraticCaps.original_tensor_quadratic_window
#print axioms OriginalTensorQuadraticCaps.original_tensor_allscale_quadratic
#print axioms OriginalTensorQuadraticCaps.dyadicScale_bounds
#print axioms OriginalTensorQuadraticCaps.dyadicScale_sum
#print axioms OriginalTensorProjectionPairs.original_pair_parameter_count
#print axioms OriginalTensorProjectionPairs.original_pair_scale_count
#print axioms OriginalTensorProjectionPairs.original_projected_cell_energy
#print axioms OriginalTensorProjectionPairs.original_collision_fubini
#print axioms OriginalTensorProjectionPairs.original_exists_annulus
#print axioms OriginalHighDimensionalProjectionEnergy.original_point_projection_energy
#print axioms OriginalHighDimensionalProjectionEnergy.original_quadratic_projection_energy
#print axioms OriginalTensorProjectionSelection.original_tensor_collision_energy
#print axioms OriginalTensorProjectionSelection.exists_original_tensor_projection
#print axioms NativePaddedPhasePullback.mem_selectedOldRows
#print axioms NativePaddedPhasePullback.padding_image
#print axioms NativePaddedPhasePullback.originalRowMap_injective
#print axioms NativePaddedPhasePullback.original_pullback_readback
#print axioms NativePaddedPhasePullback.selected_old_card_le
#print axioms NativePaddedPhasePullback.phase_original_image
#print axioms NativePaddedPhasePullback.phase_height_window_original_image
#print axioms NativePaddedPhasePullback.phaseFamily_card
#print axioms NativePaddedPhasePullback.phaseFamily_tubes
#print axioms NativePaddedPhasePullback.original_composite_capacity
#print axioms NativePaddedPhasePullback.admitted_source_cells
#print axioms NativePaddedPhasePullback.admitted_phase_mesh
#print axioms NativePaddedPhasePullback.admitted_phase_geometry
#print axioms NativeSameParentSourceSelection.select_same_parent_source
#print axioms OriginalLiteralMacroHeightBudget.original_macro_cost_absorption
#print axioms OriginalLiteralMacroHeightBudget.exists_original_macro_power_cutoff
