import Theorems.Thm_StickyKakeya4_original_three_dimensional_source_hairbrush_slab
import Theorems.Thm_StickyKakeya4_original_three_dimensional_literal_slab_cover

#print axioms OriginalThreeDimensionalHairbrushParameters.parameter_bounds
#print axioms OriginalThreeDimensionalHairbrushParameters.exact_parameter_budgets
#print axioms OriginalThreeDimensionalHairbrushParameters.small_radius_conditions
#print axioms OriginalThreeDimensionalHairbrushParameters.slab_width_ge_hundred
#print axioms OriginalThreeDimensionalHairbrushParameters.large_radius_slab_width
#print axioms OriginalThreeDimensionalHairbrushParameters.source_mass_constant_conversion
#print axioms OriginalThreeDimensionalHairbrushParameters.trivial_mass_constant
#print axioms OriginalThreeDimensionalSourceHairbrushSlab.exists_original_source_hairbrush_slab
#print axioms OriginalThreeDimensionalLiteralSlabCover.exists_original_normal_frame
#print axioms OriginalThreeDimensionalLiteralSlabCover.original_frame_coordinate_bound
#print axioms OriginalThreeDimensionalLiteralSlabCover.original_unit_slab_from_literal_rectangles
