import Theorems.Thm_StickyKakeya4_original_w_physical_displacement

#print axioms OriginalWPhysicalDisplacement.incidence_chord_error
#print axioms OriginalWPhysicalDisplacement.path_residual_bound
#print axioms OriginalWPhysicalDisplacement.witness_two_leg_residual
#print axioms OriginalWPhysicalDisplacement.difference_approximation_bound
#print axioms OriginalWPhysicalDisplacement.witness_coarse_displacement
#print axioms OriginalWPhysicalDisplacement.same_tube_same_height_error
#print axioms OriginalWPhysicalDisplacement.fixed_representative_displacement
#print axioms OriginalWPhysicalDisplacement.floor_approximation
#print axioms OriginalWPhysicalDisplacement.scalar_grid_approximation
#print axioms OriginalWPhysicalDisplacement.planar_grid_approximation
#print axioms OriginalWPhysicalDisplacement.terminal_grid_component_gap
#print axioms OriginalWPhysicalDisplacement.scalar_terminal_grid_gap
#print axioms OriginalWPhysicalDisplacement.planar_terminal_grid_gap
#print axioms OriginalWPhysicalDisplacement.witness_time_gaps
#print axioms OriginalWPhysicalDisplacement.scalar_native_witness_displacement
#print axioms OriginalWPhysicalDisplacement.planar_native_witness_displacement
