import Theorems.Thm_StickyKakeya4_native_original_tube_family_caller
import Theorems.Thm_StickyKakeya4_native_original_coarse_tube_family
import Theorems.Thm_StickyKakeya4_native_original_nonempty_coarse_family
import Theorems.Thm_StickyKakeya4_native_uniform_original_coarse_family
import Theorems.Thm_StickyKakeya4_original_fixed_internal_eta
import Theorems.Thm_StickyKakeya4_original_tube_slice_occupancy
import Theorems.Thm_StickyKakeya4_native_original_cell_chart_geometry
import Theorems.Thm_StickyKakeya4_native_original_parent_selection
import Theorems.Thm_StickyKakeya4_native_original_parent_physical_data
import Theorems.Thm_StickyKakeya4_native_near_extremal_physical_parent
import Theorems.Thm_StickyKakeya4_native_near_source_slice_population

#print axioms NativeOriginalTubeFamilyCaller.exists_native_original_tube_family_threshold
#print axioms NativeOriginalCoarseTubeFamily.exists_native_original_coarse_family_threshold
#print axioms NativeOriginalNonemptyCoarseFamily.exists_native_original_nonempty_coarse_family_threshold
#print axioms NativeUniformOriginalCoarseFamily.exists_uniform_original_nonempty_coarse_family
#print axioms OriginalFixedInternalEta.original_frostman_to_fixed_internal_eta
#print axioms OriginalFixedInternalEta.fixed_internal_error_power_le_external
#print axioms OriginalFixedInternalEta.original_pair_error_to_external_eta
#print axioms OriginalFixedInternalEta.original_pair_retention_to_external_eta
#print axioms OriginalTubeSliceOccupancy.same_physical_cell_distance
#print axioms OriginalTubeSliceOccupancy.physical_cell_injective
#print axioms OriginalTubeSliceOccupancy.separated_rectangle_card
#print axioms OriginalTubeSliceOccupancy.pointsAt_card_le
#print axioms OriginalTubeSliceOccupancy.pointsAt_card_le_of_incidenceResidual
#print axioms OriginalTubeSliceOccupancy.occupancy_constant_bound
#print axioms OriginalTubeSliceOccupancy.pointsAt_card_le_constant
#print axioms OriginalTubeSliceOccupancy.occupancy_rpow_bound
#print axioms OriginalTubeSliceOccupancy.pointsAt_card_le_rpow
#print axioms NativeOriginalCellChartGeometry.coordinate_abs_le_norm
#print axioms NativeOriginalCellChartGeometry.slope_bound
#print axioms NativeOriginalCellChartGeometry.raw_graph_identity
#print axioms NativeOriginalCellChartGeometry.raw_height_from_common
#print axioms NativeOriginalCellChartGeometry.tube_point_bounds
#print axioms NativeOriginalCellChartGeometry.cellCenter_mem
#print axioms NativeOriginalCellChartGeometry.chartIndex_injective
#print axioms NativeOriginalCellChartGeometry.chart_center_time
#print axioms NativeOriginalCellChartGeometry.chart_center_residual
#print axioms NativeOriginalCellChartGeometry.normalized_cell_bounds
#print axioms NativeOriginalParentSelection.chartIncidences_card
#print axioms NativeOriginalParentSelection.backbone_nonempty
#print axioms NativeOriginalParentSelection.parentDensity_pos
#print axioms NativeOriginalParentSelection.parentDensity_le_one
#print axioms NativeOriginalParentSelection.full_backbone_density
#print axioms NativeOriginalParentSelection.exists_parent
#print axioms NativeOriginalParentSelection.floor_parent_slope_bound
#print axioms NativeOriginalParentPhysicalData.exists_common_height
#print axioms NativeOriginalParentPhysicalData.original_cell_in_tube
#print axioms NativeOriginalParentPhysicalData.original_cell_bounds
#print axioms NativeOriginalParentPhysicalData.used_subset_backbone
#print axioms NativeOriginalParentPhysicalData.data_hypotheses
#print axioms NativeOriginalParentPhysicalData.mem_data_incidences
#print axioms NativeOriginalParentPhysicalData.exists_physical_parent
#print axioms NativeNearExtremalPhysicalParent.backbone_parameter_bounds
#print axioms NativeNearExtremalPhysicalParent.oldSupport_card_le
#print axioms NativeNearExtremalPhysicalParent.original_multiplicity_le_parent
#print axioms NativeNearExtremalPhysicalParent.original_multiplicity_le_parent_ennreal
#print axioms NativeNearExtremalPhysicalParent.exists_near_extremal_physical_parent
#print axioms NativeNearSourceSlicePopulation.original_subset_readback
#print axioms NativeNearSourceSlicePopulation.near_source_slice_population
