import Theorems.Thm_StickyKakeya4_native_padded_source_mass
import Theorems.Thm_StickyKakeya4_native_padded_source_transport
import Theorems.Thm_StickyKakeya4_native_padded_source_ad_upper
import Theorems.Thm_StickyKakeya4_native_padded_source_ad_lower
import Theorems.Thm_StickyKakeya4_native_padded_source_count_budget
import Theorems.Thm_StickyKakeya4_native_padded_source_power_budget
import Theorems.Thm_StickyKakeya4_native_padded_source_density
import Theorems.Thm_StickyKakeya4_native_padded_source_admissibility
import Theorems.Thm_StickyKakeya4_native_compact_normalized_source
import Theorems.Thm_StickyKakeya4_original_line_cover_packets
import Theorems.Thm_StickyKakeya4_compact_source_finite_readback
import Theorems.Thm_StickyKakeya4_native_fixed_compact_kakeya_exponent
import Theorems.Thm_StickyKakeya4_native_compact_volume_transport
import Theorems.Thm_StickyKakeya4_native_fixed_compact_normalized_near
import Theorems.Thm_StickyKakeya4_native_fixed_compact_incidence_parent
import Theorems.Thm_StickyKakeya4_native_fixed_compact_slice_population
import Theorems.Thm_StickyKakeya4_native_original_concentrated_slice_closure
import Theorems.Thm_StickyKakeya4_original_three_dimensional_expanded_band_count
import Theorems.Thm_StickyKakeya4_original_three_dimensional_expanded_slice_multiplicity
import Theorems.Thm_StickyKakeya4_original_three_dimensional_slice_energy_basic
import Theorems.Thm_StickyKakeya4_original_three_dimensional_averaged_slice_energy
import Theorems.Thm_StickyKakeya4_original_three_dimensional_slice_potential_cut
import Theorems.Thm_StickyKakeya4_original_three_dimensional_energy_regular_slice
import Theorems.Thm_StickyKakeya4_original_three_dimensional_marked_slice_incidences
import Theorems.Thm_StickyKakeya4_original_three_dimensional_regularized_marked_slice
import Theorems.Thm_StickyKakeya4_original_polynomial_slab
import Theorems.Thm_StickyKakeya4_original_polynomial_elimination
import Theorems.Thm_StickyKakeya4_original_tensor_frostman
import Theorems.Thm_StickyKakeya4_original_slab_overlap
import Theorems.Thm_StickyKakeya4_original_slab_relation
import Theorems.Thm_StickyKakeya4_original_slab_collision
import Theorems.Thm_StickyKakeya4_original_polynomial_dimension_drop
import Theorems.Thm_StickyKakeya4_original_finite_dimension_reduction
import Theorems.Thm_StickyKakeya4_original_quadratic_words
import Theorems.Thm_StickyKakeya4_original_pure_quadratic_dimension_drop
import Theorems.Thm_StickyKakeya4_original_quadratic_word_bounds
import Theorems.Thm_StickyKakeya4_original_literal_height_window
import Theorems.Thm_StickyKakeya4_original_literal_angular_incidences
import Theorems.Thm_StickyKakeya4_native_coarse_actual_height_vertices

#print axioms NativePaddedSourceMass.sum_originalLabel
#print axioms NativePaddedSourceMass.iUnion_originalLabel
#print axioms NativePaddedSourceMass.sourceUnion_eq_retained
#print axioms NativePaddedSourceMass.source_union_volume_le
#print axioms NativePaddedSourceMass.total_shading_eq_retained
#print axioms NativePaddedSourceMass.original_shadingMass_le_source
#print axioms NativePaddedSourceMass.unit_tube_volume_comparison
#print axioms NativePaddedSourceMass.total_tubes_eq_retained
#print axioms NativePaddedSourceMass.source_tubeMass_le_original
#print axioms NativePaddedSourceMass.source_density_cross_bound
#print axioms NativePaddedSourceTransport.card_filter_originalLabel
#print axioms NativePaddedSourceTransport.source_carrierBallCount
#print axioms NativePaddedSourceTransport.source_containedTubeCount
#print axioms NativePaddedSourceTransport.convex_contractPoint_preimage
#print axioms NativePaddedSourceTransport.convex_physicalMap_preimage
#print axioms NativePaddedSourceTransport.volume_physicalMap_preimage
#print axioms NativePaddedSourceTransport.source_CW_original_count
#print axioms NativePaddedSourceADUpper.source_carrier_upper
#print axioms NativePaddedSourceADLower.dyadic_below_radius
#print axioms NativePaddedSourceADLower.source_carrier_lower
#print axioms NativePaddedSourceCountBudget.original_card_upper
#print axioms NativePaddedSourceCountBudget.unit_lower_of_ancestors
#print axioms NativePaddedSourceCountBudget.unit_parent_count_bound
#print axioms NativePaddedSourceCountBudget.selected_parent_card_retention
#print axioms NativePaddedSourcePowerBudget.fixed_cost_bounds
#print axioms NativePaddedSourcePowerBudget.exists_master_cutoff
#print axioms NativePaddedSourcePowerBudget.cost_of_master
#print axioms NativePaddedSourcePowerBudget.positive_power_ratio
#print axioms NativePaddedSourcePowerBudget.old_exponent_coefficient
#print axioms NativePaddedSourcePowerBudget.new_exponent_coefficient
#print axioms NativePaddedSourcePowerBudget.density_power
#print axioms NativePaddedSourceDensity.tubeMass_ne_top
#print axioms NativePaddedSourceDensity.realTubeMass_eq_toReal
#print axioms NativePaddedSourceDensity.ofReal_realShadingMass
#print axioms NativePaddedSourceDensity.ofReal_realTubeMass
#print axioms NativePaddedSourceDensity.retained_shading_pos
#print axioms NativePaddedSourceDensity.exists_dense_parent_enn
#print axioms NativePaddedSourceDensity.source_raw_density
#print axioms NativePaddedSourceAdmissibility.real_AD_to_enn
#print axioms NativePaddedSourceAdmissibility.source_AD
#print axioms NativePaddedSourceAdmissibility.source_CW
#print axioms NativePaddedSourceAdmissibility.source_density
#print axioms NativeCompactNormalizedSource.compact_original_normalized_source
#print axioms StickyKakeya4.packing_selector_has_original_line_wz_packets_at_exponent
#print axioms StickyKakeya4.wang_zakharov_volume_on_to_covering
#print axioms StickyKakeya4.dimH_eq_four_of_original_compact_volume
#print axioms NativeFixedCompactKakeyaExponent.bound_mono
#print axioms NativeFixedCompactKakeyaExponent.bound_of_unrestricted
#print axioms NativeFixedCompactKakeyaExponent.bound_three
#print axioms NativeFixedCompactKakeyaExponent.exponents_nonempty
#print axioms NativeFixedCompactKakeyaExponent.exponents_bddBelow
#print axioms NativeFixedCompactKakeyaExponent.extremalExponent_nonneg
#print axioms NativeFixedCompactKakeyaExponent.extremalExponent_le_three
#print axioms NativeFixedCompactKakeyaExponent.bound_extremal
#print axioms NativeFixedCompactKakeyaExponent.not_bound_below_extremal
#print axioms NativeFixedCompactKakeyaExponent.counterexample_of_not_bound
#print axioms NativeFixedCompactKakeyaExponent.exists_near_extremizer
#print axioms NativeFixedCompactKakeyaExponent.finite_volume_of_bound_zero
#print axioms NativeFixedCompactKakeyaExponent.bound_zero_of_finite_volume
#print axioms NativeFixedCompactKakeyaExponent.bound_zero_iff_finite_volume
#print axioms NativeFixedCompactKakeyaExponent.extremal_zero_iff_finite_volume
#print axioms NativeFixedCompactKakeyaExponent.finite_volume_or_positive_extremal
#print axioms NativeFixedCompactKakeyaExponent.extremalExponent_le_unrestricted
#print axioms NativeCompactVolumeTransport.coefficient_identity
#print axioms NativeCompactVolumeTransport.volume_estimate_on_compact
#print axioms NativeCompactVolumeTransport.dimH_eq_four_from_fixed_compact_volume
#print axioms NativeFixedCompactNormalizedNear.near_volume_scale
#print axioms NativeFixedCompactNormalizedNear.exists_normalized_near_extremizer
#print axioms NativeFixedCompactNormalizedNear.exists_normalized_source
#print axioms NativeFixedCompactIncidenceParent.exists_near_extremal_incidence_counts
#print axioms NativeFixedCompactIncidenceParent.exists_near_extremal_physical_parent
#print axioms NativeFixedCompactSlicePopulation.near_source_slice_population
#print axioms OriginalThreeDimensionalSliceParameterChoice.original_slice_exponent_spec
#print axioms OriginalThreeDimensionalSliceParameterChoice.original_selected_slice_width_power
#print axioms OriginalThreeDimensionalSliceParameterChoice.original_coarse_menu_log_bound
#print axioms OriginalThreeDimensionalSliceParameterChoice.exists_original_coarse_menu_cutoff
#print axioms OriginalThreeDimensionalNativeSliceScale.exists_original_slice_parameter_cutoff
#print axioms OriginalThreeDimensionalConcentratedBudget.original_concentrated_effective_exponent
#print axioms OriginalThreeDimensionalConcentratedBudget.original_concentrated_density_lower
#print axioms OriginalThreeDimensionalConcentratedBudget.exists_original_concentrated_parameter_budget
#print axioms NativeOriginalConcentratedSlabExclusion.exists_original_concentrated_graph_cutoff
#print axioms NativeOriginalNonconcentratedSliceGraph.exists_original_nonconcentrated_slice_graph_cutoff
#print axioms NativeOriginalNonconcentratedSliceGraph.exists_native_original_two_ends_threshold
#print axioms NativeOriginalNonconcentratedSliceGraph.exists_literal_original_two_ends_threshold
#print axioms OriginalThreeDimensionalExpandedBandCount.original_expanded_normal_band_count
#print axioms OriginalThreeDimensionalExpandedSliceMultiplicity.original_grid_normal_length_le_five
#print axioms OriginalThreeDimensionalExpandedSliceMultiplicity.original_expanded_slice_raw_error
#print axioms OriginalThreeDimensionalExpandedSliceMultiplicity.original_expanded_slice_pair_multiplicity
#print axioms OriginalThreeDimensionalAveragedSliceEnergy.slice_potential_nonneg
#print axioms OriginalThreeDimensionalAveragedSliceEnergy.original_slice_energy_lower
#print axioms OriginalThreeDimensionalAveragedSliceEnergy.original_ball_count_from_slice_potential
#print axioms OriginalThreeDimensionalAveragedSliceEnergy.original_slice_energy_sum_swap
#print axioms OriginalThreeDimensionalAveragedSliceEnergy.original_averaged_slice_energy
#print axioms OriginalThreeDimensionalSlicePotentialCut.original_potential_cut_mass_loss
#print axioms OriginalThreeDimensionalSlicePotentialCut.original_potential_cut_ball_count
#print axioms OriginalThreeDimensionalSlicePotentialCut.original_restricted_graph_pair_loss
#print axioms OriginalThreeDimensionalSlicePotentialCut.original_potential_cut_graph_loss
#print axioms OriginalThreeDimensionalEnergyRegularSlice.exists_original_energy_regular_slice
#print axioms OriginalThreeDimensionalEnergyRegularSlice.original_regular_slice_cut_retention
#print axioms OriginalThreeDimensionalEnergyRegularSlice.exists_original_energy_regular_slice_core
#print axioms OriginalThreeDimensionalMarkedSliceIncidences.original_marked_slice_graph_subset
#print axioms OriginalThreeDimensionalMarkedSliceIncidences.original_marked_slice_incidence_sum
#print axioms OriginalThreeDimensionalMarkedSliceIncidences.original_marked_slice_geometry
#print axioms OriginalThreeDimensionalRegularizedMarkedSlice.exists_original_regularized_marked_slice
#print axioms OriginalPolynomialSlab.slabVector_injective
#print axioms OriginalPolynomialSlab.slabVectors_card
#print axioms OriginalPolynomialSlab.slabVector_projection
#print axioms OriginalPolynomialSlab.slabVector_coordinate_bound
#print axioms OriginalPolynomialElimination.original_coefficient_elimination
#print axioms OriginalPolynomialElimination.original_dilation_perturbation_cover
#print axioms OriginalPolynomialElimination.original_polynomial_projection_elimination
#print axioms OriginalTensorFrostman.tensor_card
#print axioms OriginalTensorFrostman.original_tensor_window
#print axioms OriginalTensorFrostman.original_tensor_frostman
#print axioms OriginalSlabOverlap.exists_original_cross_fiber_collision
#print axioms OriginalSlabOverlap.exists_original_translated_floor_collision
#print axioms OriginalSlabRelation.original_translated_cell_relation
#print axioms OriginalSlabRelation.original_relation_coefficient_bounds
#print axioms OriginalSlabCollision.original_box_projection
#print axioms OriginalSlabCollision.slabRadius_bounds
#print axioms OriginalSlabCollision.exists_original_slab_collision
#print axioms OriginalPolynomialDimensionDrop.reduced_point_mem
#print axioms OriginalPolynomialDimensionDrop.reduced_projection_eq
#print axioms OriginalPolynomialDimensionDrop.original_dimension_drop_from_relation
#print axioms OriginalFiniteDimensionReduction.original_interval_abs_bound
#print axioms OriginalFiniteDimensionReduction.exists_original_finite_dimension_reduction
#print axioms OriginalQuadraticWords.original_product_difference_mem
#print axioms OriginalQuadraticWords.quadratic_zero_mem
#print axioms OriginalQuadraticWords.quadratic_neg_mem
#print axioms OriginalQuadraticWords.integer_multiple_mem_padded
#print axioms OriginalQuadraticWords.original_reduced_alphabet_quadratic
#print axioms OriginalPureQuadraticDimensionDrop.exists_original_quadratic_dimension_drop
#print axioms OriginalQuadraticWordBounds.original_quadratic_abs_bound
#print axioms OriginalQuadraticWordBounds.original_word_abs_bound
#print axioms OriginalQuadraticWordBounds.original_diameter_square_mem
#print axioms OriginalQuadraticWordBounds.exists_original_word_endpoints
#print axioms OriginalLiteralHeightWindow.actual_height_image
#print axioms OriginalLiteralHeightWindow.whole_height_fiber
#print axioms OriginalLiteralHeightWindow.exists_populated_height_window
#print axioms OriginalLiteralAngularIncidences.exists_literal_fine_family
#print axioms OriginalLiteralAngularIncidences.exists_literal_angular_population_supplier
#print axioms NativeCoarseActualHeightVertices.coarse_pointsAt_bound
#print axioms NativeCoarseActualHeightVertices.actual_heights_bound
#print axioms NativeCoarseActualHeightVertices.actual_heights_separated
#print axioms NativeCoarseActualHeightVertices.actual_coarse_height_vertex_density
#print axioms NativeCoarseActualHeightVertices.exists_native_coarse_height_vertices
