import Theorems.Thm_StickyKakeya4_original_residual_criterion

#check StickyKakeya4.OriginalResidualCriterion.compact_full_direction_residual_reduction
#print axioms StickyKakeya4.OriginalResidualCriterion.frontParam
#print axioms StickyKakeya4.OriginalResidualCriterion.measurable_frontParam
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure_isFinite
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure_univ
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure_ne_zero
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure_supported
#print axioms StickyKakeya4.OriginalResidualCriterion.HasResidualPowerBounds
#print axioms StickyKakeya4.OriginalResidualCriterion.sourceFrontMeasure_finite_energy
#print axioms StickyKakeya4.OriginalResidualCriterion.front_frostman_of_residual_power
#print axioms StickyKakeya4.OriginalResidualCriterion.front_dimH_eq_four_of_residual_power
#print axioms StickyKakeya4.OriginalResidualCriterion.compact_full_direction_residual_reduction
