import Theorems.Thm_StickyKakeya4_original_tube_ancestor_saturation

#print axioms OriginalTubeAncestorSaturation.ancestor_incidence_residual
#print axioms OriginalTubeAncestorSaturation.same_point_normal_direction
#print axioms OriginalTubeAncestorSaturation.ancestor_fiber_inside_adapted_box
#print axioms OriginalTubeAncestorSaturation.scalar_same_parameter_cell
#print axioms OriginalTubeAncestorSaturation.planar_same_parameter_cell
#print axioms OriginalTubeAncestorSaturation.scalar_parameter_ancestor_gaps
#print axioms OriginalTubeAncestorSaturation.planar_parameter_ancestor_gaps
#print axioms OriginalTubeAncestorSaturation.fine_label_realizer_tangent_gap
