import Theorems.Thm_StickyKakeya4_original_three_dimensional_cap_count
import Theorems.Thm_StickyKakeya4_original_three_dimensional_cap_distance
import Theorems.Thm_StickyKakeya4_original_three_dimensional_separated_normals
import Theorems.Thm_StickyKakeya4_gkz_original_anchor_cover
import Theorems.Thm_StickyKakeya4_gkz_finite_anchored_plunnecke
import Theorems.Thm_StickyKakeya4_gkz_original_product_overlap
import Theorems.Thm_StickyKakeya4_gkz_grid_code_perturbation
import Theorems.Thm_StickyKakeya4_gkz_dilate_rounded_sums
import Theorems.Thm_StickyKakeya4_gkz_original_anchor_profile
import Theorems.Thm_StickyKakeya4_gkz_original_mixed_dilate_bounds
import Theorems.Thm_StickyKakeya4_gkz_real_dilation_union
import Theorems.Thm_StickyKakeya4_gkz_original_nine_sum_cover
import Theorems.Thm_StickyKakeya4_gkz_original_linear_upper
import Theorems.Thm_StickyKakeya4_gkz_original_sum_product_comparison
import Theorems.Thm_StickyKakeya4_gkz_balanced_dyadic_scale
import Theorems.Thm_StickyKakeya4_gkz_original_positive_power
import Theorems.Thm_StickyKakeya4_gkz_uniform_growth_parameters
import Theorems.Thm_StickyKakeya4_native_coarse_original_incidences
import Theorems.Thm_StickyKakeya4_native_coarse_original_geometry
import Theorems.Thm_StickyKakeya4_native_coarse_original_heights
import Theorems.Thm_StickyKakeya4_native_source_coarse_readback
import Theorems.Thm_StickyKakeya4_native_dense_source_coarse_family
import Theorems.Thm_StickyKakeya4_native_cover_ad_representatives
import Theorems.Thm_StickyKakeya4_native_unit_parent_normalization
import Theorems.Thm_StickyKakeya4_native_unit_parent_volume
import Theorems.Thm_StickyKakeya4_native_dense_retained_unit_parent
import Theorems.Thm_StickyKakeya4_native_unit_parent_shadings
import Theorems.Thm_StickyKakeya4_native_unit_parent_dyadic
import Theorems.Thm_StickyKakeya4_native_unit_parent_directions
import Theorems.Thm_StickyKakeya4_native_dense_normalized_parent
import Theorems.Thm_StickyKakeya4_original_three_dimensional_cross_geometry
import Theorems.Thm_StickyKakeya4_original_three_dimensional_slab_overlap
import Theorems.Thm_StickyKakeya4_original_three_dimensional_narrow_slab_overlap
import Theorems.Thm_StickyKakeya4_original_three_dimensional_annular_slab_charge
import Theorems.Thm_StickyKakeya4_original_three_dimensional_middle_slice_branch
import Theorems.Thm_StickyKakeya4_original_three_dimensional_tube_parameters
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pair_tube_family
import Theorems.Thm_StickyKakeya4_original_three_dimensional_common_chart
import Theorems.Thm_StickyKakeya4_original_tube_parameter_integer_count
import Theorems.Thm_StickyKakeya4_original_three_dimensional_tube_incidence_energy
import Theorems.Thm_StickyKakeya4_original_three_dimensional_heavy_cube_shading

#print axioms OriginalThreeDimensionalCapCount.integer_interval_mass
#print axioms OriginalThreeDimensionalCapCount.weighted_fiber_count
#print axioms OriginalThreeDimensionalCapCount.rectangle_mass
#print axioms OriginalThreeDimensionalCapCount.band_integer_mass
#print axioms OriginalThreeDimensionalCapCount.first_coefficient_count
#print axioms OriginalThreeDimensionalCapCount.rectangle_band_count
#print axioms OriginalThreeDimensionalCapCount.point_gap_nonneg
#print axioms OriginalThreeDimensionalCapCount.point_gap_chart_sum
#print axioms OriginalThreeDimensionalCapCount.original_normal_cap_count
#print axioms OriginalThreeDimensionalCapCount.original_cap_band_count
#print axioms OriginalThreeDimensionalCapCount.unit_center_components
#print axioms OriginalThreeDimensionalCapCount.original_unit_cap_band_card
#print axioms OriginalThreeDimensionalCapDistance.point_gap_coordinate
#print axioms OriginalThreeDimensionalCapDistance.separation_le_twice_gap
#print axioms OriginalThreeDimensionalCapDistance.original_separated_cap_count
#print axioms OriginalThreeDimensionalCapDistance.original_euclidean_cap_band_card
#print axioms OriginalThreeDimensionalSeparatedNormals.distance3_comm
#print axioms OriginalThreeDimensionalSeparatedNormals.distance3_self
#print axioms OriginalThreeDimensionalSeparatedNormals.distance3_neg_right_comm
#print axioms OriginalThreeDimensionalSeparatedNormals.unoriented_distance_comm
#print axioms OriginalThreeDimensionalSeparatedNormals.unoriented_distance_self
#print axioms OriginalThreeDimensionalSeparatedNormals.exists_symmetric_relation_net
#print axioms OriginalThreeDimensionalSeparatedNormals.actual_unoriented_net
#print axioms OriginalThreeDimensionalSeparatedNormals.weighted_cover_count
#print axioms OriginalThreeDimensionalSeparatedNormals.original_double_cap_count
#print axioms OriginalThreeDimensionalSeparatedNormals.exists_original_unoriented_separated_labels
#print axioms OriginalThreeDimensionalSeparatedNormals.exists_original_unoriented_heavy_normals
#print axioms GKZOriginalAnchorCover.original_anchor_cover_recovery
#print axioms GKZFiniteAnchoredPlunnecke.iterated_sum_from_anchor
#print axioms GKZFiniteAnchoredPlunnecke.finite_union_anchored_sum
#print axioms GKZFiniteAnchoredPlunnecke.original_overlap_mixed_bounds
#print axioms GKZOriginalProductOverlap.product_code_injective
#print axioms GKZOriginalProductOverlap.mem_dilateIncidence
#print axioms GKZOriginalProductOverlap.dilateCells_subset_productCells
#print axioms GKZOriginalProductOverlap.original_product_incidence_mass
#print axioms GKZOriginalProductOverlap.commonFiber_eq_actual_overlap
#print axioms GKZOriginalProductOverlap.exists_original_popular_multiplier
#print axioms GKZGridCodePerturbation.floor_image_le_code_image
#print axioms GKZGridCodePerturbation.code_image_le_floor_image
#print axioms GKZGridCodePerturbation.bounded_dilation_floor_image
#print axioms GKZDilateRoundedSums.image_add_image
#print axioms GKZDilateRoundedSums.image_sub_image
#print axioms GKZDilateRoundedSums.original_dilate_selfsum_cover
#print axioms GKZDilateRoundedSums.negative_dilate_anchor_cover
#print axioms GKZOriginalAnchorProfile.original_profile_constant_ge_one
#print axioms GKZOriginalAnchorProfile.original_profile_extended
#print axioms GKZOriginalAnchorProfile.original_denominator_cover_recovery
#print axioms GKZOriginalAnchorProfile.original_linear_sum_radius
#print axioms GKZOriginalMixedDilateBounds.exists_original_mixed_dilate_family
#print axioms GKZRealDilationUnion.rounded_dilateUnion
#print axioms GKZRealDilationUnion.original_dilate_union_iterated_cover
#print axioms GKZRealDilationUnion.original_gap_target_subset_nine
#print axioms GKZRealDilationUnion.original_dense_target_subset_nine
#print axioms GKZOriginalNineSumCover.gap_coefficients_are_expansion_coefficients
#print axioms GKZOriginalNineSumCover.dense_coefficients_are_expansion_coefficients
#print axioms GKZOriginalNineSumCover.exists_original_nine_sum_cover
#print axioms GKZOriginalLinearUpper.exists_original_linear_image_upper
#print axioms GKZOriginalSumProductComparison.original_sum_product_comparison
#print axioms GKZBalancedDyadicScale.gamma_bounds
#print axioms GKZBalancedDyadicScale.gainPower_pos
#print axioms GKZBalancedDyadicScale.exists_balanced_dyadic_scale
#print axioms GKZOriginalPositivePower.growthExponent_pos
#print axioms GKZOriginalPositivePower.growthExponent_formula
#print axioms GKZOriginalPositivePower.growthConstant_pos
#print axioms GKZOriginalPositivePower.original_sum_product_positive_power
#print axioms GKZOriginalPositivePower.original_sum_product_growth
#print axioms GKZOriginalPositivePower.original_occupied_sum_product_growth
#print axioms GKZUniformGrowthParameters.growthExponent_lower_on_compact
#print axioms GKZUniformGrowthParameters.original_occupied_growth_uniform
#print axioms NativeCoarseOriginalIncidences.incidences_eq_swapped_bins
#print axioms NativeCoarseOriginalIncidences.mem_incidences
#print axioms NativeCoarseOriginalIncidences.original_tubes_unchanged
#print axioms NativeCoarseOriginalIncidences.coarse_card
#print axioms NativeCoarseOriginalIncidences.original_readback
#print axioms NativeCoarseOriginalIncidences.pullback_image
#print axioms NativeCoarseOriginalIncidences.actual_fiber_capacity
#print axioms NativeCoarseOriginalIncidences.actual_capacity
#print axioms NativeCoarseOriginalIncidences.actual_density_transfer
#print axioms NativeCoarseOriginalIncidences.actual_height_membership
#print axioms NativeCoarseOriginalGeometry.scalar_floor_center_error
#print axioms NativeCoarseOriginalGeometry.spatial_rounding
#print axioms NativeCoarseOriginalGeometry.height_rounding
#print axioms NativeCoarseOriginalGeometry.rounded_residual
#print axioms NativeCoarseOriginalGeometry.rounded_height_bound
#print axioms NativeCoarseOriginalGeometry.coordinates_scale_space
#print axioms NativeCoarseOriginalGeometry.coordinates_scale_height
#print axioms NativeCoarseOriginalGeometry.normalized_residual
#print axioms NativeCoarseOriginalGeometry.original_parent_offset_bound
#print axioms NativeCoarseOriginalGeometry.normalization_pos
#print axioms NativeCoarseOriginalGeometry.normalized_coordinate_box
#print axioms NativeCoarseOriginalHeights.integer_center_gap
#print axioms NativeCoarseOriginalHeights.coordinates_injective
#print axioms NativeCoarseOriginalHeights.actual_heights_separated
#print axioms NativeCoarseOriginalHeights.actual_heights_box
#print axioms NativeCoarseOriginalHeights.heightWindow_original_readback
#print axioms NativeCoarseOriginalHeights.heightWindow_actual_diameter
#print axioms NativeSourceCoarseReadback.chartFamily_card
#print axioms NativeSourceCoarseReadback.originalFamily_eq
#print axioms NativeSourceCoarseReadback.originalFamily_tubes
#print axioms NativeSourceCoarseReadback.original_capacity
#print axioms NativeSourceCoarseReadback.original_density
#print axioms NativeSourceCoarseReadback.native_scale_readback
#print axioms NativeSourceCoarseReadback.native_original_geometry
#print axioms NativeDenseSourceCoarseFamily.exists_actual_original_coarse_family
#print axioms NativeCoverADRepresentatives.exists_original_representatives
#print axioms NativeCoverADRepresentatives.injective_subset_card_le_cover
#print axioms NativeCoverADRepresentatives.half_grid_card
#print axioms NativeCoverADRepresentatives.representative_total_upper
#print axioms NativeCoverADRepresentatives.original_representatives_AD
#print axioms NativeUnitParentNormalization.pointInv_pointMap
#print axioms NativeUnitParentNormalization.pointMap_pointInv
#print axioms NativeUnitParentNormalization.parameter_box
#print axioms NativeUnitParentNormalization.map_rawFront_graph
#print axioms NativeUnitParentNormalization.original_front_maps_into_padded_front
#print axioms NativeUnitParentNormalization.padded_line_common_slab
#print axioms NativeUnitParentNormalization.parent_slope_bound
#print axioms NativeUnitParentNormalization.pointMap_dist_le
#print axioms NativeUnitParentNormalization.original_tube_maps_into_padded_tube
#print axioms NativeUnitParentNormalization.fixedCompactClass_compact
#print axioms NativeUnitParentNormalization.padded_line_mem_fixedCompactClass
#print axioms NativeUnitParentVolume.matrix_det
#print axioms NativeUnitParentVolume.linearPart_det
#print axioms NativeUnitParentVolume.rawLinear_apply
#print axioms NativeUnitParentVolume.linearPart_apply
#print axioms NativeUnitParentVolume.pointMap_eq_linear_add
#print axioms NativeUnitParentVolume.continuous_pointMap
#print axioms NativeUnitParentVolume.continuous_pointInv
#print axioms NativeUnitParentVolume.measurableSet_image
#print axioms NativeUnitParentVolume.volume_image
#print axioms NativeUnitParentVolume.volume_preimage
#print axioms NativeUnitParentVolume.convex_preimage
#print axioms NativeDenseRetainedUnitParent.realShadingMass_eq_toReal
#print axioms NativeDenseRetainedUnitParent.exists_dense_retained_parent
#print axioms NativeDenseRetainedUnitParent.realTubeMass_pos
#print axioms NativeDenseRetainedUnitParent.exists_dense_retained_volume_parent
#print axioms NativeDenseRetainedUnitParent.retained_parent_density
#print axioms NativeUnitParentShadings.shading_measurable
#print axioms NativeUnitParentShadings.shading_subset_tube
#print axioms NativeUnitParentShadings.shading_sum_volume
#print axioms NativeUnitParentShadings.shading_union_volume
#print axioms NativeUnitParentShadings.original_CW_to_padded
#print axioms NativeUnitParentShadings.padded_tube_volume_le_original
#print axioms NativeUnitParentDyadic.floor_sub_integer_mul
#print axioms NativeUnitParentDyadic.parameterLabel_eq_projection
#print axioms NativeUnitParentDyadic.projection_mem_box
#print axioms NativeUnitParentDyadic.projectionBox_card
#print axioms NativeUnitParentDyadic.parameter_fiber_bounds
#print axioms NativeUnitParentDyadic.unit_parent_fiber_eq
#print axioms NativeUnitParentDirections.slope_newLine
#print axioms NativeUnitParentDirections.slope_sub_le_direction_dist
#print axioms NativeUnitParentDirections.normalized_direction_separation
#print axioms NativeDenseNormalizedParent.realNormalizedShadingMass_eq
#print axioms NativeDenseNormalizedParent.realPaddedTubeMass_le
#print axioms NativeDenseNormalizedParent.exists_dense_normalized_parent
#print axioms OriginalThreeDimensionalCrossGeometry.norm_sq_coordinates
#print axioms OriginalThreeDimensionalCrossGeometry.norm_sq_nonneg
#print axioms OriginalThreeDimensionalCrossGeometry.distance_squared_dot
#print axioms OriginalThreeDimensionalCrossGeometry.distance_squared_difference
#print axioms OriginalThreeDimensionalCrossGeometry.original_projective_gap_cross_coordinate
#print axioms OriginalThreeDimensionalCrossGeometry.original_cross_bound_physical_tube
#print axioms OriginalThreeDimensionalSlabOverlap.original_cross_normal_minor_bound
#print axioms OriginalThreeDimensionalSlabOverlap.original_cramer_cross_bound
#print axioms OriginalThreeDimensionalSlabOverlap.original_two_slabs_force_pair_tube
#print axioms OriginalThreeDimensionalSlabOverlap.original_shared_slab_point_forces_close_normals
#print axioms OriginalThreeDimensionalNarrowSlabOverlap.original_weighted_cramer_bound
#print axioms OriginalThreeDimensionalNarrowSlabOverlap.original_narrow_slabs_force_pair_tube
#print axioms OriginalThreeDimensionalNarrowSlabOverlap.original_shared_narrow_slab_point_forces_close_normals
#print axioms OriginalThreeDimensionalAnnularSlabCharge.original_separated_slab_annuli_disjoint
#print axioms OriginalThreeDimensionalAnnularSlabCharge.original_separated_annular_slab_sum
#print axioms OriginalThreeDimensionalMiddleSliceBranch.original_selected_middle_slice_population
#print axioms OriginalThreeDimensionalTubeParameters.original_slope_bound
#print axioms OriginalThreeDimensionalTubeParameters.original_line_graph
#print axioms OriginalThreeDimensionalTubeParameters.original_graph_point
#print axioms OriginalThreeDimensionalTubeParameters.original_tube_graph_residual
#print axioms OriginalThreeDimensionalTubeParameters.original_parameter_cell_error
#print axioms OriginalThreeDimensionalTubeParameters.original_parameter_tube_transfer
#print axioms OriginalThreeDimensionalPairTubeFamily.original_endpoints_mem_tube
#print axioms OriginalThreeDimensionalPairTubeFamily.original_parameter_pair_fiber
#print axioms OriginalThreeDimensionalPairTubeFamily.exists_original_parameter_tube_family
#print axioms OriginalThreeDimensionalCommonChart.exists_original_common_chart
#print axioms OriginalThreeDimensionalCommonChart.exists_original_common_chart_tube_family
#print axioms OriginalTubeParameterIntegerCount.floor_mesh_error
#print axioms OriginalTubeParameterIntegerCount.three_fixed_coordinate_mass
#print axioms OriginalTubeGraphPairGeometry.original_box_distance_le_four
#print axioms OriginalTubeGraphPairGeometry.graph_pair_residual
#print axioms OriginalTubeGraphPairGeometry.graph_separation_large_coordinate
#print axioms OriginalTubeGraphPairGeometry.graph_slope_concentration
#print axioms OriginalThreeDimensionalTubePairCount.graph_offset_floor_residual
#print axioms OriginalThreeDimensionalTubePairCount.original_slope_self
#print axioms OriginalThreeDimensionalTubePairCount.original_offset_self
#print axioms OriginalThreeDimensionalTubePairCount.original_offset_fiber_card
#print axioms OriginalThreeDimensionalTubePairCount.original_parameter_count_from_slope_bins
#print axioms OriginalThreeDimensionalTubePairCount.original_two_point_tube_count
#print axioms OriginalThreeDimensionalTubePairCount.original_tubes_through_pair_card
#print axioms OriginalThreeDimensionalPairEnergy.dyadic_radius_pos
#print axioms OriginalThreeDimensionalPairEnergy.dyadic_radius_successor
#print axioms OriginalThreeDimensionalPairEnergy.exists_original_dyadic_terminal
#print axioms OriginalThreeDimensionalPairEnergy.inverse_square_kernel_nonneg
#print axioms OriginalThreeDimensionalPairEnergy.inverse_square_kernel_le_mesh
#print axioms OriginalThreeDimensionalPairEnergy.inverse_square_kernel_step
#print axioms OriginalThreeDimensionalPairEnergy.inverse_square_dyadic_majorant
#print axioms OriginalThreeDimensionalPairEnergy.original_point_inverse_square_energy
#print axioms OriginalThreeDimensionalPairEnergy.original_pair_inverse_square_energy
#print axioms OriginalThreeDimensionalTubeFamilyEnergy.original_tube_square_sum_swap
#print axioms OriginalThreeDimensionalTubeFamilyEnergy.original_tube_family_square_energy
#print axioms OriginalThreeDimensionalTubeFamilyEnergy.original_rich_tube_family_card
#print axioms OriginalThreeDimensionalTubeCells.original_pair_tube_cell_count
#print axioms OriginalThreeDimensionalTubeCells.original_cell_distance
#print axioms OriginalThreeDimensionalHeavyCubes.original_heavy_cube_budget
#print axioms OriginalThreeDimensionalHeavyCubes.original_light_cube_loss
#print axioms OriginalThreeDimensionalHeavyCubes.original_rich_tube_kept_mass
#print axioms OriginalThreeDimensionalHeavyCubes.original_cube_two_frostman
#print axioms OriginalThreeDimensionalHeavyCubes.original_rich_tube_heavy_cube_shading
#print axioms OriginalThreeDimensionalTubeCells.original_same_cell_tube_transfer
#print axioms OriginalThreeDimensionalHeavyCubes.exists_original_global_heavy_cube_shading
