import Theorems.Thm_StickyKakeya4_original_three_dimensional_direct_transverse_hairbrush
import Theorems.Thm_StickyKakeya4_native_normalized_parent_carrier_metric
import Theorems.Thm_StickyKakeya4_native_contracted_unit_parent
import Theorems.Thm_StickyKakeya4_native_original_padded_cells
import Theorems.Thm_StickyKakeya4_native_padded_cell_union_bound
import Theorems.Thm_StickyKakeya4_native_padded_cell_fiber_count
import Theorems.Thm_StickyKakeya4_native_padded_cell_source
import Theorems.Thm_StickyKakeya4_original_three_dimensional_large_slice_population
import Theorems.Thm_StickyKakeya4_original_three_dimensional_common_slice_radius
import Theorems.Thm_StickyKakeya4_original_three_dimensional_common_pair_radius
import Theorems.Thm_StickyKakeya4_native_original_concentrated_pair_graph
import Theorems.Thm_StickyKakeya4_original_bourgain_graph_transfer
import Theorems.Thm_StickyKakeya4_original_shared_fiber_pruning
import Theorems.Thm_StickyKakeya4_original_rich_alphabet_profile
import Theorems.Thm_StickyKakeya4_original_weak_alphabet_selection
import Theorems.Thm_StickyKakeya4_original_kaufman_shared_host
import Theorems.Thm_StickyKakeya4_original_profiled_third_query_family
import Theorems.Thm_StickyKakeya4_original_weighted_macro_selection
import Theorems.Thm_StickyKakeya4_original_macro_slice_cell_count
import Theorems.Thm_StickyKakeya4_original_planar_ad_grid_population
import Theorems.Thm_StickyKakeya4_original_macro_grain_readback
import Theorems.Thm_StickyKakeya4_original_representative_grid_comparison
import Theorems.Thm_StickyKakeya4_original_literal_grain_profiles
import Theorems.Thm_StickyKakeya4_original_literal_macro_density
import Theorems.Thm_StickyKakeya4_native_dyadic_coarse_normalization
import Theorems.Thm_StickyKakeya4_original_scalar_literal_cover_count
import Theorems.Thm_StickyKakeya4_original_literal_common_alphabet
import Theorems.Thm_StickyKakeya4_original_literal_angular_readback
import Theorems.Thm_StickyKakeya4_original_literal_angular_budget
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pencil_geometry
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pencil_overlap
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pencil_partition
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pencil_unit_slabs
import Theorems.Thm_StickyKakeya4_original_three_dimensional_pencil_brush_groups
import Theorems.Thm_StickyKakeya4_original_three_dimensional_shade_local_count
import Theorems.Thm_StickyKakeya4_original_three_dimensional_finite_shade_union
import Theorems.Thm_StickyKakeya4_original_three_dimensional_localized_energy
import Theorems.Thm_StickyKakeya4_original_three_dimensional_near_stem_shade
import Theorems.Thm_StickyKakeya4_original_three_dimensional_shade_group_concentration
import Theorems.Thm_StickyKakeya4_original_three_dimensional_group_source_mass
import Theorems.Thm_StickyKakeya4_original_three_dimensional_shaded_brush_slab

#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_endpoint_graph
#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_parallel_wedge_neighbor_mem
#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_bad_wedge_neighbors_card
#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_transverse_parameter_transfer
#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_transverse_intersection_diameter
#print axioms OriginalThreeDimensionalTransverseWedgeGeometry.original_transverse_intersection_card
#print axioms OriginalThreeDimensionalDenseWedgeCount.original_graph_row_card
#print axioms OriginalThreeDimensionalDenseWedgeCount.original_graph_row_sum
#print axioms OriginalThreeDimensionalDenseWedgeCount.original_row_bad_wedge_count
#print axioms OriginalThreeDimensionalDenseWedgeCount.original_dense_good_wedge_count
#print axioms OriginalThreeDimensionalRepresentativeWedges.exists_original_cell_preserving_chart_map
#print axioms OriginalThreeDimensionalRepresentativeWedges.original_good_wedge_representatives_mem
#print axioms OriginalThreeDimensionalRepresentativeWedges.original_representative_row_card
#print axioms OriginalThreeDimensionalRepresentativeWedges.original_good_wedge_representative_fiber
#print axioms OriginalThreeDimensionalTransverseHairbrush.original_transverse_pairs_lower_count
#print axioms OriginalThreeDimensionalTransverseHairbrush.original_brush_pair_fiber_card
#print axioms OriginalThreeDimensionalTransverseHairbrush.exists_original_largest_transverse_brush
#print axioms OriginalThreeDimensionalTransverseHairbrush.original_rich_family_scaled_upper
#print axioms OriginalThreeDimensionalTransverseHairbrush.exists_original_transverse_hairbrush
#print axioms OriginalThreeDimensionalSourceHairbrush.exists_original_dense_graph_hairbrush
#print axioms NativeNormalizedParentCarrierMetric.euclidean_three_norm_le_two
#print axioms NativeNormalizedParentCarrierMetric.heightPoint_zero_norm
#print axioms NativeNormalizedParentCarrierMetric.heightPoint_zero_sub_norm
#print axioms NativeNormalizedParentCarrierMetric.graph_direction_dist_le
#print axioms NativeNormalizedParentCarrierMetric.orthogonal_offset_dist_le
#print axioms NativeNormalizedParentCarrierMetric.graph_carrier_dist_le_sixteen
#print axioms NativeNormalizedParentCarrierMetric.normalized_intercept_norm_le_one
#print axioms NativeNormalizedParentCarrierMetric.contractLine_carrier_dist_le
#print axioms NativeNormalizedParentCarrierMetric.normalized_parent_carrier_dist_le
#print axioms NativeNormalizedParentCarrierMetric.same_floor_mul_close
#print axioms NativeNormalizedParentCarrierMetric.same_parent_cell_carrier_dist_le
#print axioms NativeContractedUnitParent.direction_contractLine
#print axioms NativeContractedUnitParent.contractLine_valid
#print axioms NativeContractedUnitParent.contractLine_rawFront
#print axioms NativeContractedUnitParent.contracted_parameter_mem
#print axioms NativeContractedUnitParent.contract_front
#print axioms NativeContractedUnitParent.contract_dist
#print axioms NativeContractedUnitParent.contract_tube
#print axioms NativeContractedUnitParent.contractLine_norm_le
#print axioms NativeContractedUnitParent.contractLine_center_height
#print axioms NativeContractedUnitParent.original_tube_maps_into_contracted
#print axioms NativeContractedUnitParent.contracted_direction_separation
#print axioms NativeContractedUnitParent.contracted_line_compact
#print axioms NativeContractedUnitParent.contracted_line_common_slab
#print axioms NativeOriginalPaddedCells.frontPoint_mem_front
#print axioms NativeOriginalPaddedCells.cells_meet_front
#print axioms NativeOriginalPaddedCells.cell_shading_subset_contracted_tube
#print axioms NativeOriginalPaddedCells.frontPoint_height
#print axioms NativeOriginalPaddedCells.cellLabel_height
#print axioms NativePaddedCellUnionBound.frontPoint_coordinate_error
#print axioms NativePaddedCellUnionBound.physicalCell_height
#print axioms NativePaddedCellUnionBound.frontPoint_near_physicalCell
#print axioms NativePaddedCellUnionBound.neighborBox_card
#print axioms NativePaddedCellUnionBound.cellIndex_mem_neighborBox
#print axioms NativePaddedCellUnionBound.original_cell_output_menu
#print axioms NativePaddedCellUnionBound.output_support_card_le
#print axioms NativePaddedCellUnionBound.union_cellShading_eq
#print axioms NativePaddedCellUnionBound.volume_cell_union
#print axioms NativePaddedCellUnionBound.output_union_volume_le
#print axioms NativePaddedCellFiberCount.original_row_card_le
#print axioms NativePaddedCellFiberCount.output_cell_fiber_card_le
#print axioms NativePaddedCellFiberCount.original_card_le_output_card
#print axioms NativePaddedCellFiberCount.original_shading_volume_le
#print axioms NativePaddedCellSource.originalLabel_mem
#print axioms NativePaddedCellSource.originalLabel_injective
#print axioms NativePaddedCellSource.originalLabel_range
#print axioms NativePaddedCellSource.source_thickness
#print axioms NativePaddedCellSource.source_line
#print axioms NativePaddedCellSource.source_shading
#print axioms NativePaddedCellSource.source_weights
#print axioms NativePaddedCellSource.dyadic_div_power
#print axioms NativePaddedCellSource.source_geometric_fields
#print axioms OriginalThreeDimensionalLargeSlicePopulation.original_common_radius_annular_population
#print axioms OriginalThreeDimensionalLargeSlicePopulation.original_large_common_slice_population
#print axioms OriginalThreeDimensionalCommonSliceRadius.chosen_slice_index_spec
#print axioms OriginalThreeDimensionalCommonSliceRadius.exists_original_common_slice_radius
#print axioms OriginalThreeDimensionalCommonSliceRadius.exists_original_concentrated_direction_radius
#print axioms OriginalThreeDimensionalCommonPairRadius.exists_original_common_rich_pair_radius
#print axioms NativeOriginalConcentratedPairGraph.chosen_heavy_slab_code_spec
#print axioms NativeOriginalConcentratedPairGraph.original_selected_concentrated_radius_upper
#print axioms NativeOriginalConcentratedPairGraph.original_concentrated_graph_rich_radius
#print axioms NativeOriginalConcentratedPairGraph.retained_unconcentrated_direction_population
#print axioms OriginalBourgainGraphTransfer.floor_translation_pair
#print axioms OriginalBourgainGraphTransfer.original_integer_graph_transfer
#print axioms OriginalSharedFiberPruning.rich_subset
#print axioms OriginalSharedFiberPruning.original_light_fiber_budget
#print axioms OriginalSharedFiberPruning.original_rich_label_charge
#print axioms OriginalSharedFiberPruning.original_rich_window_charge
#print axioms OriginalSharedFiberPruning.original_two_fiber_query_retention
#print axioms OriginalRichAlphabetProfile.realAlphabet_eq_image
#print axioms OriginalRichAlphabetProfile.original_scalar_ball_lift
#print axioms OriginalRichAlphabetProfile.original_weighted_scalar_cap
#print axioms OriginalRichAlphabetProfile.original_rich_alphabet_profile
#print axioms OriginalWeakAlphabetSelection.balanceLoss_mul_threshold
#print axioms OriginalWeakAlphabetSelection.alphabet_balance
#print axioms OriginalWeakAlphabetSelection.exists_original_weak_alphabets
#print axioms OriginalKaufmanSharedHost.original_intersection_loss
#print axioms OriginalKaufmanSharedHost.exists_original_shared_profile_host
#print axioms OriginalProfiledThirdQueryFamily.original_slope_profile_restrict
#print axioms OriginalProfiledThirdQueryFamily.exists_original_profiled_third_queries
#print axioms OriginalWeightedMacroSelection.sum_original_local_points
#print axioms OriginalWeightedMacroSelection.local_heights_pair_fiber
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_pairs
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_height_cells
#print axioms OriginalWeightedMacroSelection.weighted_denominator_of_height_cells
#print axioms OriginalWeightedMacroSelection.exists_original_weighted_macro
#print axioms OriginalWeightedMacroSelection.exists_physical_weighted_macro
#print axioms OriginalMacroSliceCellCount.original_slice_physical_cells
#print axioms OriginalMacroSliceCellCount.original_macro_denominator
#print axioms OriginalPlanarADGridPopulation.original_planar_total_mass
#print axioms OriginalPlanarADGridPopulation.original_planar_grid_mass
#print axioms OriginalMacroGrainReadback.grains_nonempty
#print axioms OriginalMacroGrainReadback.grain_grid_readback
#print axioms OriginalRepresentativeGridComparison.neighbors_card
#print axioms OriginalRepresentativeGridComparison.original_coarse_grid_comparison
#print axioms OriginalRepresentativeGridComparison.point_AD_isometric_image
#print axioms OriginalRepresentativeGridComparison.pair_image_readback
#print axioms OriginalRepresentativeGridComparison.pair_grid_image
#print axioms OriginalRepresentativeGridComparison.pair_grid_card
#print axioms OriginalRepresentativeGridComparison.pair_representative_readback
#print axioms OriginalLiteralGrainProfiles.original_grain_mass_lower
#print axioms OriginalLiteralGrainProfiles.exists_original_grain_representatives
#print axioms OriginalLiteralGrainProfiles.original_literal_grain_grid_mass
#print axioms OriginalLiteralGrainProfiles.original_literal_own_scale_grid_mass
#print axioms OriginalLiteralMacroDensity.matrix_entry_operator_bound
#print axioms OriginalLiteralMacroDensity.original_literal_global_point_mass
#print axioms OriginalLiteralMacroDensity.original_literal_Y_macro_denominator
#print axioms OriginalLiteralMacroDensity.exists_literal_dense_macro_of_slope_bound
#print axioms OriginalLiteralMacroDensity.exists_literal_source_dense_macro
#print axioms NativeDyadicCoarseNormalization.coordinates_between_scales
#print axioms NativeDyadicCoarseNormalization.larger_normalization_box
#print axioms NativeDyadicCoarseNormalization.larger_normalization_residual
#print axioms NativeDyadicCoarseNormalization.native_dyadic_scale
#print axioms NativeDyadicCoarseNormalization.dyadic_mesh_readback
#print axioms NativeDyadicCoarseNormalization.exists_actual_dyadic_coarse_family
#print axioms OriginalScalarLiteralCoverCount.cover_count_readback
#print axioms OriginalScalarLiteralCoverCount.diameter_grid_upper
#print axioms OriginalScalarLiteralCoverCount.boxed_cover_grid_upper
#print axioms OriginalScalarLiteralCoverCount.boxed_cover_allcenter
#print axioms OriginalScalarLiteralCoverCount.separated_card_eq_grid
#print axioms OriginalLiteralCommonAlphabet.original_net_upper
#print axioms OriginalLiteralCommonAlphabet.original_net_lower
#print axioms OriginalLiteralCommonAlphabet.exists_actual_common_alphabet
#print axioms OriginalLiteralCommonAlphabet.exists_actual_fine_alphabet
#print axioms OriginalLiteralAngularReadback.cover_exponent_lt_two
#print axioms OriginalLiteralAngularReadback.original_tube_reference_error
#print axioms OriginalLiteralAngularBudget.point_AD_budget_mono
#print axioms OriginalLiteralAngularBudget.literal_angular_cost_absorption
#print axioms OriginalLiteralAngularBudget.exists_literal_angular_power_cutoff
#print axioms OriginalLiteralAngularBudget.fourfold_schedule_readback
#print axioms OriginalLiteralAngularBudget.fourfold_scheduled_law
#print axioms OriginalThreeDimensionalPencilGeometry.original_transverse_coordinates
#print axioms OriginalThreeDimensionalPencilGeometry.original_pencil_scalar_spec
#print axioms OriginalThreeDimensionalPencilGeometry.original_pencil_band_support
#print axioms OriginalThreeDimensionalPencilGeometry.original_bounded_stem_residual
#print axioms OriginalThreeDimensionalPencilGeometry.original_pencil_bin_transfer
#print axioms OriginalThreeDimensionalPencilOverlap.original_outside_stem_residual
#print axioms OriginalThreeDimensionalPencilOverlap.original_scalar_pencil_overlap
#print axioms OriginalThreeDimensionalPencilOverlap.original_pencil_band_overlap
#print axioms OriginalThreeDimensionalPencilPartition.exists_original_pencil_representatives
#print axioms OriginalThreeDimensionalPencilPartition.original_pencil_group_full_population
#print axioms OriginalThreeDimensionalPencilPartition.original_pencil_shade_union_budget
#print axioms OriginalThreeDimensionalPencilUnitSlabs.original_pencil_affine_identity
#print axioms OriginalThreeDimensionalPencilUnitSlabs.original_pencil_normal_length
#print axioms OriginalThreeDimensionalPencilUnitSlabs.original_pencil_contains_stem
#print axioms OriginalThreeDimensionalPencilUnitSlabs.original_pencil_unit_slab
#print axioms OriginalThreeDimensionalPencilBrushGroups.exists_original_pencil_brush_groups
#print axioms OriginalThreeDimensionalShadeLocalCount.original_shade_interval_count
#print axioms OriginalThreeDimensionalShadeLocalCount.original_shade_ball_count
#print axioms OriginalThreeDimensionalShadeLocalCount.original_shade_far_pairs
#print axioms OriginalThreeDimensionalFiniteShadeUnion.original_finite_shade_union
#print axioms OriginalThreeDimensionalLocalizedEnergy.original_localized_pair_energy
#print axioms OriginalThreeDimensionalLocalizedEnergy.original_localized_tube_square_energy
#print axioms OriginalThreeDimensionalLocalizedEnergy.original_supported_tube_square_energy
#print axioms OriginalThreeDimensionalNearStemShade.original_shade_near_stem_count
#print axioms OriginalThreeDimensionalNearStemShade.original_shade_outside_stem_mass
#print axioms OriginalThreeDimensionalShadeGroupConcentration.exists_original_dense_shade_group
#print axioms OriginalThreeDimensionalGroupSourceMass.original_dense_group_source_mass
#print axioms OriginalThreeDimensionalGroupSourceMass.exists_original_shaded_group_source_mass
#print axioms OriginalThreeDimensionalShadedBrushSlab.exists_original_shaded_brush_slab
