import Theorems.Thm_StickyKakeya4_original_core_endpoint_lifting

#print axioms OriginalCoreEndpointLifting.one_state_height
#print axioms OriginalCoreEndpointLifting.two_state_height
#print axioms OriginalCoreEndpointLifting.select_original_endpoint_points
#print axioms OriginalCoreEndpointLifting.selected_core_points_are_original
#print axioms OriginalCoreEndpointLifting.scalar_cells_eq_endpoint_image
#print axioms OriginalCoreEndpointLifting.planar_cells_eq_endpoint_image
#print axioms OriginalCoreEndpointLifting.exists_scalar_original_endpoint_points
#print axioms OriginalCoreEndpointLifting.exists_planar_original_endpoint_points
