import Theorems.Thm_StickyKakeya4_original_unit_line_parameters
import Theorems.Thm_StickyKakeya4_original_unit_line_grid
import Theorems.Thm_StickyKakeya4_original_line_representative_charge
import Theorems.Thm_StickyKakeya4_original_unit_parameter_physical
import Theorems.Thm_StickyKakeya4_original_localized_line_cell_charge
import Theorems.Thm_StickyKakeya4_original_line_cell_physical_cover
import Theorems.Thm_StickyKakeya4_original_representative_shading
import Theorems.Thm_StickyKakeya4_original_line_cell_source_mass
import Theorems.Thm_StickyKakeya4_original_clipped_unit_tube
import Theorems.Thm_StickyKakeya4_original_clipped_tube_parameter_inverse
import Theorems.Thm_StickyKakeya4_original_line_residue_separation
import Theorems.Thm_StickyKakeya4_original_weighted_line_color_selection
import Theorems.Thm_StickyKakeya4_original_external_tube_cap_geometry
import Theorems.Thm_StickyKakeya4_original_clipped_tube_cap_charge
import Theorems.Thm_StickyKakeya4_original_clipped_tube_representation
import Theorems.Thm_StickyKakeya4_original_arbitrary_strip_cap_charge
import Theorems.Thm_StickyKakeya4_original_admissible_shaded_family
import Theorems.Thm_StickyKakeya4_original_thickening_color_budget
import Theorems.Thm_StickyKakeya4_native_original_step3_caller
import Theorems.Thm_StickyKakeya4_native_selected_physical_multiplicity
import Theorems.Thm_StickyKakeya4_native_original_slice_multiplicity
import Theorems.Thm_StickyKakeya4_native_finite_kakeya_counts
import Theorems.Thm_StickyKakeya4_native_finite_kakeya_exponent
import Theorems.Thm_StickyKakeya4_native_kakeya_volume_interface
import Theorems.Thm_StickyKakeya4_native_common_cubical_mesh
import Theorems.Thm_StickyKakeya4_native_cubical_incidence_counts
import Theorems.Thm_StickyKakeya4_native_abc_original_loss_budget
import Theorems.Thm_StickyKakeya4_native_original_log_budget
import Theorems.Thm_StickyKakeya4_native_uniform_abc_input
import Theorems.Thm_StickyKakeya4_native_abc_euclidean_strip
import Theorems.Thm_StickyKakeya4_original_common_scalar_fibers
import Theorems.Thm_StickyKakeya4_original_separated_packing
import Theorems.Thm_StickyKakeya4_original_scalar_line_cover
import Theorems.Thm_StickyKakeya4_original_scalar_collision_geometry
import Theorems.Thm_StickyKakeya4_original_scalar_affine_packing
import Theorems.Thm_StickyKakeya4_original_scalar_collision_counts
import Theorems.Thm_StickyKakeya4_original_line_collision_collapse
import Theorems.Thm_StickyKakeya4_original_common_fiber_projection
import Theorems.Thm_StickyKakeya4_original_direction_pair_count
import Theorems.Thm_StickyKakeya4_original_common_radial_pairs
import Theorems.Thm_StickyKakeya4_original_directional_double_count
import Theorems.Thm_StickyKakeya4_original_common_scalar_growth
import Theorems.Thm_StickyKakeya4_original_graph_radial_growth

#print axioms OriginalUnitLineParameters.original_unit_normal_trigonometric
#print axioms OriginalUnitLineParameters.original_unit_normal_square
#print axioms OriginalUnitLineParameters.original_line_point_parameter
#print axioms OriginalUnitLineParameters.original_unit_parameter_swap
#print axioms OriginalUnitLineParameters.original_same_root_parameter_close
#print axioms OriginalUnitLineParameters.original_class_hops_parameter_close
#print axioms OriginalUnitLineGrid.neighboring_cells_card
#print axioms OriginalUnitLineGrid.original_two_hop_cell_localization
#print axioms OriginalUnitLineGrid.exists_original_line_cell_representatives
#print axioms OriginalUnitLineGrid.original_two_hop_representative_multiplicity
#print axioms OriginalLineRepresentativeCharge.original_representative_pair_charge
#print axioms OriginalLineRepresentativeCharge.localized_original_representative_pair_charge
#print axioms OriginalLineRepresentativeCharge.exists_charged_original_line_representatives
#print axioms OriginalUnitParameterPhysical.original_unit_strip_residual_identity
#print axioms OriginalUnitParameterPhysical.original_unit_residual_physical
#print axioms OriginalUnitParameterPhysical.original_physical_unit_residual
#print axioms OriginalUnitParameterPhysical.original_parameter_residual_compare
#print axioms OriginalUnitParameterPhysical.original_parameter_support_transfer
#print axioms OriginalUnitParameterPhysical.original_parameter_close_endpoints
#print axioms OriginalLocalizedLineCellCharge.original_local_two_hop_physical_endpoints
#print axioms OriginalLocalizedLineCellCharge.original_local_line_cell_charge
#print axioms OriginalLineCellPhysicalCover.original_same_cell_parameter_close
#print axioms OriginalLineCellPhysicalCover.original_same_cell_physical_cover
#print axioms OriginalLineCellPhysicalCover.exists_charged_original_physical_cover
#print axioms OriginalRepresentativeShading.original_representative_shading_lower
#print axioms OriginalRepresentativeShading.original_representative_shading_support
#print axioms OriginalRepresentativeShading.original_shading_center_tube_witness
#print axioms OriginalLineCellSourceMass.original_line_cell_fiber_mass
#print axioms OriginalLineCellSourceMass.original_line_representative_fiber_partition
#print axioms OriginalLineCellSourceMass.original_line_representative_source_mass
#print axioms OriginalClippedUnitTube.original_unit_coordinate_bounds
#print axioms OriginalClippedUnitTube.original_normal_chart_valid
#print axioms OriginalClippedUnitTube.original_same_chart_sum_square
#print axioms OriginalClippedUnitTube.original_core_point_coordinates
#print axioms OriginalClippedUnitTube.original_core_point_mem
#print axioms OriginalClippedUnitTube.original_shading_half_mem_clipped
#print axioms OriginalClippedTubeParameterInverse.original_same_chart_determinant_normal_close
#print axioms OriginalClippedTubeParameterInverse.original_bounded_unit_offset
#print axioms OriginalClippedTubeParameterInverse.original_clipped_containment_parameter_close
#print axioms OriginalLineResidueSeparation.line_colors_card
#print axioms OriginalLineResidueSeparation.original_line_color_mem
#print axioms OriginalLineResidueSeparation.original_same_color_close_cell
#print axioms OriginalLineResidueSeparation.original_same_color_clipped_distinct
#print axioms OriginalWeightedLineColorSelection.original_selected_cell_graph_card
#print axioms OriginalWeightedLineColorSelection.exists_original_weighted_line_color
#print axioms OriginalWeightedLineColorSelection.exists_weighted_clipped_original_family
#print axioms OriginalExternalTubeCapGeometry.original_unit_dot_det_square
#print axioms OriginalExternalTubeCapGeometry.original_clipped_strip_moments
#print axioms OriginalExternalTubeCapGeometry.original_common_external_strip_parameter_close
#print axioms OriginalClippedTubeCapCharge.original_clipped_cap_pair_charge
#print axioms OriginalClippedTubeRepresentation.original_clipped_rectangle_representation
#print axioms OriginalClippedTubeRepresentation.original_half_point_injective
#print axioms OriginalClippedTubeRepresentation.original_half_shading_card
#print axioms OriginalArbitraryStripCapCharge.external_unit_line_representation
#print axioms OriginalArbitraryStripCapCharge.original_arbitrary_strip_cap_pair_charge
#print axioms OriginalAdmissibleShadedFamily.exists_original_admissible_shaded_family
#print axioms OriginalThickeningColorBudget.original_thickening_color_budget
#print axioms NativeOriginalStep3Caller.off_root_le_endpoint_counts
#print axioms NativeOriginalStep3Caller.exists_native_original_step3_threshold
#print axioms NativeSelectedPhysicalMultiplicity.refinementLoss_pos
#print axioms NativeSelectedPhysicalMultiplicity.eq_pullback_of_whole_fibers
#print axioms NativeSelectedPhysicalMultiplicity.selected_capacity
#print axioms NativeSelectedPhysicalMultiplicity.selected_support_gain
#print axioms NativeSelectedPhysicalMultiplicity.selected_cross_multiplicity
#print axioms NativeSelectedPhysicalMultiplicity.selected_density_cross_multiplicity
#print axioms NativeSelectedPhysicalMultiplicity.selected_density_multiplicity
#print axioms NativeSelectedPhysicalMultiplicity.source_count_lower_multiplicity
#print axioms NativeOriginalSliceMultiplicity.original_slice_population_with_multiplicity
#print axioms NativeFiniteKakeyaCounts.input_mono
#print axioms NativeFiniteKakeyaCounts.total_shading_le_card_mul_union
#print axioms NativeFiniteKakeyaCounts.carrier_count_lower
#print axioms NativeFiniteKakeyaCounts.total_tube_lower
#print axioms NativeFiniteKakeyaCounts.total_shading_lower
#print axioms NativeFiniteKakeyaCounts.union_volume_lower
#print axioms NativeFiniteKakeyaExponent.bound_mono
#print axioms NativeFiniteKakeyaExponent.bound_three
#print axioms NativeFiniteKakeyaExponent.exponents_nonempty
#print axioms NativeFiniteKakeyaExponent.exponents_bddBelow
#print axioms NativeFiniteKakeyaExponent.extremalExponent_nonneg
#print axioms NativeFiniteKakeyaExponent.extremalExponent_le_three
#print axioms NativeFiniteKakeyaExponent.bound_extremal
#print axioms NativeFiniteKakeyaExponent.not_bound_below_extremal
#print axioms NativeFiniteKakeyaExponent.counterexample_of_not_bound
#print axioms NativeFiniteKakeyaExponent.exists_near_extremizer
#print axioms NativeFiniteKakeyaExponent.finite_volume_of_bound_zero
#print axioms NativeKakeyaVolumeInterface.bound_zero_of_finite_volume
#print axioms NativeKakeyaVolumeInterface.bound_zero_iff_finite_volume
#print axioms NativeKakeyaVolumeInterface.extremal_zero_iff_finite_volume
#print axioms NativeKakeyaVolumeInterface.finite_volume_or_positive_extremal
#print axioms NativeCommonCubicalMesh.mem_halfChildren
#print axioms NativeCommonCubicalMesh.cell_eq_half_children
#print axioms NativeCommonCubicalMesh.cubical_at_half
#print axioms NativeCommonCubicalMesh.comparable_dyadic_cases
#print axioms NativeCommonCubicalMesh.input_exists_common_cells
#print axioms NativeCubicalIncidenceCounts.mem_incidences
#print axioms NativeCubicalIncidenceCounts.support_eq_image
#print axioms NativeCubicalIncidenceCounts.card_incidences
#print axioms NativeCubicalIncidenceCounts.sourceUnion_eq_support_cells
#print axioms NativeCubicalIncidenceCounts.total_shading_eq_incidence_volume
#print axioms NativeCubicalIncidenceCounts.union_eq_support_volume
#print axioms NativeCubicalIncidenceCounts.multiplicity_eq_card_ratio
#print axioms NativeCubicalIncidenceCounts.input_exists_incidence_counts
#print axioms NativeCubicalIncidenceCounts.exists_near_extremal_incidence_counts
#print axioms NativeABCOriginalLossBudget.graphLoss_le_fourth
#print axioms NativeABCOriginalLossBudget.graphMassLoss_le_ninth
#print axioms NativeABCOriginalLossBudget.actual_constructor_loss_budget
#print axioms NativeABCOriginalLossBudget.native_sixteenth_budget
#print axioms NativeOriginalLogBudget.exists_logarithmic_budget_cutoff
#print axioms NativeOriginalLogBudget.projection_menu_log_envelope
#print axioms NativeOriginalLogBudget.exists_projection_menu_budget_cutoff
#print axioms NativeUniformABCInput.exists_uniform_ABC_input
#print axioms NativeABCEuclideanStrip.actual_euclidean_strip_bound
#print axioms OriginalCommonScalarFibers.commonFiber_subset
#print axioms OriginalCommonScalarFibers.commonFiber_card_le
#print axioms OriginalCommonScalarFibers.commonFiber_eq_collision_fiber
#print axioms OriginalCommonScalarFibers.sum_commonFiber_eq_collisions
#print axioms OriginalCommonScalarFibers.commonFiber_second_moment
#print axioms OriginalCommonScalarFibers.richPairs_subset
#print axioms OriginalCommonScalarFibers.richPairs_common_lower
#print axioms OriginalCommonScalarFibers.commonFiber_sum_upper
#print axioms OriginalCommonScalarFibers.richPairs_card_lower
#print axioms OriginalCommonScalarFibers.richPairs_inter_card_lower
#print axioms OriginalSeparatedPacking.scalar_ball_card
#print axioms OriginalSeparatedPacking.planar_ball_card
#print axioms OriginalSeparatedPacking.card_le_real_mul_image
#print axioms OriginalScalarLineCover.common_lineOutput_subset
#print axioms OriginalScalarLineCover.common_line_grid_cover
#print axioms OriginalScalarLineCover.line_cover_collision_energy
#print axioms OriginalScalarLineCover.common_line_collision_energy
#print axioms OriginalScalarCollisionGeometry.same_grid_norm_le
#print axioms OriginalScalarCollisionGeometry.original_collision_separation
#print axioms OriginalScalarCollisionGeometry.original_collision_det
#print axioms OriginalScalarCollisionGeometry.det_two_near_directions
#print axioms OriginalScalarAffinePacking.scalar_affine_card
#print axioms OriginalScalarAffinePacking.planar_affine_card
#print axioms OriginalScalarCollisionCounts.collision_fiber_le_ball
#print axioms OriginalScalarCollisionCounts.close_scalar_collision_card
#print axioms OriginalLineCollisionCollapse.fixed_points_scalar_fiber_card
#print axioms OriginalLineCollisionCollapse.original_A_pair_collision_bound
#print axioms OriginalCommonFiberProjection.original_line_projected_pairs
#print axioms OriginalCommonFiberProjection.common_fiber_projected_pairs
#print axioms OriginalDirectionPairCount.original_residual_det
#print axioms OriginalDirectionPairCount.near_directions_mem_physical
#print axioms OriginalDirectionPairCount.directionPairs_card
#print axioms OriginalCommonRadialPairs.closePairs_card
#print axioms OriginalCommonRadialPairs.farPairs_complement_card
#print axioms OriginalCommonRadialPairs.exists_common_radial_pairs
#print axioms OriginalDirectionalDoubleCount.sum_projectedPairs_eq
#print axioms OriginalDirectionalDoubleCount.projectedPairs_sum_upper
#print axioms OriginalDirectionalDoubleCount.original_pair_double_count_growth
#print axioms OriginalCommonScalarGrowth.original_common_scalar_growth
#print axioms OriginalGraphRadialGrowth.original_graph_growth_of_original_radial_cap
