import Theorems.Thm_StickyKakeya4_original_three_dimensional_owner_tube_geometry
import Theorems.Thm_StickyKakeya4_original_three_dimensional_owner_query_tube
import Theorems.Thm_StickyKakeya4_original_three_dimensional_fiber_slab_geometry
import Theorems.Thm_StickyKakeya4_original_three_dimensional_projected_query_lift
import Theorems.Thm_StickyKakeya4_original_balanced_owner_counts
import Theorems.Thm_StickyKakeya4_original_three_dimensional_raw_owner_net
import Theorems.Thm_StickyKakeya4_original_dense_coefficient_counts
import Theorems.Thm_StickyKakeya4_original_dense_coefficient_energy
import Theorems.Thm_StickyKakeya4_original_dense_coefficient_projection
import Theorems.Thm_StickyKakeya4_original_three_dimensional_cover_ball_uniformity
import Theorems.Thm_StickyKakeya4_native_original_grid_balanced_fibers
import Theorems.Thm_StickyKakeya4_native_coarse_ancestor_counts
import Theorems.Thm_StickyKakeya4_native_coarse_color_selection
import Theorems.Thm_StickyKakeya4_native_coarse_direction_thinning
import Theorems.Thm_StickyKakeya4_original_coefficient_radius
import Theorems.Thm_StickyKakeya4_original_coefficient_density_profile
import Theorems.Thm_StickyKakeya4_original_coefficient_normalization
import Theorems.Thm_StickyKakeya4_original_coefficient_profile_radius
import Theorems.Thm_StickyKakeya4_original_full_coefficient_normalization
import Theorems.Thm_StickyKakeya4_original_rounded_ruzsa_cover
import Theorems.Thm_StickyKakeya4_original_rounded_ring_product
import Theorems.Thm_StickyKakeya4_original_monomial_small_cover
import Theorems.Thm_StickyKakeya4_original_signed_coefficient_cover
import Theorems.Thm_StickyKakeya4_original_selected_word_cover
import Theorems.Thm_StickyKakeya4_original_polynomial_ring_cover
import Theorems.Thm_StickyKakeya4_original_polynomial_mesh_transfer
import Theorems.Thm_StickyKakeya4_original_coefficient_zero_removal
import Theorems.Thm_StickyKakeya4_original_coefficient_cover_net
import Theorems.Thm_StickyKakeya4_original_polynomial_word_length
import Theorems.Thm_StickyKakeya4_original_uniform_quadratic_step
import Theorems.Thm_StickyKakeya4_original_uniform_polynomial_iteration
import Theorems.Thm_StickyKakeya4_original_normalized_polynomial_cover
import Theorems.Thm_StickyKakeya4_original_polynomial_word_homogeneity
import Theorems.Thm_StickyKakeya4_original_projected_owner_profile
import Theorems.Thm_StickyKakeya4_original_normalized_owner_query
import Theorems.Thm_StickyKakeya4_original_three_dimensional_owner_scale_cutoff
import Theorems.Thm_StickyKakeya4_original_three_dimensional_owner_tube_cap
import Theorems.Thm_StickyKakeya4_original_three_dimensional_projected_owner_cap
import Theorems.Thm_StickyKakeya4_original_normalized_owner_physical_bridge
import Theorems.Thm_StickyKakeya4_native_coarse_shading_capacity
import Theorems.Thm_StickyKakeya4_native_coarse_representative_geometry
import Theorems.Thm_StickyKakeya4_native_coarse_dyadic_shading
import Theorems.Thm_StickyKakeya4_native_coarse_weighted_pruning
import Theorems.Thm_StickyKakeya4_native_coarse_pruning_budget
import Theorems.Thm_StickyKakeya4_native_coarse_physical_containment
import Theorems.Thm_StickyKakeya4_native_coarse_cell_source
import Theorems.Thm_StickyKakeya4_native_coarse_shading_pruning
import Theorems.Thm_StickyKakeya4_native_coarse_carrier_geometry
import Theorems.Thm_StickyKakeya4_original_macro_direction_cells
import Theorems.Thm_StickyKakeya4_original_macro_direction_source
import Theorems.Thm_StickyKakeya4_original_macro_printed_w
import Theorems.Thm_StickyKakeya4_native_original_macro_tube_count
import Theorems.Thm_StickyKakeya4_native_rescaled_macro_tube_count
import Theorems.Thm_StickyKakeya4_original_macro_height_incidence_density
import Theorems.Thm_StickyKakeya4_original_selected_full_direction
import Theorems.Thm_StickyKakeya4_original_macro_w_tuple_readback

#print axioms OriginalThreeDimensionalOwnerTubeGeometry.original_distance_triangle
#print axioms OriginalThreeDimensionalOwnerTubeGeometry.original_coordinate_box_distance
#print axioms OriginalThreeDimensionalOwnerTubeGeometry.original_pair_owner_tube_perturbation
#print axioms OriginalThreeDimensionalOwnerTubeGeometry.original_delta_owner_tube
#print axioms OriginalThreeDimensionalOwnerQueryTube.original_query_tube_movement
#print axioms OriginalThreeDimensionalOwnerQueryTube.original_three_owner_tube
#print axioms OriginalThreeDimensionalOwnerQueryTube.original_owner_pair_separation
#print axioms OriginalThreeDimensionalFiberSlabGeometry.original_frame_coordinate_lipschitz
#print axioms OriginalThreeDimensionalFiberSlabGeometry.original_full_fiber_in_expanded_slab
#print axioms OriginalThreeDimensionalFiberSlabGeometry.original_raw_net_projected_separation
#print axioms OriginalThreeDimensionalProjectedQueryLift.original_euclidean_pair_strip
#print axioms OriginalThreeDimensionalProjectedQueryLift.original_projected_query_tube_lifts
#print axioms OriginalBalancedOwnerCounts.original_owner_mass_bounds
#print axioms OriginalBalancedOwnerCounts.original_dense_carrier_mass
#print axioms OriginalBalancedOwnerCounts.original_unweighted_owner_graph
#print axioms OriginalBalancedOwnerCounts.original_owner_rich_image
#print axioms OriginalBalancedOwnerCounts.original_owner_region_count
#print axioms OriginalThreeDimensionalRawOwnerNet.exists_original_raw_owner_net
#print axioms OriginalDenseCoefficientCounts.original_collision_b_count
#print axioms OriginalDenseCoefficientCounts.original_far_coefficient_count
#print axioms OriginalDenseCoefficientCounts.original_collision_near_far_partition
#print axioms OriginalDenseCoefficientEnergy.original_near_collision_count
#print axioms OriginalDenseCoefficientEnergy.original_far_collision_energy
#print axioms OriginalDenseCoefficientEnergy.original_dense_coefficient_collision_energy
#print axioms OriginalDenseCoefficientProjection.original_sum_cover_energy
#print axioms OriginalDenseCoefficientProjection.exists_original_coefficient_projection_bound
#print axioms OriginalDenseCoefficientProjection.original_common_small_sum_obstruction
#print axioms OriginalThreeDimensionalCoverBallUniformity.original_cardinal_mesh_cover_bounds
#print axioms OriginalThreeDimensionalCoverBallUniformity.original_cover_uniform_cardinal_ball_comparison
#print axioms OriginalThreeDimensionalUniformBallCover.original_uniform_outer_ball_population
#print axioms OriginalThreeDimensionalGridUniformity.original_grid_cell_capacity
#print axioms OriginalThreeDimensionalGridUniformity.original_cardinal_grid_cover_bounds
#print axioms OriginalThreeDimensionalGridUniformity.original_grid_uniform_implies_cover_uniform
#print axioms OriginalThreeDimensionalVoronoiFibers.original_owner_mem
#print axioms OriginalThreeDimensionalVoronoiFibers.original_owner_min
#print axioms OriginalThreeDimensionalVoronoiFibers.exists_original_euclidean_owner_net
#print axioms OriginalThreeDimensionalVoronoiFibers.original_full_fiber_ball_sandwich
#print axioms OriginalThreeDimensionalVoronoiFibers.original_full_fiber_partition
#print axioms OriginalThreeDimensionalVoronoiFibers.original_uniform_full_fiber_population
#print axioms OriginalThreeDimensionalVoronoiFibers.exists_original_common_fiber_population
#print axioms OriginalThreeDimensionalGridBalancedFibers.exists_original_grid_balanced_fibers
#print axioms NativeCoarseAncestorCounts.fiber_in_ancestor_eq
#print axioms NativeCoarseAncestorCounts.descendant_fiber_sum
#print axioms NativeCoarseAncestorCounts.descendant_counts_cross
#print axioms NativeCoarseAncestorCounts.scale_ratio
#print axioms NativeCoarseAncestorCounts.coarse_ancestor_AD
#print axioms NativeCoarseAncestorCounts.compact_original_coarse_ancestor_counts
#print axioms NativeCoarseColorSelection.rank_lt
#print axioms NativeCoarseColorSelection.same_slope_rank_injective
#print axioms NativeCoarseColorSelection.same_slope_color_injective
#print axioms NativeCoarseColorSelection.palette_card
#print axioms NativeCoarseColorSelection.color_mem_palette
#print axioms NativeCoarseColorSelection.image_color_card_le
#print axioms NativeCoarseColorSelection.exists_dense_color
#print axioms NativeCoarseColorSelection.equal_floor_of_same_residue_close
#print axioms NativeCoarseDirectionThinning.representative_spec
#print axioms NativeCoarseDirectionThinning.same_color_direction_separation
#print axioms NativeCoarseDirectionThinning.original_rank_budget
#print axioms NativeCoarseDirectionThinning.exists_dense_direction_thinning
#print axioms OriginalCoefficientRadius.mesh_le_radius
#print axioms OriginalCoefficientRadius.pair_le_radius
#print axioms OriginalCoefficientRadius.radius_le
#print axioms OriginalCoefficientRadius.radius_mono
#print axioms OriginalCoefficientRadius.exists_original_maximal_density
#print axioms OriginalCoefficientRadius.original_radius_packing
#print axioms OriginalCoefficientDensityProfile.original_maximal_window
#print axioms OriginalCoefficientDensityProfile.original_normalization_injective
#print axioms OriginalCoefficientDensityProfile.original_normalized_profile
#print axioms OriginalCoefficientDensityProfile.original_retained_mass
#print axioms OriginalCoefficientDensityProfile.original_radius_lower
#print axioms OriginalCoefficientNormalization.original_normalized_mesh_bound
#print axioms OriginalCoefficientNormalization.exists_original_normalized_coefficients
#print axioms OriginalCoefficientNormalization.exists_original_profile_separated_pair
#print axioms OriginalCoefficientNormalization.original_coarse_profile_cardinality
#print axioms OriginalCoefficientNormalization.absolute_diameter_threshold
#print axioms OriginalCoefficientProfileRadius.original_available_profile_radius
#print axioms OriginalCoefficientProfileRadius.original_full_profile_radius
#print axioms OriginalFullCoefficientNormalization.exists_original_full_profile_normalization
#print axioms OriginalFullCoefficientNormalization.original_full_radius_power
#print axioms OriginalFullCoefficientNormalization.original_final_polynomial_mesh
#print axioms OriginalRoundedRuzsaCover.sum_cells_product
#print axioms OriginalRoundedRuzsaCover.sub_cells_product
#print axioms OriginalRoundedRuzsaCover.sum_rounding_comparison
#print axioms OriginalRoundedRuzsaCover.sub_rounding_comparison
#print axioms OriginalRoundedRuzsaCover.original_rounded_sum_triangle
#print axioms OriginalRoundedRuzsaCover.original_rounded_sub_sum_triangle
#print axioms OriginalRoundedRingProduct.dilate_sum
#print axioms OriginalRoundedRingProduct.dilate_product
#print axioms OriginalRoundedRingProduct.dilate_inverse
#print axioms OriginalRoundedRingProduct.original_dilation_cover
#print axioms OriginalRoundedRingProduct.original_inverse_dilation_cover
#print axioms OriginalRoundedRingProduct.original_product_coefficient_cover
#print axioms OriginalRoundedRingProduct.original_product_small_cover
#print axioms OriginalMonomialSmallCover.original_product_factor_bound
#print axioms OriginalMonomialSmallCover.original_monomial_small_cover
#print axioms OriginalSignedCoefficientCover.original_self_sum_cover
#print axioms OriginalSignedCoefficientCover.original_self_sum_small_cover
#print axioms OriginalSignedCoefficientCover.original_negative_dilate_identity
#print axioms OriginalSignedCoefficientCover.original_negative_small_cover
#print axioms OriginalSelectedWordCover.original_selected_word_cover
#print axioms OriginalPolynomialRingCover.original_signed_monomial_covers
#print axioms OriginalPolynomialRingCover.original_polynomial_word_cover
#print axioms OriginalPolynomialMeshTransfer.exists_original_coarser_dyadic_mesh
#print axioms OriginalPolynomialMeshTransfer.original_coarse_cover_le
#print axioms OriginalPolynomialMeshTransfer.original_homogeneous_mesh
#print axioms OriginalPolynomialMeshTransfer.original_homogeneous_cover_transfer
#print axioms OriginalCoefficientZeroRemoval.original_remove_zero_mass
#print axioms OriginalCoefficientZeroRemoval.original_remove_zero_profile
#print axioms OriginalCoefficientCoverNet.exists_original_separated_coefficient_net
#print axioms OriginalCoefficientCoverNet.exists_original_dense_coefficient_net
#print axioms OriginalPolynomialWordLength.signed_monomial_zero
#print axioms OriginalPolynomialWordLength.original_atom_mem
#print axioms OriginalPolynomialWordLength.signed_monomial_neg
#print axioms OriginalPolynomialWordLength.signed_monomial_mul
#print axioms OriginalPolynomialWordLength.finite_mul_word_subset
#print axioms OriginalPolynomialWordLength.finite_word_mul_word_subset
#print axioms OriginalPolynomialWordLength.polynomial_word_neg
#print axioms OriginalPolynomialWordLength.polynomial_word_product
#print axioms OriginalPolynomialWordLength.original_quadratic_word_complexity
#print axioms OriginalPolynomialWordLength.exists_signed_monomial_witness
#print axioms OriginalPolynomialWordLength.exists_polynomial_word_witnesses
#print axioms OriginalUniformQuadraticStep.uniform_word_count_two_le
#print axioms OriginalUniformQuadraticStep.uniform_step_positive
#print axioms OriginalUniformQuadraticStep.uniform_slab_radius_bound
#print axioms OriginalUniformQuadraticStep.uniform_word_count_bound
#print axioms OriginalUniformQuadraticStep.uniform_coefficient_bound
#print axioms OriginalUniformQuadraticStep.exists_uniform_original_quadratic_step
#print axioms OriginalUniformPolynomialIteration.uniform_cover_constant_pos
#print axioms OriginalUniformPolynomialIteration.uniform_monomial_count_pos
#print axioms OriginalUniformPolynomialIteration.original_iteration_word_complexity
#print axioms OriginalUniformPolynomialIteration.original_tensor_one_cover
#print axioms OriginalUniformPolynomialIteration.original_uniform_iteration_cover
#print axioms OriginalUniformPolynomialIteration.exists_fixed_original_polynomial_word_cover
#print axioms OriginalNormalizedPolynomialCover.exists_fixed_polynomial_cover_of_normalized_profile
#print axioms OriginalNormalizedPolynomialCover.exists_original_profile_interval_endpoints
#print axioms OriginalNormalizedPolynomialCover.exists_fixed_polynomial_cover_of_absolute_profile
#print axioms OriginalPolynomialWordHomogeneity.polynomial_word_zero
#print axioms OriginalPolynomialWordHomogeneity.centered_original_atom_word
#print axioms OriginalPolynomialWordHomogeneity.normalized_monomial_homogeneity
#print axioms OriginalPolynomialWordHomogeneity.normalized_signed_monomial_homogeneity
#print axioms OriginalPolynomialWordHomogeneity.original_polynomial_word_homogeneity
#print axioms OriginalProjectedOwnerProfile.original_normalized_project_distance
#print axioms OriginalProjectedOwnerProfile.original_normalized_project_box
#print axioms OriginalProjectedOwnerProfile.original_normalized_owner_separation
#print axioms OriginalProjectedOwnerProfile.original_normalized_owner_injective
#print axioms OriginalProjectedOwnerProfile.original_normalized_owner_card
#print axioms OriginalProjectedOwnerProfile.original_normalized_region_readback
#print axioms OriginalProjectedOwnerProfile.original_owner_region_in_original_ball
#print axioms OriginalProjectedOwnerProfile.original_owner_region_original_mass
#print axioms OriginalProjectedOwnerProfile.original_normalized_owner_profile
#print axioms OriginalProjectedOwnerProfile.original_projected_owner_point_profile
#print axioms OriginalProjectedOwnerProfile.original_dense_graph_projected_owner_profile
#print axioms OriginalNormalizedOwnerQuery.original_normalized_linePoint
#print axioms OriginalNormalizedOwnerQuery.original_normalized_chart_linePoint
#print axioms OriginalNormalizedOwnerQuery.original_normalized_chart_distance
#print axioms OriginalNormalizedOwnerQuery.original_chart_euclidean_pair_tube_iff
#print axioms OriginalNormalizedOwnerQuery.original_normalized_chart_query_iff
#print axioms OriginalNormalizedOwnerQuery.original_normalized_query_iff
#print axioms OriginalNormalizedOwnerQuery.original_normalized_query_subset_readback
#print axioms OriginalNormalizedOwnerQuery.original_normalized_query_card_readback
#print axioms OriginalThreeDimensionalOwnerScaleCutoff.exists_original_owner_scale_cutoff
#print axioms OriginalThreeDimensionalOwnerTubeCap.original_reverse_owner_tube
#print axioms OriginalThreeDimensionalOwnerTubeCap.original_owner_tube_preimage
#print axioms OriginalThreeDimensionalOwnerTubeCap.original_unweighted_owner_tube_cap
#print axioms OriginalThreeDimensionalProjectedOwnerCap.original_projected_owner_preimage_tube
#print axioms OriginalThreeDimensionalProjectedOwnerCap.original_projected_owner_tube_cap
#print axioms OriginalNormalizedOwnerPhysicalBridge.original_distance2_eq_a1_euclidean
#print axioms OriginalNormalizedOwnerPhysicalBridge.original_distance2_eq_a1_euclidean_reverse
#print axioms OriginalNormalizedOwnerPhysicalBridge.original_a1_physical_pair_tube_iff
#print axioms OriginalNormalizedOwnerPhysicalBridge.original_physical_tube_normalizes
#print axioms OriginalNormalizedOwnerPhysicalBridge.original_physical_tube_normalized_membership
#print axioms NativeCoarseShadingCapacity.projectedLabel_height
#print axioms NativeCoarseShadingCapacity.projected_fiber_card_le
#print axioms NativeCoarseShadingCapacity.joint_fiber_card_le
#print axioms NativeCoarseShadingCapacity.total_incidence_capacity
#print axioms NativeCoarseShadingCapacity.cell_mass_scale_cancellation
#print axioms NativeCoarseShadingCapacity.retained_spec
#print axioms NativeCoarseShadingCapacity.retained_card
#print axioms NativeCoarseShadingCapacity.coarse_card_sum_rows
#print axioms NativeCoarseShadingCapacity.retained_shading_real
#print axioms NativeCoarseShadingCapacity.coarse_shading_real
#print axioms NativeCoarseShadingCapacity.actual_aggregate_shading_transfer
#print axioms NativeCoarseRepresentativeGeometry.direction_zero_parent
#print axioms NativeCoarseRepresentativeGeometry.zero_parent_valid_slab
#print axioms NativeCoarseRepresentativeGeometry.projected_point_mem_front
#print axioms NativeCoarseRepresentativeGeometry.projected_rows_meet_front
#print axioms NativeCoarseRepresentativeGeometry.projected_shading_subset_tube
#print axioms NativeCoarseRepresentativeGeometry.compact_mark_offset
#print axioms NativeCoarseRepresentativeGeometry.zero_intercept_bound
#print axioms NativeCoarseRepresentativeGeometry.zero_parent_mem_fixedCompactClass
#print axioms NativeCoarseDyadicShading.block_pos
#print axioms NativeCoarseDyadicShading.block_scale
#print axioms NativeCoarseDyadicShading.block_mesh
#print axioms NativeCoarseDyadicShading.block_thickness
#print axioms NativeCoarseDyadicShading.block_thickness_dyadic
#print axioms NativeCoarseDyadicShading.original_dyadic_shading_transfer
#print axioms NativeCoarseWeightedPruning.ancestor_pruning
#print axioms NativeCoarseWeightedPruning.weighted_loss
#print axioms NativeCoarseWeightedPruning.ancestor_menu_subset
#print axioms NativeCoarseWeightedPruning.original_color_weighted_pruning
#print axioms NativeCoarsePruningBudget.original_occupied_count
#print axioms NativeCoarsePruningBudget.occupied_threshold_charge
#print axioms NativeCoarsePruningBudget.weighted_pruning_power_budget
#print axioms NativeCoarsePhysicalContainment.graphPoint_mem_front
#print axioms NativeCoarsePhysicalContainment.graphPoint_same_cell_dist
#print axioms NativeCoarsePhysicalContainment.physicalMap_dist_zero
#print axioms NativeCoarsePhysicalContainment.original_front_height_bound
#print axioms NativeCoarsePhysicalContainment.original_tube_in_representative
#print axioms NativeCoarseCellSource.parentIndex_mem
#print axioms NativeCoarseCellSource.parentIndex_injective
#print axioms NativeCoarseCellSource.parentIndex_range
#print axioms NativeCoarseCellSource.source_thickness
#print axioms NativeCoarseCellSource.source_line
#print axioms NativeCoarseCellSource.source_shading
#print axioms NativeCoarseCellSource.source_geometric_fields
#print axioms NativeCoarseShadingPruning.coarse_thickness_le_one
#print axioms NativeCoarseShadingPruning.actual_weight_upper
#print axioms NativeCoarseShadingPruning.actual_shading_pruning
#print axioms NativeCoarseCarrierGeometry.parameter_error_carrier_dist
#print axioms NativeCoarseCarrierGeometry.same_parameter_cell_carrier_dist
#print axioms NativeCoarseCarrierGeometry.pruned_carrier_lower
#print axioms OriginalMacroDirectionCells.direction_cells_box_bound
#print axioms OriginalMacroDirectionCells.original_reference_cell_count
#print axioms OriginalMacroDirectionCells.literal_original_direction_mass
#print axioms OriginalMacroDirectionCells.direction_cell_gap
#print axioms OriginalMacroDirectionCells.full_direction_collision
#print axioms OriginalMacroDirectionSource.original_direction_reference_cover
#print axioms OriginalMacroDirectionSource.original_full_terminal_population
#print axioms OriginalMacroPrintedW.original_full_witness_conditions
#print axioms OriginalMacroPrintedW.original_full_terminal_fiber_cap
#print axioms NativeOriginalMacroTubeCount.direction_vector_readback
#print axioms NativeOriginalMacroTubeCount.native_terminal_fiber_card
#print axioms NativeOriginalMacroTubeCount.native_tubes_le_terminal_cells
#print axioms NativeOriginalMacroTubeCount.native_original_macro_tube_population
#print axioms NativeRescaledMacroTubeCount.actual_slope_readback
#print axioms NativeRescaledMacroTubeCount.actual_mesh_le_source_scale
#print axioms NativeRescaledMacroTubeCount.rescaled_terminal_fiber_card
#print axioms NativeRescaledMacroTubeCount.rescaled_tubes_le_terminal_cells
#print axioms NativeRescaledMacroTubeCount.rescaled_original_macro_tube_population
#print axioms OriginalMacroHeightIncidenceDensity.original_degree_power_mass
#print axioms OriginalMacroHeightIncidenceDensity.original_height_density_from_source_counts
#print axioms OriginalSelectedFullDirection.selected_joint_direction_realization
#print axioms OriginalSelectedFullDirection.coarse_reference_error_at_double_scale
#print axioms OriginalMacroWTupleReadback.original_nine_tuple_readback
