import Theorems.Thm_StickyKakeya4_parameterized_scalar_potential

#print axioms StickyKakeya4.ScalarProjection.measurable_parameterizedScalarPotential
#print axioms StickyKakeya4.ScalarProjection.parameterizedScalarPotential_eq_map_potential
#print axioms StickyKakeya4.ScalarProjection.parameterizedScalarPotential_integral_eq_pair_energy
#print axioms StickyKakeya4.ScalarProjection.ae_finite_parameterizedScalarPotential_integral
#print axioms StickyKakeya4.ScalarProjection.ae_finite_parameterizedScalarPotential
