import Theorems.Thm_StickyKakeya4_positive_bush_frostman
#print axioms StickyKakeya4.PositiveBush.exists_separated_subinterval
#print axioms StickyKakeya4.PositiveBush.exact_bush_displacement
#print axioms StickyKakeya4.PositiveBush.exact_bush_collision_mass_le_cubic
#print axioms StickyKakeya4.PositiveBush.exact_bush_averaged_collision_power
#print axioms StickyKakeya4.PositiveBush.front_frostman_of_positive_exact_bush
#print axioms StickyKakeya4.PositiveBush.front_dimH_eq_four_of_positive_exact_bush
#check StickyKakeya4.PositiveBush.front_dimH_eq_four_of_positive_exact_bush

#print axioms StickyKakeya4.PositiveBush.front_frostman_of_positive_exact_bush_piece
#print axioms StickyKakeya4.PositiveBush.front_dimH_eq_four_of_positive_exact_bush_piece

#print axioms StickyKakeya4.PositiveBush.exact_bush_mass_ge_of_convergent_approximate_bushes
#print axioms StickyKakeya4.PositiveBush.approximate_bush_center_bound
#print axioms StickyKakeya4.PositiveBush.exists_positive_exact_bush_of_shrinking_bushes
#print axioms StickyKakeya4.PositiveBush.front_frostman_of_shrinking_positive_bushes
#check StickyKakeya4.PositiveBush.front_frostman_of_shrinking_positive_bushes

#print axioms StickyKakeya4.PositiveBush.front_frostman_of_shrinking_positive_bushes_of_bounded_intercept
#print axioms StickyKakeya4.PositiveBush.front_dimH_eq_four_of_shrinking_positive_bushes
#check StickyKakeya4.PositiveBush.front_dimH_eq_four_of_shrinking_positive_bushes

#print axioms StickyKakeya4.PositiveBush.uniform_small_bush_mass_of_no_front_frostman
#print axioms StickyKakeya4.PositiveBush.uniform_small_bush_mass_of_front_dimH_ne_four
#check StickyKakeya4.PositiveBush.uniform_small_bush_mass_of_front_dimH_ne_four
