import Theorems.Thm_StickyKakeya4_positive_cell_regularization

set_option autoImplicit false

#print axioms StickyKakeya4.PositiveCellRegularization.stage
#print axioms StickyKakeya4.PositiveCellRegularization.stage_zero
#print axioms StickyKakeya4.PositiveCellRegularization.stage_antitone
#print axioms StickyKakeya4.PositiveCellRegularization.measurableSet_stage
#print axioms StickyKakeya4.PositiveCellRegularization.firstCharge
#print axioms StickyKakeya4.PositiveCellRegularization.measure_firstCharge_le
#print axioms StickyKakeya4.PositiveCellRegularization.stage_inter_subset_firstCharge
#print axioms StickyKakeya4.PositiveCellRegularization.stage_compl_subset_firstCharges
#print axioms StickyKakeya4.PositiveCellRegularization.retained
#print axioms StickyKakeya4.PositiveCellRegularization.measurableSet_retained
#print axioms StickyKakeya4.PositiveCellRegularization.measure_retained_compl_le
#print axioms StickyKakeya4.PositiveCellRegularization.retained_cell_zero_or_ge
#print axioms StickyKakeya4.PositiveCellRegularization.measure_retained_pos
#print axioms StickyKakeya4.PositiveCellRegularization.exists_positive_restriction
#print axioms StickyKakeya4.PositiveCellRegularization.exists_positive_restriction_of_finite_weight
#print axioms StickyKakeya4.PositiveCellRegularization.dyadicScale
#print axioms StickyKakeya4.PositiveCellRegularization.multiscale_weight_ne_top
#print axioms StickyKakeya4.PositiveCellRegularization.exists_multiscale_positive_restriction
#print axioms StickyKakeya4.PositiveCellRegularization.exists_clean_restriction
