import Theorems.Thm_StickyKakeya4_positive_flag_conditioning

#check @StickyKakeya4.PositiveFlagConditioning.successProbability
#check @StickyKakeya4.PositiveFlagConditioning.positiveSource
#check @StickyKakeya4.PositiveFlagConditioning.measurable_successProbability
#check @StickyKakeya4.PositiveFlagConditioning.measurableSet_positiveSource
#check @StickyKakeya4.PositiveFlagConditioning.successfulMeasure
#check @StickyKakeya4.PositiveFlagConditioning.successful_source_density
#check @StickyKakeya4.PositiveFlagConditioning.successful_source_null_iff
#check @StickyKakeya4.PositiveFlagConditioning.successful_source_ae_iff
#check @StickyKakeya4.PositiveFlagConditioning.successful_source_equivalent
#check @StickyKakeya4.PositiveFlagConditioning.conditionedKernel
#check @StickyKakeya4.PositiveFlagConditioning.successful_disintegration
#check @StickyKakeya4.PositiveFlagConditioning.conditionedExtension
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_equivalent
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_success
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_kernel_success
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_kernel_success_mass
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_restrict_success
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_original
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_observable
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_mass
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_extension_genuine
#check @StickyKakeya4.PositiveFlagConditioning.conditioned_subsource_law
#check @StickyKakeya4.PositiveFlagConditioning.exists_lossless_positive_conditioning
#check @StickyKakeya4.PositiveFlagConditioning.exists_lossless_conditioning_of_ae_positive

#print axioms StickyKakeya4.PositiveFlagConditioning.successProbability
#print axioms StickyKakeya4.PositiveFlagConditioning.positiveSource
#print axioms StickyKakeya4.PositiveFlagConditioning.measurable_successProbability
#print axioms StickyKakeya4.PositiveFlagConditioning.measurableSet_positiveSource
#print axioms StickyKakeya4.PositiveFlagConditioning.successfulMeasure
#print axioms StickyKakeya4.PositiveFlagConditioning.successful_source_density
#print axioms StickyKakeya4.PositiveFlagConditioning.successful_source_null_iff
#print axioms StickyKakeya4.PositiveFlagConditioning.successful_source_ae_iff
#print axioms StickyKakeya4.PositiveFlagConditioning.successful_source_equivalent
#print axioms StickyKakeya4.PositiveFlagConditioning.conditionedKernel
#print axioms StickyKakeya4.PositiveFlagConditioning.successful_disintegration
#print axioms StickyKakeya4.PositiveFlagConditioning.conditionedExtension
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_equivalent
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_success
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_kernel_success
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_kernel_success_mass
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_restrict_success
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_original
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_observable
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_mass
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_extension_genuine
#print axioms StickyKakeya4.PositiveFlagConditioning.conditioned_subsource_law
#print axioms StickyKakeya4.PositiveFlagConditioning.exists_lossless_positive_conditioning
#print axioms StickyKakeya4.PositiveFlagConditioning.exists_lossless_conditioning_of_ae_positive
