import Theorems.Thm_StickyKakeya4_positive_routing_exhaustion

#print axioms StickyKakeya4.PositiveRoutingExhaustion.exists_countable_routing_cover
#print axioms StickyKakeya4.PositiveRoutingExhaustion.exists_disjoint_routing_partition
#print axioms StickyKakeya4.PositiveRoutingExhaustion.exists_routing_measure_identity
#print axioms StickyKakeya4.PositiveRoutingExhaustion.exhaustive_markov_extensions_preserve_occurrence
#print axioms StickyKakeya4.PositiveRoutingExhaustion.source_piece_positive_of_lower_density
#print axioms StickyKakeya4.PositiveRoutingExhaustion.positive_route_withDensity
#print axioms StickyKakeya4.PositiveRoutingExhaustion.source_density_routing_exhaustion
#print axioms StickyKakeya4.PositiveRoutingExhaustion.finite_truncation_arbitrarily_small_tail
