import Theorems.Thm_StickyKakeya4_qualitative_union_growth_termination

#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.densitySupport
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.density_support_sdiff_null
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.density_support_ae_subset
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.density_support_measure_le
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.density_support_real_le
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.submeasure_density_support_sdiff_null
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.withDensity_compl_densitySupport
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.submeasure_endpoint_density_support_sdiff_null
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversal_source_eq
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversal_target_eq
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversed_labeled_source_eq
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversed_labeled_submeasure_target_le
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversed_labeled_target_support_sdiff_null
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.reversed_labeled_target_support_real_le
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.source_density_support_restrict_eq
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.source_cut_trim_to_density_support
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.exhaustive_source_partition_selector_cover
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.finite_selector_cover_gt_half
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.two_growths_impossible_of_support_bound
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.no_two_whole_support_growths
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.finiteSelectorSupport
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.finite_exhaustive_reversal_blocks_second_growth
#print axioms StickyKakeya4.QualitativeUnionGrowthTermination.positive_routing_forces_qualitative_termination
