import Theorems.Thm_StickyKakeya4_rank_one_native_potentials

#print axioms StickyKakeya4.RankOneNativePotentials.potential₁_eq_source
#print axioms StickyKakeya4.RankOneNativePotentials.measurable_potential₁
#print axioms StickyKakeya4.RankOneNativePotentials.ae_finite_identity_potential
#print axioms StickyKakeya4.RankOneNativePotentials.nativeOwnPotential_eq_source
#print axioms StickyKakeya4.RankOneNativePotentials.measurable_nativeOwnPotential
#print axioms StickyKakeya4.RankOneNativePotentials.translated_nativeOwnPotential_eq
#print axioms StickyKakeya4.RankOneNativePotentials.ae_finite_translated_nativeOwnPotential
#print axioms StickyKakeya4.RankOneNativePotentials.feedback_potential₁_eq_scaled
#print axioms StickyKakeya4.RankOneNativePotentials.ae_finite_feedback_potential₁
#print axioms StickyKakeya4.RankOneNativePotentials.ae_finite_zero_feedback_potential₁
