import Theorems.Thm_StickyKakeya4_rank_one_general_input_escape

#print axioms StickyKakeya4.RankOneGeneralInputEscape.exists_input_matrix
#print axioms StickyKakeya4.RankOneGeneralInputEscape.sourceChange_apply
#print axioms StickyKakeya4.RankOneGeneralInputEscape.transformed_source_product_domination
#print axioms StickyKakeya4.RankOneGeneralInputEscape.exists_input_normalization
#print axioms StickyKakeya4.RankOneGeneralInputEscape.vectorChange_source
#print axioms StickyKakeya4.RankOneGeneralInputEscape.conjugatedMatrix_apply
#print axioms StickyKakeya4.RankOneGeneralInputEscape.conjugated_spatial
#print axioms StickyKakeya4.RankOneGeneralInputEscape.measurable_generalPoint
#print axioms StickyKakeya4.RankOneGeneralInputEscape.point_conjugacy
#print axioms StickyKakeya4.RankOneGeneralInputEscape.actual_law_conjugacy
#print axioms StickyKakeya4.RankOneGeneralInputEscape.exists_general_input_supported_frostman_bounded
#print axioms StickyKakeya4.RankOneGeneralInputEscape.general_input_front_dimH_eq_four_bounded
#print axioms StickyKakeya4.RankOneGeneralInputEscape.exists_general_input_supported_frostman
#print axioms StickyKakeya4.RankOneGeneralInputEscape.general_input_front_dimH_eq_four
