import Theorems.Thm_StickyKakeya4_rational_feedback_time_window

#print axioms RankOneFeedbackPolynomials.denominator_eval
#print axioms RankOneFeedbackPolynomials.denominator_monic
#print axioms RankOneFeedbackPolynomials.denominator_natDegree
#print axioms RankOneFeedbackPolynomials.adjugate_natDegree
#print axioms RankOneFeedbackPolynomials.numerator_natDegree
#print axioms RankOneFeedbackPolynomials.eval_charmatrix
#print axioms RankOneFeedbackPolynomials.numerator_eval
#print axioms RankOneFeedbackPolynomials.inverse_feedback
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.matrix_inverse_bounded_on_closed_interval
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.polynomial_wronskian_ne_zero
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.abs_image_sub_ge_of_abs_deriv_ge
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.abs_image_sub_le_of_abs_deriv_le
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.exists_closed_interval_eventually
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.exists_rational_time_window
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.feedbackScalar_eq_rational
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.exists_matrix_time_window
#print axioms StickyKakeya4.RationalFeedbackTimeWindow.actual_feedback_zero_or_time_window
