import Theorems.Thm_StickyKakeya4_residual_collision_bridge

#check StickyKakeya4.collision_sublevel_localization
#check StickyKakeya4.collisionTimeFiber_volume_le
#check StickyKakeya4.collisionTimeFiber_volume_le_localized
#check StickyKakeya4.collisionTimeFiber_volume_le_fixed_buffer
#check StickyKakeya4.residualContentWeight
#check StickyKakeya4.weightedResidualContent
#check StickyKakeya4.lintegral_collision_mass_eq_fiber_volume
#check StickyKakeya4.averaged_collision_mass_le_weightedResidualContent
#check StickyKakeya4.collision_norm_lower_outside_enlarged_interval
#check StickyKakeya4.measurable_residualContentWeight

#print axioms StickyKakeya4.collision_sublevel_localization
#print axioms StickyKakeya4.collisionTimeFiber_subset_closest_interval
#print axioms StickyKakeya4.collisionTimeFiber_volume_le
#print axioms StickyKakeya4.collisionTimeFiber_nonempty_imp_residual_and_time
#print axioms StickyKakeya4.collisionTimeFiber_volume_le_localized
#print axioms StickyKakeya4.collisionTimeFiber_volume_le_fixed_buffer
#print axioms StickyKakeya4.measurableSet_collisionTimeFiber
#print axioms StickyKakeya4.collisionTimeFiber_volume_le_residualContentWeight
#print axioms StickyKakeya4.lintegral_collisionTimeFiber_le_weightedResidualContent
#print axioms StickyKakeya4.lintegral_collision_mass_eq_fiber_volume
#print axioms StickyKakeya4.averaged_collision_mass_le_weightedResidualContent
#print axioms StickyKakeya4.collision_norm_lower_of_closest_time_separation
#print axioms StickyKakeya4.collision_norm_lower_outside_enlarged_interval
#print axioms StickyKakeya4.measurable_collisionTime_comp
#print axioms StickyKakeya4.measurable_collisionResidual_comp
#print axioms StickyKakeya4.measurable_residualContentWeight

#check StickyKakeya4.averaged_collision_mass_le_residual_plus_near
#print axioms StickyKakeya4.collisionTimeFiber_volume_le_residual_plus_near
#print axioms StickyKakeya4.averaged_collision_mass_le_residual_plus_near
