import Theorems.Thm_StickyKakeya4_residual_phase_localization

#print StickyKakeya4.ResidualPhaseLocalization.firstHit
#print axioms StickyKakeya4.ResidualPhaseLocalization.firstHit
#print StickyKakeya4.ResidualPhaseLocalization.assignedGraph
#print axioms StickyKakeya4.ResidualPhaseLocalization.assignedGraph
#print StickyKakeya4.ResidualPhaseLocalization.measurableSet_firstHit
#print axioms StickyKakeya4.ResidualPhaseLocalization.measurableSet_firstHit
#print StickyKakeya4.ResidualPhaseLocalization.firstHit_subset
#print axioms StickyKakeya4.ResidualPhaseLocalization.firstHit_subset
#print StickyKakeya4.ResidualPhaseLocalization.firstHit_pairwiseDisjoint
#print axioms StickyKakeya4.ResidualPhaseLocalization.firstHit_pairwiseDisjoint
#print StickyKakeya4.ResidualPhaseLocalization.iUnion_firstHit
#print axioms StickyKakeya4.ResidualPhaseLocalization.iUnion_firstHit
#print StickyKakeya4.ResidualPhaseLocalization.firstHit_ae_partition
#print axioms StickyKakeya4.ResidualPhaseLocalization.firstHit_ae_partition
#print StickyKakeya4.ResidualPhaseLocalization.sum_assignedGraph_mass
#print axioms StickyKakeya4.ResidualPhaseLocalization.sum_assignedGraph_mass
#print StickyKakeya4.ResidualPhaseLocalization.assignedGraph_le_block_product
#print axioms StickyKakeya4.ResidualPhaseLocalization.assignedGraph_le_block_product
#print StickyKakeya4.ResidualPhaseLocalization.assignedGraph_mass_le_sq
#print axioms StickyKakeya4.ResidualPhaseLocalization.assignedGraph_mass_le_sq
#print StickyKakeya4.ResidualPhaseLocalization.assignedGraph_eq_zero_of_block_null
#print axioms StickyKakeya4.ResidualPhaseLocalization.assignedGraph_eq_zero_of_block_null
#print StickyKakeya4.ResidualPhaseLocalization.sum_assignedGraph_mass_toReal
#print axioms StickyKakeya4.ResidualPhaseLocalization.sum_assignedGraph_mass_toReal
#print StickyKakeya4.ResidualPhaseLocalization.exists_weighted_density_ge_average
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_weighted_density_ge_average
#print StickyKakeya4.ResidualPhaseLocalization.sum_block_mass_le
#print axioms StickyKakeya4.ResidualPhaseLocalization.sum_block_mass_le
#print StickyKakeya4.ResidualPhaseLocalization.sum_sq_block_mass_le
#print axioms StickyKakeya4.ResidualPhaseLocalization.sum_sq_block_mass_le
#print StickyKakeya4.ResidualPhaseLocalization.exists_assignedGraph_density_ge_average
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_assignedGraph_density_ge_average
#print StickyKakeya4.ResidualPhaseLocalization.exists_assignedGraph_density_ge_mass_budget
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_assignedGraph_density_ge_mass_budget
#print StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_indexed_ball_card_bound
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_indexed_ball_card_bound
#print StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_indexed_ball_overlap_bound
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_indexed_ball_overlap_bound
#print StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_fin_ball_overlap_bound
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_uniform_expanded_fin_ball_overlap_bound
#print StickyKakeya4.ResidualPhaseLocalization.phaseCover
#print axioms StickyKakeya4.ResidualPhaseLocalization.phaseCover
#print StickyKakeya4.ResidualPhaseLocalization.phaseBlock
#print axioms StickyKakeya4.ResidualPhaseLocalization.phaseBlock
#print StickyKakeya4.ResidualPhaseLocalization.graphMeasure
#print axioms StickyKakeya4.ResidualPhaseLocalization.graphMeasure
#print StickyKakeya4.ResidualPhaseLocalization.graphMeasure_le_product
#print axioms StickyKakeya4.ResidualPhaseLocalization.graphMeasure_le_product
#print StickyKakeya4.ResidualPhaseLocalization.near_phase_endpoints_in_block
#print axioms StickyKakeya4.ResidualPhaseLocalization.near_phase_endpoints_in_block
#print StickyKakeya4.ResidualPhaseLocalization.graphMeasure_ae_endpoints_in_block
#print axioms StickyKakeya4.ResidualPhaseLocalization.graphMeasure_ae_endpoints_in_block
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion
#print StickyKakeya4.ResidualPhaseLocalization.construct_localization
#print axioms StickyKakeya4.ResidualPhaseLocalization.construct_localization
#print StickyKakeya4.ResidualPhaseLocalization.exists_uniform_near_phase_graph_localization
#print axioms StickyKakeya4.ResidualPhaseLocalization.exists_uniform_near_phase_graph_localization
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_measurable
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_measurable
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_disjoint
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_disjoint
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_partition
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_partition
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_subordinate
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.cells_subordinate
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.blocks_measurable
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.blocks_measurable
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.exact_mass_split
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.exact_mass_split
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.block_domination
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.block_domination
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.bounded_overlap
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.bounded_overlap
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.square_mass_budget
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.square_mass_budget
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.positive_square_mass
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.positive_square_mass
#print StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.selected_block
#print axioms StickyKakeya4.ResidualPhaseLocalization.LocalizationConclusion.selected_block
