import Theorems.Thm_StickyKakeya4_rooted_cycle_witness_kernel

#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.fresh_pair_ae_ne
#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.fresh_pair_measure_one
#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.extension_ae_ne
#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.positive_cycle_fourDistinct
#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.extension_ae_cycle_distinct
#check @StickyKakeya4.RootedCycleWitnessKernel.Diffuse.ac_extension_ae_cycle_distinct
#check @StickyKakeya4.RootedCycleWitnessKernel.witnessEvent
#check @StickyKakeya4.RootedCycleWitnessKernel.measurableSet_witnessEvent
#check @StickyKakeya4.RootedCycleWitnessKernel.freshVertexKernel
#check @StickyKakeya4.RootedCycleWitnessKernel.freshVertexKernel_isMarkov
#check @StickyKakeya4.RootedCycleWitnessKernel.rootSuccess_le_event_probability
#check @StickyKakeya4.RootedCycleWitnessKernel.ae_witness_probability_pos
#check @StickyKakeya4.RootedCycleWitnessKernel.ae_root_edge_pos
#check @StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessKernel
#check @StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessKernel_isMarkov
#check @StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessExtension
#check @StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessExtension_isFinite
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_original
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_observable
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_inherited
#check @StickyKakeya4.RootedCycleWitnessKernel.conditioned_extension_eq_rooted
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_success
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_kernel_success_mass
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_subsource_witness
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_absolutelyContinuous
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_all_edges_pos
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_old_edge_support
#check @StickyKakeya4.RootedCycleWitnessKernel.exists_rooted_witness_kernel
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_opposite_distinct
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_restrict_opposite_distinct
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_four_distinct
#check @StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_restrict_four_distinct

#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.fresh_pair_ae_ne
#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.fresh_pair_measure_one
#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.extension_ae_ne
#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.positive_cycle_fourDistinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.extension_ae_cycle_distinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.Diffuse.ac_extension_ae_cycle_distinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.witnessEvent
#print axioms StickyKakeya4.RootedCycleWitnessKernel.measurableSet_witnessEvent
#print axioms StickyKakeya4.RootedCycleWitnessKernel.freshVertexKernel
#print axioms StickyKakeya4.RootedCycleWitnessKernel.freshVertexKernel_isMarkov
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rootSuccess_le_event_probability
#print axioms StickyKakeya4.RootedCycleWitnessKernel.ae_witness_probability_pos
#print axioms StickyKakeya4.RootedCycleWitnessKernel.ae_root_edge_pos
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessKernel
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessKernel_isMarkov
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessExtension
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rootedWitnessExtension_isFinite
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_original
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_observable
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_inherited
#print axioms StickyKakeya4.RootedCycleWitnessKernel.conditioned_extension_eq_rooted
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_success
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_kernel_success_mass
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_subsource_witness
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_absolutelyContinuous
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_all_edges_pos
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_old_edge_support
#print axioms StickyKakeya4.RootedCycleWitnessKernel.exists_rooted_witness_kernel
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_opposite_distinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_restrict_opposite_distinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_four_distinct
#print axioms StickyKakeya4.RootedCycleWitnessKernel.rooted_extension_restrict_four_distinct
