import Theorems.Thm_StickyKakeya4_shifted_original_height_rescaling

#print axioms ShiftedOriginalHeightRescaling.translated_card
#print axioms ShiftedOriginalHeightRescaling.translated_mass
#print axioms ShiftedOriginalHeightRescaling.labelShift_tube
#print axioms ShiftedOriginalHeightRescaling.labelShift_time
#print axioms ShiftedOriginalHeightRescaling.mem_selected
#print axioms ShiftedOriginalHeightRescaling.selected_subset
#print axioms ShiftedOriginalHeightRescaling.selected_mass
#print axioms ShiftedOriginalHeightRescaling.weighted_height_retention
#print axioms ShiftedOriginalHeightRescaling.height_card_retention
#print axioms ShiftedOriginalHeightRescaling.chosenHeight_bin
#print axioms ShiftedOriginalHeightRescaling.selected_bin_fiber
#print axioms ShiftedOriginalHeightRescaling.selected_point_fiber
#print axioms ShiftedOriginalHeightRescaling.shiftedBin_eq_translated_triangular
#print axioms ShiftedOriginalHeightRescaling.shiftedBin_injective_on_selected
#print axioms ShiftedOriginalHeightRescaling.selected_image_cardinalities
#print axioms ShiftedOriginalHeightRescaling.density_original_backbone
#print axioms ShiftedOriginalHeightRescaling.shifted_nested_time
#print axioms ShiftedOriginalHeightRescaling.native_coarse_time
#print axioms ShiftedOriginalHeightRescaling.native_final_height_selection
#print axioms ShiftedOriginalHeightRescaling.native_selected_original_height
