import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_core
import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_selection
import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_density
import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_lift
import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_geometry
import Theorems.Thm_StickyKakeya4_finite_plane_projection_graph_final
import Theorems.Thm_StickyKakeya4_original_menu_section
import Theorems.Thm_StickyKakeya4_original_height_graph_coarsening
import Theorems.Thm_StickyKakeya4_original_height_graph_density
import Theorems.Thm_StickyKakeya4_original_separated_height_cap
import Theorems.Thm_StickyKakeya4_original_coarse_height_curve
import Theorems.Thm_StickyKakeya4_original_coarse_height_tube_transfer
import Theorems.Thm_StickyKakeya4_original_slope_graph_nonconcentration
import Theorems.Thm_StickyKakeya4_original_menu_bc_graph
import Theorems.Thm_StickyKakeya4_native_original_phase_bounds
import Theorems.Thm_StickyKakeya4_original_angular_alphabet_translation
import Theorems.Thm_StickyKakeya4_actual_planar_target_cover
import Theorems.Thm_StickyKakeya4_original_reference_angle_selection
import Theorems.Thm_StickyKakeya4_original_reference_angle_geometry
import Theorems.Thm_StickyKakeya4_original_angular_frostman
import Theorems.Thm_StickyKakeya4_native_reference_phase_window_graph
import Theorems.Thm_StickyKakeya4_planar_abc_balanced_normalization
import Theorems.Thm_StickyKakeya4_original_angular_graph_translation
import Theorems.Thm_StickyKakeya4_original_angular_balanced_frostman
import Theorems.Thm_StickyKakeya4_actual_abc_image_assembly
import Theorems.Thm_StickyKakeya4_planar_abc_projected_profiles
import Theorems.Thm_StickyKakeya4_original_population_relative
import Theorems.Thm_StickyKakeya4_original_coarse_height_population_ratio
import Theorems.Thm_StickyKakeya4_native_planar_abc_input
import Theorems.Thm_StickyKakeya4_native_radial_class_pruning
import Theorems.Thm_StickyKakeya4_native_radial_class_geometry
import Theorems.Thm_StickyKakeya4_original_pair_strip_physical_bridge
import Theorems.Thm_StickyKakeya4_original_disjoint_support_selection
import Theorems.Thm_StickyKakeya4_rooted_shared_annular_tube_transfer
import Theorems.Thm_StickyKakeya4_original_annular_row_cover
import Theorems.Thm_StickyKakeya4_original_densest_wide_extension
import Theorems.Thm_StickyKakeya4_original_annular_row_charge
import Theorems.Thm_StickyKakeya4_native_original_annular_row_bound
import Theorems.Thm_StickyKakeya4_native_original_radial_reduction
import Theorems.Thm_StickyKakeya4_original_shading_cell_selection
import Theorems.Thm_StickyKakeya4_original_shading_cell_mass
import Theorems.Thm_StickyKakeya4_original_shading_grid_geometry
import Theorems.Thm_StickyKakeya4_original_shading_coarse_frostman
import Theorems.Thm_StickyKakeya4_original_shading_representatives
import Theorems.Thm_StickyKakeya4_original_shading_representative_frostman
import Theorems.Thm_StickyKakeya4_original_coarse_shading_preparation

#print axioms FinitePlaneProjectionGraph.goodEdges_subset
#print axioms FinitePlaneProjectionGraph.goodEdges_product
#print axioms FinitePlaneProjectionGraph.deleted_edge_bound
#print axioms FinitePlaneProjectionGraph.goodEdges_half_of_density
#print axioms FinitePlaneProjectionGraph.goodEdges_three_quarters_of_density
#print axioms FinitePlaneProjectionGraph.quotientEdges_product
#print axioms FinitePlaneProjectionGraph.quotient_fiber_bound
#print axioms FinitePlaneProjectionGraph.quotientEdges_card_bound
#print axioms FinitePlaneProjectionGraph.exists_edge_color
#print axioms FinitePlaneProjectionGraph.graphLoss_pos
#print axioms FinitePlaneProjectionGraph.graphLoss_ge
#print axioms FinitePlaneProjectionGraph.graphRetained_subset
#print axioms FinitePlaneProjectionGraph.graphRetained_deleted_mass
#print axioms FinitePlaneProjectionGraph.graphRetained_cell_bound
#print axioms FinitePlaneProjectionGraph.graphRetained_ball_bound
#print axioms FinitePlaneProjectionGraph.exists_dense_colored_quotient
#print axioms FinitePlaneProjectionGraph.original_density_le_one
#print axioms FinitePlaneProjectionGraph.original_vertex_retention_from_graph_mass
#print axioms FinitePlaneProjectionGraph.reciprocal_population_bound
#print axioms FinitePlaneProjectionGraph.exists_selected_representatives
#print axioms FinitePlaneProjectionGraph.selectedEdges_subset_product
#print axioms FinitePlaneProjectionGraph.selectedEdges_card_le
#print axioms FinitePlaneProjectionGraph.selectedEdges_image
#print axioms FinitePlaneProjectionGraph.quotientEdge_injOn_product
#print axioms FinitePlaneProjectionGraph.selectedEdges_card
#print axioms FinitePlaneProjectionGraph.selectedEdges_original_witness
#print axioms FinitePlaneProjectionGraph.selectedEdges_support_left
#print axioms FinitePlaneProjectionGraph.selectedEdges_support_right
#print axioms FinitePlaneProjectionGraph.exists_selected_graph_lift
#print axioms FinitePlaneProjectionGraph.selected_graph_lift_colors
#print axioms FinitePlaneProjectionGraph.fixed_color_projection_separation
#print axioms FinitePlaneProjectionGrid.projectionLinear_norm_le_of_abs
#print axioms FinitePlaneProjectionGrid.projectionLinear_norm_le
#print axioms FinitePlaneProjectionGrid.projectionLinear_sub_norm_le
#print axioms FinitePlaneProjectionGrid.projectionLinear_lipschitz
#print axioms FinitePlaneProjectionGrid.same_projected_cell_norm_le
#print axioms FinitePlaneProjectionGrid.original_edge_projected_error
#print axioms FinitePlaneProjectionGrid.original_edge_same_cell_transport
#print axioms FinitePlaneProjectionGrid.original_edge_same_cell_target_transport
#print axioms FinitePlaneProjectionGraph.graphMassLoss_pos
#print axioms FinitePlaneProjectionGraph.exists_graph_aware_projection
#print axioms FinitePlaneProjectionGraph.retained_edges_original_error
#print axioms OriginalMenuSection.section_card
#print axioms OriginalMenuSection.section_subset
#print axioms OriginalMenuSection.exists_large_original_section
#print axioms OriginalMenuSection.section_relative_density
#print axioms OriginalHeightGraphCoarsening.edgeBin_subset
#print axioms OriginalHeightGraphCoarsening.edgeBin_card_sum
#print axioms OriginalHeightGraphCoarsening.exists_edge_mass_bin
#print axioms OriginalHeightGraphCoarsening.quotient_fiber_cap
#print axioms OriginalHeightGraphCoarsening.coarseGraph_subset
#print axioms OriginalHeightGraphCoarsening.dyadic_label_mass_bounds
#print axioms OriginalHeightGraphCoarsening.edgeBin_coarse_card
#print axioms OriginalHeightGraphCoarsening.exists_original_graph_coarsening
#print axioms OriginalHeightGraphDensity.exists_dense_original_coarsening
#print axioms OriginalHeightGraphDensity.bad_coarse_labels_count
#print axioms OriginalHeightGraphDensity.coarse_bad_fraction
#print axioms OriginalSeparatedHeightCap.floor_injective_of_separated
#print axioms OriginalSeparatedHeightCap.separated_interval_cap
#print axioms OriginalSeparatedHeightCap.original_coarse_height_fiber_cap
#print axioms OriginalCoarseHeightCurve.representative_spec
#print axioms OriginalCoarseHeightCurve.sampled_height_interval_cap
#print axioms OriginalCoarseHeightCurve.sampled_curve_ball_cap
#print axioms OriginalCoarseHeightCurve.original_coarse_curve_KT1
#print axioms OriginalCoarseHeightCurve.same_cell_graph_error
#print axioms OriginalCoarseHeightTubeTransfer.coarse_cross_tube_original_charge
#print axioms OriginalCoarseHeightTubeTransfer.coarse_cross_tube_fraction
#print axioms OriginalSlopeGraphNonconcentration.original_affine_avoidance_normalized
#print axioms OriginalSlopeGraphNonconcentration.original_normalized_height_cap
#print axioms OriginalSlopeGraphNonconcentration.original_slope_graph_cross_tube_bound
#print axioms OriginalMenuBCGraph.section_original_witness
#print axioms OriginalMenuBCGraph.coarse_section_original_witness
#print axioms OriginalMenuBCGraph.exists_actual_BC_graph
#print axioms NativeOriginalPhaseBounds.original_macro_phase_bound
#print axioms NativeOriginalPhaseBounds.enlarged_original_phase_grid_bound
#print axioms NativeOriginalPhaseBounds.gridPoint_rescale
#print axioms NativeOriginalPhaseBounds.common_rescaling_relation
#print axioms OriginalAngularAlphabetTranslation.subtract_injective
#print axioms OriginalAngularAlphabetTranslation.shifted_card
#print axioms OriginalAngularAlphabetTranslation.shifted_ball
#print axioms OriginalAngularAlphabetTranslation.shifted_ball_card
#print axioms OriginalAngularAlphabetTranslation.shifted_ADBounds
#print axioms OriginalAngularAlphabetTranslation.shifted_separated
#print axioms OriginalAngularAlphabetTranslation.shifted_box
#print axioms OriginalAngularAlphabetTranslation.shifted_mesh
#print axioms OriginalAngularAlphabetTranslation.shifted_card_lower
#print axioms OriginalAngularAlphabetTranslation.original_angles_subset
#print axioms ActualPlanarTargetCover.actual_target_grid_cover
#print axioms ActualPlanarTargetCover.retained_target_cover
#print axioms OriginalReferenceAngleSelection.source_common_angle_near
#print axioms OriginalReferenceAngleSelection.angle_spec
#print axioms OriginalReferenceAngleSelection.angle_fiber_cap
#print axioms OriginalReferenceAngleSelection.exists_full_reference_rich_core
#print axioms OriginalReferenceAngleGeometry.constructed_reference_grain_drift
#print axioms OriginalReferenceAngleGeometry.reference_original_normalized_phase
#print axioms OriginalAngularFrostman.AD_relative_point_bound
#print axioms OriginalAngularFrostman.AD_relative_allcenter
#print axioms OriginalAngularFrostman.shifted_finer_mesh_frostman
#print axioms NativeReferencePhaseWindowGraph.exists_reference_phase_window_graph
#print axioms PlanarABCBalancedNormalization.product_identity
#print axioms PlanarABCBalancedNormalization.residual_identity
#print axioms PlanarABCBalancedNormalization.balanced_error
#print axioms PlanarABCBalancedNormalization.source_box
#print axioms PlanarABCBalancedNormalization.direction_box
#print axioms PlanarABCBalancedNormalization.scalar_box
#print axioms PlanarABCBalancedNormalization.source_injective
#print axioms PlanarABCBalancedNormalization.direction_injective
#print axioms PlanarABCBalancedNormalization.scalar_injective
#print axioms PlanarABCBalancedNormalization.projected_balanced_error
#print axioms PlanarABCBalancedNormalization.normalized_cover_factor
#print axioms OriginalAngularGraphTranslation.translateEdge_injective
#print axioms OriginalAngularGraphTranslation.translatedGraph_card
#print axioms OriginalAngularGraphTranslation.translatedGraph_subset
#print axioms OriginalAngularGraphTranslation.translatedGraph_original_edge
#print axioms OriginalAngularGraphTranslation.translatedGraph_density
#print axioms OriginalAngularBalancedFrostman.balancedC_card
#print axioms OriginalAngularBalancedFrostman.balancedC_box
#print axioms OriginalAngularBalancedFrostman.balancedC_separated
#print axioms OriginalAngularBalancedFrostman.balancedC_ball_card
#print axioms OriginalAngularBalancedFrostman.balancedC_frostman
#print axioms OriginalAngularBalancedFrostman.weaken_upper_exponent
#print axioms ActualABCImageAssembly.embedEdge_injOn
#print axioms ActualABCImageAssembly.imageGraph_card
#print axioms ActualABCImageAssembly.imageGraph_subset
#print axioms ActualABCImageAssembly.imageGraph_density
#print axioms ActualABCImageAssembly.imageGraph_output_cells
#print axioms ActualABCImageAssembly.actual_ABC_sumset_cover
#print axioms ActualABCImageAssembly.filtered_image_card
#print axioms PlanarABCProjectedProfiles.source_injOn
#print axioms PlanarABCProjectedProfiles.direction_injOn
#print axioms PlanarABCProjectedProfiles.source_image_separated
#print axioms PlanarABCProjectedProfiles.direction_image_separated
#print axioms PlanarABCProjectedProfiles.direction_image_ball_bound
#print axioms PlanarABCProjectedProfiles.direction_image_strip_bound
#print axioms OriginalPopulationRelative.ball_from_original_mass
#print axioms OriginalCoarseHeightPopulationRatio.selected_height_card_upper
#print axioms OriginalCoarseHeightPopulationRatio.original_coarse_height_mass
#print axioms NativePlanarABCInput.exists_actual_planar_ABC_input
#print axioms NativeRadialClassPruning.retained_oriented_labels
#print axioms NativeRadialClassPruning.oriented_degree_counts
#print axioms NativeRadialClassPruning.exists_original_radial_class_core
#print axioms NativeRadialClassGeometry.forward_class_geometry
#print axioms NativeRadialClassGeometry.reverse_class_geometry
#print axioms OriginalPairStripPhysicalBridge.original_axis_line_witness
#print axioms OriginalPairStripPhysicalBridge.original_strip_subset_physical
#print axioms OriginalDisjointSupportSelection.exists_maximal_disjoint_original_supports
#print axioms OriginalDisjointSupportSelection.exists_rich_disjoint_original_supports
#print axioms RootedSharedAnnularTubeTransfer.rooted_original_shared_point_transfer
#print axioms OriginalAnnularRowCover.exists_original_annular_row_cover
#print axioms OriginalDensestWideExtension.original_all_larger_width_control
#print axioms OriginalDensestWideExtension.original_source_density_of_native_gain
#print axioms OriginalAnnularRowCharge.original_annular_row_charge
#print axioms OriginalAnnularRowCharge.original_annular_row_frostman_charge
#print axioms NativeOriginalAnnularRowBound.annular_power_identity
#print axioms NativeOriginalAnnularRowBound.native_original_annular_bad_row
#print axioms NativeOriginalRadialReduction.exists_original_densest_graph_with_annular_control
#print axioms OriginalShadingCellSelection.original_cell_charge
#print axioms OriginalShadingCellSelection.original_union_cell_charge
#print axioms OriginalShadingCellSelection.levelCount_mono
#print axioms OriginalShadingCellSelection.exists_shading_bin_label
#print axioms OriginalShadingCellSelection.exists_uniform_original_shading_bins
#print axioms OriginalShadingCellMass.bin_card_le_twice_occupancy
#print axioms OriginalShadingCellMass.original_mass_le_four_log_occupancy_cells
#print axioms OriginalShadingCellMass.selected_cells_original_charge
#print axioms OriginalShadingCellMass.coarse_fraction_from_original_points
#print axioms OriginalShadingGridGeometry.point_in_own_cell
#print axioms OriginalShadingGridGeometry.InBox.trans
#print axioms OriginalShadingGridGeometry.InBox.mono
#print axioms OriginalShadingGridGeometry.coarse_box_original_preimage
#print axioms OriginalShadingGridGeometry.coarse_box_preimage_subset
#print axioms OriginalShadingCoarseFrostman.coarse_grid_frostman
#print axioms OriginalShadingRepresentatives.same_cell_close
#print axioms OriginalShadingRepresentatives.exists_separated_original_representatives
#print axioms OriginalShadingRepresentatives.representative_ball_original_preimage
#print axioms OriginalShadingRepresentativeFrostman.original_representative_frostman
#print axioms OriginalCoarseShadingPreparation.exists_original_coarse_shadings
