import Theorems.Thm_StickyKakeya4_spacetime_collision_energy

#check StickyKakeya4.map_inverse_energy_eq_distance_pair_integral
#check StickyKakeya4.ae_finite_map_inverse_energy_of_finite_time_pair_energy
#check StickyKakeya4.spacetimeLift_castSucc
#check StickyKakeya4.spacetimeLift_last
#check StickyKakeya4.spacetimeLift_sub
#check StickyKakeya4.spacetimeLift_norm_sq
#check StickyKakeya4.measurable_spacetimeLift
#check StickyKakeya4.spacetimeLift_collision_coordinates
#check StickyKakeya4.measurable_slopeSpacetimePoint
#check StickyKakeya4.spacetime_collision_imp_same_time
#check StickyKakeya4.spacetime_time_fiber_volume_le
#check StickyKakeya4.spacetime_source_row_mass_le
#check StickyKakeya4.spacetime_pair_sublevel_le_time_collision
#check StickyKakeya4.finite_inverse_energy_of_local_sublevel_power
#check StickyKakeya4.finite_spacetime_pair_energy_of_averaged_sublevel_power
#check StickyKakeya4.finite_spacetime_front_energy_of_averaged_sublevel_power

#print axioms StickyKakeya4.map_inverse_energy_eq_distance_pair_integral
#print axioms StickyKakeya4.ae_finite_map_inverse_energy_of_finite_time_pair_energy
#print axioms StickyKakeya4.spacetimeLift_castSucc
#print axioms StickyKakeya4.spacetimeLift_last
#print axioms StickyKakeya4.spacetimeLift_sub
#print axioms StickyKakeya4.spacetimeLift_norm_sq
#print axioms StickyKakeya4.measurable_spacetimeLift
#print axioms StickyKakeya4.spacetimeLift_collision_coordinates
#print axioms StickyKakeya4.measurable_slopeSpacetimePoint
#print axioms StickyKakeya4.spacetime_collision_imp_same_time
#print axioms StickyKakeya4.spacetime_time_fiber_volume_le
#print axioms StickyKakeya4.spacetime_source_row_mass_le
#print axioms StickyKakeya4.spacetime_pair_sublevel_le_time_collision
#print axioms StickyKakeya4.finite_inverse_energy_of_local_sublevel_power
#print axioms StickyKakeya4.finite_spacetime_pair_energy_of_averaged_sublevel_power
#print axioms StickyKakeya4.finite_spacetime_front_energy_of_averaged_sublevel_power
