import Theorems.Thm_StickyKakeya4_submeasure_routing_exhaustion

#print axioms StickyKakeya4.SubmeasureRoutingExhaustion.exists_half_maximal_submeasure
#print axioms StickyKakeya4.SubmeasureRoutingExhaustion.exists_submeasure_routing_exhaustion
#print axioms StickyKakeya4.SubmeasureRoutingExhaustion.exhaustive_markov_extensions_preserve_occurrence
#print axioms StickyKakeya4.SubmeasureRoutingExhaustion.exhaustive_markov_extensions_preserve_endpoints
