import Theorems.Thm_StickyKakeya4_time_changed_scalar_energy

#print axioms StickyKakeya4.ScalarProjection.parameter_fiber_linear_le
#print axioms StickyKakeya4.ScalarProjection.parameter_min_linear_le_fractional
#print axioms StickyKakeya4.ScalarProjection.parameter_fiber_fractional_le
#print axioms StickyKakeya4.ScalarProjection.parameter_averaged_collision_le_source_energy
#print axioms StickyKakeya4.ScalarProjection.finite_parameter_average_scalar_projection_pair_energy
#print axioms StickyKakeya4.ScalarProjection.ae_finite_parameter_scalar_projection_pair_energy
#print axioms StickyKakeya4.ScalarProjection.time_change_map_ball_le
#print axioms StickyKakeya4.ScalarProjection.ae_finite_parameter_law_potential_integral
#print axioms StickyKakeya4.ScalarProjection.ae_finite_parameter_law_potential
#print axioms StickyKakeya4.ScalarProjection.ae_finite_time_changed_parameterizedScalarPotential
#print axioms StickyKakeya4.ScalarProjection.ae_finite_time_changed_scalar_potential
