import Theorems.Thm_StickyKakeya4_triangular_heavy_root_power

#print axioms StickyKakeya4.TriangularHeavyRootPower.exists_small_power_le_one
#print axioms StickyKakeya4.TriangularHeavyRootPower.cutoff_threshold_identity
#print axioms StickyKakeya4.TriangularHeavyRootPower.measurableSet_triangularHeavySet
#print axioms StickyKakeya4.TriangularHeavyRootPower.exists_triangular_original_heavy_root_power
#print axioms StickyKakeya4.TriangularHeavyRootPower.tsum_lt_top_of_eventually_le_geometric
#print axioms StickyKakeya4.TriangularHeavyRootPower.dyadic_tsum_lt_top_of_small_power_bound
#print axioms StickyKakeya4.TriangularHeavyRootPower.triangular_original_heavy_root_dyadic_sum_lt_top
