import Theorems.Thm_StickyKakeya4_triangular_uniform_potential_bound

#print axioms StickyKakeya4.TriangularUniformPotentialBound.lintegral_dummy_coordinate
#print axioms StickyKakeya4.TriangularUniformPotentialBound.lintegral_prod_le_of_measure_le_smul
#print axioms StickyKakeya4.TriangularUniformPotentialBound.uniformTriangularPotentialBound_lt_top
#print axioms StickyKakeya4.TriangularUniformPotentialBound.potential₁_affine_eq_parameterized
#print axioms StickyKakeya4.TriangularUniformPotentialBound.potential₂_affine_eq_parameterized
#print axioms StickyKakeya4.TriangularUniformPotentialBound.potential₃_affine_eq_parameterized
#print axioms StickyKakeya4.TriangularUniformPotentialBound.measurable_potential₁_affine
#print axioms StickyKakeya4.TriangularUniformPotentialBound.measurable_potential₂_affine
#print axioms StickyKakeya4.TriangularUniformPotentialBound.measurable_potential₃_affine
#print axioms StickyKakeya4.TriangularUniformPotentialBound.measurable_nativePotentialSum
#print axioms StickyKakeya4.TriangularUniformPotentialBound.average_potential₁_affine_le
#print axioms StickyKakeya4.TriangularUniformPotentialBound.reference_nativePotentialSum_integral_le
#print axioms StickyKakeya4.TriangularUniformPotentialBound.actual_nativePotentialSum_integral_le
