import Theorems.Thm_StickyKakeya4_triangular_potential_charge

#print axioms StickyKakeya4.TriangularPotentialCharge.bad_common_cut_le
#print axioms StickyKakeya4.TriangularPotentialCharge.measurable_ball_mass
#print axioms StickyKakeya4.TriangularPotentialCharge.ball_mass_integral_swap
#print axioms StickyKakeya4.TriangularPotentialCharge.measurable_original_root_ball_mass
#print axioms StickyKakeya4.TriangularPotentialCharge.original_heavy_event_measure_eq
#print axioms StickyKakeya4.TriangularPotentialCharge.heavy_root_measure_le_twice_bad
#print axioms StickyKakeya4.TriangularPotentialCharge.original_heavy_root_measure_le_twice_bad
#print axioms StickyKakeya4.TriangularPotentialCharge.measurable_spatialPoint
#print axioms StickyKakeya4.TriangularPotentialCharge.spatial_coordinate_mem_ball
#print axioms StickyKakeya4.TriangularPotentialCharge.good_spatial_ball_bound
#print axioms StickyKakeya4.TriangularPotentialCharge.triangular_original_heavy_root_charge
