import Theorems.Thm_StickyKakeya4_two_dimensional_transverse_escape

#print axioms TwoDimensionalTransverseEscape.det_abs_lower_of_max_transverse
#print axioms TwoDimensionalTransverseEscape.coefficients_mul_bound_of_det_bound
#print axioms TwoDimensionalTransverseEscape.coefficients_bound_of_det_bound
#print axioms TwoDimensionalTransverseEscape.coefficient_differences_bound_of_max_transverse
