import Theorems.Thm_StickyKakeya4_two_tube_path_collision_count
set_option autoImplicit false
set_option warningAsError true
#print axioms TwoTubePathCollisionCount.mem_paths
#print axioms TwoTubePathCollisionCount.tubeDegree_eq_fiber_card
#print axioms TwoTubePathCollisionCount.card_incidence_eq_sum_tubeDegree
#print axioms TwoTubePathCollisionCount.sum_fiber_card_eq_sum_sq
#print axioms TwoTubePathCollisionCount.sum_halfPaths_eq_sum_tubeDegree_sq
#print axioms TwoTubePathCollisionCount.card_paths_eq_sum_halfPaths_sq
#print axioms TwoTubePathCollisionCount.nat_sum_sq_le_card_mul_sum_sq
#print axioms TwoTubePathCollisionCount.fourth_power_walk_bound
#print axioms TwoTubePathCollisionCount.fourth_power_walk_bound_of_subset
#print axioms TwoTubePathCollisionCount.mem_collisions
#print axioms TwoTubePathCollisionCount.card_collisions_eq_sum_fiber_sq
#print axioms TwoTubePathCollisionCount.square_card_le_image_mul_collisions
#print axioms TwoTubePathCollisionCount.eighth_power_collision_bound
