import Theorems.Thm_StickyKakeya4_original_separated_point_packing
import Theorems.Thm_StickyKakeya4_original_source_log_budgets
import Theorems.Thm_StickyKakeya4_original_critical_width_bound
import Theorems.Thm_StickyKakeya4_native_original_critical_query_range
import Theorems.Thm_StickyKakeya4_native_original_pruning_loss
import Theorems.Thm_StickyKakeya4_native_original_nonempty_coarse_family
import Theorems.Thm_StickyKakeya4_native_uniform_original_coarse_family
import Theorems.Thm_StickyKakeya4_original_angular_source_population
import Theorems.Thm_StickyKakeya4_original_selected_angular_incidences
import Theorems.Thm_StickyKakeya4_native_original_phase_source_costs
import Theorems.Thm_StickyKakeya4_native_original_phase_source_kt
import Theorems.Thm_StickyKakeya4_native_original_macro_phase_box
import Theorems.Thm_StickyKakeya4_native_original_graph_density_costs

#print axioms OriginalSeparatedPointPacking.original_separated_floor_injective
#print axioms OriginalSeparatedPointPacking.original_separated_square_packing
#print axioms OriginalSourceLogBudgets.original_level_count_le_menu
#print axioms OriginalSourceLogBudgets.exists_original_logarithmic_power_cutoff
#print axioms OriginalCriticalWidthBound.original_family_critical_width_bound
#print axioms OriginalCriticalWidthBound.original_family_native_critical_width_bound
#print axioms NativeOriginalCriticalQueryRange.minimal_thickening_modulus
#print axioms NativeOriginalCriticalQueryRange.original_critical_width_ge_base
#print axioms NativeOriginalCriticalQueryRange.original_A1_critical_exponent_margin
#print axioms NativeOriginalCriticalQueryRange.exists_original_critical_query_threshold
#print axioms NativeOriginalPruningLoss.original_annular_exponent_ge
#print axioms NativeOriginalPruningLoss.exists_original_pruning_loss_cutoff
#print axioms NativeOriginalPruningLoss.original_retained_graph_half
#print axioms NativeOriginalNonemptyCoarseFamily.exists_native_original_nonempty_coarse_family_threshold
#print axioms NativeUniformOriginalCoarseFamily.exists_uniform_original_nonempty_coarse_family
#print axioms OriginalAngularSourcePopulation.unit_diameter_card
#print axioms OriginalAngularSourcePopulation.boxed_AD_card
#print axioms OriginalAngularSourcePopulation.boxed_AD_allcenter
#print axioms OriginalAngularSourcePopulation.selected_ball_cap_general
#print axioms OriginalAngularSourcePopulation.source_label_fiber_cap
#print axioms OriginalAngularSourcePopulation.selected_degree_lower
#print axioms OriginalAngularSourcePopulation.selected_ball_cap
#print axioms OriginalAngularSourcePopulation.selected_reference_ball_cap
#print axioms OriginalAngularSourcePopulation.degree_pos
#print axioms OriginalAngularSourcePopulation.ballCap_pos
#print axioms OriginalAngularSourcePopulation.ballCap_double_error_le
#print axioms OriginalAngularSourcePopulation.population_ratio_from_card
#print axioms OriginalAngularSourcePopulation.original_population_ratio
#print axioms OriginalAngularSourcePopulation.original_reference_population_ratio
#print axioms OriginalSelectedAngularIncidences.mem_incidences
#print axioms OriginalSelectedAngularIncidences.tubesAt_eq_selected
#print axioms OriginalSelectedAngularIncidences.tubesAt_eq_empty
#print axioms OriginalSelectedAngularIncidences.incidences_subset_source
#print axioms OriginalSelectedAngularIncidences.incidences_nonempty
#print axioms OriginalSelectedAngularIncidences.points_eq
#print axioms OriginalSelectedAngularIncidences.incidence_realization
#print axioms OriginalSelectedAngularIncidences.selected_populations
#print axioms OriginalSelectedAngularIncidences.reference_ball_cap
#print axioms OriginalSelectedAngularIncidences.common_angle_near
#print axioms OriginalSelectedAngularIncidences.chooseSource_spec
#print axioms OriginalSelectedAngularIncidences.exists_selected_source_populations
#print axioms OriginalSelectedAngularIncidences.exists_original_angular_population_supplier
#print axioms NativeOriginalPhaseSourceCosts.scalar_matrix_operator_bound
#print axioms NativeOriginalPhaseSourceCosts.original_grain_coefficient_bound
#print axioms NativeOriginalPhaseSourceCosts.source_window_KT_coefficient
#print axioms NativeOriginalPhaseSourceCosts.source_window_KT_power
#print axioms NativeOriginalPhaseSourceKT.exists_original_field
#print axioms NativeOriginalPhaseSourceKT.exists_scheduled_original_field
#print axioms NativeOriginalPhaseSourceKT.actual_window_source_power_KT
#print axioms NativeOriginalMacroPhaseBox.same_physical_cell_x_gap
#print axioms NativeOriginalMacroPhaseBox.original_macro_phase_bound
#print axioms NativeOriginalMacroPhaseBox.actual_window_source_box
#print axioms NativeOriginalGraphDensityCosts.menuBeta_pos
#print axioms NativeOriginalGraphDensityCosts.windowBeta_pos
#print axioms NativeOriginalGraphDensityCosts.bcBeta_pos
#print axioms NativeOriginalGraphDensityCosts.heightMass_pos
#print axioms NativeOriginalGraphDensityCosts.menu_scale_eq
#print axioms NativeOriginalGraphDensityCosts.bcBeta_eq
#print axioms NativeOriginalGraphDensityCosts.heightMass_nearby_eq
#print axioms NativeOriginalGraphDensityCosts.bcBeta_inverse_eq
#print axioms NativeOriginalGraphDensityCosts.heightMass_inverse_eq
#print axioms NativeOriginalGraphDensityCosts.original_reference_ratio_six
#print axioms NativeOriginalGraphDensityCosts.original_reference_ratio_seven
#print axioms NativeOriginalGraphDensityCosts.bcBeta_inverse_le
#print axioms NativeOriginalGraphDensityCosts.heightMass_inverse_le
#print axioms NativeOriginalGraphDensityCosts.original_power_quotient
#print axioms NativeOriginalGraphDensityCosts.original_two_power_quotient
#print axioms NativeOriginalGraphDensityCosts.original_source_coefficients
#print axioms NativeOriginalGraphDensityCosts.windowBeta_eq
#print axioms NativeOriginalGraphDensityCosts.chosen_BC_graph_density
#print axioms NativeOriginalGraphDensityCosts.chosen_actual_B_mass
