import Theorems.Thm_StickyKakeya4_uniform_scalar_projection_energy

#print axioms StickyKakeya4.ScalarProjection.powerTailIntegral_lt_top
#print axioms StickyKakeya4.ScalarProjection.lintegral_le_of_power_tail
#print axioms StickyKakeya4.ScalarProjection.inverse_energy_le_of_sublevel_power
#print axioms StickyKakeya4.ScalarProjection.uniformScalarEnergyBound_lt_top
#print axioms StickyKakeya4.ScalarProjection.average_scalar_projection_pair_energy_le
#print axioms StickyKakeya4.ScalarProjection.average_scalar_projection_energy_le
#print axioms StickyKakeya4.ScalarProjection.exists_uniform_average_scalar_projection_energy_bound
#print axioms StickyKakeya4.ScalarProjection.parameterizedScalarPotential_integral_eq_parameter_integral
#print axioms StickyKakeya4.ScalarProjection.parameterizedScalarPotential_integral_le_of_uniform_bound
#print axioms StickyKakeya4.ScalarProjection.average_parameterizedScalarPotential_le
#print axioms StickyKakeya4.ScalarProjection.finite_average_parameterizedScalarPotential
#print axioms StickyKakeya4.ScalarProjection.parameterizedScalarPotential_superlevel_le
#print axioms StickyKakeya4.ScalarProjection.exists_uniform_parameterizedScalarPotential_cutoff
