import Theorems.Thm_StickyKakeya4_vector_bush_frostman

#check StickyKakeya4.VectorBushFrostman.familyFrontProbability_finite_scale_bound
#print axioms StickyKakeya4.VectorBushFrostman.vectorCenter
#print axioms StickyKakeya4.VectorBushFrostman.source_mem_vector_cap
#print axioms StickyKakeya4.VectorBushFrostman.spacetimeLift_horizontalProjection
#print axioms StickyKakeya4.VectorBushFrostman.bush_ball_preimage_le_cap
#print axioms StickyKakeya4.VectorBushFrostman.bush_ball_preimage_le_scaled_cap
#print axioms StickyKakeya4.VectorBushFrostman.family_physical_ball_mass_le
#print axioms StickyKakeya4.VectorBushFrostman.familyFrontProbability
#print axioms StickyKakeya4.VectorBushFrostman.familyFrontProbability_isProbability
#print axioms StickyKakeya4.VectorBushFrostman.familyFrontProbability_ball_le
#print axioms StickyKakeya4.VectorBushFrostman.familyFrontProbability_supported
#print axioms StickyKakeya4.VectorBushFrostman.familyFrostmanConstant
#print axioms StickyKakeya4.VectorBushFrostman.familyFrostmanConstant_ne_top
#print axioms StickyKakeya4.VectorBushFrostman.familyFrontProbability_finite_scale_bound
