import Theorems.Thm_StickyKakeya4_weighted_growth_star_split

#print axioms StickyKakeya4.WeightedGrowthStarSplit.targetDensity_le_on_low_multiplicity
#print axioms StickyKakeya4.WeightedGrowthStarSplit.restricted_density_le_const_smul
#print axioms StickyKakeya4.WeightedGrowthStarSplit.low_multiplicity_measure_domination
#print axioms StickyKakeya4.WeightedGrowthStarSplit.supported_mass_toReal_le
#print axioms StickyKakeya4.WeightedGrowthStarSplit.low_or_high_carries_half
#print axioms StickyKakeya4.WeightedGrowthStarSplit.amplified_layer_mass_lower
#print axioms StickyKakeya4.WeightedGrowthStarSplit.robust_target_support_growth
#print axioms StickyKakeya4.WeightedGrowthStarSplit.measurable_multiplicity
#print axioms StickyKakeya4.WeightedGrowthStarSplit.robust_low_multiplicity_support_growth
#print axioms StickyKakeya4.WeightedGrowthStarSplit.weighted_growth_or_distinct_source_star
#print axioms StickyKakeya4.WeightedGrowthStarSplit.high_branch_linear_star_mass
#print axioms StickyKakeya4.WeightedGrowthStarSplit.high_half_branch_retains_quarter
