import Theorems.Thm_StickyKakeya4_whole_parent_heavy_bush

#print axioms StickyKakeya4.WholeParentHeavyBush.measurableSet_bush
#print axioms StickyKakeya4.WholeParentHeavyBush.exists_heavy_bush_at_arbitrarily_fine_scale
#print axioms StickyKakeya4.WholeParentHeavyBush.positive_remainder_contains_fixed_coefficient_bush
#print axioms StickyKakeya4.WholeParentHeavyBush.exists_disjoint_heavy_bush_exhaustion
#print axioms StickyKakeya4.WholeParentHeavyBush.exists_finite_heavy_bush_retention
#print axioms StickyKakeya4.WholeParentHeavyBush.sticky_deficit_exists_whole_parent_heavy_bush_families
