import Theorems.Thm_StickyKakeya4_cover_adapted_wang_zakharov_closure
#print axioms StickyKakeya4.packing_selector_has_cover_adapted_wz_packets_at_exponent
#print axioms StickyKakeya4.coherent_boundary_has_cover_adapted_wz_packets
#print axioms StickyKakeya4.packing_three_pruning_assembles_wz_finite_input
#print axioms StickyKakeya4.separated_directions_convex_wolff_estimate
