import Theorems.Thm_StickyKakeya4_finite_plane_projection_grid
import Theorems.Thm_StickyKakeya4_finite_plane_projection_triangles
import Theorems.Thm_StickyKakeya4_finite_plane_projection_energy
import Theorems.Thm_StickyKakeya4_finite_plane_projection_selection
import Theorems.Thm_StickyKakeya4_finite_plane_projection_joint
import Theorems.Thm_StickyKakeya4_finite_plane_projection_line_tubes
import Theorems.Thm_StickyKakeya4_finite_plane_projection_original_b
import Theorems.Thm_StickyKakeya4_finite_plane_projection_representatives
import Theorems.Thm_StickyKakeya4_finite_plane_projection_frostman
import Theorems.Thm_StickyKakeya4_finite_plane_projection_frostman_geometry
import Theorems.Thm_StickyKakeya4_finite_plane_projection_allscale
import Theorems.Thm_StickyKakeya4_finite_plane_projection_native_geometry
import Theorems.Thm_StickyKakeya4_finite_plane_projection_separated
import Theorems.Thm_StickyKakeya4_finite_plane_projection_final
import Theorems.Thm_StickyKakeya4_finite_plane_projection_original_graph
import Theorems.Thm_StickyKakeya4_finite_plane_projection_perturbation

#print axioms FinitePlaneProjectionGrid.mesh_pos
#print axioms FinitePlaneProjectionGrid.slopes_card
#print axioms FinitePlaneProjectionGrid.mesh_mul_slopes_card
#print axioms FinitePlaneProjectionGrid.slopes_card_pos
#print axioms FinitePlaneProjectionGrid.parameters_card
#print axioms FinitePlaneProjectionGrid.slope_abs_le_one
#print axioms FinitePlaneProjectionGrid.slope_interval_count
#print axioms FinitePlaneProjectionGrid.vertical_half_of_collision
#print axioms FinitePlaneProjectionGrid.residual_slope_interval
#print axioms FinitePlaneProjectionGrid.collision_count_far
#print axioms FinitePlaneProjectionGrid.collision_count
#print axioms FinitePlaneProjectionGrid.product_filter_card_sum
#print axioms FinitePlaneProjectionGrid.scalar_affine_count
#print axioms FinitePlaneProjectionGrid.affine_strip_count_second
#print axioms FinitePlaneProjectionGrid.product_filter_card_sum_right
#print axioms FinitePlaneProjectionGrid.affine_strip_count_first
#print axioms FinitePlaneProjectionGrid.constant_bound_of_strip
#print axioms FinitePlaneProjectionGrid.strip_large_gradient
#print axioms FinitePlaneProjectionGrid.affine_strip_count
#print axioms FinitePlaneProjectionGrid.projected_determinant_identity
#print axioms FinitePlaneProjectionGrid.projected_triangle_count
#print axioms FinitePlaneProjectionGrid.dist3_eq_norm
#print axioms FinitePlaneProjectionGrid.pairParameters_iff
#print axioms FinitePlaneProjectionGrid.exists_shell
#print axioms FinitePlaneProjectionGrid.two_pow_reciprocal
#print axioms FinitePlaneProjectionGrid.finite_geometric_le_two
#print axioms FinitePlaneProjectionGrid.shell_pair_count
#print axioms FinitePlaneProjectionGrid.shell_energy_bound
#print axioms FinitePlaneProjectionGrid.sum_le_near_add_shells
#print axioms FinitePlaneProjectionGrid.point_energy_bound
#print axioms FinitePlaneProjectionGrid.collision_fubini
#print axioms FinitePlaneProjectionGrid.actual_KT1_collision_energy
#print axioms FinitePlaneProjectionGrid.same_floor_close
#print axioms FinitePlaneProjectionGrid.same_projected_cell_close
#print axioms FinitePlaneProjectionGrid.projected_cell_energy
#print axioms FinitePlaneProjectionGrid.parameters_nonempty
#print axioms FinitePlaneProjectionGrid.exists_le_average
#print axioms FinitePlaneProjectionGrid.exists_large_projected_image
#print axioms FinitePlaneProjectionGrid.triples_card
#print axioms FinitePlaneProjectionGrid.actual_triangle_parameter_count
#print axioms FinitePlaneProjectionGrid.triangle_fubini
#print axioms FinitePlaneProjectionGrid.original_triangle_projection_budget
#print axioms FinitePlaneProjectionGrid.exists_joint_average
#print axioms FinitePlaneProjectionGrid.exists_common_projection
#print axioms FinitePlaneProjectionGrid.determinant_bound_normal
#print axioms FinitePlaneProjectionGrid.secant_line_residual
#print axioms FinitePlaneProjectionGrid.triangle_in_line_strip
#print axioms FinitePlaneProjectionGrid.bounded_projected_point
#print axioms FinitePlaneProjectionGrid.projected_line_strip_cube
#print axioms FinitePlaneProjectionGrid.triple_filter_card
#print axioms FinitePlaneProjectionGrid.original_degenerate_triple_count
#print axioms FinitePlaneProjectionGrid.exists_common_projection_line_control
#print axioms FinitePlaneProjectionGrid.line_strip_fraction_of_cube
#print axioms FinitePlaneProjectionGrid.exists_three_averages
#print axioms FinitePlaneProjectionGrid.image_lower_of_collision_bound
#print axioms FinitePlaneProjectionGrid.exists_common_two_images
#print axioms FinitePlaneProjectionGrid.exists_cell_representatives
#print axioms FinitePlaneProjectionGrid.line_fraction_to_original_subset
#print axioms FinitePlaneProjectionGrid.exists_common_original_subsets
#print axioms FinitePlaneProjectionGrid.actual_KT1_collision_energy_at_scale
#print axioms FinitePlaneProjectionGrid.scaleEnergy_nonneg
#print axioms FinitePlaneProjectionGrid.scaleEnergy_budget
#print axioms FinitePlaneProjectionGrid.heavyScale_subset
#print axioms FinitePlaneProjectionGrid.badScales_subset
#print axioms FinitePlaneProjectionGrid.retainedScales_subset
#print axioms FinitePlaneProjectionGrid.heavyScale_mass
#print axioms FinitePlaneProjectionGrid.badScales_mass
#print axioms FinitePlaneProjectionGrid.retainedScales_cell_bound
#print axioms FinitePlaneProjectionGrid.retainedScales_half
#print axioms FinitePlaneProjectionGrid.retainedScales_ball_bound
#print axioms FinitePlaneProjectionGrid.base_mem_dyadicScales
#print axioms FinitePlaneProjectionGrid.dyadicScales_ge_base
#print axioms FinitePlaneProjectionGrid.dyadicScales_card_bound
#print axioms FinitePlaneProjectionGrid.exists_dyadicScale
#print axioms FinitePlaneProjectionGrid.retainedScales_allscale_ball_bound
#print axioms FinitePlaneProjectionGrid.retainedScales_representatives
#print axioms FinitePlaneProjectionGrid.allscaleLoss_pos
#print axioms FinitePlaneProjectionGrid.allscaleLoss_ge
#print axioms FinitePlaneProjectionGrid.projectedBall_wide_bound
#print axioms FinitePlaneProjectionGrid.exists_common_scale_energies
#print axioms FinitePlaneProjectionGrid.exists_common_allscale_original_subsets
#print axioms FinitePlaneProjectionGrid.relative_ball_bound_of_original_density
#print axioms FinitePlaneProjectionGrid.projectionLinear_surjective
#print axioms FinitePlaneProjectionGrid.projectedBall_eq_native_ball
#print axioms FinitePlaneProjectionGrid.projection_injective_of_cells
#print axioms FinitePlaneProjectionGrid.projected_original_card
#print axioms FinitePlaneProjectionGrid.cellColor_mem
#print axioms FinitePlaneProjectionGrid.nineColors_card
#print axioms FinitePlaneProjectionGrid.exists_cell_color
#print axioms FinitePlaneProjectionGrid.same_residue_floor_separation
#print axioms FinitePlaneProjectionGrid.exists_separated_projection_subset
#print axioms FinitePlaneProjectionGrid.projectedBall_mono
#print axioms FinitePlaneProjectionGrid.exists_common_separated_original_subsets
#print axioms FinitePlaneProjectionGrid.relative_native_ball_bound
#print axioms FinitePlaneProjectionGrid.cross_height_component_bounds
#print axioms FinitePlaneProjectionGrid.determinant_height_bound
#print axioms FinitePlaneProjectionGrid.determinant_affine_bound
#print axioms FinitePlaneProjectionGrid.original_cross_tube_dichotomy
#print axioms FinitePlaneProjectionGrid.originalCrossTube_card_of_height_affine_caps
#print axioms FinitePlaneProjectionGrid.dist3_nonneg
#print axioms FinitePlaneProjectionGrid.dist3_coordinate_bounds
#print axioms FinitePlaneProjectionGrid.determinant_point_perturbation
#print axioms FinitePlaneProjectionGrid.crossSize_point_perturbation
#print axioms FinitePlaneProjectionGrid.original_cross_tube_point_transport
#print axioms FinitePlaneProjectionGrid.originalCrossTube_transport
