import Theorems.Thm_StickyKakeya4_two_dimensional_transverse_escape
import Theorems.Thm_StickyKakeya4_two_step_menu_paths
import Theorems.Thm_StickyKakeya4_two_dimensional_time_fibers
import Theorems.Thm_StickyKakeya4_finite_transverse_menu_growth
import Theorems.Thm_StickyKakeya4_quadratic_image_count
import Theorems.Thm_StickyKakeya4_grain_jump_additive_relation
import Theorems.Thm_StickyKakeya4_sheared_grid_spine_columns
import Theorems.Thm_StickyKakeya4_native_fractional_reference_composition
import Theorems.Thm_StickyKakeya4_rich_witness_core
import Theorems.Thm_StickyKakeya4_rich_witness_real_core

#print axioms TwoDimensionalTransverseEscape.det_abs_lower_of_max_transverse
#print axioms TwoDimensionalTransverseEscape.coefficients_mul_bound_of_det_bound
#print axioms TwoDimensionalTransverseEscape.coefficients_bound_of_det_bound
#print axioms TwoDimensionalTransverseEscape.coefficient_differences_bound_of_max_transverse
#print axioms TwoStepMenuPaths.mem_paths
#print axioms TwoStepMenuPaths.card_paths
#print axioms TwoStepMenuPaths.card_paths_lower
#print axioms TwoStepMenuPaths.mem_frozen
#print axioms TwoStepMenuPaths.mem_frozen_paths
#print axioms TwoStepMenuPaths.frozen_subset
#print axioms TwoStepMenuPaths.frozen_label
#print axioms TwoStepMenuPaths.exists_frozen
#print axioms TwoStepMenuPaths.exists_frozen_paths
#print axioms TwoStepMenuPaths.orderedTimes_injOn_of_fixed_angles
#print axioms TwoStepMenuPaths.card_orderedTimes_image_of_fixed_angles
#print axioms TwoStepMenuPaths.orderedTimes_injOn_frozen
#print axioms TwoStepMenuPaths.card_orderedTimes_image_frozen
#print axioms TwoStepMenuPaths.orderedTimes_image_lower_frozen
#print axioms TwoDimensionalTimeFibers.card_le_real_mul_of_fibers
#print axioms TwoDimensionalTimeFibers.same_floor_abs_sub_le
#print axioms TwoDimensionalTimeFibers.floor_fiber_card_le
#print axioms TwoDimensionalTimeFibers.interval_population
#print axioms TwoDimensionalTimeFibers.linear_combination_control
#print axioms TwoDimensionalTimeFibers.coefficient_control
#print axioms TwoDimensionalTimeFibers.firstTimes_fixed_secondTimes_injective
#print axioms TwoDimensionalTimeFibers.two_dimensional_endpoint_fiber
#print axioms TwoDimensionalTimeFibers.two_dimensional_fixed_angle_growth
#print axioms FiniteTransverseMenuGrowth.card_le_real_mul_of_fibers
#print axioms FiniteTransverseMenuGrowth.same_floor_abs_sub_le
#print axioms FiniteTransverseMenuGrowth.floor_fiber_card_le
#print axioms FiniteTransverseMenuGrowth.interval_population
#print axioms FiniteTransverseMenuGrowth.scalar_coefficient_control
#print axioms FiniteTransverseMenuGrowth.first_fixed_second_injective
#print axioms FiniteTransverseMenuGrowth.scalar_endpoint_fiber
#print axioms FiniteTransverseMenuGrowth.scalar_fixed_angle_growth
#print axioms FiniteTransverseMenuGrowth.scalar_menu_growth
#print axioms FiniteTransverseMenuGrowth.planar_line_ne_top
#print axioms FiniteTransverseMenuGrowth.planar_line_richness_of_subspaces
#print axioms FiniteTransverseMenuGrowth.planar_frozen_paths
#print axioms FiniteTransverseMenuGrowth.scalar_infDist_bot
#print axioms FiniteTransverseMenuGrowth.scalar_menu_growth_from_subspaces
#print axioms FiniteTransverseMenuGrowth.two_step_coordinate_error
#print axioms FiniteTransverseMenuGrowth.planar_menu_growth
#print axioms QuadraticImageCount.time_gap
#print axioms QuadraticImageCount.near_vertex_card
#print axioms QuadraticImageCount.select_side
#print axioms QuadraticImageCount.select_dense_side
#print axioms QuadraticImageCount.square_difference_lower
#print axioms QuadraticImageCount.noisy_square_gap
#print axioms QuadraticImageCount.quadratic_pair_gap
#print axioms QuadraticImageCount.quadratic_fiber_bound
#print axioms QuadraticImageCount.quadratic_image_count
#print axioms QuadraticImageCount.quadratic_fiber_card_bound
#print axioms QuadraticImageCount.exists_dense_quadratic_image
#print axioms QuadraticImageCount.dense_quadratic_image_count
#print axioms QuadraticImageCount.unit_density_quadratic_image_count
#print axioms QuadraticImageCount.interval_density_le
#print axioms QuadraticImageCount.interval_quadratic_image_count
#print axioms GrainJumpAdditiveRelation.Data.endpoint_identity
#print axioms GrainJumpAdditiveRelation.Data.difference_identity
#print axioms GrainJumpAdditiveRelation.Data.error_bound
#print axioms GrainJumpAdditiveRelation.Data.additive_relation_bound
#print axioms ShearedGridSpineColumns.pairLabel_injective
#print axioms ShearedGridSpineColumns.pair_cell_image_card
#print axioms ShearedGridSpineColumns.anchor_spec
#print axioms ShearedGridSpineColumns.slope_bound
#print axioms ShearedGridSpineColumns.slope_mul
#print axioms ShearedGridSpineColumns.tube_pair_residual
#print axioms ShearedGridSpineColumns.overlap_budget
#print axioms ShearedGridSpineColumns.columns_from_coarse_spines
#print axioms ShearedGridSpineColumns.lift_image
#print axioms ShearedGridSpineColumns.localCapacity_pos
#print axioms ShearedGridSpineColumns.local_fine_grid_card
#print axioms ShearedGridSpineColumns.fine_grid_card_le_coarse
#print axioms ShearedGridSpineColumns.coarse_spine_richness
#print axioms ShearedGridSpineColumns.columns_from_fine_spines
#print axioms ShearedGridSpineColumns.richness_div_capacity
#print axioms ShearedGridSpineColumns.column_power_of_weighted
#print axioms ShearedGridSpineColumns.columns_card_le_from_AD_fine_spines
#print axioms NativeFractionalReferenceComposition.exists_native_fractional_refinement
#print axioms RichWitnessCore.retained_subset
#print axioms RichWitnessCore.retained_eq_of_endpoints
#print axioms RichWitnessCore.swap_mem_retained
#print axioms RichWitnessCore.outgoing_card_eq_incoming
#print axioms RichWitnessCore.erase_vertex_loss
#print axioms RichWitnessCore.exists_rich_core
#print axioms RichWitnessCore.exists_half_mass_rich_core
#print axioms RichWitnessCore.collision_swap_mem
#print axioms RichWitnessCore.exists_collision_rich_core
#print axioms RichWitnessRealCore.exists_rich_core
#print axioms RichWitnessRealCore.exists_half_mass_rich_core
#print axioms RichWitnessRealCore.exists_half_mass_collision_core
