import Theorems.Thm_StickyKakeya4_planar_strip_intersection
import Theorems.Thm_StickyKakeya4_finite_common_point_tube_representatives
import Theorems.Thm_StickyKakeya4_rich_family_incidence_bound
import Theorems.Thm_StickyKakeya4_native_rich_strip_representatives
import Theorems.Thm_StickyKakeya4_original_pair_strip_geometry
import Theorems.Thm_StickyKakeya4_native_rich_pair_tube_family
import Theorems.Thm_StickyKakeya4_transverse_original_strip_points
import Theorems.Thm_StickyKakeya4_original_pair_row_cut
import Theorems.Thm_StickyKakeya4_native_weak_radial_pair_graph
import Theorems.Thm_StickyKakeya4_four_unit_tube_band_cover
import Theorems.Thm_StickyKakeya4_planar_frostman_ball_conversion
import Theorems.Thm_StickyKakeya4_physical_weak_radial_pair_graph
import Theorems.Thm_StickyKakeya4_native_a2_power_budget
import Theorems.Thm_StickyKakeya4_native_a2_parameter_identities
import Theorems.Thm_StickyKakeya4_original_physical_pair_tube
import Theorems.Thm_StickyKakeya4_native_a2_weak_radial_caller

#print axioms PlanarStripIntersection.abs_combination_le_four
#print axioms PlanarStripIntersection.common_point_coordinate_bounds
#print axioms PlanarStripIntersection.determinant_bound_of_common_separation
#print axioms PlanarStripIntersection.transverse_intersection_ball
#print axioms PlanarStripIntersection.unit_coordinate_transfer
#print axioms PlanarStripIntersection.bounded_strip_containment
#print axioms PlanarStripIntersection.long_overlap_containment
#print axioms FiniteCommonPointTubeRepresentatives.compatible_symm
#print axioms FiniteCommonPointTubeRepresentatives.exists_original_representatives
#print axioms RichFamilyIncidenceBound.incidence_collision_count
#print axioms RichFamilyIncidenceBound.incidence_cauchy
#print axioms RichFamilyIncidenceBound.intersection_sum_upper
#print axioms RichFamilyIncidenceBound.rich_family_cardinality
#print axioms NativeRichStripRepresentatives.diameter_support_card_bound
#print axioms NativeRichStripRepresentatives.finite_rich_strip_representatives
#print axioms OriginalPairStripGeometry.scale_pos
#print axioms OriginalPairStripGeometry.original_pair_normalized
#print axioms OriginalPairStripGeometry.original_pair_on_line
#print axioms OriginalPairStripGeometry.affine_pair_line_residual
#print axioms OriginalPairStripGeometry.near_original_pair_line
#print axioms NativeRichPairTubeFamily.original_rich_pair_representatives
#print axioms TransverseOriginalStripPoints.common_card_bound
#print axioms TransverseOriginalStripPoints.transverse_card_bound
#print axioms TransverseOriginalStripPoints.transverse_card_from_rich_family
#print axioms TransverseOriginalStripPoints.nontransverse_common_strip
#print axioms OriginalPairRowCut.exists_good_pairs
#print axioms NativeWeakRadialPairGraph.finite_weak_radial_graph
#print axioms FourUnitTubeBandCover.normalized_frame
#print axioms FourUnitTubeBandCover.four_unit_intervals
#print axioms FourUnitTubeBandCover.band_card_le_four
#print axioms PlanarFrostmanBallConversion.euclidean_le_two_box
#print axioms PlanarFrostmanBallConversion.box_ball_card_le
#print axioms PlanarFrostmanBallConversion.box_frostman_bound
#print axioms PlanarFrostmanBallConversion.diagonal_charge
#print axioms PhysicalWeakRadialPairGraph.original_physical_weak_radial_graph
#print axioms NativeA2PowerBudget.exists_power_threshold
#print axioms NativeA2PowerBudget.absorb_power_term
#print axioms NativeA2PowerBudget.native_power_budget
#print axioms NativeA2PowerBudget.exists_native_threshold
#print axioms NativeA2ParameterIdentities.native_geometric_scales
#print axioms NativeA2ParameterIdentities.overlap_power_identity
#print axioms NativeA2ParameterIdentities.transverse_power_identity
#print axioms NativeA2ParameterIdentities.diagonal_power_identity
#print axioms OriginalPhysicalPairTube.coordinates_le_euclidean
#print axioms OriginalPhysicalPairTube.physical_pair_tube_subset
#print axioms OriginalPhysicalPairTube.physical_pair_tube_card
#print axioms NativeA2WeakRadialCaller.native_weak_radial_graph
#print axioms NativeA2WeakRadialCaller.exists_uniform_native_weak_radial_graph_threshold
