import Theorems.Thm_StickyKakeya4_symmetry_set_difference_step
import Theorems.Thm_StickyKakeya4_dyadic_original_fiber_selection
import Theorems.Thm_StickyKakeya4_symmetry_difference_growth_chain
import Theorems.Thm_StickyKakeya4_balanced_bsg_iteration_core
import Theorems.Thm_StickyKakeya4_balanced_bsg_polynomial_loss
import Theorems.Thm_StickyKakeya4_original_difference_translate_pullback
import Theorems.Thm_StickyKakeya4_iterated_difference_translate_pullback
import Theorems.Thm_StickyKakeya4_disjoint_rich_translate_cover
import Theorems.Thm_StickyKakeya4_slow_symmetry_balanced_core
import Theorems.Thm_StickyKakeya4_chain_original_core_pullback
import Theorems.Thm_StickyKakeya4_difference_core_iterated_cover
import Theorems.Thm_StickyKakeya4_rich_symmetry_translate_centers
import Theorems.Thm_StickyKakeya4_asymmetric_original_subset_assembly
import Theorems.Thm_StickyKakeya4_symmetry_chain_uniform_density
import Theorems.Thm_StickyKakeya4_symmetry_slow_factor_budget
import Theorems.Thm_StickyKakeya4_shifted_label_energy
import Theorems.Thm_StickyKakeya4_actual_rounded_additive_energy
import Theorems.Thm_StickyKakeya4_rounded_iterated_cover_transfer
import Theorems.Thm_StickyKakeya4_original_real_asymmetric_construction
import Theorems.Thm_StickyKakeya4_native_asymmetric_scale_budget
import Theorems.Thm_StickyKakeya4_native_asymmetric_polynomial_retention
import Theorems.Thm_StickyKakeya4_separated_dyadic_cardinality
import Theorems.Thm_StickyKakeya4_partitioned_collision_energy
import Theorems.Thm_StickyKakeya4_asymmetric_dyadic_absorption

#print axioms SymmetrySetDifferenceStep.overlap_subset
#print axioms SymmetrySetDifferenceStep.overlap_card_le
#print axioms SymmetrySetDifferenceStep.mem_symmetrySet_iff
#print axioms SymmetrySetDifferenceStep.incidence_sum
#print axioms SymmetrySetDifferenceStep.incidence_second_moment
#print axioms SymmetrySetDifferenceStep.common_witnesses_card_le
#print axioms SymmetrySetDifferenceStep.second_moment_le_energy
#print axioms SymmetrySetDifferenceStep.difference_energy_lower
#print axioms SymmetrySetDifferenceStep.overlap_sum_le_square
#print axioms SymmetrySetDifferenceStep.symmetry_family_card_bound
#print axioms SymmetrySetDifferenceStep.symmetrySet_card_bound
#print axioms SymmetrySetDifferenceStep.difference_energy_upper
#print axioms SymmetrySetDifferenceStep.good_pairs_lower
#print axioms SymmetrySetDifferenceStep.good_pairs_difference_image_subset
#print axioms SymmetrySetDifferenceStep.symmetrySet_card_mul_bound
#print axioms SymmetrySetDifferenceStep.good_pairs_lower_of_energy
#print axioms SymmetrySetDifferenceStep.additive_fiber_card
#print axioms SymmetrySetDifferenceStep.differenceEnergy_eq_addEnergy
#print axioms SymmetrySetDifferenceStep.good_pairs_lower_of_addEnergy
#print axioms DyadicOriginalFiberSelection.fiber_card_pos
#print axioms DyadicOriginalFiberSelection.fiber_sum
#print axioms DyadicOriginalFiberSelection.level_lt
#print axioms DyadicOriginalFiberSelection.bin_saturated
#print axioms DyadicOriginalFiberSelection.fiber_bin_eq
#print axioms DyadicOriginalFiberSelection.bin_fiber_bounds
#print axioms DyadicOriginalFiberSelection.bin_card_sum
#print axioms DyadicOriginalFiberSelection.exists_dyadic_bin
#print axioms DyadicOriginalFiberSelection.bin_half_average
#print axioms DyadicOriginalFiberSelection.exists_original_fiber_refinement
#print axioms DyadicOriginalFiberSelection.exists_original_fiber_refinement_real
#print axioms DyadicOriginalFiberSelection.levelCount_eq_log2
#print axioms DyadicOriginalFiberSelection.fiber_eq_of_saturated
#print axioms DyadicOriginalFiberSelection.exists_refined_good_pairs
#print axioms DyadicOriginalFiberSelection.exists_refined_symmetry_pairs
#print axioms DyadicOriginalFiberSelection.exists_refined_pairs_of_addEnergy
#print axioms SymmetryDifferenceGrowthChain.threshold_pos
#print axioms SymmetryDifferenceGrowthChain.threshold_formula
#print axioms SymmetryDifferenceGrowthChain.exists_step_of_energy
#print axioms SymmetryDifferenceGrowthChain.exists_step_of_symmetry
#print axioms SymmetryDifferenceGrowthChain.selectedEdges_spec
#print axioms SymmetryDifferenceGrowthChain.chainSet_zero
#print axioms SymmetryDifferenceGrowthChain.chainSet_succ
#print axioms SymmetryDifferenceGrowthChain.chain_steps
#print axioms SymmetryDifferenceGrowthChain.chain_nonempty
#print axioms SymmetryDifferenceGrowthChain.density_pos
#print axioms SymmetryDifferenceGrowthChain.chain_edge_density
#print axioms SymmetryDifferenceGrowthChain.difference_fiber_card_le
#print axioms SymmetryDifferenceGrowthChain.edge_card_le_image_mul
#print axioms SymmetryDifferenceGrowthChain.chain_growth_lower
#print axioms SymmetryDifferenceGrowthChain.density_le_one
#print axioms SymmetryDifferenceGrowthChain.chain_card_upper
#print axioms SymmetryDifferenceGrowthChain.chain_fiber_lower
#print axioms SymmetryDifferenceGrowthChain.threshold_le_one_of_energy
#print axioms SymmetryDifferenceGrowthChain.density_formula
#print axioms SymmetryDifferenceGrowthChain.positive_ratio_product
#print axioms SymmetryDifferenceGrowthChain.terminalBound_pos
#print axioms SymmetryDifferenceGrowthChain.terminal_ratio_bound
#print axioms SymmetryDifferenceGrowthChain.chain_ratio_product
#print axioms SymmetryDifferenceGrowthChain.exists_adjacent_ratio_le_root
#print axioms SymmetryDifferenceGrowthChain.exists_slow_stage
#print axioms SymmetryDifferenceGrowthChain.one_le_slowFactor
#print axioms BalancedBSGIterationCore.iterated_differences_of_small_difference
#print axioms BalancedBSGIterationCore.balanced_energy_core
#print axioms BalancedBSGPolynomialLoss.difference_constant_polynomial
#print axioms BalancedBSGPolynomialLoss.growth_constant_polynomial
#print axioms BalancedBSGPolynomialLoss.growth_constant_le_div
#print axioms OriginalDifferenceTranslatePullback.exists_original_translate_pullback
#print axioms OriginalDifferenceTranslatePullback.exists_original_translate_pullback_density
#print axioms IteratedDifferenceTranslatePullback.pullback_chain
#print axioms DisjointRichTranslateCover.exists_disjoint_translate_cover
#print axioms DisjointRichTranslateCover.exists_rich_translate_selection
#print axioms DisjointRichTranslateCover.exists_rich_translate_selection_quantitative
#print axioms SlowSymmetryBalancedCore.difference_collisions_le_energy
#print axioms SlowSymmetryBalancedCore.original_difference_graph_energy
#print axioms SlowSymmetryBalancedCore.energy_of_slow_ratio
#print axioms SlowSymmetryBalancedCore.exists_balanced_chain_core
#print axioms ChainOriginalCorePullback.pullback_original_subset
#print axioms DifferenceCoreIteratedCover.difference_core_neg
#print axioms DifferenceCoreIteratedCover.difference_core_growth
#print axioms DifferenceCoreIteratedCover.difference_core_difference_growth
#print axioms DifferenceCoreIteratedCover.covered_iterated_sum_difference
#print axioms RichSymmetryTranslateCenters.translate_eq_add_singleton
#print axioms RichSymmetryTranslateCenters.translate_card
#print axioms RichSymmetryTranslateCenters.translated_intersection_card_le
#print axioms RichSymmetryTranslateCenters.original_incidence_sum_le
#print axioms RichSymmetryTranslateCenters.symmetry_overlap_sum_lower
#print axioms RichSymmetryTranslateCenters.overlap_sum_upper
#print axioms RichSymmetryTranslateCenters.exists_rich_centers
#print axioms RichSymmetryTranslateCenters.exists_rich_centers_translate
#print axioms AsymmetricOriginalSubsetAssembly.original_subsets_from_chain_core
#print axioms AsymmetricOriginalSubsetAssembly.finite_asymmetric_original_subsets
#print axioms SymmetryChainUniformDensity.threshold_antitone
#print axioms SymmetryChainUniformDensity.chain_card_budget
#print axioms SymmetryChainUniformDensity.good_pairs_card_budget
#print axioms SymmetryChainUniformDensity.chain_level_count_budget
#print axioms SymmetryChainUniformDensity.common_density_lower
#print axioms SymmetryChainUniformDensity.common_threshold_range
#print axioms SymmetryChainUniformDensity.source_budget_bounds
#print axioms SymmetryChainUniformDensity.constructed_common_density
#print axioms SymmetrySlowFactorBudget.root_factor_le
#print axioms SymmetrySlowFactorBudget.balanced_density_lower
#print axioms SymmetrySlowFactorBudget.chain_balanced_density_lower
#print axioms SymmetrySlowFactorBudget.growth_cost_budget
#print axioms ShiftedLabelEnergy.population_zero
#print axioms ShiftedLabelEnergy.shifted_count_by_original_points
#print axioms ShiftedLabelEnergy.shifted_count_by_labels
#print axioms ShiftedLabelEnergy.shifted_square_sum_le
#print axioms ShiftedLabelEnergy.shifted_pairs_le_zero_energy
#print axioms ShiftedLabelEnergy.five_discrepancies
#print axioms ShiftedLabelEnergy.near_pairs_le_five_energy
#print axioms ActualRoundedAdditiveEnergy.round_error
#print axioms ActualRoundedAdditiveEnergy.rounding_injOn
#print axioms ActualRoundedAdditiveEnergy.collisions_image_card
#print axioms ActualRoundedAdditiveEnergy.rounded_product_image
#print axioms ActualRoundedAdditiveEnergy.rounded_label_energy
#print axioms ActualRoundedAdditiveEnergy.near_energy_le_five_rounded_energy
#print axioms ActualRoundedAdditiveEnergy.rounded_card
#print axioms ActualRoundedAdditiveEnergy.near_difference_eq_near_sum
#print axioms ActualRoundedAdditiveEnergy.near_difference_le_five_rounded_energy
#print axioms ActualRoundedAdditiveEnergy.rounded_energy_density
#print axioms RoundedIteratedCoverTransfer.original_preimage
#print axioms RoundedIteratedCoverTransfer.round_abs_error
#print axioms RoundedIteratedCoverTransfer.nsmul_rounding_witness
#print axioms RoundedIteratedCoverTransfer.mixed_rounding_witness
#print axioms RoundedIteratedCoverTransfer.rounded_label_close
#print axioms RoundedIteratedCoverTransfer.iterated_grid_cover_bound
#print axioms OriginalRealAsymmetricConstruction.original_real_subsets
#print axioms NativeAsymmetricScaleBudget.ceil_inverse_bound
#print axioms NativeAsymmetricScaleBudget.budget_linear_bound
#print axioms NativeAsymmetricScaleBudget.threshold_native
#print axioms NativeAsymmetricScaleBudget.density_native_lower
#print axioms NativeAsymmetricScaleBudget.inverse_le_binary_ceil
#print axioms NativeAsymmetricScaleBudget.native_card_budget
#print axioms NativeAsymmetricPolynomialRetention.retained_product_lower
#print axioms NativeAsymmetricPolynomialRetention.original_x_retention
#print axioms NativeAsymmetricPolynomialRetention.growth_power_budget
#print axioms NativeAsymmetricPolynomialRetention.original_y_retention
#print axioms NativeAsymmetricPolynomialRetention.iterated_cost_budget
#print axioms SeparatedDyadicCardinality.original_rounded_label_bounds
#print axioms SeparatedDyadicCardinality.original_cardinality_bound
#print axioms PartitionedCollisionEnergy.histogram_partition
#print axioms PartitionedCollisionEnergy.collision_energy_on_original_menu
#print axioms PartitionedCollisionEnergy.partition_collision_energy
#print axioms PartitionedCollisionEnergy.translated_pair_energy_cap
#print axioms AsymmetricDyadicAbsorption.polynomial_absorption
#print axioms AsymmetricDyadicAbsorption.slow_factor_absorption
#print axioms AsymmetricDyadicAbsorption.polynomial_retention_absorption
#print axioms AsymmetricDyadicAbsorption.polynomial_cost_absorption
#print axioms AsymmetricDyadicAbsorption.real_floor_cover_factor
#print axioms AsymmetricDyadicAbsorption.densityCoefficient_pos
#print axioms AsymmetricDyadicAbsorption.nativeDensity_lower
#print axioms AsymmetricDyadicAbsorption.choose_depth
#print axioms AsymmetricDyadicAbsorption.native_absorption
#print axioms AsymmetricDyadicAbsorption.dyadic_mesh_rpow
#print axioms AsymmetricDyadicAbsorption.native_dyadic_absorption
#print axioms AsymmetricDyadicAbsorption.original_real_dyadic_bsg
