import Theorems.Thm_StickyKakeya4_adapted_box_volume
import Theorems.Thm_StickyKakeya4_original_w_adapted_boxes
import Theorems.Thm_StickyKakeya4_native_tangent_grid_coarsening
import Theorems.Thm_StickyKakeya4_original_tube_ancestor_saturation
import Theorems.Thm_StickyKakeya4_original_ancestor_counting
import Theorems.Thm_StickyKakeya4_original_ancestor_fiber_geometry
import Theorems.Thm_StickyKakeya4_native_original_ancestor_counts
import Theorems.Thm_StickyKakeya4_original_cw_scale_cancellation
import Theorems.Thm_StickyKakeya4_original_carrier_image_count
import Theorems.Thm_StickyKakeya4_original_core_endpoint_lifting
import Theorems.Thm_StickyKakeya4_original_core_box_paths
import Theorems.Thm_StickyKakeya4_native_original_scalar_cw
import Theorems.Thm_StickyKakeya4_native_original_planar_cw
import Theorems.Thm_StickyKakeya4_original_w_joint_phase
import Theorems.Thm_StickyKakeya4_abelian_shifted_label_energy
import Theorems.Thm_StickyKakeya4_planar_shifted_near_energy
import Theorems.Thm_StickyKakeya4_actual_planar_rounded_energy
import Theorems.Thm_StickyKakeya4_planar_rounded_sumset_cover
import Theorems.Thm_StickyKakeya4_planar_dyadic_numerics
import Theorems.Thm_StickyKakeya4_planar_original_subset_construction
import Theorems.Thm_StickyKakeya4_planar_original_dyadic_bsg
import Theorems.Thm_StickyKakeya4_original_w_normalized_phase

#print axioms AdaptedBoxVolume.box_eq_preimage
#print axioms AdaptedBoxVolume.residualCoordinates_measurePreserving
#print axioms AdaptedBoxVolume.volume_box_product
#print axioms AdaptedBoxVolume.convex_box
#print axioms AdaptedBoxVolume.volume_closedBall_real_pair
#print axioms AdaptedBoxVolume.volume_box_a1
#print axioms AdaptedBoxVolume.volume_box_a2
#print axioms AdaptedBoxVolume.volume_box_a1_pos_finite
#print axioms AdaptedBoxVolume.volume_box_a2_pos_finite
#print axioms OriginalWAdaptedBoxes.original_data_bounds
#print axioms OriginalWAdaptedBoxes.original_witness_box_comparison
#print axioms OriginalWAdaptedBoxes.constructed_successor_box_comparison
#print axioms NativeTangentGridCoarsening.scalar_interval_grid_card
#print axioms NativeTangentGridCoarsening.scalar_filtered_interval_grid_card
#print axioms NativeTangentGridCoarsening.planar_rectangle_grid_card
#print axioms NativeTangentGridCoarsening.planar_filtered_rectangle_grid_card
#print axioms NativeTangentGridCoarsening.coarse_floor_interval
#print axioms NativeTangentGridCoarsening.scalar_coarse_fiber_card
#print axioms NativeTangentGridCoarsening.planar_coarse_fiber_card
#print axioms NativeTangentGridCoarsening.image_card_le_real_mul_of_fiber_images
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening_add_two
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening_add_two
#print axioms NativeTangentGridCoarsening.ratio_add_two_le_three
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening_chain
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening_chain
#print axioms NativeTangentGridCoarsening.scalar_grid_coarsening
#print axioms NativeTangentGridCoarsening.planar_grid_coarsening
#print axioms NativeTangentGridCoarsening.scalar_centered_grid_card
#print axioms NativeTangentGridCoarsening.planar_centered_grid_card
#print axioms NativeTangentGridCoarsening.scalar_injective_grid_centered_card
#print axioms NativeTangentGridCoarsening.planar_injective_grid_centered_card
#print axioms OriginalTubeAncestorSaturation.ancestor_incidence_residual
#print axioms OriginalTubeAncestorSaturation.same_point_normal_direction
#print axioms OriginalTubeAncestorSaturation.ancestor_fiber_inside_adapted_box
#print axioms OriginalTubeAncestorSaturation.scalar_same_parameter_cell
#print axioms OriginalTubeAncestorSaturation.planar_same_parameter_cell
#print axioms OriginalTubeAncestorSaturation.scalar_parameter_ancestor_gaps
#print axioms OriginalTubeAncestorSaturation.planar_parameter_ancestor_gaps
#print axioms OriginalTubeAncestorSaturation.fine_label_realizer_tangent_gap
#print axioms OriginalAncestorCounting.exists_original_cell_representatives
#print axioms OriginalAncestorCounting.original_pair_ancestor_count
#print axioms OriginalAncestorCounting.fine_label_in_ancestor_ball
#print axioms OriginalAncestorCounting.same_ancestor_fixed_height_ball
#print axioms OriginalAncestorCounting.original_carrier_saturation_count
#print axioms OriginalAncestorCounting.original_carrier_convex_count
#print axioms OriginalAncestorFiberGeometry.occupied_ancestor_has_original_realizer
#print axioms OriginalAncestorFiberGeometry.original_direction_fiber_bound
#print axioms OriginalAncestorFiberGeometry.active_points_in_ancestor_ball
#print axioms NativeOriginalAncestorCounts.scalar_original_ancestor_count
#print axioms NativeOriginalAncestorCounts.planar_original_ancestor_count
#print axioms OriginalCWScaleCancellation.original_count_scale_cancellation
#print axioms OriginalCWScaleCancellation.carrier_global_normalization
#print axioms OriginalCWScaleCancellation.original_fine_AD_ratio
#print axioms OriginalCWScaleCancellation.original_CW_ratio_lower
#print axioms OriginalCarrierImageCount.occupied_ancestors_mem_reference
#print axioms OriginalCarrierImageCount.labelwise_containment_covers_full_saturation
#print axioms OriginalCarrierImageCount.original_realizer_carrier_CW_count
#print axioms OriginalCoreEndpointLifting.one_state_height
#print axioms OriginalCoreEndpointLifting.two_state_height
#print axioms OriginalCoreEndpointLifting.select_original_endpoint_points
#print axioms OriginalCoreEndpointLifting.selected_core_points_are_original
#print axioms OriginalCoreEndpointLifting.scalar_cells_eq_endpoint_image
#print axioms OriginalCoreEndpointLifting.planar_cells_eq_endpoint_image
#print axioms OriginalCoreEndpointLifting.exists_scalar_original_endpoint_points
#print axioms OriginalCoreEndpointLifting.exists_planar_original_endpoint_points
#print axioms OriginalCoreBoxPaths.box_mono
#print axioms OriginalCoreBoxPaths.coreBox_mono
#print axioms OriginalCoreBoxPaths.oneStates_box_comparison
#print axioms OriginalCoreBoxPaths.twoStates_box_comparison
#print axioms NativeOriginalScalarCW.adapted_box_measurable
#print axioms NativeOriginalScalarCW.scalar_original_CW_concentration
#print axioms NativeOriginalPlanarCW.adapted_box_measurable
#print axioms NativeOriginalPlanarCW.planar_original_CW_concentration
#print axioms OriginalWJointPhase.offset_identity
#print axioms OriginalWJointPhase.offset_error_bound
#print axioms OriginalWJointPhase.original_witness_offset_remainder
#print axioms OriginalWJointPhase.original_coarse_offset_displacement
#print axioms OriginalWJointPhase.scalar_native_joint_displacement
#print axioms AbelianShiftedLabelEnergy.shifted_pairs_le_zero_energy
#print axioms AbelianShiftedLabelEnergy.pair_set_le_menu_energy
#print axioms PlanarShiftedNearEnergy.seven_discrepancies
#print axioms PlanarShiftedNearEnergy.near_pairs_le_fortynine_energy
#print axioms PlanarShiftedNearEnergy.original_labelled_planar_rounding
#print axioms ActualPlanarRoundedEnergy.planar_rounding_injOn
#print axioms ActualPlanarRoundedEnergy.planar_rounded_card
#print axioms ActualPlanarRoundedEnergy.rounded_planar_product_image
#print axioms ActualPlanarRoundedEnergy.rounded_planar_label_energy
#print axioms ActualPlanarRoundedEnergy.original_planar_near_energy
#print axioms ActualPlanarRoundedEnergy.max_norm_separation_of_euclidean_squared
#print axioms ActualPlanarRoundedEnergy.original_euclidean_planar_near_energy
#print axioms PlanarRoundedSumsetCover.point_rounding_error
#print axioms PlanarRoundedSumsetCover.actual_planar_iterated_cover
#print axioms PlanarDyadicNumerics.polynomial_absorption
#print axioms PlanarDyadicNumerics.slow_factor_absorption
#print axioms PlanarDyadicNumerics.polynomial_retention_absorption
#print axioms PlanarDyadicNumerics.polynomial_cost_absorption
#print axioms PlanarDyadicNumerics.real_floor_cover_factor
#print axioms PlanarDyadicNumerics.planar_floor_cover_factor
#print axioms PlanarDyadicNumerics.densityCoefficient_pos
#print axioms PlanarDyadicNumerics.nativeDensity_lower
#print axioms PlanarDyadicNumerics.choose_depth
#print axioms PlanarDyadicNumerics.native_absorption
#print axioms PlanarDyadicNumerics.dyadic_mesh_rpow
#print axioms PlanarDyadicNumerics.native_dyadic_absorption
#print axioms PlanarOriginalSubsetConstruction.half_mesh
#print axioms PlanarOriginalSubsetConstruction.rounded_cardinality_bound
#print axioms PlanarOriginalSubsetConstruction.original_preimage
#print axioms PlanarOriginalSubsetConstruction.original_planar_subsets
#print axioms PlanarOriginalDyadicBSG.coordinate_planar_dyadic_bsg
#print axioms PlanarOriginalDyadicBSG.euclidean_near_energy_le_coordinate
#print axioms PlanarOriginalDyadicBSG.original_planar_dyadic_bsg
#print axioms OriginalWNormalizedPhase.scalar_operator_apply
#print axioms OriginalWNormalizedPhase.phase_error_identity
#print axioms OriginalWNormalizedPhase.scaled_scalar_error
#print axioms OriginalWNormalizedPhase.scaled_normal_error
#print axioms OriginalWNormalizedPhase.normalized_phase_error
#print axioms OriginalWNormalizedPhase.scalar_original_normalized_phase
