import Theorems.Thm_StickyKakeya4_original_core_menu_density
import Theorems.Thm_StickyKakeya4_finite_phase_field_images
import Theorems.Thm_StickyKakeya4_original_w_grain_drift
import Theorems.Thm_StickyKakeya4_original_phase_cell_population
import Theorems.Thm_StickyKakeya4_original_phase_grid_population
import Theorems.Thm_StickyKakeya4_original_phase_window_graph
import Theorems.Thm_StickyKakeya4_native_original_phase_window_graph
import Theorems.Thm_StickyKakeya4_native_original_phase_window_population
import Theorems.Thm_StickyKakeya4_native_original_phase_window_edges
import Theorems.Thm_StickyKakeya4_original_phase_grid_error
import Theorems.Thm_StickyKakeya4_original_phase_window_density
import Theorems.Thm_StickyKakeya4_native_original_phase_grid_edges
import Theorems.Thm_StickyKakeya4_heavy_energy_bin_selection
import Theorems.Thm_StickyKakeya4_original_fiber_energy_collapse
import Theorems.Thm_StickyKakeya4_energy_preserving_original_fiber_bin
import Theorems.Thm_StickyKakeya4_labelled_real_energy_bin
import Theorems.Thm_StickyKakeya4_integer_bin_real_near_energy
import Theorems.Thm_StickyKakeya4_original_real_energy_bin_caller
import Theorems.Thm_StickyKakeya4_original_bin_label_lift
import Theorems.Thm_StickyKakeya4_native_a2_dilated_parameters
import Theorems.Thm_StickyKakeya4_native_a2_dilated_caller
import Theorems.Thm_StickyKakeya4_native_a1_initial_radial_graph

#print axioms OriginalCoreMenuDensity.all_menus_card_bound
#print axioms OriginalCoreMenuDensity.exists_original_menu_rich_core
#print axioms OriginalCoreMenuDensity.normalize_phase_menu_degree
#print axioms FinitePhaseFieldImages.original_field_cell_phase_image
#print axioms FinitePhaseFieldImages.original_field_phase_image
#print axioms FinitePhaseFieldImages.phase_card_of_fixed_tangent_cell
#print axioms OriginalWGrainDrift.original_witness_grain_drift
#print axioms OriginalWGrainDrift.scalar_constructed_successor_grain_drift
#print axioms OriginalPhaseCellPopulation.physical_cells_in_rectangle
#print axioms OriginalPhaseCellPopulation.same_x_and_grain_window_physical_cells
#print axioms OriginalPhaseCellPopulation.original_phase_cells_over_x_cell
#print axioms OriginalPhaseCellPopulation.phase_cap_of_working_scale_ratio
#print axioms OriginalPhaseGridPopulation.gridPoint_injective
#print axioms OriginalPhaseGridPopulation.first_interval_population
#print axioms OriginalPhaseGridPopulation.grid_ball_population
#print axioms OriginalPhaseGridPopulation.grid_ball_population_large_radius
#print axioms OriginalPhaseGridPopulation.phase_filter_first_image
#print axioms OriginalPhaseGridPopulation.original_phase_first_fiber_cap
#print axioms OriginalPhaseGridPopulation.original_phase_ball_population
#print axioms OriginalPhaseWindowGraph.neighborCells_card
#print axioms OriginalPhaseWindowGraph.self_mem_neighborCells
#print axioms OriginalPhaseWindowGraph.grainCell_neighbor
#print axioms OriginalPhaseWindowGraph.mem_menuGraph
#print axioms OriginalPhaseWindowGraph.menuGraph_card
#print axioms OriginalPhaseWindowGraph.exists_maximal_occupied
#print axioms OriginalPhaseWindowGraph.exists_maximal_window_graph
#print axioms NativeOriginalPhaseWindowGraph.exists_original_phase_window_graph
#print axioms NativeOriginalPhaseWindowPopulation.expanded_eq_phase_image
#print axioms NativeOriginalPhaseWindowPopulation.neighbor_grain_window
#print axioms NativeOriginalPhaseWindowPopulation.original_enlarged_phase_ball_population
#print axioms NativeOriginalPhaseWindowEdges.graph_edge_original_witness
#print axioms NativeOriginalPhaseWindowEdges.graph_edge_normalized_phase_error
#print axioms OriginalPhaseGridError.scalar_floor_error
#print axioms OriginalPhaseGridError.grid_floor_error
#print axioms OriginalPhaseGridError.original_phase_label_identity
#print axioms OriginalPhaseGridError.original_phase_grid_error
#print axioms OriginalPhaseGridError.rounded_phase_relation
#print axioms OriginalPhaseWindowDensity.window_graph_relative_density
#print axioms OriginalPhaseWindowDensity.original_alphabet_degree_lower
#print axioms NativeOriginalPhaseGridEdges.graph_edge_grid_phase_error
#print axioms HeavyEnergyBinSelection.exists_heavy_energy_index
#print axioms HeavyEnergyBinSelection.product_partition_piece
#print axioms HeavyEnergyBinSelection.exists_original_energy_bin
#print axioms OriginalFiberEnergyCollapse.translated_histogram_card
#print axioms OriginalFiberEnergyCollapse.original_filter_fiber_bound
#print axioms OriginalFiberEnergyCollapse.translated_histogram_bound
#print axioms OriginalFiberEnergyCollapse.translated_output_image
#print axioms OriginalFiberEnergyCollapse.labelled_sum_energy_le
#print axioms EnergyPreservingOriginalFiberBin.exists_energy_preserving_bin
#print axioms LabelledRealEnergyBin.labelled_near_energy_le_five
#print axioms LabelledRealEnergyBin.labelled_near_energy_cap
#print axioms LabelledRealEnergyBin.exists_real_energy_preserving_bin
#print axioms IntegerBinRealNearEnergy.real_grid_injective
#print axioms IntegerBinRealNearEnergy.real_grid_card
#print axioms IntegerBinRealNearEnergy.real_grid_separated
#print axioms IntegerBinRealNearEnergy.integer_energy_le_original_near
#print axioms OriginalRealEnergyBinCaller.exists_original_real_bsg_bin
#print axioms OriginalBinLabelLift.original_bin_lift
#print axioms OriginalBinLabelLift.original_bin_lift_density
#print axioms NativeA2DilatedParameters.dilated_geometric_scales
#print axioms NativeA2DilatedParameters.transverse_constant_power_identity
#print axioms NativeA2DilatedParameters.dilated_power_budget
#print axioms NativeA2DilatedParameters.exists_dilated_native_threshold
#print axioms NativeA2DilatedCaller.dilated_native_weak_radial_graph
#print axioms NativeA2DilatedCaller.exists_uniform_dilated_native_weak_radial_graph_threshold
#print axioms NativeA1InitialRadialGraph.exists_original_eta_dilated_radial_threshold
