import Theorems.Thm_StickyKakeya4_native_parent_spines
import Theorems.Thm_StickyKakeya4_native_contact_spine_columns
import Theorems.Thm_StickyKakeya4_native_contact_fractional_composition
import Theorems.Thm_StickyKakeya4_native_angular_chart_selection
import Theorems.Thm_StickyKakeya4_native_separated_fractional_patches
import Theorems.Thm_StickyKakeya4_real_scale_tube_profile_transfer
import Theorems.Thm_StickyKakeya4_original_w_successor_selection
import Theorems.Thm_StickyKakeya4_original_w_core_dynamics
import Theorems.Thm_StickyKakeya4_native_planar_slab_norm_conversion
import Theorems.Thm_StickyKakeya4_original_height_interval_cap
import Theorems.Thm_StickyKakeya4_original_w_physical_displacement
import Theorems.Thm_StickyKakeya4_original_w_physical_growth
import Theorems.Thm_StickyKakeya4_native_original_w_end_to_end
import Theorems.Thm_StickyKakeya4_retained_height_growth_normalization

#print axioms NativeParentSpines.owner_spec
#print axioms NativeParentSpines.mem_pairedMenu_of
#print axioms NativeParentSpines.pair_label_image_subset
#print axioms NativeParentSpines.pairedMenu_card_le
#print axioms NativeParentSpines.pair_label_menu_le
#print axioms NativeParentSpines.support_card_lower
#print axioms NativeParentSpines.original_cell_card_le
#print axioms NativeParentSpines.mass_le_original_grid_cells
#print axioms NativeParentSpines.fiber_parent_menu_le
#print axioms NativeParentSpines.unit_degree_eq_card
#print axioms NativeParentSpines.exists_uniform_parent_core
#print axioms NativeParentSpines.parentSpine_anchor
#print axioms NativeParentSpines.parentSpine_subset_owner
#print axioms NativeParentSpines.parentSpine_same_cell
#print axioms NativeParentSpines.parentSpine_point_richness
#print axioms NativeParentSpines.spine_power_cancellation
#print axioms NativeParentSpines.parent_power_cancellation
#print axioms NativeParentSpines.exists_parent_core
#print axioms NativeParentSpines.exists_native_parent_preparation
#print axioms NativeContactSpineColumns.same_cell_graph_residual
#print axioms NativeContactSpineColumns.tube_contact_residual
#print axioms NativeContactSpineColumns.contact_overlap_budget
#print axioms NativeContactSpineColumns.columns_from_coarse_contact_spines
#print axioms NativeContactSpineColumns.columns_from_fine_contact_spines
#print axioms NativeContactSpineColumns.columns_card_le_from_AD_contact_spines
#print axioms NativeContactFractionalComposition.exists_native_contact_fractional_refinement
#print axioms NativeAngularChartSelection.chart_unit
#print axioms NativeAngularChartSelection.chartPoint_zero
#print axioms NativeAngularChartSelection.chartPoint_involutive
#print axioms NativeAngularChartSelection.chartTube_involutive
#print axioms NativeAngularChartSelection.chartTube_unit_zero
#print axioms NativeAngularChartSelection.chartPoint_injective
#print axioms NativeAngularChartSelection.chartPoint_dist
#print axioms NativeAngularChartSelection.chart_carrierBall
#print axioms NativeAngularChartSelection.chart_AD
#print axioms NativeAngularChartSelection.chart_inTube_iff
#print axioms NativeAngularChartSelection.chart_grid
#print axioms NativeAngularChartSelection.chart_grid_card
#print axioms NativeAngularChartSelection.chart_trace
#print axioms NativeAngularChartSelection.chart_trace_inverse
#print axioms NativeAngularChartSelection.chart_footprints
#print axioms NativeAngularChartSelection.chart_profile
#print axioms NativeAngularChartSelection.chartSlope_bound
#print axioms NativeAngularChartSelection.exists_heavy_chart
#print axioms NativeAngularChartSelection.angleLabel_bounds
#print axioms NativeAngularChartSelection.angle_menu_card
#print axioms NativeAngularChartSelection.angularBudget_power
#print axioms NativeAngularChartSelection.angularResolution_pos
#print axioms NativeAngularChartSelection.workingLevel_mono
#print axioms NativeAngularChartSelection.workingLevel_bounds
#print axioms NativeAngularChartSelection.workingLevel_angle_scale
#print axioms NativeAngularChartSelection.selectedSlope_bound
#print axioms NativeAngularChartSelection.angleLabel_close
#print axioms NativeAngularChartSelection.grid_scale_ancestor
#print axioms NativeAngularChartSelection.grid_scale_nested
#print axioms NativeAngularChartSelection.uniform_cell_card
#print axioms NativeAngularChartSelection.uniform_joint_card
#print axioms NativeAngularChartSelection.select_parent_core_angles
#print axioms NativeAngularChartSelection.exists_native_chart_parent_preparation
#print axioms NativeSeparatedFractionalPatches.pairPoint_dist
#print axioms NativeSeparatedFractionalPatches.pairPoint_injective
#print axioms NativeSeparatedFractionalPatches.pairPoint_realized
#print axioms NativeSeparatedFractionalPatches.pairPoint_quantized
#print axioms NativeSeparatedFractionalPatches.quantized_coordinate_movement
#print axioms NativeSeparatedFractionalPatches.quantized_euclidean_movement
#print axioms NativeSeparatedFractionalPatches.exists_separated_source_residue
#print axioms NativeSeparatedFractionalPatches.quantized_image_proximity
#print axioms NativeSeparatedFractionalPatches.isolate_original_parent_patches
#print axioms NativeSeparatedFractionalPatches.exists_native_separated_fractional_refinement
#print axioms RealScaleTubeProfileTransfer.comparisonBox_card
#print axioms RealScaleTubeProfileTransfer.grid_mem_comparisonBox
#print axioms RealScaleTubeProfileTransfer.grid_card_comparison
#print axioms RealScaleTubeProfileTransfer.inTube_mono
#print axioms RealScaleTubeProfileTransfer.moved_real_tube_le_profile
#print axioms RealScaleTubeProfileTransfer.exists_minimal_upper_level
#print axioms RealScaleTubeProfileTransfer.exists_nested_upper_levels
#print axioms RealScaleTubeProfileTransfer.stopped_moved_real_tube
#print axioms RealScaleTubeProfileTransfer.shiftedBox_card
#print axioms RealScaleTubeProfileTransfer.shifted_grid_mem
#print axioms RealScaleTubeProfileTransfer.shifted_grid_card_le
#print axioms RealScaleTubeProfileTransfer.normalized_grid
#print axioms RealScaleTubeProfileTransfer.normalized_inTube
#print axioms RealScaleTubeProfileTransfer.normalized_stopped_moved_real_tube
#print axioms OriginalWSuccessorSelection.vertex_has_original_terminal_point
#print axioms OriginalWSuccessorSelection.exists_deterministic_original_successors
#print axioms OriginalWCoreDynamics.core_nonempty
#print axioms OriginalWCoreDynamics.rep_spec
#print axioms OriginalWCoreDynamics.originalNext_spec
#print axioms OriginalWCoreDynamics.next_eq_self_of_not_mem
#print axioms OriginalWCoreDynamics.next_spec
#print axioms OriginalWCoreDynamics.next_preserves_height
#print axioms OriginalWCoreDynamics.angles_nonempty
#print axioms OriginalWCoreDynamics.witness_menu_mem_alphabet
#print axioms OriginalWCoreDynamics.M_subset_alphabet
#print axioms OriginalWCoreDynamics.exists_original_core_dynamics
#print axioms OriginalWCoreDynamics.exists_original_total_core_dynamics
#print axioms NativePlanarSlabNormConversion.apply_eq_coordinates
#print axioms NativePlanarSlabNormConversion.opNorm_le_abs_coefficients
#print axioms NativePlanarSlabNormConversion.coefficientLength_ge_half
#print axioms NativePlanarSlabNormConversion.normalized_coefficients_unit
#print axioms NativePlanarSlabNormConversion.functional_slab_subset
#print axioms NativePlanarSlabNormConversion.slab_law_conversion
#print axioms NativePlanarSlabNormConversion.coefficientLength_pos
#print axioms OriginalHeightIntervalCap.floor_original_mesh
#print axioms OriginalHeightIntervalCap.original_floor_injective
#print axioms OriginalHeightIntervalCap.floor_interval_card
#print axioms OriginalHeightIntervalCap.original_interval_cap_add_two
#print axioms OriginalHeightIntervalCap.original_interval_cap
#print axioms OriginalHeightIntervalCap.density_ratio
#print axioms OriginalHeightIntervalCap.original_height_cap_and_ratio
#print axioms OriginalWPhysicalDisplacement.incidence_chord_error
#print axioms OriginalWPhysicalDisplacement.path_residual_bound
#print axioms OriginalWPhysicalDisplacement.witness_two_leg_residual
#print axioms OriginalWPhysicalDisplacement.difference_approximation_bound
#print axioms OriginalWPhysicalDisplacement.witness_coarse_displacement
#print axioms OriginalWPhysicalDisplacement.same_tube_same_height_error
#print axioms OriginalWPhysicalDisplacement.fixed_representative_displacement
#print axioms OriginalWPhysicalDisplacement.floor_approximation
#print axioms OriginalWPhysicalDisplacement.scalar_grid_approximation
#print axioms OriginalWPhysicalDisplacement.planar_grid_approximation
#print axioms OriginalWPhysicalDisplacement.terminal_grid_component_gap
#print axioms OriginalWPhysicalDisplacement.scalar_terminal_grid_gap
#print axioms OriginalWPhysicalDisplacement.planar_terminal_grid_gap
#print axioms OriginalWPhysicalDisplacement.witness_time_gaps
#print axioms OriginalWPhysicalDisplacement.scalar_native_witness_displacement
#print axioms OriginalWPhysicalDisplacement.planar_native_witness_displacement
#print axioms OriginalWPhysicalGrowth.scalar_constructed_step_displacement
#print axioms OriginalWPhysicalGrowth.planar_constructed_step_displacement
#print axioms OriginalWPhysicalGrowth.original_heights_nonempty
#print axioms OriginalWPhysicalGrowth.scalar_growth_of_constructed_core
#print axioms OriginalWPhysicalGrowth.planar_decoded_alphabet_bound
#print axioms OriginalWPhysicalGrowth.planar_growth_of_constructed_core
#print axioms OriginalWPhysicalGrowth.normalize_original_escape
#print axioms NativeOriginalWEndToEnd.scalar_unit_functional_slab
#print axioms NativeOriginalWEndToEnd.scalar_original_w_growth
#print axioms NativeOriginalWEndToEnd.planar_original_w_growth
#print axioms RetainedHeightGrowthNormalization.scalar_normalized_growth
#print axioms RetainedHeightGrowthNormalization.scalar_output_lower_bound
#print axioms RetainedHeightGrowthNormalization.planar_normalized_growth
#print axioms RetainedHeightGrowthNormalization.planar_output_lower_bound
