import Theorems.Thm_StickyKakeya4_native_phase_height_key
import Theorems.Thm_StickyKakeya4_native_configured_slice_occupancy
import Theorems.Thm_StickyKakeya4_native_fixed_height_pair_cap
import Theorems.Thm_StickyKakeya4_native_matched_shadow_configured_counts
import Theorems.Thm_StickyKakeya4_native_actual_fine_weight_shading_bridge
set_option autoImplicit false
#print axioms NativePhaseHeightKey.originalKey
#print axioms NativePhaseHeightKey.constant_on_pair
#print axioms NativePhaseHeightKey.old_height_card_eq_physical
#print axioms NativePhaseHeightKey.onPair
#print axioms NativePhaseHeightKey.onPair_readback
#print axioms NativeConfiguredSliceOccupancy.height_first_dist
#print axioms NativeConfiguredSliceOccupancy.pointsAt_card_le
#print axioms NativeConfiguredSliceOccupancy.full_source_pointsAt
#print axioms NativeFixedHeightPairCap.same_height_card_le
#print axioms NativeFixedHeightPairCap.full_source_old_slope_cube
#print axioms NativeFixedHeightPairCap.full_source_old_parent_height_fiber
#print axioms NativeFixedHeightPairCap.same_reference_old_parent_height_fiber
#print axioms NativeMatchedShadowConfiguredCounts.separated_ball_card
#print axioms NativeMatchedShadowConfiguredCounts.shadowLabel
#print axioms NativeMatchedShadowConfiguredCounts.inverse_point_fiber
#print axioms NativeMatchedShadowConfiguredCounts.forward_point_fiber
#print axioms NativeMatchedShadowConfiguredCounts.pair_fiber_bound
#print axioms NativeMatchedShadowConfiguredCounts.inverse_image_bounds
#print axioms NativeMatchedShadowConfiguredCounts.image_bounds
#print axioms NativeActualFineWeightShadingBridge.pair_capacity_to_shading
#print axioms NativeActualFineWeightShadingBridge.fine_graph_le_shadow
#print axioms NativeActualFineWeightShadingBridge.same_Q_weight_shading
#print axioms NativeActualFineWeightShadingBridge.actual_weight_upper
