import Theorems.Thm_StickyKakeya4_native_prescribed_final_configuration

#print axioms NativePrescribedFinalConfiguration.HasPrescribedFinalRetainedHistory
#print axioms NativePrescribedFinalConfiguration.HasPrescribedFinalStage
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_of_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_of_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_history
#print axioms NativePrescribedFinalConfiguration.exists_prescribed_final_configuration
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_forget
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_forget
