import Theorems.Thm_StickyKakeya4_native_actual_quotient_ad
import Theorems.Thm_StickyKakeya4_native_actual_sharp_X_power
import Theorems.Thm_StickyKakeya4_native_angular_rank_contradiction
import Theorems.Thm_StickyKakeya4_native_angular_test_scale
import Theorems.Thm_StickyKakeya4_native_angular_test_source_window
import Theorems.Thm_StickyKakeya4_native_bounded_reference_relative_upper
import Theorems.Thm_StickyKakeya4_native_quotient_constant_bound
import Theorems.Thm_StickyKakeya4_native_reference_relative_menu
import Theorems.Thm_StickyKakeya4_native_scheduled_angular_ancestor
import Theorems.Thm_StickyKakeya4_native_sharp_X_budget_power
import Theorems.Thm_StickyKakeya4_native_sharp_X_history_power

set_option autoImplicit false
#print axioms NativeActualQuotientAD.of_reference_cross
#print axioms NativeActualSharpXPower.source_reference_X_power_lower
#print axioms NativeAngularRankContradiction.angular_count_cancellation
#print axioms NativeAngularRankContradiction.exists_original_scale_cutoff
#print axioms NativeAngularRankContradiction.incompatible_rank_two_counts
#print axioms NativeAngularRankContradiction.rank_gain_survives
#print axioms NativeAngularTestScale.exists_actual_test_scale
#print axioms NativeAngularTestScale.exists_dyadic_angular_scale
#print axioms NativeAngularTestSourceWindow.exists_original_test_cutoff
#print axioms NativeAngularTestSourceWindow.original_angular_depth_window
#print axioms NativeBoundedReferenceRelativeUpper.exists_bounded_reference_engine
#print axioms NativeQuotientConstantBound.quotientConstant_le
#print axioms NativeReferenceRelativeMenu.caller_uniformities
#print axioms NativeReferenceRelativeMenu.relation_count
#print axioms NativeReferenceRelativeMenu.relations
#print axioms NativeReferenceRelativeMenu.relations_refl
#print axioms NativeReferenceRelativeMenu.relations_symm
#print axioms NativeScheduledAngularAncestor.exists_actual_angular_ancestor
#print axioms NativeScheduledAngularAncestor.formal_uniformity_readback
#print axioms NativeSharpXBudgetPower.baseConstant
#print axioms NativeSharpXBudgetPower.baseConstant_nonneg
#print axioms NativeSharpXBudgetPower.fiber_coefficient_rank_bound
#print axioms NativeSharpXBudgetPower.rank_bound_to_scale
#print axioms NativeSharpXBudgetPower.sourceConstant
#print axioms NativeSharpXBudgetPower.sourceConstant_one_le
#print axioms NativeSharpXBudgetPower.squared_scale_power
#print axioms NativeSharpXHistoryPower.actual_time_count
#print axioms NativeSharpXHistoryPower.history_power_to_X
