import Theorems.Thm_StickyKakeya4_native_middle_grain_parent_budget

#print axioms NativeMiddleGrainParentBudget.middleIndex
#print axioms NativeMiddleGrainParentBudget.middleDepth
#print axioms NativeMiddleGrainParentBudget.grainDepth_middle
#print axioms NativeMiddleGrainParentBudget.middle_depth_bounds
#print axioms NativeMiddleGrainParentBudget.middle_query_readback
#print axioms NativeMiddleGrainParentBudget.middle_scale_bounds
#print axioms NativeMiddleGrainParentBudget.middle_scale_root_bound
#print axioms NativeMiddleGrainParentBudget.normalizedError
#print axioms NativeMiddleGrainParentBudget.normalized_error_le_scale
#print axioms NativeMiddleGrainParentBudget.actual_test_radius_lower
#print axioms NativeMiddleGrainParentBudget.coefficient_power_bound
#print axioms NativeMiddleGrainParentBudget.errorConstant
#print axioms NativeMiddleGrainParentBudget.normalized_error_power
#print axioms NativeMiddleGrainParentBudget.exists_uniform_cutoff
#print axioms NativeMiddleGrainParentBudget.absorb_error_constant
#print axioms NativeMiddleGrainParentBudget.actual_middle_error
#print axioms NativeMiddleGrainParentBudget.parent_direction_from_error
#print axioms NativeMiddleGrainParentBudget.actual_middle_parent_direction
