import Theorems.Thm_StickyKakeya4_native_actual_compatible_configuration
import Theorems.Thm_StickyKakeya4_native_tagged_node_vertex_count
import Theorems.Thm_StickyKakeya4_native_actual_rich_packet_layers

set_option autoImplicit false
#print axioms NativeActualCompatibleConfiguration.HasCompatibleSquaredStage
#print axioms NativeActualCompatibleConfiguration.exists_actual_compatible_configuration
#print axioms NativeActualCompatibleConfiguration.pairedCount
#print axioms NativeActualCompatibleConfiguration.pairedCount_eq
#print axioms NativeActualRichPacketLayers.computed_reference_budget_le
#print axioms NativeActualRichPacketLayers.construct_rich_packet_layers
#print axioms NativeActualRichPacketLayers.original_point_mass_positive
#print axioms NativeActualRichPacketLayers.packetMass_eq_of_subset
#print axioms NativeActualRichPacketLayers.packet_overlap_le
#print axioms NativeActualRichPacketLayers.real_le_referenceMinimum
#print axioms NativeActualRichPacketLayers.referenceConstant
#print axioms NativeActualRichPacketLayers.referenceConstant_pos
#print axioms NativeActualRichPacketLayers.threshold_ratio_lower
#print axioms NativeTaggedNodeVertexCount.current_nodes_disjoint
#print axioms NativeTaggedNodeVertexCount.current_tag_node
#print axioms NativeTaggedNodeVertexCount.layers_vertices_sum_le
#print axioms NativeTaggedNodeVertexCount.sum_current_vertices_le
#print axioms NativeTaggedNodeVertexCount.vertex_ancestor
