import Theorems.Thm_StickyKakeya4_native_parent_slice_caller_menu

#print axioms NativeParentSliceCallerMenu.pointLabel
#print axioms NativeParentSliceCallerMenu.classLabel
#print axioms NativeParentSliceCallerMenu.relations
#print axioms NativeParentSliceCallerMenu.relations_refl
#print axioms NativeParentSliceCallerMenu.relations_symm
#print axioms NativeParentSliceCallerMenu.parent_uniformities
#print axioms NativeParentSliceCallerMenu.parent_occupied_class_counts
