import Theorems.Thm_StickyKakeya4_native_actual_configured_residue
import Theorems.Thm_StickyKakeya4_native_configured_third_relation
set_option autoImplicit false
#print axioms NativeActualConfiguredResidue.parameter
#print axioms NativeActualConfiguredResidue.parameter_height
#print axioms NativeActualConfiguredResidue.parameterX_eq_coarse
#print axioms NativeActualConfiguredResidue.parameterY_eq_recoded
#print axioms NativeActualConfiguredResidue.parameterY_of_frozen
#print axioms NativeActualConfiguredResidue.graphGrid_eq
#print axioms NativeActualConfiguredResidue.graphGrid_eq_iff_parameter
#print axioms NativeActualConfiguredResidue.graphGrid_eq_iff_keys
#print axioms NativeActualConfiguredResidue.select_actual_edges
#print axioms NativeConfiguredThirdRelation.coarseYKey
#print axioms NativeConfiguredThirdRelation.coarseYKey_of_frozen
#print axioms NativeConfiguredThirdRelation.geometricPairKey
#print axioms NativeConfiguredThirdRelation.relations
#print axioms NativeConfiguredThirdRelation.relations_refl
#print axioms NativeConfiguredThirdRelation.relations_symm
#print axioms NativeConfiguredThirdRelation.caller_coarseY_uniformity
#print axioms NativeConfiguredThirdRelation.completeRelations
#print axioms NativeConfiguredThirdRelation.completeRelations_refl
#print axioms NativeConfiguredThirdRelation.completeRelations_symm
#print axioms NativeConfiguredThirdRelation.caller_geometricPair_uniformity
#print axioms NativeConfiguredThirdRelation.caller_configuredPoint_uniformity
