import Theorems.Thm_StickyKakeya4_native_sharp_population_parent_configuration

#print axioms NativeSharpPopulationParentConfiguration.SharpParentFinalCleanupData
#print axioms NativeSharpPopulationParentConfiguration.HasSharpParentRetainedHistory
#print axioms NativeSharpPopulationParentConfiguration.HasSharpPopulationParentStage
#print axioms NativeSharpPopulationParentConfiguration.sharp_stage_with_population_parent
#print axioms NativeSharpPopulationParentConfiguration.exists_sharp_population_parent_configuration
