import Theorems.Thm_StickyKakeya4_native_saturated_population_parent_configuration

#print axioms NativeSaturatedPopulationParentConfiguration.SaturatedParentFinalCleanupData
#print axioms NativeSaturatedPopulationParentConfiguration.HasSaturatedParentRetainedHistory
#print axioms NativeSaturatedPopulationParentConfiguration.HasSaturatedPopulationParentStage
#print axioms NativeSaturatedPopulationParentConfiguration.saturated_stage_with_population_parent
#print axioms NativeSaturatedPopulationParentConfiguration.exists_saturated_population_parent_configuration
