import Theorems.Thm_StickyKakeya4_native_generic_final_history
import Theorems.Thm_StickyKakeya4_native_generic_parent_graph
import Theorems.Thm_StickyKakeya4_native_generic_parent_menu
import Theorems.Thm_StickyKakeya4_native_generic_prescribed_history
import Theorems.Thm_StickyKakeya4_native_generic_saturated_parent
import Theorems.Thm_StickyKakeya4_native_physical_reference_data
import Theorems.Thm_StickyKakeya4_native_third_XY_fixed_budget

set_option autoImplicit false
#print axioms NativeGenericFinalHistory.HasPrescribedFinalStage
#print axioms NativeGenericFinalHistory.prescribed_final_stage_history
#print axioms NativeGenericFinalHistory.prescribed_final_stage_of_history
#print axioms NativeGenericParentGraph.HasSaturatedCurveParentRetainedHistory
#print axioms NativeGenericParentGraph.HasSaturatedCurveParentStage
#print axioms NativeGenericParentGraph.SaturatedCurveParentFinalCleanupData
#print axioms NativeGenericParentGraph.half_depth_eq_depth
#print axioms NativeGenericParentGraph.middleSelected
#print axioms NativeGenericParentGraph.middle_selected_depth
#print axioms NativeGenericParentGraph.saturated_stage_with_parent_graph
#print axioms NativeGenericParentMenu.HasPrescribedHorizontalStage
#print axioms NativeGenericParentMenu.callerRelations
#print axioms NativeGenericParentMenu.prescribed_stage_with_horizontal_menu
#print axioms NativeGenericPrescribedHistory.HasPrescribedHistoryStage
#print axioms NativeGenericPrescribedHistory.prescribed_history_stage_of_compatible
#print axioms NativeGenericSaturatedParent.HasSaturatedParentRetainedHistory
#print axioms NativeGenericSaturatedParent.HasSaturatedPopulationParentStage
#print axioms NativeGenericSaturatedParent.SaturatedParentFinalCleanupData
#print axioms NativeGenericSaturatedParent.saturated_stage_with_population_parent
#print axioms NativePhysicalReferenceData.HasPhysicalUniformities
#print axioms NativePhysicalReferenceData.retained_scheduled_upper
#print axioms NativePhysicalReferenceData.squared_raw_ratio_of_middle
#print axioms NativeThirdXYFixedBudget.exists_source_cutoff
#print axioms NativeThirdXYFixedBudget.fixedCost
#print axioms NativeThirdXYFixedBudget.fixedCost_one_le
#print axioms NativeThirdXYFixedBudget.pay_XY_and_quotient_constants
#print axioms NativeThirdXYFixedBudget.sourceCutoff
#print axioms NativeThirdXYFixedBudget.sourceCutoff_le_one
#print axioms NativeThirdXYFixedBudget.sourceCutoff_pays
#print axioms NativeThirdXYFixedBudget.sourceCutoff_pos
