import Theorems.Thm_StickyKakeya4_native_coarse_source_parent_readback
import Theorems.Thm_StickyKakeya4_native_intermediate_parent_population
import Theorems.Thm_StickyKakeya4_native_matched_shadow_configured_geometry
import Theorems.Thm_StickyKakeya4_native_matched_height_bound
set_option autoImplicit false
#print axioms NativeCoarseSourceParentReadback.contracted_line_eq_local_one
#print axioms NativeCoarseSourceParentReadback.shiftedIntercept_zero
#print axioms NativeCoarseSourceParentReadback.zeroProjection
#print axioms NativeCoarseSourceParentReadback.projection_zero
#print axioms NativeCoarseSourceParentReadback.source_parentLabel_relative
#print axioms NativeCoarseSourceParentReadback.source_parentLabel
#print axioms NativeCoarseSourceParentReadback.parent_fiber_old_labels
#print axioms NativeCoarseSourceParentReadback.parent_image
#print axioms NativeIntermediateParentPopulation.parent_from_ancestor
#print axioms NativeIntermediateParentPopulation.old_fiber_card_le_current
#print axioms NativeIntermediateParentPopulation.intermediate_dyadic
#print axioms NativeIntermediateParentPopulation.actual_population_lower
#print axioms NativeIntermediateParentPopulation.actual_population_upper
#print axioms NativeIntermediateParentPopulation.intermediateCells
#print axioms NativeIntermediateParentPopulation.intermediate_common_mesh
#print axioms NativeIntermediateParentPopulation.intermediate_common_height
#print axioms NativeIntermediateParentPopulation.second_source_AD
#print axioms NativeIntermediateParentPopulation.second_source_CW
#print axioms NativeIntermediateParentPopulation.second_source_geometry
#print axioms NativeIntermediateParentPopulation.second_parent_normalized_count
#print axioms NativeIntermediateParentPopulation.second_source_density_from_count
#print axioms NativeMatchedShadowConfiguredGeometry.distance_of_coordinates
#print axioms NativeMatchedShadowConfiguredGeometry.point_front_distance
#print axioms NativeMatchedShadowConfiguredGeometry.point_shadow_center_distance
#print axioms NativeMatchedHeightBound.point_time_bound
#print axioms NativeMatchedHeightBound.baseline_height_bound
