import Theorems.Thm_StickyKakeya4_native_projector_graph_map
import Theorems.Thm_StickyKakeya4_native_selected_horizontal_graph_chart
import Theorems.Thm_StickyKakeya4_native_weighted_height_node_selection

set_option autoImplicit false
#print axioms NativeProjectorGraphMap.graphMap
#print axioms NativeProjectorGraphMap.graphMap_characterization
#print axioms NativeProjectorGraphMap.graphMap_decomposition
#print axioms NativeProjectorGraphMap.graphMap_horizontal
#print axioms NativeProjectorGraphMap.graphMap_norm
#print axioms NativeProjectorGraphMap.graphMap_val
#print axioms NativeProjectorGraphMap.graphMap_variation
#print axioms NativeProjectorGraphMap.inverse_norm
#print axioms NativeProjectorGraphMap.inverse_projection
#print axioms NativeProjectorGraphMap.projectionEquiv
#print axioms NativeProjectorGraphMap.projectionEquiv_apply
#print axioms NativeProjectorGraphMap.projectionMap
#print axioms NativeProjectorGraphMap.projectionMap_bijective
#print axioms NativeSelectedHorizontalGraphChart.select_horizontal_graph_chart
#print axioms NativeSelectedHorizontalGraphChart.totalGraph
#print axioms NativeSelectedHorizontalGraphChart.totalGraph_characterization
#print axioms NativeSelectedHorizontalGraphChart.totalGraph_eq
#print axioms NativeSelectedHorizontalGraphChart.totalGraph_horizontal
#print axioms NativeSelectedHorizontalGraphChart.totalGraph_norm
#print axioms NativeSelectedHorizontalGraphChart.totalGraph_variation
#print axioms NativeWeightedHeightNodeSelection.cutByNodes
#print axioms NativeWeightedHeightNodeSelection.mem_cutByNodes
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_fiber_eq
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_label_fiber_eq
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_weight_eq
#print axioms NativeWeightedHeightNodeSelection.weighted_height_node_selection
#print axioms NativeWeightedHeightNodeSelection.weighted_height_node_selection_nonempty
