import Theorems.Thm_StickyKakeya4_native_translated_grain_height_overlap

#print axioms NativeTranslatedGrainHeightOverlap.floor_shift_carry
#print axioms NativeTranslatedGrainHeightOverlap.two_integer_card
#print axioms NativeTranslatedGrainHeightOverlap.raw_cell_translated_card
#print axioms NativeTranslatedGrainHeightOverlap.translated_cell_raw_card
#print axioms NativeTranslatedGrainHeightOverlap.rawHeight
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight
#print axioms NativeTranslatedGrainHeightOverlap.rawHeight_readback
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight_readback
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight_column
#print axioms NativeTranslatedGrainHeightOverlap.actual_raw_cell_card
#print axioms NativeTranslatedGrainHeightOverlap.actual_translated_cell_card
#print axioms NativeTranslatedGrainHeightOverlap.floor_shift_distance
#print axioms NativeTranslatedGrainHeightOverlap.actual_height_distance
#print axioms NativeTranslatedGrainHeightOverlap.actual_height_metric
