import Theorems.Thm_StickyKakeya4_native_remembered_source_mass_construction
set_option autoImplicit false
#print axioms NativeActualPhaseHeightPopulation.actual_full_phase_card
#print axioms NativeActualPhaseHeightPopulation.relative_parent_mem_full
#print axioms NativeActualMassiveOldPhase.image_card_le_sum_fiber_images
#print axioms NativeActualMassiveOldPhase.graph_filter_relative_phase
#print axioms NativeActualMassiveOldPhase.from_original_reference_same_Q
#print axioms NativeRememberedSourceShading.count_to_mass
#print axioms NativeRememberedSourceShading.select_height_and_shading
#print axioms NativeRememberedSourceRealization.phaseConstant
#print axioms NativeRememberedSourceRealization.massive_phase_payment
#print axioms NativeRememberedSourceRealization.power_payment
#print axioms NativeRememberedSourceRealization.exists_same_Q_source
