import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_source

#print axioms NativeReferenceSliceBudgetSource.actualConstant
#print axioms NativeReferenceSliceBudgetSource.actual_reference_constant_bound
