import Theorems.Thm_StickyKakeya4_native_lipschitz_coarse_height_selection
set_option autoImplicit false
#print axioms NativeLipschitzCoarseHeightSelection.subdivisions
#print axioms NativeLipschitzCoarseHeightSelection.subdivisions_bounds
#print axioms NativeLipschitzCoarseHeightSelection.coarse
#print axioms NativeLipschitzCoarseHeightSelection.fine
#print axioms NativeLipschitzCoarseHeightSelection.center
#print axioms NativeLipschitzCoarseHeightSelection.coarse_eq_fine_div
#print axioms NativeLipschitzCoarseHeightSelection.paint
#print axioms NativeLipschitzCoarseHeightSelection.same_coarse_same_fine
#print axioms NativeLipschitzCoarseHeightSelection.coarse_color_eq
#print axioms NativeLipschitzCoarseHeightSelection.center_close
#print axioms NativeLipschitzCoarseHeightSelection.center_distance
#print axioms NativeLipschitzCoarseHeightSelection.colored_height_distance
#print axioms NativeLipschitzCoarseHeightSelection.selectedField
#print axioms NativeLipschitzCoarseHeightSelection.select_weighted_coarse_field
