import Theorems.Thm_StickyKakeya4_native_joint_xy_support_count
import Theorems.Thm_StickyKakeya4_native_joint_local_xy_geometry
import Theorems.Thm_StickyKakeya4_native_actual_baseline_graph_mass
import Theorems.Thm_StickyKakeya4_native_configured_Y_weighted_retention
import Theorems.Thm_StickyKakeya4_native_original_shading_restriction
import Theorems.Thm_StickyKakeya4_native_original_cell_presentation_unique
set_option autoImplicit false
#print axioms NativeJointXYSupportCount.encoded_realized_bound
#print axioms NativeJointXYSupportCount.source_realized_box
#print axioms NativeJointXYSupportCount.realized_coarse_label
#print axioms NativeJointXYSupportCount.coarse_xy_image_card
#print axioms NativeJointXYSupportCount.source_height_physical_card
#print axioms NativeJointXYSupportCount.source_height_base_keys_global
#print axioms NativeJointLocalXYGeometry.scalar_center_gap
#print axioms NativeJointLocalXYGeometry.base_XY_footprint
#print axioms NativeJointLocalXYGeometry.base_center_readback
#print axioms NativeJointLocalXYGeometry.source_height_cell_base_keys
#print axioms NativeActualBaselineGraphMass.of_admitted_core
#print axioms NativeActualBaselineGraphMass.exists_actual_baseline_mass
#print axioms NativeConfiguredYWeightedRetention.uniform_subset_retention
#print axioms NativeConfiguredYWeightedRetention.select_literal_Y
#print axioms NativeConfiguredYWeightedRetention.from_source_data
#print axioms NativeOriginalShadingRestriction.source
#print axioms NativeOriginalShadingRestriction.shading_subset
#print axioms NativeOriginalShadingRestriction.total_shading
#print axioms NativeOriginalShadingRestriction.union_subset
#print axioms NativeOriginalShadingRestriction.mass_retention
#print axioms NativeOriginalShadingRestriction.native_input
#print axioms NativeOriginalShadingRestriction.multiplicity_retention
#print axioms NativeOriginalCellPresentationUnique.mem_cells_iff_center_mem
#print axioms NativeOriginalCellPresentationUnique.cells_eq_of_shading_eq
#print axioms NativeOriginalCellPresentationUnique.restricted_cells_eq
#print axioms NativeOriginalCellPresentationUnique.restricted_incidences_eq
#print axioms NativeOriginalCellPresentationUnique.subset_original_cut
#print axioms NativeOriginalCellPresentationUnique.core_subset_original_cut
#print axioms NativeOriginalCellPresentationUnique.core_preserves_original_predicate
