import Theorems.Thm_StickyKakeya4_native_actual_retained_rank_configuration
import Theorems.Thm_StickyKakeya4_native_approximate_fiber_iteration
import Theorems.Thm_StickyKakeya4_native_refined_row_relations
import Theorems.Thm_StickyKakeya4_native_spatial_shadow_point_menu

set_option autoImplicit false
#print axioms NativeActualRetainedRankConfiguration.HasSecondStageCore
#print axioms NativeActualRetainedRankConfiguration.exists_actual_retained_rank_configuration
#print axioms NativeApproximateFiberIteration.directionAt
#print axioms NativeApproximateFiberIteration.directionAt_eq
#print axioms NativeApproximateFiberIteration.fiber_mono_radius
#print axioms NativeApproximateFiberIteration.full_lower_bound
#print axioms NativeApproximateFiberIteration.iterated_count
#print axioms NativeApproximateFiberIteration.iterated_lower_bound
#print axioms NativeApproximateFiberIteration.le_radius
#print axioms NativeApproximateFiberIteration.overlap
#print axioms NativeApproximateFiberIteration.overlap_le_common
#print axioms NativeApproximateFiberIteration.predecessorMinimum
#print axioms NativeApproximateFiberIteration.radius
#print axioms NativeApproximateFiberIteration.radius_pos
#print axioms NativeApproximateFiberIteration.radius_succ
#print axioms NativeRefinedRowRelations.exists_refined_row_core
#print axioms NativeRefinedRowRelations.rowPair
#print axioms NativeRefinedRowRelations.rowRelationMenu
#print axioms NativeRefinedRowRelations.rowRelationMenu_old
#print axioms NativeRefinedRowRelations.rowRelationMenu_refl
#print axioms NativeRefinedRowRelations.rowRelationMenu_symm
#print axioms NativeRefinedRowRelations.rowRelationMenu_uniformities
#print axioms NativeSpatialShadowPointMenu.cellIndex_mem_box
#print axioms NativeSpatialShadowPointMenu.physical_cube_close
#print axioms NativeSpatialShadowPointMenu.spatial_point_image_card
