import Theorems.Thm_StickyKakeya4_native_XY_pre_loss_budget
import Theorems.Thm_StickyKakeya4_native_actual_XY_budget_allowance
import Theorems.Thm_StickyKakeya4_native_actual_XY_budget_source
import Theorems.Thm_StickyKakeya4_native_actual_post_graph_XY_hook
import Theorems.Thm_StickyKakeya4_native_angular_dyadic_interpolation
import Theorems.Thm_StickyKakeya4_native_candidate_XY_configuration
import Theorems.Thm_StickyKakeya4_native_conditional_reference_angular_upper
import Theorems.Thm_StickyKakeya4_native_conditional_reference_menu
import Theorems.Thm_StickyKakeya4_native_extra_XY_configuration
import Theorems.Thm_StickyKakeya4_native_generic_XY_rank
import Theorems.Thm_StickyKakeya4_native_post_graph_XY_hook_data
import Theorems.Thm_StickyKakeya4_native_post_graph_XY_hook_stage
import Theorems.Thm_StickyKakeya4_native_post_graph_XY_stage
import Theorems.Thm_StickyKakeya4_native_same_source_angular_ball_upper
import Theorems.Thm_StickyKakeya4_native_supported_two_map_ad
import Theorems.Thm_StickyKakeya4_native_supported_two_map_transfer
import Theorems.Thm_StickyKakeya4_native_supported_two_map_upper
import Theorems.Thm_StickyKakeya4_native_variable_height_counts_upper
import Theorems.Thm_StickyKakeya4_native_variable_height_geometry
import Theorems.Thm_StickyKakeya4_native_variable_height_population
import Theorems.Thm_StickyKakeya4_native_window_XY_labels
import Theorems.Thm_StickyKakeya4_native_window_XY_metric
import Theorems.Thm_StickyKakeya4_native_window_XY_reference_maps

set_option autoImplicit false
#print axioms NativeActualPostGraphXYHook.attach_actual_post_graph_XY
#print axioms NativeActualXYBudgetAllowance.exists_actual_native_XY_budget_with_raw
#print axioms NativeActualXYBudgetSource.exists_actual_native_XY_budget
#print axioms NativeAngularDyadicInterpolation.angular_ancestor
#print axioms NativeAngularDyadicInterpolation.angular_fiber_card
#print axioms NativeAngularDyadicInterpolation.angular_image_interpolation
#print axioms NativeAngularDyadicInterpolation.bottom_angular_interpolation
#print axioms NativeAngularDyadicInterpolation.descendants
#print axioms NativeAngularDyadicInterpolation.descendants_card
#print axioms NativeAngularDyadicInterpolation.mem_descendants
#print axioms NativeAngularDyadicInterpolation.physical_ancestor
#print axioms NativeCandidateXYConfiguration.exists_candidate_XY_configuration
#print axioms NativeConditionalReferenceAngularUpper.exists_reference_angular_ball_upper
#print axioms NativeConditionalReferenceMenu.candidate
#print axioms NativeConditionalReferenceMenu.factory
#print axioms NativeConditionalReferenceMenu.factory_refl
#print axioms NativeConditionalReferenceMenu.factory_symm
#print axioms NativeConditionalReferenceMenu.gridDepth
#print axioms NativeConditionalReferenceMenu.gridDepth_bounds
#print axioms NativeConditionalReferenceMenu.outerDepth
#print axioms NativeConditionalReferenceMenu.pair
#print axioms NativeConditionalReferenceMenu.parentDepth
#print axioms NativeConditionalReferenceMenu.queryCount
#print axioms NativeConditionalReferenceMenu.query_bounds
#print axioms NativeConditionalReferenceMenu.query_phase_depth
#print axioms NativeConditionalReferenceMenu.reference_uniformities
#print axioms NativeConditionalReferenceMenu.relationCount
#print axioms NativeConditionalReferenceMenu.relation_count
#print axioms NativeConditionalReferenceMenu.relativeScales
#print axioms NativeConditionalReferenceMenu.rhoDepth
#print axioms NativeConditionalReferenceMenu.sigmaDepth
#print axioms NativeExtraXYConfiguration.exists_extra_XY_configuration
#print axioms NativeGenericXYRank.HasXYRankSelection
#print axioms NativeGenericXYRank.xy_rank_of_graph
#print axioms NativePostGraphXYHookData.HasThirdXYFinish
#print axioms NativePostGraphXYHookData.HasXYParentProfiles
#print axioms NativePostGraphXYHookStage.HasXYRetainedHistory
#print axioms NativePostGraphXYHookStage.HasXYStage
#print axioms NativePostGraphXYHookStage.XYCleanupData
#print axioms NativePostGraphXYHookStage.stage_with_post_graph_XY
#print axioms NativePostGraphXYStage.HasXYRetainedHistory
#print axioms NativePostGraphXYStage.HasXYStage
#print axioms NativePostGraphXYStage.XYCleanupData
#print axioms NativePostGraphXYStage.stage_with_post_graph_XY
#print axioms NativeSameSourceAngularBallUpper.exists_angular_ball_upper
#print axioms NativeSupportedTwoMapAD.all_radius_bounds
#print axioms NativeSupportedTwoMapTransfer.coarse_image_count_le
#print axioms NativeSupportedTwoMapTransfer.retained_class_count_cross
#print axioms NativeSupportedTwoMapTransfer.retained_class_count_lower
#print axioms NativeSupportedTwoMapUpper.height_image_cap
#print axioms NativeSupportedTwoMapUpper.retained_class_upper
#print axioms NativeVariableHeightCountsUpper.column_point_image_card_le
#print axioms NativeVariableHeightCountsUpper.pair_image_card_le_columns
#print axioms NativeVariableHeightCountsUpper.parent_counts_upper
#print axioms NativeVariableHeightCountsUpper.point_image_card_le_columns
#print axioms NativeVariableHeightGeometry.short_row_chart_close
#print axioms NativeVariableHeightGeometry.short_row_column_mem_halo
#print axioms NativeVariableHeightPopulation.columnPair
#print axioms NativeVariableHeightPopulation.column_height_image
#print axioms NativeVariableHeightPopulation.column_phase_height_image
#print axioms NativeVariableHeightPopulation.height_population_upper
#print axioms NativeVariableHeightPopulation.height_population_upper_eight
#print axioms NativeVariableHeightPopulation.parent_height_population
#print axioms NativeVariableHeightPopulation.phase_height_population
#print axioms NativeVariableHeightPopulation.reference_numerator_lower
#print axioms NativeWindowXYLabels.encode_window_coarse
#print axioms NativeWindowXYLabels.gridDiv
#print axioms NativeWindowXYLabels.gridDiv_comp
#print axioms NativeWindowXYLabels.window
#print axioms NativeWindowXYLabels.window_coarse
#print axioms NativeWindowXYLabels.window_comp
#print axioms NativeWindowXYLabels.window_height
#print axioms NativeWindowXYMetric.field_window_variation
#print axioms NativeWindowXYMetric.menuRadius
#print axioms NativeWindowXYMetric.menuRadius_lower
#print axioms NativeWindowXYMetric.menu_cost_upper
#print axioms NativeWindowXYMetric.old_dist_of_window_coordinates
#print axioms NativeWindowXYMetric.old_height_window
#print axioms NativeWindowXYMetric.raw_dist_of_window_pref
#print axioms NativeWindowXYMetric.raw_height_window
#print axioms NativeWindowXYReferenceMaps.dyadic_height_width
#print axioms NativeWindowXYReferenceMaps.dyadic_scale_mul
#print axioms NativeWindowXYReferenceMaps.reference_height_window
#print axioms NativeWindowXYReferenceMaps.same_integer_window
#print axioms NativeWindowXYReferenceMaps.scheduled_reference_readback
#print axioms NativeWindowXYReferenceMaps.varying_inverse
#print axioms NativeWindowXYReferenceMaps.windowIndex
#print axioms NativeWindowXYReferenceMaps.windowIndex_height
#print axioms NativeWindowXYReferenceMaps.windowIndex_spatial
#print axioms NativeWindowXYReferenceMaps.window_pref_column
#print axioms NativeWindowXYReferenceMaps.window_pref_height
#print axioms NativeWindowXYReferenceMaps.window_pref_spatial
#print axioms NativeXYPreLossBudget.constant_pre_loss
#print axioms NativeXYPreLossBudget.xyConstant_pre_loss
