import Theorems.Thm_StickyKakeya4_native_sharp_parent_graph_forget

#print axioms NativeSharpParentGraphForget.curve_parent_profiles_forget
#print axioms NativeSharpParentGraphForget.curve_cleanup_forget
#print axioms NativeSharpParentGraphForget.curve_retained_forget
#print axioms NativeSharpParentGraphForget.curve_stage_forget
