import Theorems.Thm_StickyKakeya4_native_finite_tuple_fibers
import Theorems.Thm_StickyKakeya4_native_rank_mesoscopic_radius_menu
import Theorems.Thm_StickyKakeya4_native_two_stage_transversality_budget

set_option autoImplicit false
#print axioms NativeFiniteTupleFibers.card_le_coarse_tuple_card_mul
#print axioms NativeFiniteTupleFibers.coarse_tuple_card_lower
#print axioms NativeFiniteTupleFibers.cons_pair_injective
#print axioms NativeFiniteTupleFibers.list_map_fiber_card_le
#print axioms NativeFiniteTupleFibers.mem_tupleLifts
#print axioms NativeFiniteTupleFibers.tupleLifts
#print axioms NativeFiniteTupleFibers.tupleLifts_card_le
#print axioms NativeRankMesoscopicRadiusMenu.allowed
#print axioms NativeRankMesoscopicRadiusMenu.allowed_antitone
#print axioms NativeRankMesoscopicRadiusMenu.allowed_nonempty
#print axioms NativeRankMesoscopicRadiusMenu.exists_mesoscopic_rank_retention
#print axioms NativeRankMesoscopicRadiusMenu.exists_middle_entry
#print axioms NativeRankMesoscopicRadiusMenu.menu
#print axioms NativeRankMesoscopicRadiusMenu.radius_ge_quarter_power
#print axioms NativeRankMesoscopicRadiusMenu.radius_le_cutoff_of_eighth_depth
#print axioms NativeRankMesoscopicRadiusMenu.radius_square_ge_source
#print axioms NativeTwoStageTransversalityBudget.exists_half_mass_cutoff
#print axioms NativeTwoStageTransversalityBudget.retention_radix_le_of_transfer_cost
#print axioms NativeTwoStageTransversalityBudget.test_power_le
