import Theorems.Thm_StickyKakeya4_native_prescribed_parent_graph_configuration

#print axioms NativePrescribedParentGraphConfiguration.CurveParentFinalCleanupData
#print axioms NativePrescribedParentGraphConfiguration.HasCurveParentRetainedHistory
#print axioms NativePrescribedParentGraphConfiguration.HasCurveParentStage
#print axioms NativePrescribedParentGraphConfiguration.middleSelected
#print axioms NativePrescribedParentGraphConfiguration.middle_selected_depth
#print axioms NativePrescribedParentGraphConfiguration.half_depth_eq_depth
#print axioms NativePrescribedParentGraphConfiguration.stage_with_parent_graph
#print axioms NativePrescribedParentGraphConfiguration.exists_prescribed_parent_graph_configuration
