import Theorems.Thm_StickyKakeya4_native_normalized_population_admission_budget

#print axioms NativeNormalizedPopulationAdmissionBudget.populationValue
#print axioms NativeNormalizedPopulationAdmissionBudget.population_from_original_mass
#print axioms NativeNormalizedPopulationAdmissionBudget.local_scale_root
#print axioms NativeNormalizedPopulationAdmissionBudget.pay_local_root
#print axioms NativeNormalizedPopulationAdmissionBudget.exists_original_population_admission_cutoff
