import Theorems.Thm_StickyKakeya4_native_angular_candidate_capacity_product

#print axioms NativeAngularCandidateCapacityProduct.costConstant
#print axioms NativeAngularCandidateCapacityProduct.costConstant_one_le
#print axioms NativeAngularCandidateCapacityProduct.depthPower_comp
#print axioms NativeAngularCandidateCapacityProduct.depthPower_pow
#print axioms NativeAngularCandidateCapacityProduct.depthPower_product
#print axioms NativeAngularCandidateCapacityProduct.depthPower_one_le
#print axioms NativeAngularCandidateCapacityProduct.singleCapacity_cast_le
#print axioms NativeAngularCandidateCapacityProduct.successor_capacity_product
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_zero
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_succ
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_product_split
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_product_le
#print axioms NativeAngularCandidateCapacityProduct.native_master_product_bound
