import Theorems.Thm_StickyKakeya4_native_normalized_offset_count
import Theorems.Thm_StickyKakeya4_native_normalized_offset_field
import Theorems.Thm_StickyKakeya4_native_normalized_offset_time
import Theorems.Thm_StickyKakeya4_native_parent_original_point_menu
import Theorems.Thm_StickyKakeya4_native_parent_reference_relation_menu
import Theorems.Thm_StickyKakeya4_native_saturated_parent_graph_configuration
import Theorems.Thm_StickyKakeya4_native_saturated_parent_graph_data
import Theorems.Thm_StickyKakeya4_native_saturated_parent_graph_forget
import Theorems.Thm_StickyKakeya4_native_saturated_population_parent_configuration
import Theorems.Thm_StickyKakeya4_native_saturated_reference_graph_configuration
import Theorems.Thm_StickyKakeya4_native_sharp_population_admission
import Theorems.Thm_StickyKakeya4_native_trimmed_angular_class_counts
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_actual_ad

set_option autoImplicit false
#print axioms NativeNormalizedOffsetCount.offset_count_from_mapped_field
#print axioms NativeNormalizedOffsetCount.offset_count_from_raw_field
#print axioms NativeNormalizedOffsetField.mapped_raw_field_variation
#print axioms NativeNormalizedOffsetField.raw_field_variation
#print axioms NativeNormalizedOffsetField.translated_field_variation
#print axioms NativeNormalizedOffsetField.window_variation_le_twice
#print axioms NativeNormalizedOffsetTime.chart_height_window
#print axioms NativeNormalizedOffsetTime.physical_cell_time_distance
#print axioms NativeNormalizedOffsetTime.quantized_time_distance
#print axioms NativeNormalizedOffsetTime.raw_height_window
#print axioms NativeNormalizedOffsetTime.same_floor_distance
#print axioms NativeNormalizedOffsetTime.translated_height_window
#print axioms NativeParentOriginalPointMenu.parent_original_point_uniformities
#print axioms NativeParentOriginalPointMenu.relations
#print axioms NativeParentOriginalPointMenu.relations_refl
#print axioms NativeParentOriginalPointMenu.relations_symm
#print axioms NativeParentReferenceRelationMenu.relations
#print axioms NativeParentReferenceRelationMenu.relations_refl
#print axioms NativeParentReferenceRelationMenu.relations_symm
#print axioms NativeParentReferenceRelationMenu.uniformities
#print axioms NativeSaturatedParentGraphConfiguration.HasSaturatedCurveParentRetainedHistory
#print axioms NativeSaturatedParentGraphConfiguration.HasSaturatedCurveParentStage
#print axioms NativeSaturatedParentGraphConfiguration.SaturatedCurveParentFinalCleanupData
#print axioms NativeSaturatedParentGraphConfiguration.exists_saturated_parent_graph_configuration
#print axioms NativeSaturatedParentGraphConfiguration.half_depth_eq_depth
#print axioms NativeSaturatedParentGraphConfiguration.middleSelected
#print axioms NativeSaturatedParentGraphConfiguration.middle_selected_depth
#print axioms NativeSaturatedParentGraphConfiguration.saturated_stage_with_parent_graph
#print axioms NativeSaturatedParentGraphData.HasParentHeightCore
#print axioms NativeSaturatedParentGraphData.HasSaturatedCurveParentProfiles
#print axioms NativeSaturatedParentGraphData.attach_saturated_parent_graph
#print axioms NativeSaturatedParentGraphData.saturated_curve_parent_profiles_forget
#print axioms NativeSaturatedParentGraphForget.curve_cleanup_forget
#print axioms NativeSaturatedParentGraphForget.curve_parent_profiles_forget
#print axioms NativeSaturatedParentGraphForget.curve_retained_forget
#print axioms NativeSaturatedParentGraphForget.curve_stage_forget
#print axioms NativeSaturatedPopulationParentConfiguration.HasSaturatedParentRetainedHistory
#print axioms NativeSaturatedPopulationParentConfiguration.HasSaturatedPopulationParentStage
#print axioms NativeSaturatedPopulationParentConfiguration.SaturatedParentFinalCleanupData
#print axioms NativeSaturatedPopulationParentConfiguration.exists_saturated_population_parent_configuration
#print axioms NativeSaturatedPopulationParentConfiguration.saturated_stage_with_population_parent
#print axioms NativeSaturatedReferenceGraphConfiguration.exists_saturated_reference_graph_configuration
#print axioms NativeSharpPopulationAdmission.exists_sharp_admission_cutoff
#print axioms NativeSharpPopulationAdmission.hierarchy_admission_margins
#print axioms NativeSharpPopulationAdmission.original_refinement_cost
#print axioms NativeSharpPopulationAdmission.sharp_population_readback
#print axioms NativeTrimmedAngularClassCounts.coarse_fiber_image
#print axioms NativeTrimmedAngularClassCounts.coarse_weight_sum
#print axioms NativeTrimmedAngularClassCounts.distinct_class_lower
#print axioms NativeTrimmedAngularClassCounts.distinct_class_upper
#print axioms NativeTrimmedAngularClassCounts.nested_fiber
#print axioms NativeTwoMapRetainedSliceActualAD.actual_ADBounds
#print axioms NativeTwoMapRetainedSliceActualAD.actual_all_radius_bounds
