import Theorems.Thm_StickyKakeya4_native_saturated_parent_graph_configuration

#print axioms NativeSaturatedParentGraphConfiguration.SaturatedCurveParentFinalCleanupData
#print axioms NativeSaturatedParentGraphConfiguration.HasSaturatedCurveParentRetainedHistory
#print axioms NativeSaturatedParentGraphConfiguration.HasSaturatedCurveParentStage
#print axioms NativeSaturatedParentGraphConfiguration.middleSelected
#print axioms NativeSaturatedParentGraphConfiguration.middle_selected_depth
#print axioms NativeSaturatedParentGraphConfiguration.half_depth_eq_depth
#print axioms NativeSaturatedParentGraphConfiguration.saturated_stage_with_parent_graph
#print axioms NativeSaturatedParentGraphConfiguration.exists_saturated_parent_graph_configuration
