import Theorems.Thm_StickyKakeya4_native_coarse_point_multiplicity
#print axioms NativeCoarsePointMultiplicity.zero_front_eq_local
#print axioms NativeCoarsePointMultiplicity.same_parent_front_error
#print axioms NativeCoarsePointMultiplicity.projected_front_near_physical
#print axioms NativeCoarsePointMultiplicity.projectedLabel_mem_menu
#print axioms NativeCoarsePointMultiplicity.pointLabel
#print axioms NativeCoarsePointMultiplicity.original_cell_image_card_le
#print axioms NativeCoarsePointMultiplicity.pairProjection
#print axioms NativeCoarsePointMultiplicity.abstract_projected_image
#print axioms NativeCoarsePointMultiplicity.old_fiber_projected_support
#print axioms NativeCoarsePointMultiplicity.multiplicity_le_actual
#print axioms NativeCoarsePointMultiplicity.reindexed_rows_image
#print axioms NativeCoarsePointMultiplicity.full_source_multiplicity_real
#print axioms NativeCoarsePointMultiplicity.multiplicity_le_full_source
