import Theorems.Thm_StickyKakeya4_native_prescribed_parent_menu_configuration
import Theorems.Thm_StickyKakeya4_native_complete_parent_profiles
import Theorems.Thm_StickyKakeya4_native_prescribed_population_parent_configuration
import Theorems.Thm_StickyKakeya4_native_slice_class_algebra
import Theorems.Thm_StickyKakeya4_native_reference_slice_class_bounds
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_cap

set_option autoImplicit false
#print axioms NativeCompleteParentProfiles.HasCompleteParentProfiles
#print axioms NativeCompleteParentProfiles.complete_selected_parent_profiles
#print axioms NativePrescribedParentMenuConfiguration.HasPrescribedHorizontalStage
#print axioms NativePrescribedParentMenuConfiguration.callerRelations
#print axioms NativePrescribedParentMenuConfiguration.exists_prescribed_parent_menu_configuration
#print axioms NativePrescribedParentMenuConfiguration.prescribed_horizontal_stage_forget
#print axioms NativePrescribedParentMenuConfiguration.prescribed_stage_with_horizontal_menu
#print axioms NativePrescribedPopulationParentConfiguration.HasPrescribedParentRetainedHistory
#print axioms NativePrescribedPopulationParentConfiguration.HasPrescribedPopulationParentStage
#print axioms NativePrescribedPopulationParentConfiguration.PrescribedParentFinalCleanupData
#print axioms NativePrescribedPopulationParentConfiguration.complete_profiles_forget
#print axioms NativePrescribedPopulationParentConfiguration.exists_prescribed_population_parent_configuration
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_parent_cleanup_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_parent_retained_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_population_stage_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_stage_with_population_parent
#print axioms NativeReferenceSliceClassBounds.HasColumnPowerProfile
#print axioms NativeReferenceSliceClassBounds.reference_class_power_bounds
#print axioms NativeReferenceSliceClassBounds.relativeWidth_ratio
#print axioms NativeSliceClassAlgebra.class_bounds_from_global_counts
#print axioms NativeSliceClassAlgebra.global_count_ratio_bounds
#print axioms NativeSliceClassAlgebra.scaled_power_quotient
#print axioms NativeWeightedGrainQuotientCap.local_threshold_to_X
#print axioms NativeWeightedGrainQuotientCap.selected_X_cross
#print axioms NativeWeightedGrainQuotientCap.source_selected_X_cross
#print axioms NativeWeightedGrainQuotientCap.weighted_density_cap_cancellation
