import Theorems.Thm_StickyKakeya4_native_queried_vertex_weights
import Theorems.Thm_StickyKakeya4_native_full_vertex_fiber_density

set_option autoImplicit false
#print axioms NativeFullVertexFiberDensity.anchor_mem_short_closure
#print axioms NativeFullVertexFiberDensity.cap_le_vertex_mass
#print axioms NativeFullVertexFiberDensity.full_vertex_fiber_mass
#print axioms NativeFullVertexFiberDensity.full_vertex_fibers_lower
#print axioms NativeFullVertexFiberDensity.queried_short_closure_lower
#print axioms NativeFullVertexFiberDensity.short_children_le_vertices
#print axioms NativeFullVertexFiberDensity.short_closure_image
#print axioms NativeFullVertexFiberDensity.short_closure_weight_cross
#print axioms NativeFullVertexFiberDensity.vertex_lift_cost
#print axioms NativeQueriedVertexWeights.center_injective
#print axioms NativeQueriedVertexWeights.embedded_vertex_cap
#print axioms NativeQueriedVertexWeights.mass_le_vertices_mul_cap
#print axioms NativeQueriedVertexWeights.mass_pointWeight
#print axioms NativeQueriedVertexWeights.pointWeight
#print axioms NativeQueriedVertexWeights.queried_vertex_mass_bounds
#print axioms NativeQueriedVertexWeights.reference_mass
#print axioms NativeQueriedVertexWeights.squared_grain_width
#print axioms NativeQueriedVertexWeights.vertexCap
#print axioms NativeQueriedVertexWeights.vertexCap_le_average
#print axioms NativeQueriedVertexWeights.vertexCap_pos
#print axioms NativeQueriedVertexWeights.vertexMultiplicity
#print axioms NativeQueriedVertexWeights.vertex_lower_cross
#print axioms NativeQueriedVertexWeights.vertex_mass_bounds
#print axioms NativeQueriedVertexWeights.vertex_mass_eq
#print axioms NativeQueriedVertexWeights.vertex_mass_le_cap
#print axioms NativeQueriedVertexWeights.vertex_upper_cross
#print axioms NativeQueriedVertexWeights.vertices
#print axioms NativeQueriedVertexWeights.weighted_approximate_predecessor_vertices
#print axioms NativeQueriedVertexWeights.weighted_predecessor_vertices
