import Theorems.Thm_StickyKakeya4_native_actual_raw_source_geometry
set_option autoImplicit false
#print axioms NativeActualRawSourceSlopeReadbackDraft2317.coarse_source_slope
#print axioms NativeActualRawSourceSlopeReadbackDraft2317.actual_final_slope_error
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.rawHeightFromInteger
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.rawHeight_eq_integer
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.chosenOriginalHeight
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.chosenOriginalHeight_readback
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.sourceField
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.sourceField_on_raw_witness
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.parentSlope
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.horizontal_error_norm
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.quotient_residual_of_slope_error
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.actual_final_quotient_error
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.actual_one_T_quotient_error
#print axioms NativeActualRawSourceQuotientReadbackDraft2321.error_budget
