import Theorems.Thm_StickyKakeya4_native_angular_test_source_window

#print axioms NativeAngularTestSourceWindow.original_angular_depth_window
#print axioms NativeAngularTestSourceWindow.exists_original_test_cutoff
