import Theorems.Thm_StickyKakeya4_native_common_phi_grid
import Theorems.Thm_StickyKakeya4_native_common_phi_metric
import Theorems.Thm_StickyKakeya4_native_conditional_angular_power_budget
import Theorems.Thm_StickyKakeya4_native_conditional_angular_scale_readback
import Theorems.Thm_StickyKakeya4_native_generic_final_attachment
import Theorems.Thm_StickyKakeya4_native_generic_graph_rank_data
import Theorems.Thm_StickyKakeya4_native_generic_history_dimension_range
import Theorems.Thm_StickyKakeya4_native_height_window_relations
import Theorems.Thm_StickyKakeya4_native_physical_queried_rank_configuration
import Theorems.Thm_StickyKakeya4_native_post_graph_XY_data
import Theorems.Thm_StickyKakeya4_native_same_source_conditional_angular_upper

set_option autoImplicit false
#print axioms NativeCommonPhiGrid.angle_grid_mem_box
#print axioms NativeCommonPhiGrid.angular_card_le_projected
#print axioms NativeCommonPhiGrid.double_bin_distance
#print axioms NativeCommonPhiGrid.forward_projected_fiber_cap
#print axioms NativeCommonPhiGrid.inverse_projected_fiber_cap
#print axioms NativeCommonPhiGrid.same_angle_distance
#print axioms NativeCommonPhiMetric.frozen_residual
#print axioms NativeCommonPhiMetric.full_distance
#print axioms NativeCommonPhiMetric.normal_graph_error
#print axioms NativeCommonPhiMetric.tangent_ball_inverse
#print axioms NativeCommonPhiMetric.tangent_ball_pair_inverse
#print axioms NativeCommonPhiMetric.tangent_distance
#print axioms NativeConditionalAngularPowerBudget.angular_slack_to_rank
#print axioms NativeConditionalAngularPowerBudget.first_radix_fourth_cost
#print axioms NativeConditionalAngularPowerBudget.original_loss_to_rank
#print axioms NativeConditionalAngularPowerBudget.source_conditional_power_cost
#print axioms NativeConditionalAngularScaleReadback.actual_nested_scale_budgets
#print axioms NativeConditionalAngularScaleReadback.inner_query_product
#print axioms NativeConditionalAngularScaleReadback.relative_width_ratio
#print axioms NativeGenericFinalAttachment.retainedCutoff
#print axioms NativeGenericFinalAttachment.retainedCutoff_pos
#print axioms NativeGenericFinalAttachment.select_final_stage
#print axioms NativeGenericGraphRankData.HasGraphRankSelection
#print axioms NativeGenericHistoryDimensionRange.history_stage_dimension_range
#print axioms NativeHeightWindowRelations.caller_window_uniformities
#print axioms NativeHeightWindowRelations.coarsen
#print axioms NativeHeightWindowRelations.coarsen_column
#print axioms NativeHeightWindowRelations.horizontal_class_counts
#print axioms NativeHeightWindowRelations.points
#print axioms NativeHeightWindowRelations.points_horizontal_coarsen
#print axioms NativeHeightWindowRelations.relations
#print axioms NativeHeightWindowRelations.relations_refl
#print axioms NativeHeightWindowRelations.relations_symm
#print axioms NativeHeightWindowRelations.window_height_counts_comparable
#print axioms NativePhysicalQueriedRankConfiguration.exists_candidate_queried_rank_configuration
#print axioms NativePhysicalQueriedRankConfiguration.exists_extra_queried_rank_configuration
#print axioms NativePostGraphXYData.HasThirdXYFinish
#print axioms NativePostGraphXYData.HasXYParentProfiles
#print axioms NativeSameSourceConditionalAngularUpper.conditionalConstant
#print axioms NativeSameSourceConditionalAngularUpper.exists_conditional_angular_upper
