import Theorems.Thm_StickyKakeya4_native_same_source_multiplicity_balance
#print axioms NativeSameSourceMultiplicityBalance.multiplicity_nonneg
#print axioms NativeSameSourceMultiplicityBalance.selected_multiplicity_retention
#print axioms NativeSameSourceMultiplicityBalance.selected_source_near
#print axioms NativeSameSourceMultiplicityBalance.fine_le_coarse_from_parent_upper
#print axioms NativeSameSourceMultiplicityBalance.exists_parent_from_coarse_upper
#print axioms NativeSameSourceMultiplicityBalance.actual_scale_product
#print axioms NativeSameSourceMultiplicityBalance.complementary_power_identity
#print axioms NativeSameSourceMultiplicityBalance.complementary_lower
#print axioms NativeSameSourceMultiplicityBalance.move_density_loss
#print axioms NativeSameSourceMultiplicityBalance.localCost
#print axioms NativeSameSourceMultiplicityBalance.balanceCost
#print axioms NativeSameSourceMultiplicityBalance.coarse_near_lower
#print axioms NativeSameSourceMultiplicityBalance.exists_parent_near_lower
