import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_algebra
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_costs
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_powers
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_source
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_cutoff
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_final
import Theorems.Thm_StickyKakeya4_native_reference_slice_budget_readback
import Theorems.Thm_StickyKakeya4_native_actual_reference_W_geometry
import Theorems.Thm_StickyKakeya4_native_actual_reference_W_count
import Theorems.Thm_StickyKakeya4_native_actual_reference_W_directions
import Theorems.Thm_StickyKakeya4_native_incident_affine_anchor_geometry
import Theorems.Thm_StickyKakeya4_native_incident_affine_anchor_source
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_transfer
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_core

set_option autoImplicit false
#print axioms NativeActualReferenceWCount.point_image
#print axioms NativeActualReferenceWCount.retained_original_W_count
#print axioms NativeActualReferenceWCount.tube_image
#print axioms NativeActualReferenceWDirections.full_direction_menu
#print axioms NativeActualReferenceWDirections.representative_parent
#print axioms NativeActualReferenceWDirections.slope
#print axioms NativeActualReferenceWDirections.witness_full_direction_conditions
#print axioms NativeActualReferenceWGeometry.equal_column_height_gap
#print axioms NativeActualReferenceWGeometry.heightColumnCost
#print axioms NativeActualReferenceWGeometry.incidence_card
#print axioms NativeActualReferenceWGeometry.incidences
#print axioms NativeActualReferenceWGeometry.pointsAt_card_bound
#print axioms NativeActualReferenceWGeometry.same_phase_height_column_halo
#print axioms NativeIncidentAffineAnchorGeometry.anchorTube
#print axioms NativeIncidentAffineAnchorGeometry.anchorTube_mem
#print axioms NativeIncidentAffineAnchorGeometry.coordinates_norm_le
#print axioms NativeIncidentAffineAnchorGeometry.coordinates_normal_sub_matrix
#print axioms NativeIncidentAffineAnchorGeometry.exists_incident_affine_anchors
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_mem_heightKernel
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_norm
#print axioms NativeIncidentAffineAnchorGeometry.localHorizontalSlope_sub
#print axioms NativeIncidentAffineAnchorGeometry.normalCoordinates
#print axioms NativeIncidentAffineAnchorSource.exists_actual_incident_affine_anchors
#print axioms NativeReferenceSliceBudgetAlgebra.actual_reference_ratio
#print axioms NativeReferenceSliceBudgetAlgebra.columnEpsilon
#print axioms NativeReferenceSliceBudgetAlgebra.population
#print axioms NativeReferenceSliceBudgetAlgebra.profileLower
#print axioms NativeReferenceSliceBudgetAlgebra.profileUpper
#print axioms NativeReferenceSliceBudgetAlgebra.ratioConstant
#print axioms NativeReferenceSliceBudgetAlgebra.ratioConstant_pos
#print axioms NativeReferenceSliceBudgetAlgebra.reference_ratio
#print axioms NativeReferenceSliceBudgetCosts.first_retention_density_cost
#print axioms NativeReferenceSliceBudgetCosts.pay_actual_costs
#print axioms NativeReferenceSliceBudgetCosts.pay_source_costs
#print axioms NativeReferenceSliceBudgetCosts.source_exponent_le
#print axioms NativeReferenceSliceBudgetCutoff.absorb_remaining_power
#print axioms NativeReferenceSliceBudgetCutoff.exists_fixed_ad_parameters
#print axioms NativeReferenceSliceBudgetCutoff.exists_source_constant_cutoff
#print axioms NativeReferenceSliceBudgetCutoff.sourceCutoff
#print axioms NativeReferenceSliceBudgetCutoff.sourceCutoff_le_one
#print axioms NativeReferenceSliceBudgetCutoff.sourceCutoff_pays
#print axioms NativeReferenceSliceBudgetCutoff.sourceCutoff_pos
#print axioms NativeReferenceSliceBudgetFinal.actual_reference_constant_le_power
#print axioms NativeReferenceSliceBudgetPowers.rank_history_power
#print axioms NativeReferenceSliceBudgetPowers.reference_ad_constant_eq
#print axioms NativeReferenceSliceBudgetPowers.sourceConstant
#print axioms NativeReferenceSliceBudgetPowers.sourceConstant_one_le
#print axioms NativeReferenceSliceBudgetPowers.squared_grain_power
#print axioms NativeReferenceSliceBudgetReadback.parent_profiles_readback
#print axioms NativeReferenceSliceBudgetReadback.population_mass_ratio
#print axioms NativeReferenceSliceBudgetSource.actualConstant
#print axioms NativeReferenceSliceBudgetSource.actual_reference_constant_bound
#print axioms NativeTwoMapRetainedSliceCore.exists_two_map_slice_grain_core
#print axioms NativeTwoMapRetainedSliceTransfer.coarse_image_count_le
#print axioms NativeTwoMapRetainedSliceTransfer.point_image_retention
#print axioms NativeTwoMapRetainedSliceTransfer.retained_class_count_cross
#print axioms NativeTwoMapRetainedSliceTransfer.retained_class_count_lower
