import Theorems.Thm_StickyKakeya4_native_weighted_height_node_selection

#print axioms NativeWeightedHeightNodeSelection.weighted_height_node_selection
#print axioms NativeWeightedHeightNodeSelection.weighted_height_node_selection_nonempty
#print axioms NativeWeightedHeightNodeSelection.cutByNodes
#print axioms NativeWeightedHeightNodeSelection.mem_cutByNodes
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_fiber_eq
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_label_fiber_eq
#print axioms NativeWeightedHeightNodeSelection.surviving_grain_weight_eq
