import Theorems.Thm_StickyKakeya4_native_local_parent_multiplicity
set_option autoImplicit false
#print axioms NativeLocalParentMultiplicity.parentEdges
#print axioms NativeLocalParentMultiplicity.parentEdges_subset
#print axioms NativeLocalParentMultiplicity.globalPair_eq_localPair
#print axioms NativeLocalParentMultiplicity.parent_fiber_eq_global
#print axioms NativeLocalParentMultiplicity.parent_pair_fiber_lower
#print axioms NativeLocalParentMultiplicity.retained_pair_fiber_capacity
#print axioms NativeLocalParentMultiplicity.retained_pair_image_capacity
#print axioms NativeLocalParentMultiplicity.parent_multiplicity_cross
#print axioms NativeLocalParentMultiplicity.native_parent_multiplicity_cross
#print axioms NativeLocalParentMultiplicity.native_parent_multiplicity_transfer
