import Theorems.Thm_StickyKakeya4_native_original_cell_presentation_unique
set_option autoImplicit false
#print axioms NativeOriginalCellPresentationUnique.mem_cells_iff_center_mem
#print axioms NativeOriginalCellPresentationUnique.cells_eq_of_shading_eq
#print axioms NativeOriginalCellPresentationUnique.restricted_cells_eq
#print axioms NativeOriginalCellPresentationUnique.restricted_incidences_eq
#print axioms NativeOriginalCellPresentationUnique.subset_original_cut
#print axioms NativeOriginalCellPresentationUnique.core_subset_original_cut
#print axioms NativeOriginalCellPresentationUnique.core_preserves_original_predicate
