import Theorems.Thm_StickyKakeya4_native_actual_configured_point
import Theorems.Thm_StickyKakeya4_native_alignment_parent_width
import Theorems.Thm_StickyKakeya4_original_weighted_macro_selection
set_option autoImplicit false
#print axioms NativeActualConfiguredPoint.assemble_height
#print axioms NativeActualConfiguredPoint.assemble_spatial
#print axioms NativeActualConfiguredPoint.graphGrid
#print axioms NativeActualConfiguredPoint.sourceLabel
#print axioms NativeActualConfiguredPoint.point
#print axioms NativeActualConfiguredPoint.point_factorization
#print axioms NativeActualConfiguredPoint.sourceLabel_oneTwo
#print axioms NativeActualConfiguredPoint.sourceLabel_twoOne
#print axioms NativeActualConfiguredPoint.sourceLabel_height
#print axioms NativeActualConfiguredPoint.graphGrid_height
#print axioms NativeActualConfiguredPoint.point_height_floor
#print axioms NativeActualConfiguredPoint.sourceLabel_coordinates
#print axioms NativeActualConfiguredPoint.graphGrid_distance
#print axioms NativeActualConfiguredPoint.point_distance
#print axioms NativeAlignmentParentWidth.exists_factor_gap_cutoff
#print axioms NativeAlignmentParentWidth.parent_4096_depth
#print axioms NativeAlignmentParentWidth.exists_actual_parent_cutoff
#print axioms OriginalWeightedMacroSelection.localPoints
#print axioms OriginalWeightedMacroSelection.localHeights
#print axioms OriginalWeightedMacroSelection.sum_original_local_points
#print axioms OriginalWeightedMacroSelection.occupiedHeightPairs
#print axioms OriginalWeightedMacroSelection.local_heights_pair_fiber
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_pairs
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_height_cells
#print axioms OriginalWeightedMacroSelection.weighted_denominator_of_height_cells
#print axioms OriginalWeightedMacroSelection.exists_original_weighted_macro
#print axioms OriginalWeightedMacroSelection.exists_physical_weighted_macro
