import Theorems.Thm_StickyKakeya4_native_fixed_source_reference
import Theorems.Thm_StickyKakeya4_native_remembered_reference_tags
import Theorems.Thm_StickyKakeya4_native_physical_local_offset_coherence
import Theorems.Thm_StickyKakeya4_native_actual_physical_third_prerequisites
set_option autoImplicit false
#print axioms NativeFixedSourceReference.fixed_balanced_configuration
#print axioms NativeFixedSourceReference.fixed_two_scale_configuration
#print axioms NativeFixedSourceReference.fixed_middle_two_scale_extra_configuration
#print axioms NativeFixedSourceReference.fixed_all_two_scale_extra_configuration
#print axioms NativeFixedSourceReference.exists_fixed_source_reference
#print axioms NativeFixedSourceReference.union_pos_of_shading_lower
#print axioms NativeFixedSourceReference.native_near_of_volume_bounds
#print axioms NativeFixedSourceReference.exists_reference_from_volume_bounds
#print axioms NativeRememberedReferenceTags.oldHeight
#print axioms NativeRememberedReferenceTags.oldHeight_readback
#print axioms NativeRememberedReferenceTags.reference_edge_witness
#print axioms NativePhysicalLocalOffsetCoherence.actual_local_cell_offset_cap
#print axioms NativePhysicalLocalOffsetCoherence.select_actual_matrix_offset_menu
#print axioms NativePreThirdHeightSupport.configured_fine_to_support
#print axioms NativePreThirdHeightSupport.select_actual_height_support
#print axioms NativeSourcePhysicalCoherence.HasUpperEngine
#print axioms NativeSourcePhysicalCoherence.mesh_window
#print axioms NativeSourcePhysicalCoherence.HasPhysicalCoherenceEngine
#print axioms NativeSourcePhysicalCoherence.coherence_of_actual_upper
#print axioms NativePhysicalCoherentThirdJoin.from_actual_source
#print axioms NativeActualHeightThirdJoin.source_total_charge
#print axioms NativeActualHeightThirdJoin.attach_rank_two
#print axioms NativeActualHeightThirdJoin.attach_rank_three
