import Theorems.Thm_StickyKakeya4_native_actual_paid_X_power
import Theorems.Thm_StickyKakeya4_native_reference_parent_admission_budget
import Theorems.Thm_StickyKakeya4_native_reference_parent_angular_upper
import Theorems.Thm_StickyKakeya4_native_reference_parent_population
import Theorems.Thm_StickyKakeya4_native_sharp_X_budget_actual
import Theorems.Thm_StickyKakeya4_native_sharp_X_budget_cutoff
import Theorems.Thm_StickyKakeya4_native_source_quotient_ad

set_option autoImplicit false
#print axioms NativeActualPaidXPower.source_reference_X_small_power
#print axioms NativeReferenceParentAdmissionBudget.exists_first_stage_admission_cutoff
#print axioms NativeReferenceParentAngularUpper.exists_reference_parent_angular_upper
#print axioms NativeReferenceParentPopulation.candidate_middle_bounds
#print axioms NativeReferenceParentPopulation.candidate_middle_square
#print axioms NativeReferenceParentPopulation.first_cost_density
#print axioms NativeReferenceParentPopulation.reference_parent_population
#print axioms NativeSharpXBudgetActual.actual_fiber_coefficient_le_power
#print axioms NativeSharpXBudgetCutoff.exists_source_cutoff
#print axioms NativeSharpXBudgetCutoff.paid_X_lower
#print axioms NativeSharpXBudgetCutoff.sourceCutoff
#print axioms NativeSharpXBudgetCutoff.sourceCutoff_le_one
#print axioms NativeSharpXBudgetCutoff.sourceCutoff_pays
#print axioms NativeSharpXBudgetCutoff.sourceCutoff_pos
#print axioms NativeSourceQuotientAD.source_quotient_AD
