import Theorems.Thm_StickyKakeya4_native_reference_slice_all_radii
import Theorems.Thm_StickyKakeya4_native_fixed_horizontal_menu
import Theorems.Thm_StickyKakeya4_native_slice_menu_ball_join
import Theorems.Thm_StickyKakeya4_native_reference_horizontal_menu
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_fibers
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_hereditary
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_density

set_option autoImplicit false
#print axioms NativeFixedHorizontalMenu.depths
#print axioms NativeFixedHorizontalMenu.depths_bounds
#print axioms NativeFixedHorizontalMenu.depths_gap
#print axioms NativeFixedHorizontalMenu.depths_last
#print axioms NativeFixedHorizontalMenu.depths_monotone
#print axioms NativeFixedHorizontalMenu.depths_zero
#print axioms NativeReferenceHorizontalMenu.caller_reference_menu_counts
#print axioms NativeReferenceHorizontalMenu.menu_width_window
#print axioms NativeReferenceSliceAllRadii.caller_reference_all_radius_bounds
#print axioms NativeReferenceSliceAllRadii.horizontalMesh
#print axioms NativeReferenceSliceAllRadii.horizontalMesh_outer
#print axioms NativeReferenceSliceAllRadii.horizontalMesh_pos
#print axioms NativeReferenceSliceAllRadii.horizontalMesh_readback
#print axioms NativeSliceMenuBallJoin.height_card_le_of_class_bounds
#print axioms NativeSliceMenuBallJoin.menu_classes_all_radius
#print axioms NativeWeightedGrainQuotientDensity.every_H3_fiber_density
#print axioms NativeWeightedGrainQuotientDensity.every_H3_fiber_density_cross
#print axioms NativeWeightedGrainQuotientDensity.every_retained_fiber_density
#print axioms NativeWeightedGrainQuotientFibers.edgeX
#print axioms NativeWeightedGrainQuotientFibers.fullX
#print axioms NativeWeightedGrainQuotientFibers.key
#print axioms NativeWeightedGrainQuotientFibers.mixed_edgeX_image
#print axioms NativeWeightedGrainQuotientFibers.mixed_key_eq
#print axioms NativeWeightedGrainQuotientFibers.wholeX_subset_fullX
#print axioms NativeWeightedGrainQuotientHereditary.edgeX_image_vertices
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_X_cross
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_mixed_X_subset_fullX
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_vertices_le_X
#print axioms NativeWeightedGrainQuotientHereditary.subset_wholeFiber_card_le_X
