import Theorems.Thm_StickyKakeya4_native_nested_population_selection
import Theorems.Thm_StickyKakeya4_native_actual_height_metric_variation

set_option autoImplicit false
#print axioms NativeActualHeightMetricVariation.actual_half_metric_variation
#print axioms NativeActualHeightMetricVariation.actual_metric_variation
#print axioms NativeNestedPopulationSelection.exists_nested_population_parent
#print axioms NativeNestedPopulationSelection.nested_parent_subset
#print axioms NativeNestedPopulationSelection.parentEdges_nested_eq
