import Theorems.Thm_StickyKakeya4_native_actual_rank_two_three_grain_configuration
import Theorems.Thm_StickyKakeya4_native_graph_direction_in_plane

set_option autoImplicit false
#print axioms NativeActualRankTwoThreeGrainConfiguration.exists_actual_rank_two_three_grain_configuration
#print axioms NativeGraphDirectionInPlane.exists_near_graph_direction
