import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_source_angular_cap

#print axioms NativeReferenceXYGridSourceAngularCap.angularCapConstant
#print axioms NativeReferenceXYGridSourceAngularCap.dyadic_resolution
#print axioms NativeReferenceXYGridSourceAngularCap.dyadic_cap_power
#print axioms NativeReferenceXYGridSourceAngularCap.pointMenu_original_card
#print axioms NativeReferenceXYGridSourceAngularCap.point_menu_cap
#print axioms NativeReferenceXYGridSourceAngularCap.quotient_anchor_readback
#print axioms NativeReferenceXYGridSourceAngularCap.actual_point_angular_cap
