from pathlib import Path
import json,subprocess,hashlib,os,sys,datetime
w=Path('/workspace/shared/sticky-recovery-20261006');r=Path('/workspace/scratch/5f2524fd4117/4dstickykakeya');cache=Path(sys.argv[1]);d=json.loads((cache/'CACHE_MANIFEST.json').read_text());tool=Path('/workspace/scratch/5f2524fd4117/lean-tools/lean-4.33.1-linux/bin');assert hashlib.sha256((tool/'lean').read_bytes()).hexdigest()==d['compiler_sha256'];assert hashlib.sha256((r/'lake-manifest.json').read_bytes()).hexdigest()==d['lake_manifest_sha256'];names={x['module'] for x in d['artifacts']}
for x in d['artifacts']:
 assert hashlib.sha256((r/x['source_path']).read_bytes()).hexdigest()==x['source_sha256'];assert hashlib.sha256((cache/x['olean_path']).read_bytes()).hexdigest()==x['olean_sha256'];assert all(z in names for z in x['project_imports'])
run=w/'cache-import-check-20261006T0726';run.mkdir();s=run/'Check.lean';s.write_text(''.join('import '+x['module']+'\n' for x in d['artifacts'])+'set_option autoImplicit false\n#print axioms NativeExactHeightFields.select_two_exact_fields\n#print axioms NativeLocalOffsetCount.actual_offset_count\n')
env=os.environ.copy();env['PATH']=str(tool)+':'+env.get('PATH','');env['LEAN_NUM_THREADS']='1';base=subprocess.check_output([str(tool/'lake'),'env','printenv','LEAN_PATH'],cwd=r,env=env,text=True).strip().split(':');project=(r/'.lake/build/lib/lean').resolve();filtered=[x for x in base if (r/x).resolve()!=project];env['LEAN_PATH']=':'.join([str(cache/'lib/lean'),*filtered]);assert all((r/x).resolve()!=project for x in filtered)
cmd=['flock',str(w/'global-lean-locks/3.lock'),str(tool/'lean'),'-j1','-DautoImplicit=false','-R',str(run),str(s)];log=run/'import.log';state={'state':'running','started_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'artifact_count':len(names),'source_hashes_verified':True,'artifact_hashes_verified':True,'project_import_closure_verified':True,'project_fallback_removed':True,'scope':'independent cache import validation; not a new source compilation','lean_path':env['LEAN_PATH'],'command':cmd};(run/'status.json').write_text(json.dumps(state,indent=2)+'\n')
with log.open('w') as f:q=subprocess.run(cmd,cwd=r,env=env,stdout=f,stderr=subprocess.STDOUT)
state.update(state='passed' if q.returncode==0 else 'failed',exit_code=q.returncode,finished_utc=datetime.datetime.now(datetime.timezone.utc).isoformat());(run/'status.json').write_text(json.dumps(state,indent=2)+'\n');print(json.dumps(state));raise SystemExit(q.returncode)
