import Theorems.Thm_StickyKakeya4_native_actual_relative_coarse_admission
#print axioms NativeActualRelativeCoarseAdmission.OriginalPopulationLaw
#print axioms NativeActualRelativeCoarseAdmission.source_common_mesh
#print axioms NativeActualRelativeCoarseAdmission.source_common_height_zero
#print axioms NativeActualRelativeCoarseAdmission.incidences_retained_univ
#print axioms NativeActualRelativeCoarseAdmission.source_population_law
#print axioms NativeActualRelativeCoarseAdmission.actual_local_relative_coarse_admission
#print axioms NativeActualRelativeCoarseAdmission.actual_local_relative_full_coarse_upper
#print axioms NativeActualRelativeCoarseAdmission.two_step_scale_trace
#print axioms NativeActualRelativeCoarseAdmission.actual_relative_parameter_trace
#print axioms NativeActualRelativeCoarseAdmission.exists_relative_population_budget
