import Theorems.Thm_StickyKakeya4_native_weighted_packet_layers
import Theorems.Thm_StickyKakeya4_native_short_row_packets
import Theorems.Thm_StickyKakeya4_native_angular_candidate_capacity_product

set_option autoImplicit false
#print axioms NativeAngularCandidateCapacityProduct.costConstant
#print axioms NativeAngularCandidateCapacityProduct.costConstant_one_le
#print axioms NativeAngularCandidateCapacityProduct.depthPower_comp
#print axioms NativeAngularCandidateCapacityProduct.depthPower_one_le
#print axioms NativeAngularCandidateCapacityProduct.depthPower_pow
#print axioms NativeAngularCandidateCapacityProduct.depthPower_product
#print axioms NativeAngularCandidateCapacityProduct.native_master_product_bound
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_product_le
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_product_split
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_succ
#print axioms NativeAngularCandidateCapacityProduct.selectionBudget_zero
#print axioms NativeAngularCandidateCapacityProduct.singleCapacity_cast_le
#print axioms NativeAngularCandidateCapacityProduct.successor_capacity_product
#print axioms NativeShortRowPackets.projected_image_eq_rowChildren
#print axioms NativeShortRowPackets.projected_short_height
#print axioms NativeShortRowPackets.shortCells
#print axioms NativeShortRowPackets.shortEdges
#print axioms NativeShortRowPackets.shortVertexClosure
#print axioms NativeShortRowPackets.shortVertices
#print axioms NativeShortRowPackets.shortVertices_eq_cells_image
#print axioms NativeShortRowPackets.short_member_packet
#print axioms NativeShortRowPackets.short_member_readback
#print axioms NativeShortRowPackets.short_vertex_closure_packet
#print axioms NativeShortRowPackets.short_vertex_cube_packet
#print axioms NativeShortRowPackets.short_vertex_rounded_height
#print axioms NativeShortRowPackets.short_vertex_rounded_packet
#print axioms NativeShortRowPackets.short_vertex_witness
#print axioms NativeWeightedPacketLayers.active_packet_count
#print axioms NativeWeightedPacketLayers.cover_count_le_overlap
#print axioms NativeWeightedPacketLayers.layers
#print axioms NativeWeightedPacketLayers.layers_mass_loss
#print axioms NativeWeightedPacketLayers.layers_predecessors
#print axioms NativeWeightedPacketLayers.layers_step_subset
#print axioms NativeWeightedPacketLayers.layers_subset_start
#print axioms NativeWeightedPacketLayers.overlapCount
#print axioms NativeWeightedPacketLayers.packetMass
#print axioms NativeWeightedPacketLayers.packet_mass_sum
#print axioms NativeWeightedPacketLayers.packet_mass_sum_le
#print axioms NativeWeightedPacketLayers.restriction
#print axioms NativeWeightedPacketLayers.restriction_mass_loss
#print axioms NativeWeightedPacketLayers.restriction_predecessors
#print axioms NativeWeightedPacketLayers.restriction_subset
