import Theorems.Thm_StickyKakeya4_native_middle_two_scale_configuration
import Theorems.Thm_StickyKakeya4_native_all_two_scale_configuration

set_option autoImplicit false
#print axioms NativeAllTwoScaleConfiguration.boundaryWindow
#print axioms NativeAllTwoScaleConfiguration.boundaryWindow_pos
#print axioms NativeAllTwoScaleConfiguration.exists_all_two_scale_configuration
#print axioms NativeAllTwoScaleConfiguration.fullSchedule
#print axioms NativeMiddleTwoScaleConfiguration.exists_middle_two_scale_configuration
