import Theorems.Thm_StickyKakeya4_native_full_reference_direction_drift
set_option autoImplicit false
#print axioms NativeFullReferenceDirectionDrift.horizontalSlope
#print axioms NativeFullReferenceDirectionDrift.same_parent_horizontal_distance
#print axioms NativeFullReferenceDirectionDrift.full_direction_readback
#print axioms NativeFullReferenceDirectionDrift.full_horizontal_readback
#print axioms NativeFullReferenceDirectionDrift.full_horizontal_distance
#print axioms NativeFullReferenceDirectionDrift.local_horizontal_readback
#print axioms NativeFullReferenceDirectionDrift.same_reference_horizontal_distance
