import Theorems.Thm_StickyKakeya4_native_compatible_node_directions
import Theorems.Thm_StickyKakeya4_native_raw_shadow_point_comparison
import Theorems.Thm_StickyKakeya4_native_tagged_reference_density

set_option autoImplicit false
#print axioms NativeCompatibleNodeDirections.IsNodeDirectionSystem
#print axioms NativeCompatibleNodeDirections.angular_ofFn_coordinate
#print axioms NativeCompatibleNodeDirections.exists_node_direction_system
#print axioms NativeCompatibleNodeDirections.exists_node_word
#print axioms NativeCompatibleNodeDirections.exists_scheduled_node_directions
#print axioms NativeCompatibleNodeDirections.natStageAnchorIndex
#print axioms NativeCompatibleNodeDirections.natStageDirectionIndex
#print axioms NativeCompatibleNodeDirections.nat_stage_anchor_readback
#print axioms NativeCompatibleNodeDirections.nat_stage_index_readback
#print axioms NativeCompatibleNodeDirections.node_direction_system_mono
#print axioms NativeCompatibleNodeDirections.nodes
#print axioms NativeCompatibleNodeDirections.projected_word_global
#print axioms NativeCompatibleNodeDirections.stageAnchorIndex
#print axioms NativeCompatibleNodeDirections.stageDirectionIndex
#print axioms NativeCompatibleNodeDirections.stage_anchor_readback
#print axioms NativeCompatibleNodeDirections.stage_direction_bounds
#print axioms NativeCompatibleNodeDirections.stage_direction_readback
#print axioms NativeCompatibleNodeDirections.stage_index_readback
#print axioms NativeCompatibleNodeDirections.terminal_fixed_tuple
#print axioms NativeRawShadowPointComparison.point_image_card_comparison
#print axioms NativeRawShadowPointComparison.same_R_point_image_card_comparison
#print axioms NativeRawShadowPointComparison.same_shadow_coordinate_close
#print axioms NativeRawShadowPointComparison.shadow_spatial_image_card
#print axioms NativeTaggedReferenceDensity.queried_tagged_packet_lower
#print axioms NativeTaggedReferenceDensity.reference_mass_le
#print axioms NativeTaggedReferenceDensity.reference_vertex_cap
#print axioms NativeTaggedReferenceDensity.tagWeight
#print axioms NativeTaggedReferenceDensity.tag_mass
#print axioms NativeTaggedReferenceDensity.tagged_packet_mass_ge_closure
