import Theorems.Thm_StickyKakeya4_native_reference_horizontal_menu

#print axioms NativeReferenceHorizontalMenu.menu_width_window
#print axioms NativeReferenceHorizontalMenu.caller_reference_menu_counts
