import Theorems.Thm_StickyKakeya4_native_prescribed_history_configuration

#print axioms NativePrescribedHistoryConfiguration.HasPrescribedHistoryStage
#print axioms NativePrescribedHistoryConfiguration.prescribed_history_stage_of_compatible
#print axioms NativePrescribedHistoryConfiguration.exists_prescribed_history_configuration
#print axioms NativePrescribedHistoryConfiguration.prescribed_history_stage_forget
