import Theorems.Thm_StickyKakeya4_native_height_window_boundary
import Theorems.Thm_StickyKakeya4_native_paid_mesh_angular_bounds
import Theorems.Thm_StickyKakeya4_native_paid_third_data
import Theorems.Thm_StickyKakeya4_native_paid_third_record
import Theorems.Thm_StickyKakeya4_native_paid_third_record_readback
import Theorems.Thm_StickyKakeya4_native_parent_unit_angular_ball
import Theorems.Thm_StickyKakeya4_native_retained_rich_all_mesh_lower
import Theorems.Thm_StickyKakeya4_native_retained_rich_angular_power_lower
import Theorems.Thm_StickyKakeya4_native_retained_rich_angular_rank_lower
import Theorems.Thm_StickyKakeya4_native_rich_angular_rank_payment
import Theorems.Thm_StickyKakeya4_native_saturated_all_mesh_lower
import Theorems.Thm_StickyKakeya4_native_slab_grid_pullback
import Theorems.Thm_StickyKakeya4_native_slab_original_plane
import Theorems.Thm_StickyKakeya4_native_slab_parent_normalization
import Theorems.Thm_StickyKakeya4_native_slab_plane_frame
import Theorems.Thm_StickyKakeya4_native_slab_plane_pullback
import Theorems.Thm_StickyKakeya4_native_window_coefficient_comparison
import Theorems.Thm_StickyKakeya4_native_window_quotient_transport
import Theorems.Thm_StickyKakeya4_native_window_source_counts

set_option autoImplicit false
#print axioms NativeHeightWindowBoundary.card_le_height_image
#print axioms NativeHeightWindowBoundary.heightPreimages
#print axioms NativeHeightWindowBoundary.heightPreimages_card
#print axioms NativeHeightWindowBoundary.mem_heightPreimages
#print axioms NativeHeightWindowBoundary.point_count_bounds
#print axioms NativeHeightWindowBoundary.points_time_image
#print axioms NativeHeightWindowBoundary.time_map_column
#print axioms NativeHeightWindowBoundary.weighted_point_counts_max_six
#print axioms NativePaidMeshAngularBounds.ballEdges
#print axioms NativePaidMeshAngularBounds.exists_paid_mesh_angular_bounds
#print axioms NativePaidThirdData.ADBounds_mono_constant
#print axioms NativePaidThirdData.paid_data_from_budget
#print axioms NativePaidThirdRecord.HasPaidThirdXYSourceData
#print axioms NativePaidThirdRecordReadback.paid_record_from_budget
#print axioms NativeParentUnitAngularBall.center
#print axioms NativeParentUnitAngularBall.localSlope_in_unit_ball
#print axioms NativeRetainedRichAllMeshLower.actual_all_mesh_rich_class_lower
#print axioms NativeRetainedRichAngularPowerLower.retained_rich_reference_power_lower
#print axioms NativeRetainedRichAngularRankLower.actual_retained_rich_angular_rank_lower
#print axioms NativeRichAngularRankPayment.cancel_rich_class
#print axioms NativeRichAngularRankPayment.third_cost
#print axioms NativeSaturatedAllMeshLower.actual_all_mesh_point_lower
#print axioms NativeSaturatedAllMeshLower.all_mesh_depth_window
#print axioms NativeSlabGridPullback.grid_slab_transfer
#print axioms NativeSlabGridPullback.original_grid_infDist
#print axioms NativeSlabGridPullback.original_grid_point_slab_near
#print axioms NativeSlabGridPullback.phiCenter
#print axioms NativeSlabGridPullback.phiCenter_error
#print axioms NativeSlabOriginalPlane.originalPlane
#print axioms NativeSlabOriginalPlane.originalPlane_finrank
#print axioms NativeSlabOriginalPlane.originalWitness
#print axioms NativeSlabOriginalPlane.original_infDist
#print axioms NativeSlabOriginalPlane.original_point_slab_near
#print axioms NativeSlabOriginalPlane.original_slab_pullback
#print axioms NativeSlabParentNormalization.parentDirection_lift
#print axioms NativeSlabParentNormalization.parentEquiv
#print axioms NativeSlabParentNormalization.parentEquiv_apply
#print axioms NativeSlabParentNormalization.parentEquiv_symm_apply
#print axioms NativeSlabParentNormalization.parent_coordinates
#print axioms NativeSlabParentNormalization.parent_unparent
#print axioms NativeSlabParentNormalization.unparentDirection
#print axioms NativeSlabParentNormalization.unparentDirection_last
#print axioms NativeSlabParentNormalization.unparentDirection_sub
#print axioms NativeSlabParentNormalization.unparent_distance
#print axioms NativeSlabParentNormalization.unparent_parent
#print axioms NativeSlabPlaneFrame.coordinateMap
#print axioms NativeSlabPlaneFrame.coordinateMap_injective
#print axioms NativeSlabPlaneFrame.coordinate_finrank
#print axioms NativeSlabPlaneFrame.frameEquiv
#print axioms NativeSlabPlaneFrame.frameEquiv_apply
#print axioms NativeSlabPlaneFrame.inverse_coordinates
#print axioms NativeSlabPlaneFrame.matrixContinuous
#print axioms NativeSlabPlaneFrame.matrixContinuous_apply
#print axioms NativeSlabPlaneFrame.matrixContinuous_norm
#print axioms NativeSlabPlanePullback.frame_graph_error
#print axioms NativeSlabPlanePullback.nativePlane
#print axioms NativeSlabPlanePullback.nativePlane_finrank
#print axioms NativeSlabPlanePullback.nativeWitness
#print axioms NativeSlabPlanePullback.nativeWitness_coordinates
#print axioms NativeSlabPlanePullback.nativeWitness_distance
#print axioms NativeSlabPlanePullback.native_slab_pullback
#print axioms NativeWindowCoefficientComparison.geometric_factor_bound
#print axioms NativeWindowCoefficientComparison.source_ratio_le
#print axioms NativeWindowQuotientTransport.abs_ediv_bound
#print axioms NativeWindowQuotientTransport.factor
#print axioms NativeWindowQuotientTransport.width_factorization
#print axioms NativeWindowQuotientTransport.windowHalfWidth
#print axioms NativeWindowQuotientTransport.window_mesh_halfWidth
#print axioms NativeWindowQuotientTransport.window_quotient_AD
#print axioms NativeWindowQuotientTransport.window_support
#print axioms NativeWindowSourceCounts.prepared_window_geometry
#print axioms NativeWindowSourceCounts.queried_window_point_power_bounds
