import Theorems.Thm_StickyKakeya4_native_reference_column_exponents
import Theorems.Thm_StickyKakeya4_native_slice_population_algebra
import Theorems.Thm_StickyKakeya4_native_column_population_bounds

set_option autoImplicit false
#print axioms NativeColumnPopulationBounds.column_height_image
#print axioms NativeColumnPopulationBounds.column_multiplicity_card
#print axioms NativeColumnPopulationBounds.column_phase_height_image
#print axioms NativeColumnPopulationBounds.column_point_image
#print axioms NativeColumnPopulationBounds.inverse_scale_cube
#print axioms NativeColumnPopulationBounds.reference_numerator_height_bounds
#print axioms NativeColumnPopulationBounds.relativeWidth
#print axioms NativeColumnPopulationBounds.relativeWidth_pos
#print axioms NativeReferenceColumnExponents.count_coefficients_pos
#print axioms NativeReferenceColumnExponents.lowerCountCoefficient
#print axioms NativeReferenceColumnExponents.quotient_power_bounds
#print axioms NativeReferenceColumnExponents.reference_column_point_power_bounds
#print axioms NativeReferenceColumnExponents.reference_height_point_power_bounds
#print axioms NativeReferenceColumnExponents.upperCountCoefficient
#print axioms NativeSlicePopulationAlgebra.slice_power_bounds
#print axioms NativeSlicePopulationAlgebra.slice_ratio_bounds
