import Theorems.Thm_StickyKakeya4_native_actual_final_grain_configuration

set_option autoImplicit false
#print axioms NativeActualFinalGrainConfiguration.FinalCleanupData
#print axioms NativeActualFinalGrainConfiguration.HasFinalGrainSquaredStage
#print axioms NativeActualFinalGrainConfiguration.HasFinalRetainedHistory
#print axioms NativeActualFinalGrainConfiguration.exists_actual_final_grain_configuration
#print axioms NativeActualFinalGrainConfiguration.final_cleanup_of_history
#print axioms NativeActualFinalGrainConfiguration.final_retained_history_of_history
#print axioms NativeActualFinalGrainConfiguration.final_retained_history_readback
#print axioms NativeActualFinalGrainConfiguration.final_stage_history
#print axioms NativeActualFinalGrainConfiguration.final_stage_of_history
