import Theorems.Thm_StickyKakeya4_native_finite_slice_homogeneity
import Theorems.Thm_StickyKakeya4_native_parent_slice_height_geometry
import Theorems.Thm_StickyKakeya4_native_slice_count_comparison
import Theorems.Thm_StickyKakeya4_native_anisotropic_pair_numerator
import Theorems.Thm_StickyKakeya4_native_height_metric_menu
import Theorems.Thm_StickyKakeya4_native_population_parent_profiles
import Theorems.Thm_StickyKakeya4_native_phase_height_population
import Theorems.Thm_StickyKakeya4_native_source_parent_population_profile
import Theorems.Thm_StickyKakeya4_native_grain_height_projection_transport
import Theorems.Thm_StickyKakeya4_native_actual_population_parent_configuration

set_option autoImplicit false
#print axioms NativeActualPopulationParentConfiguration.HasParentRetainedHistory
#print axioms NativeActualPopulationParentConfiguration.HasPopulationParentStage
#print axioms NativeActualPopulationParentConfiguration.ParentFinalCleanupData
#print axioms NativeActualPopulationParentConfiguration.exists_actual_population_parent_configuration
#print axioms NativeActualPopulationParentConfiguration.stage_with_population_parent
#print axioms NativeAnisotropicPairNumerator.fixedPair_card_sum
#print axioms NativeAnisotropicPairNumerator.pairUpperConstant
#print axioms NativeAnisotropicPairNumerator.pairUpperConstant_pos
#print axioms NativeAnisotropicPairNumerator.parent_column_pair_upper
#print axioms NativeAnisotropicPairNumerator.shortRowColumnCost
#print axioms NativeAnisotropicPairNumerator.short_pair_column_image_card
#print axioms NativeFiniteSliceHomogeneity.coarsen_fiber_comparison
#print axioms NativeFiniteSliceHomogeneity.fiber_card_average_cross
#print axioms NativeGrainHeightProjectionTransport.exists_parent_controlled_direction
#print axioms NativeGrainHeightProjectionTransport.parentDirection
#print axioms NativeGrainHeightProjectionTransport.parentDirection_last
#print axioms NativeGrainHeightProjectionTransport.parentDirection_slopeVector
#print axioms NativeGrainHeightProjectionTransport.parentDirection_sub
#print axioms NativeGrainHeightProjectionTransport.physical_projectToHeight
#print axioms NativeGrainHeightProjectionTransport.physical_projection_displacement
#print axioms NativeGrainHeightProjectionTransport.projectToHeight
#print axioms NativeGrainHeightProjectionTransport.projectToHeight_last
#print axioms NativeGrainHeightProjectionTransport.projectToHeight_sub
#print axioms NativeGrainHeightProjectionTransport.projected_grain_near
#print axioms NativeGrainHeightProjectionTransport.removeHeight_norm_general
#print axioms NativeGrainHeightProjectionTransport.retained_direction_norm
#print axioms NativeHeightMetricMenu.chartHeightCoordinate
#print axioms NativeHeightMetricMenu.chartHeightCoordinate_distance
#print axioms NativeHeightMetricMenu.halfDepth
#print axioms NativeHeightMetricMenu.halfDepth_gap
#print axioms NativeHeightMetricMenu.halfDepth_last
#print axioms NativeHeightMetricMenu.halfDepth_le_middle
#print axioms NativeHeightMetricMenu.halfDepth_mono
#print axioms NativeHeightMetricMenu.halfDepth_zero
#print axioms NativeHeightMetricMenu.menu_crossing
#print axioms NativeHeightMetricMenu.meshWidth
#print axioms NativeHeightMetricMenu.meshWidth_pos
#print axioms NativeHeightMetricMenu.meshWidth_ratio
#print axioms NativeHeightMetricMenu.metricConstant
#print axioms NativeHeightMetricMenu.metricConstant_nonneg
#print axioms NativeHeightMetricMenu.metric_from_menu
#print axioms NativeHeightMetricMenu.metric_from_menu_chart
#print axioms NativeHeightMetricMenu.rawHeightCoordinate
#print axioms NativeHeightMetricMenu.rawHeightCoordinate_distance
#print axioms NativeParentSliceHeightGeometry.endpointHeightMenu
#print axioms NativeParentSliceHeightGeometry.endpointHeightMenu_card
#print axioms NativeParentSliceHeightGeometry.endpoint_column_mem_menu
#print axioms NativeParentSliceHeightGeometry.endpoint_height_card_le
#print axioms NativeParentSliceHeightGeometry.physical_parent_spatial_bound
#print axioms NativePhaseHeightPopulation.column_height_readback
#print axioms NativePhaseHeightPopulation.dyadic_height_mesh
#print axioms NativePhaseHeightPopulation.dyadic_height_row_capacity
#print axioms NativePhaseHeightPopulation.heightEdges
#print axioms NativePhaseHeightPopulation.heightLabel
#print axioms NativePhaseHeightPopulation.heightLabel_integer
#print axioms NativePhaseHeightPopulation.heightLabels
#print axioms NativePhaseHeightPopulation.height_population_upper
#print axioms NativePhaseHeightPopulation.height_row_card
#print axioms NativePhaseHeightPopulation.original_translated_height_abs
#print axioms NativePhaseHeightPopulation.parent_height_population
#print axioms NativePhaseHeightPopulation.phaseHeightLabels
#print axioms NativePhaseHeightPopulation.phase_height_population
#print axioms NativePhaseHeightPopulation.retained_height_capacity
#print axioms NativePopulationParentProfiles.HasPopulationParentProfiles
#print axioms NativePopulationParentProfiles.source_population_parent_profiles
#print axioms NativeSliceCountComparison.HasSliceAverage
#print axioms NativeSliceCountComparison.caller_local_class_counts
#print axioms NativeSliceCountComparison.caller_reference_slice_averages
#print axioms NativeSliceCountComparison.column_class_counts_comparable
#print axioms NativeSliceCountComparison.heightSlice
#print axioms NativeSliceCountComparison.points
#print axioms NativeSliceCountComparison.points_coarsen
#print axioms NativeSliceCountComparison.reference_height_counts_comparable
#print axioms NativeSliceCountComparison.reference_slice_average_cross
#print axioms NativeSourceParentPopulationProfile.source_parent_population_profile
