import Theorems.Thm_StickyKakeya4_native_fixed_reference_angular_profile
set_option autoImplicit false
#print axioms NativeFixedReferenceAngularProfile.ballIncidences
#print axioms NativeFixedReferenceAngularProfile.ballDirections
#print axioms NativeFixedReferenceAngularProfile.ballDirections_card
#print axioms NativeFixedReferenceAngularProfile.formal_uniformity
#print axioms NativeFixedReferenceAngularProfile.parent_point_uniformity
#print axioms NativeFixedReferenceAngularProfile.uniform_point_fiber_le_mean
#print axioms NativeFixedReferenceAngularProfile.parent_point_fiber_bounds
#print axioms NativeFixedReferenceAngularProfile.parent_point_fiber_upper
#print axioms NativeFixedReferenceAngularProfile.same_parent_direction_close
#print axioms NativeFixedReferenceAngularProfile.scheduled_ball_lower
#print axioms NativeFixedReferenceAngularProfile.floor_mem_radius
#print axioms NativeFixedReferenceAngularProfile.ball_angular_cells_card
#print axioms NativeFixedReferenceAngularProfile.scheduled_ball_upper
#print axioms NativeFixedReferenceAngularProfile.scheduled_angular_profile
#print axioms NativeFixedReferenceAngularProfile.relative_power
#print axioms NativeFixedReferenceAngularProfile.scheduled_angular_power_profile
