import Theorems.Thm_StickyKakeya4_native_sharp_parent_graph_configuration

#print axioms NativeSharpParentGraphConfiguration.SharpCurveParentFinalCleanupData
#print axioms NativeSharpParentGraphConfiguration.HasSharpCurveParentRetainedHistory
#print axioms NativeSharpParentGraphConfiguration.HasSharpCurveParentStage
#print axioms NativeSharpParentGraphConfiguration.middleSelected
#print axioms NativeSharpParentGraphConfiguration.middle_selected_depth
#print axioms NativeSharpParentGraphConfiguration.half_depth_eq_depth
#print axioms NativeSharpParentGraphConfiguration.sharp_stage_with_parent_graph
#print axioms NativeSharpParentGraphConfiguration.exists_sharp_parent_graph_configuration
