import Theorems.Thm_StickyKakeya4_native_actual_angular_menu_cost
import Theorems.Thm_StickyKakeya4_native_automatic_weighted_grain_core
import Theorems.Thm_StickyKakeya4_native_nodal_reference_lift
import Theorems.Thm_StickyKakeya4_native_original_packet_reference
import Theorems.Thm_StickyKakeya4_native_tagged_packet_rows

set_option autoImplicit false
#print axioms NativeActualAngularMenuCost.actual_cost_ratio_lower
#print axioms NativeActualAngularMenuCost.original_factor_pos
#print axioms NativeActualAngularMenuCost.parent_scale_identity
#print axioms NativeActualAngularMenuCost.retained_mean_lower
#print axioms NativeActualAngularMenuCost.stopping_weighted_numerator
#print axioms NativeAutomaticWeightedGrainCore.exists_automatic_simultaneous_dense_core
#print axioms NativeAutomaticWeightedGrainCore.threshold
#print axioms NativeAutomaticWeightedGrainCore.threshold_budget
#print axioms NativeAutomaticWeightedGrainCore.threshold_crossmul
#print axioms NativeAutomaticWeightedGrainCore.threshold_pos
#print axioms NativeAutomaticWeightedGrainCore.threshold_real
#print axioms NativeNodalReferenceLift.boxReference
#print axioms NativeNodalReferenceLift.boxReference_mass
#print axioms NativeNodalReferenceLift.box_reference_duplication
#print axioms NativeNodalReferenceLift.currentLift
#print axioms NativeNodalReferenceLift.currentLift_card
#print axioms NativeNodalReferenceLift.currentLift_mass
#print axioms NativeNodalReferenceLift.currentLift_snd_injective
#print axioms NativeNodalReferenceLift.currentLift_subset_reference
#print axioms NativeNodalReferenceLift.fixed_node_vertex_mass
#print axioms NativeNodalReferenceLift.occupiedLabels_nodes
#print axioms NativeNodalReferenceLift.referenceLift
#print axioms NativeNodalReferenceLift.referenceLift_card
#print axioms NativeNodalReferenceLift.referenceLift_original
#print axioms NativeNodalReferenceLift.referenceLift_subset_box
#print axioms NativeNodalReferenceLift.reference_label_duplication
#print axioms NativeNodalReferenceLift.roundedVertex
#print axioms NativeNodalReferenceLift.roundedVertex_distance
#print axioms NativeNodalReferenceLift.rounded_currentLift_subset_box
#print axioms NativeNodalReferenceLift.rounded_occupied_overlap
#print axioms NativeNodalReferenceLift.taggedPacket
#print axioms NativeNodalReferenceLift.tagged_packet_overlap
#print axioms NativeOriginalPacketReference.full_fiber_mem_packet
#print axioms NativeOriginalPacketReference.rawVertex
#print axioms NativeTaggedPacketRows.assignedLabel
#print axioms NativeTaggedPacketRows.packetSet
#print axioms NativeTaggedPacketRows.reference
#print axioms NativeTaggedPacketRows.short_closure_tag_subset
