import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_incidence

#print axioms NativeReferenceXYGridIncidence.original_edge_rawPoint
#print axioms NativeReferenceXYGridIncidence.original_edge_rawPoint_three_rho
#print axioms NativeReferenceXYGridIncidence.dyadic_original_edge_rawPoint
#print axioms NativeReferenceXYGridIncidence.retained_original_rawPoint_incidence
#print axioms NativeReferenceXYGridIncidence.frame
#print axioms NativeReferenceXYGridIncidence.frame_line_formula
#print axioms NativeReferenceXYGridIncidence.frame_dist_le
#print axioms NativeReferenceXYGridIncidence.frame_infDist_le
#print axioms NativeReferenceXYGridIncidence.point_quotient_reconstruction
#print axioms NativeReferenceXYGridIncidence.frame_injective
#print axioms NativeReferenceXYGridIncidence.framed_retained_original_incidence
