import Theorems.Thm_StickyKakeya4_native_actual_sparse_reference_admission
import Theorems.Thm_StickyKakeya4_native_output_alignment_menu_budget
import Theorems.Thm_StickyKakeya4_native_Y_common_scale_selection
set_option autoImplicit false
#print axioms NativeActualSparseReferenceAdmission.retentionFactor
#print axioms NativeActualSparseReferenceAdmission.exists_actual_sparse_admission
#print axioms NativeOutputAlignmentMenuBudget.exists_menu_cutoff
#print axioms NativeOutputAlignmentMenuBudget.inverse_selected_fraction
#print axioms NativeYCommonScaleSelection.menu_card
#print axioms NativeYCommonScaleSelection.select_common
