import Theorems.Thm_StickyKakeya4_native_fixed_zero_original_theorem
import Theorems.Thm_StickyKakeya4_native_raw_point_source_profiles

set_option autoImplicit false
#print axioms NativeFixedZeroOriginalTheorem.sticky_kakeya_four_dimensional_of_fixed_zero
#print axioms NativeRawPointSourceProfiles.full_mass_eq_multiplicity_point_volume
#print axioms NativeRawPointSourceProfiles.middle_raw_point_profile
#print axioms NativeRawPointSourceProfiles.rawPointCount
#print axioms NativeRawPointSourceProfiles.raw_point_lower_with_retention
#print axioms NativeRawPointSourceProfiles.raw_point_upper
#print axioms NativeRawPointSourceProfiles.shadowPointCount
#print axioms NativeRawPointSourceProfiles.two_stage_incidence_retention
