import Theorems.Thm_StickyKakeya4_native_actual_quotient_density
import Theorems.Thm_StickyKakeya4_native_actual_quotient_support
import Theorems.Thm_StickyKakeya4_native_encoded_quotient_ad
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_source_angular_cap
import Theorems.Thm_StickyKakeya4_native_saturated_angular_power_lower
import Theorems.Thm_StickyKakeya4_native_saturated_source_angular_rank_lower
import Theorems.Thm_StickyKakeya4_native_sharp_X_budget_costs

set_option autoImplicit false
#print axioms NativeActualQuotientDensity.normalized_density
#print axioms NativeActualQuotientDensity.reference_cross_dense
#print axioms NativeActualQuotientDensity.rho_halfWidth
#print axioms NativeActualQuotientSupport.encoded_image
#print axioms NativeActualQuotientSupport.halfWidth_pos
#print axioms NativeActualQuotientSupport.product_support
#print axioms NativeActualQuotientSupport.quotient_exponent
#print axioms NativeEncodedQuotientAD.quotientConstant
#print axioms NativeEncodedQuotientAD.quotientConstant_one_le
#print axioms NativeEncodedQuotientAD.quotient_AD_of_encoded_AD
#print axioms NativeReferenceXYGridSourceAngularCap.actual_point_angular_cap
#print axioms NativeReferenceXYGridSourceAngularCap.angularCapConstant
#print axioms NativeReferenceXYGridSourceAngularCap.dyadic_cap_power
#print axioms NativeReferenceXYGridSourceAngularCap.dyadic_resolution
#print axioms NativeReferenceXYGridSourceAngularCap.pointMenu_original_card
#print axioms NativeReferenceXYGridSourceAngularCap.point_menu_cap
#print axioms NativeReferenceXYGridSourceAngularCap.quotient_anchor_readback
#print axioms NativeSaturatedAngularPowerLower.actual_angular_scale_ratio
#print axioms NativeSaturatedAngularPowerLower.ancestor_parent_power_upper
#print axioms NativeSaturatedAngularPowerLower.cancel_parent_powers
#print axioms NativeSaturatedAngularPowerLower.local_scale_ratio
#print axioms NativeSaturatedAngularPowerLower.saturated_reference_power_lower
#print axioms NativeSaturatedSourceAngularRankLower.actual_saturated_angular_rank_lower
#print axioms NativeSharpXBudgetCosts.rank_denominator
#print axioms NativeSharpXBudgetCosts.raw_cost_power
#print axioms NativeSharpXBudgetCosts.reference_factor
#print axioms NativeSharpXBudgetCosts.transverse_power
