import Theorems.Thm_StickyKakeya4_native_actual_offset_cell_caps
import Theorems.Thm_StickyKakeya4_native_actual_sharp_X_lower
import Theorems.Thm_StickyKakeya4_native_fixed_coherence_cost
import Theorems.Thm_StickyKakeya4_native_fixed_offset_coherence
import Theorems.Thm_StickyKakeya4_native_half_scale_interpolation
import Theorems.Thm_StickyKakeya4_native_quotient_fiber_readback
import Theorems.Thm_StickyKakeya4_native_quotient_grid_centers
import Theorems.Thm_StickyKakeya4_native_quotient_lattice_counts
import Theorems.Thm_StickyKakeya4_native_quotient_lattice_transport
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_angular_cap
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_support
import Theorems.Thm_StickyKakeya4_native_reference_original_parent_profiles
import Theorems.Thm_StickyKakeya4_native_saturated_ancestor_angular_lower
import Theorems.Thm_StickyKakeya4_native_saturated_angular_rank_budget
import Theorems.Thm_StickyKakeya4_native_sharp_X_power_algebra
import Theorems.Thm_StickyKakeya4_native_sharp_X_source_count

set_option autoImplicit false
#print axioms NativeActualOffsetCellCaps.actual_cell_offset_cap
#print axioms NativeActualOffsetCellCaps.point_fiber_in_cell
#print axioms NativeActualSharpXLower.source_reference_X_cross
#print axioms NativeFixedCoherenceCost.actual_cap_one_le
#print axioms NativeFixedCoherenceCost.ceiling_product_bound
#print axioms NativeFixedCoherenceCost.fixed_round_power_cost
#print axioms NativeFixedOffsetCoherence.offsetMesh
#print axioms NativeFixedOffsetCoherence.offsetMesh_pos
#print axioms NativeFixedOffsetCoherence.same_offset_norm
#print axioms NativeFixedOffsetCoherence.select_fixed_offset_menu
#print axioms NativeHalfScaleInterpolation.ADBounds_of_counts
#print axioms NativeHalfScaleInterpolation.all_radius_counts
#print axioms NativeHalfScaleInterpolation.constant
#print axioms NativeHalfScaleInterpolation.constant_one_le
#print axioms NativeQuotientFiberReadback.actual_referenceX_card
#print axioms NativeQuotientFiberReadback.product_fiber_card
#print axioms NativeQuotientFiberReadback.product_fiber_image
#print axioms NativeQuotientGridCenters.ball_card
#print axioms NativeQuotientGridCenters.center
#print axioms NativeQuotientGridCenters.center_dist_iff
#print axioms NativeQuotientGridCenters.center_injective
#print axioms NativeQuotientGridCenters.quotient_ball_count
#print axioms NativeQuotientGridCenters.quotient_card
#print axioms NativeQuotientLatticeCounts.global_card_le
#print axioms NativeQuotientLatticeCounts.global_quotient_card_le
#print axioms NativeQuotientLatticeCounts.quotient_counts
#print axioms NativeQuotientLatticeTransport.ambient_bounds_of_AD
#print axioms NativeQuotientLatticeTransport.ambient_box_real_card
#print axioms NativeQuotientLatticeTransport.atHeight
#print axioms NativeQuotientLatticeTransport.atHeight_injective
#print axioms NativeQuotientLatticeTransport.height_slice_eq
#print axioms NativeQuotientLatticeTransport.productSlice
#print axioms NativeQuotientLatticeTransport.realized_slice_eq
#print axioms NativeQuotientLatticeTransport.spatial_ball_eq
#print axioms NativeQuotientLatticeTransport.spatial_box_iff
#print axioms NativeReferenceOriginalParentProfiles.actual_all_parent_profiles
#print axioms NativeReferenceOriginalParentProfiles.endpoint_constant_from_first_cost
#print axioms NativeReferenceXYGridAngularCap.affine_angle_cap
#print axioms NativeReferenceXYGridAngularCap.angle
#print axioms NativeReferenceXYGridAngularCap.angle_mem_box
#print axioms NativeReferenceXYGridAngularCap.localAngle
#print axioms NativeReferenceXYGridAngularCap.localAngle_image_card
#print axioms NativeReferenceXYGridAngularCap.localAngle_inverse
#print axioms NativeReferenceXYGridAngularCap.original_angular_cap
#print axioms NativeReferenceXYGridAngularCap.same_tangent_bin_diameter
#print axioms NativeReferenceXYGridAngularCap.source_local_angle_cap
#print axioms NativeReferenceXYGridSupport.dyadic_pxy_support
#print axioms NativeReferenceXYGridSupport.halfWidth
#print axioms NativeReferenceXYGridSupport.label_support
#print axioms NativeReferenceXYGridSupport.mu_fullWidth
#print axioms NativeReferenceXYGridSupport.mu_halfWidth
#print axioms NativeReferenceXYGridSupport.oldPoint_norm
#print axioms NativeReferenceXYGridSupport.pxy_support
#print axioms NativeReferenceXYGridSupport.rawPoint_norm
#print axioms NativeReferenceXYGridSupport.terminal_bounds
#print axioms NativeSaturatedAncestorAngularLower.ancestor_point_fiber_upper
#print axioms NativeSaturatedAncestorAngularLower.saturated_ancestor_point_lower
#print axioms NativeSaturatedAngularRankBudget.angular_parent_cost
#print axioms NativeSaturatedAngularRankBudget.angular_rank_cost
#print axioms NativeSharpXPowerAlgebra.fiberCoefficient
#print axioms NativeSharpXPowerAlgebra.gain_identity
#print axioms NativeSharpXPowerAlgebra.gain_to_X
#print axioms NativeSharpXSourceCount.cancel_depth_and_taxes_le
#print axioms NativeSharpXSourceCount.source_threshold_cross_cancellation
