import Theorems.Thm_StickyKakeya4_native_conditional_coarse_interpolation

#print axioms NativeConditionalCoarseInterpolation.subset_image_multiplicity
#print axioms NativeConditionalCoarseInterpolation.image_parent_filter
#print axioms NativeConditionalCoarseInterpolation.physicalPair_parent
#print axioms NativeConditionalCoarseInterpolation.physical_image_parent
#print axioms NativeConditionalCoarseInterpolation.finer_outer_parent_upper
#print axioms NativeConditionalCoarseInterpolation.coarser_outer_parent_lower
