import Theorems.Thm_StickyKakeya4_native_actual_history_configuration
import Theorems.Thm_StickyKakeya4_native_actual_rank_four_count
import Theorems.Thm_StickyKakeya4_native_horizontal_grain_slice
import Theorems.Thm_StickyKakeya4_native_history_grain_cleanup

set_option autoImplicit false
#print axioms NativeActualHistoryConfiguration.HasHistorySquaredStage
#print axioms NativeActualHistoryConfiguration.exists_actual_history_configuration
#print axioms NativeActualHistoryConfiguration.history_stage_of_compatible
#print axioms NativeActualRankFourCount.actual_rank_four_count
#print axioms NativeActualRankFourCount.clear_four_count
#print axioms NativeActualRankFourCount.rankFourConstant
#print axioms NativeActualRankFourCount.rankFourConstant_pos
#print axioms NativeHistoryGrainCleanup.classical_image_eq
#print axioms NativeHistoryGrainCleanup.density_from_count
#print axioms NativeHistoryGrainCleanup.exists_actual_final_grain_core
#print axioms NativeHorizontalGrainSlice.affine_slice_containment
#print axioms NativeHorizontalGrainSlice.heightKernel
#print axioms NativeHorizontalGrainSlice.heightKernel_finrank
#print axioms NativeHorizontalGrainSlice.near_horizontal_slice
#print axioms NativeHorizontalGrainSlice.removeHeight
#print axioms NativeHorizontalGrainSlice.removeHeight_mem_heightKernel
#print axioms NativeHorizontalGrainSlice.removeHeight_mem_slice
#print axioms NativeHorizontalGrainSlice.removeHeight_norm
#print axioms NativeHorizontalGrainSlice.removeHeight_sub
#print axioms NativeHorizontalGrainSlice.sliceSpace
#print axioms NativeHorizontalGrainSlice.sliceSpace_finrank
