import Theorems.Thm_StickyKakeya4_native_actual_angular_menu_lower
import Theorems.Thm_StickyKakeya4_native_nodal_packet_overlap
import Theorems.Thm_StickyKakeya4_native_packet_retained_layers
import Theorems.Thm_StickyKakeya4_native_simultaneous_weighted_grain_core

set_option autoImplicit false
#print axioms NativeActualAngularMenuLower.mean_le_point_fiber
#print axioms NativeActualAngularMenuLower.point_angular_menu_lower
#print axioms NativeActualAngularMenuLower.weighted_angular_numerator_lower
#print axioms NativeNodalPacketOverlap.graph_displacement
#print axioms NativeNodalPacketOverlap.hit_node_mem_box
#print axioms NativeNodalPacketOverlap.hits
#print axioms NativeNodalPacketOverlap.nodal_duplication
#print axioms NativeNodalPacketOverlap.nodal_packet_overlap
#print axioms NativeNodalPacketOverlap.node_mem_box
#print axioms NativeNodalPacketOverlap.normal_norm_le_infDist
#print axioms NativeNodalPacketOverlap.occupiedLabels
#print axioms NativeNodalPacketOverlap.occupiedLabels_anchors
#print axioms NativeNodalPacketOverlap.occupied_overlap
#print axioms NativeNodalPacketOverlap.original_anchor_distance
#print axioms NativeNodalPacketOverlap.packet_anchor_distance
#print axioms NativePacketRetainedLayers.active_count_reference_budget
#print axioms NativePacketRetainedLayers.construct_actual_packet_layers
#print axioms NativePacketRetainedLayers.le_referenceMinimum
#print axioms NativePacketRetainedLayers.referenceBudget
#print axioms NativePacketRetainedLayers.referenceBudget_positive
#print axioms NativePacketRetainedLayers.referenceMinimum
#print axioms NativePacketRetainedLayers.referenceMinimum_le
#print axioms NativeSimultaneousWeightedGrainCore.classBudget
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_budget
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_mass
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_subset
#print axioms NativeSimultaneousWeightedGrainCore.exists_simultaneous_dense_core
#print axioms NativeSimultaneousWeightedGrainCore.exists_simultaneous_dense_core_half
#print axioms NativeSimultaneousWeightedGrainCore.removed_mass_le
