import Theorems.Thm_StickyKakeya4_native_compatible_weighted_retention

#print axioms NativeCompatibleWeightedRetention.menuCost
#print axioms NativeCompatibleWeightedRetention.combinedLoss
#print axioms NativeCompatibleWeightedRetention.retainedFraction
#print axioms NativeCompatibleWeightedRetention.menuCost_pos
#print axioms NativeCompatibleWeightedRetention.retainedFraction_closed_form
#print axioms NativeCompatibleWeightedRetention.denominator_power
#print axioms NativeCompatibleWeightedRetention.cancel_terminal_scale
#print axioms NativeCompatibleWeightedRetention.RetainedFamily
#print axioms NativeCompatibleWeightedRetention.retainedFamily_mono
#print axioms NativeCompatibleWeightedRetention.exact_retention_from_numerator
#print axioms NativeCompatibleWeightedRetention.from_master_and_actual_cost
#print axioms NativeCompatibleWeightedRetention.combinedLoss_budget
#print axioms NativeCompatibleWeightedRetention.delta_loss_lower
#print axioms NativeCompatibleWeightedRetention.exists_rank_retention_cutoff
#print axioms NativeCompatibleWeightedRetention.exists_uniform_weak_retention
