import Theorems.Thm_StickyKakeya4_native_actual_XY_grain_core
import Theorems.Thm_StickyKakeya4_native_actual_sharp_X_power_loss
import Theorems.Thm_StickyKakeya4_native_all_two_scale_extra_configuration
import Theorems.Thm_StickyKakeya4_native_candidate_reference_admission
import Theorems.Thm_StickyKakeya4_native_candidate_reference_configuration
import Theorems.Thm_StickyKakeya4_native_initial_extra_relations
import Theorems.Thm_StickyKakeya4_native_middle_two_scale_extra_configuration
import Theorems.Thm_StickyKakeya4_native_parent_local_XY_grain_core
import Theorems.Thm_StickyKakeya4_native_reference_angular_power_budget
import Theorems.Thm_StickyKakeya4_native_third_XY_data

set_option autoImplicit false
#print axioms NativeActualSharpXPowerLoss.source_reference_X_power_lower_with_loss
#print axioms NativeActualXYGrainCore.exists_actual_xy_grain_core
#print axioms NativeAllTwoScaleExtraConfiguration.exists_all_two_scale_extra_configuration
#print axioms NativeCandidateReferenceAdmission.exists_candidate_menu_angular_upper
#print axioms NativeCandidateReferenceConfiguration.HasCandidateReferenceUpper
#print axioms NativeCandidateReferenceConfiguration.exists_candidate_reference_configuration
#print axioms NativeInitialExtraRelations.caller_uniformities
#print axioms NativeInitialExtraRelations.relations
#print axioms NativeInitialExtraRelations.relations_refl
#print axioms NativeInitialExtraRelations.relations_symm
#print axioms NativeMiddleTwoScaleExtraConfiguration.exists_middle_two_scale_extra_configuration
#print axioms NativeParentLocalXYGrainCore.exists_parent_local_xy_grain_core
#print axioms NativeReferenceAngularPowerBudget.coherence_excess_factor
#print axioms NativeReferenceAngularPowerBudget.coherence_radius_payment
#print axioms NativeReferenceAngularPowerBudget.first_cost_angular_factor
#print axioms NativeReferenceAngularPowerBudget.independent_exponent_margin
#print axioms NativeReferenceAngularPowerBudget.relative_power_payment
#print axioms NativeThirdXYData.HasThirdXYData
#print axioms NativeThirdXYData.xyConstant
#print axioms NativeThirdXYData.xyConstant_one_le
