import Theorems.Thm_StickyKakeya4_native_prescribed_population_parent_configuration

#print axioms NativePrescribedPopulationParentConfiguration.PrescribedParentFinalCleanupData
#print axioms NativePrescribedPopulationParentConfiguration.HasPrescribedParentRetainedHistory
#print axioms NativePrescribedPopulationParentConfiguration.HasPrescribedPopulationParentStage
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_stage_with_population_parent
#print axioms NativePrescribedPopulationParentConfiguration.exists_prescribed_population_parent_configuration
#print axioms NativePrescribedPopulationParentConfiguration.complete_profiles_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_parent_cleanup_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_parent_retained_forget
#print axioms NativePrescribedPopulationParentConfiguration.prescribed_population_stage_forget
