import Theorems.Thm_StickyKakeya4_native_actual_parent_height_chart
import Theorems.Thm_StickyKakeya4_native_parent_height_graph_core
import Theorems.Thm_StickyKakeya4_native_retained_slice_count_transfer

set_option autoImplicit false
#print axioms NativeActualParentHeightChart.nodeCut_image
#print axioms NativeActualParentHeightChart.nodeCut_nested
#print axioms NativeActualParentHeightChart.select_actual_parent_height_chart
#print axioms NativeParentHeightGraphCore.construct_parent_height_graph_core
#print axioms NativeParentHeightGraphCore.selectionCost
#print axioms NativeRetainedSliceCountTransfer.point_class_homogeneity
#print axioms NativeRetainedSliceCountTransfer.point_image_retention
#print axioms NativeRetainedSliceCountTransfer.retained_class_count_cross
#print axioms NativeRetainedSliceCountTransfer.retained_class_count_lower
