import Theorems.Thm_StickyKakeya4_original_weighted_macro_selection
set_option autoImplicit false
#print axioms OriginalWeightedMacroSelection.localPoints
#print axioms OriginalWeightedMacroSelection.localHeights
#print axioms OriginalWeightedMacroSelection.sum_original_local_points
#print axioms OriginalWeightedMacroSelection.occupiedHeightPairs
#print axioms OriginalWeightedMacroSelection.local_heights_pair_fiber
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_pairs
#print axioms OriginalWeightedMacroSelection.sum_local_heights_eq_height_cells
#print axioms OriginalWeightedMacroSelection.weighted_denominator_of_height_cells
#print axioms OriginalWeightedMacroSelection.exists_original_weighted_macro
#print axioms OriginalWeightedMacroSelection.exists_physical_weighted_macro
