import Theorems.Thm_StickyKakeya4_native_actual_population_parent_configuration

#print axioms NativeActualPopulationParentConfiguration.ParentFinalCleanupData
#print axioms NativeActualPopulationParentConfiguration.HasParentRetainedHistory
#print axioms NativeActualPopulationParentConfiguration.HasPopulationParentStage
#print axioms NativeActualPopulationParentConfiguration.stage_with_population_parent
#print axioms NativeActualPopulationParentConfiguration.exists_actual_population_parent_configuration
