import Theorems.Thm_StickyKakeya4_native_translated_grain_height_selection

#print axioms NativeTranslatedGrainHeightSelection.first
#print axioms NativeTranslatedGrainHeightSelection.second
#print axioms NativeTranslatedGrainHeightSelection.first_subset
#print axioms NativeTranslatedGrainHeightSelection.second_subset_first
#print axioms NativeTranslatedGrainHeightSelection.second_subset
#print axioms NativeTranslatedGrainHeightSelection.rawHeight_of_mixed_eq
#print axioms NativeTranslatedGrainHeightSelection.first_menu
#print axioms NativeTranslatedGrainHeightSelection.second_menu
#print axioms NativeTranslatedGrainHeightSelection.first_card_retention
#print axioms NativeTranslatedGrainHeightSelection.second_card_retention
#print axioms NativeTranslatedGrainHeightSelection.card_retention_four
#print axioms NativeTranslatedGrainHeightSelection.selected_uniform
#print axioms NativeTranslatedGrainHeightSelection.first_translated_constant
#print axioms NativeTranslatedGrainHeightSelection.translated_determines_raw
#print axioms NativeTranslatedGrainHeightSelection.second_saturated
#print axioms NativeTranslatedGrainHeightSelection.surviving_grain_eq
#print axioms NativeTranslatedGrainHeightSelection.surviving_local_retention
#print axioms NativeTranslatedGrainHeightSelection.hereditary_alignment
