import Theorems.Thm_StickyKakeya4_native_original_tuple_parent_interpolation

#print axioms NativeOriginalTupleParentInterpolation.point_parent_fiber_subset_ancestor
#print axioms NativeOriginalTupleParentInterpolation.point_parent_fiber_upper_of_ancestor
#print axioms NativeOriginalTupleParentInterpolation.coarse_menu_lower_of_ancestor
