import Theorems.Thm_StickyKakeya4_native_parent_grain_incidence_cleanup

#print axioms NativeParentGrainIncidenceCleanup.cutEdges
#print axioms NativeParentGrainIncidenceCleanup.mixedLabel
#print axioms NativeParentGrainIncidenceCleanup.mixedFiber
#print axioms NativeParentGrainIncidenceCleanup.mixedVertices
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_subset
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_card
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_points
#print axioms NativeParentGrainIncidenceCleanup.cutEdges_grain_image
#print axioms NativeParentGrainIncidenceCleanup.parent_mixed_fiber_eq
#print axioms NativeParentGrainIncidenceCleanup.mixed_fiber_geometry
#print axioms NativeParentGrainIncidenceCleanup.mixed_label_count
#print axioms NativeParentGrainIncidenceCleanup.mixed_fiber_vertex_cap
#print axioms NativeParentGrainIncidenceCleanup.exists_mixed_dense_core
#print axioms NativeParentGrainIncidenceCleanup.exists_cleaned_parent
