import Theorems.Thm_StickyKakeya4_native_normalized_cell_relative_core
import Theorems.Thm_StickyKakeya4_native_normalized_cell_relative_menu
import Theorems.Thm_StickyKakeya4_native_normalized_cell_source_upper
import Theorems.Thm_StickyKakeya4_native_parent_local_slice_grain_ad
import Theorems.Thm_StickyKakeya4_native_parent_slice_relation_readback
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_linear
import Theorems.Thm_StickyKakeya4_native_sharp_complete_parent_profiles
import Theorems.Thm_StickyKakeya4_native_sharp_mixed_grain_core
import Theorems.Thm_StickyKakeya4_native_sharp_population_parent_configuration
import Theorems.Thm_StickyKakeya4_native_sharp_population_parent_profiles

set_option autoImplicit false
#print axioms NativeNormalizedCellRelativeCore.backboneRepresentative
#print axioms NativeNormalizedCellRelativeCore.caller_relative_uniformities
#print axioms NativeNormalizedCellRelativeCore.normalizedPair
#print axioms NativeNormalizedCellRelativeCore.normalized_cell_degree_upper
#print axioms NativeNormalizedCellRelativeCore.pairLabel
#print axioms NativeNormalizedCellRelativeCore.physical_fiber_relative_menu
#print axioms NativeNormalizedCellRelativeCore.pointLabel
#print axioms NativeNormalizedCellRelativeCore.relations
#print axioms NativeNormalizedCellRelativeCore.relations_refl
#print axioms NativeNormalizedCellRelativeCore.relations_symm
#print axioms NativeNormalizedCellRelativeMenu.double_front_physical_error
#print axioms NativeNormalizedCellRelativeMenu.double_label_mem_forward
#print axioms NativeNormalizedCellRelativeMenu.forwardMenu
#print axioms NativeNormalizedCellRelativeMenu.forwardMenu_card
#print axioms NativeNormalizedCellRelativeMenu.physicalCell
#print axioms NativeNormalizedCellRelativeMenu.physicalPoint
#print axioms NativeNormalizedCellRelativeMenu.zero_local_front
#print axioms NativeNormalizedCellSourceUpper.exists_source_normalized_degree_upper
#print axioms NativeNormalizedCellSourceUpper.source_native_from_population
#print axioms NativeParentLocalSliceGrainAD.exists_parent_local_slice_grain_AD
#print axioms NativeParentSliceRelationReadback.parentEdges_twice
#print axioms NativeParentSliceRelationReadback.parent_relations
#print axioms NativeReferenceXYGridLinear.coordinates_remove_vertical
#print axioms NativeReferenceXYGridLinear.euclidean_norm_le_sum
#print axioms NativeReferenceXYGridLinear.horizontal_inverse
#print axioms NativeReferenceXYGridLinear.inverse_norm
#print axioms NativeReferenceXYGridLinear.matrix_action_norm
#print axioms NativeReferenceXYGridLinear.normalCoordinates
#print axioms NativeReferenceXYGridLinear.normalCoordinates_norm
#print axioms NativeReferenceXYGridLinear.normalProjection_horizontal
#print axioms NativeReferenceXYGridLinear.normal_norm_le
#print axioms NativeReferenceXYGridLinear.quotientMap
#print axioms NativeReferenceXYGridLinear.quotient_norm_le
#print axioms NativeReferenceXYGridLinear.tangent_norm_le
#print axioms NativeReferenceXYGridLinear.totalField
#print axioms NativeReferenceXYGridLinear.totalField_norm
#print axioms NativeReferenceXYGridLinear.totalField_off
#print axioms NativeReferenceXYGridLinear.totalField_on
#print axioms NativeReferenceXYGridLinear.vertical
#print axioms NativeReferenceXYGridLinear.vertical_last
#print axioms NativeReferenceXYGridLinear.vertical_norm
#print axioms NativeReferenceXYGridLinear.vertical_orthogonal
#print axioms NativeSharpCompleteParentProfiles.HasSharpCompleteParentProfiles
#print axioms NativeSharpCompleteParentProfiles.complete_sharp_selected_parent_profiles
#print axioms NativeSharpMixedGrainCore.HasMixedIncidenceThreshold
#print axioms NativeSharpMixedGrainCore.source_sharp_mixed_grain_core
#print axioms NativeSharpPopulationParentConfiguration.HasSharpParentRetainedHistory
#print axioms NativeSharpPopulationParentConfiguration.HasSharpPopulationParentStage
#print axioms NativeSharpPopulationParentConfiguration.SharpParentFinalCleanupData
#print axioms NativeSharpPopulationParentConfiguration.exists_sharp_population_parent_configuration
#print axioms NativeSharpPopulationParentConfiguration.sharp_stage_with_population_parent
#print axioms NativeSharpPopulationParentProfiles.HasSharpPopulationParentProfiles
#print axioms NativeSharpPopulationParentProfiles.source_sharp_population_parent_profiles
