import Theorems.Thm_StickyKakeya4_native_all_dyadic_reference_angular_upper
import Theorems.Thm_StickyKakeya4_native_angular_bottom_endpoint
import Theorems.Thm_StickyKakeya4_native_candidate_paid_XY_configuration
import Theorems.Thm_StickyKakeya4_native_conditional_grid_coverage
import Theorems.Thm_StickyKakeya4_native_conditional_grid_power_cost
import Theorems.Thm_StickyKakeya4_native_conditional_upper_parameters
import Theorems.Thm_StickyKakeya4_native_extra_paid_XY_configuration
import Theorems.Thm_StickyKakeya4_native_paid_XY_parameters
import Theorems.Thm_StickyKakeya4_native_paid_mesh_angular_upper
import Theorems.Thm_StickyKakeya4_native_paid_third_budget
import Theorems.Thm_StickyKakeya4_native_paid_third_readback
import Theorems.Thm_StickyKakeya4_native_variable_height_numerator_upper
import Theorems.Thm_StickyKakeya4_native_variable_height_reference_counts
import Theorems.Thm_StickyKakeya4_native_variable_height_row_lower
import Theorems.Thm_StickyKakeya4_native_variable_height_source_bridge
import Theorems.Thm_StickyKakeya4_native_variable_height_source_counts
import Theorems.Thm_StickyKakeya4_native_window_XY_menus
import Theorems.Thm_StickyKakeya4_native_window_XY_source_caps
import Theorems.Thm_StickyKakeya4_native_window_X_fibers

set_option autoImplicit false
#print axioms NativeAllDyadicReferenceAngularUpper.exists_all_dyadic_angular_ball_upper
#print axioms NativeAllDyadicReferenceAngularUpper.width_mono
#print axioms NativeAngularBottomEndpoint.extend_bottom
#print axioms NativeCandidatePaidXYConfiguration.exists_candidate_paid_XY_configuration
#print axioms NativeConditionalGridCoverage.exists_grid_predecessor
#print axioms NativeConditionalGridCoverage.exists_query_predecessors
#print axioms NativeConditionalGridCoverage.gridDepth_schedule
#print axioms NativeConditionalGridCoverage.queryIndex
#print axioms NativeConditionalGridCoverage.queryIndex_candidate
#print axioms NativeConditionalGridCoverage.queryIndex_pair
#print axioms NativeConditionalGridPowerCost.dyadic_width_ratio
#print axioms NativeConditionalGridPowerCost.gap_cost
#print axioms NativeConditionalGridPowerCost.middle_width_dyadic
#print axioms NativeConditionalGridPowerCost.two_scale_cost
#print axioms NativeConditionalUpperParameters.exists_upper_parameters
#print axioms NativeExtraPaidXYConfiguration.exists_extra_paid_XY_configuration
#print axioms NativePaidMeshAngularUpper.exists_paid_mesh_angular_ball_upper
#print axioms NativePaidMeshAngularUpper.meshAngularConstant
#print axioms NativePaidThirdBudget.HasBudget
#print axioms NativePaidThirdBudget.exists_paid_third_budget
#print axioms NativePaidThirdReadback.constants_from_budget
#print axioms NativePaidXYParameters.exists_parameters
#print axioms NativeVariableHeightNumeratorUpper.pairUpperConstant
#print axioms NativeVariableHeightNumeratorUpper.pairUpperConstant_pos
#print axioms NativeVariableHeightNumeratorUpper.parent_column_pair_upper
#print axioms NativeVariableHeightNumeratorUpper.shortRowColumnCost
#print axioms NativeVariableHeightNumeratorUpper.short_pair_column_image_card
#print axioms NativeVariableHeightReferenceCounts.column_multiplicity_card
#print axioms NativeVariableHeightReferenceCounts.column_point_image
#print axioms NativeVariableHeightReferenceCounts.reference_column_point_power_bounds
#print axioms NativeVariableHeightReferenceCounts.reference_numerator_height_bounds
#print axioms NativeVariableHeightRowLower.chargeConstant
#print axioms NativeVariableHeightRowLower.parent_counts_of_actual_rows
#print axioms NativeVariableHeightRowLower.queried_parent_counts_lower
#print axioms NativeVariableHeightRowLower.shortEdges_subset_parent
#print axioms NativeVariableHeightSourceBridge.comparisonCost
#print axioms NativeVariableHeightSourceBridge.comparisonCost_pos
#print axioms NativeVariableHeightSourceBridge.queried_global_source_comparison
#print axioms NativeVariableHeightSourceCounts.queried_column_point_power_bounds
#print axioms NativeWindowXFibers.fineX
#print axioms NativeWindowXFibers.fineX_image_subset
#print axioms NativeWindowXFibers.fine_fiber_card
#print axioms NativeWindowXFibers.gridBox
#print axioms NativeWindowXFibers.gridBox_card
#print axioms NativeWindowXFibers.gridDiv_card_le
#print axioms NativeWindowXFibers.gridDiv_fiber_card
#print axioms NativeWindowXFibers.window_fiber_card
#print axioms NativeWindowXFibers.window_fiber_density
#print axioms NativeWindowXYMenus.forward_menu
#print axioms NativeWindowXYMenus.inverse_menu
#print axioms NativeWindowXYMenus.reference_neighbor
#print axioms NativeWindowXYMenus.window_pxy_x
#print axioms NativeWindowXYMenus.window_pxy_y
#print axioms NativeWindowXYSourceCaps.actual_window_capacities
#print axioms NativeWindowXYSourceCaps.finest_window_capacities
#print axioms NativeWindowXYSourceCaps.scheduled_window_capacities
