import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_hereditary

#print axioms NativeWeightedGrainQuotientHereditary.subset_wholeFiber_card_le_X
#print axioms NativeWeightedGrainQuotientHereditary.edgeX_image_vertices
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_vertices_le_X
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_X_cross
#print axioms NativeWeightedGrainQuotientHereditary.hereditary_mixed_X_subset_fullX
