import Theorems.Thm_StickyKakeya4_native_slice_radius_interpolation
import Theorems.Thm_StickyKakeya4_native_retained_grain_density_transfer
import Theorems.Thm_StickyKakeya4_native_retained_grain_density_core

set_option autoImplicit false
#print axioms NativeRetainedGrainDensityCore.exists_slice_grain_core
#print axioms NativeRetainedGrainDensityCore.grainRelations
#print axioms NativeRetainedGrainDensityCore.grainRelations_refl
#print axioms NativeRetainedGrainDensityCore.grainRelations_symm
#print axioms NativeRetainedGrainDensityTransfer.extra_relation_grain_uniformity
#print axioms NativeRetainedGrainDensityTransfer.original_grain_count_cross
#print axioms NativeRetainedGrainDensityTransfer.retained_grain_density
#print axioms NativeRetainedGrainDensityTransfer.retained_grain_density_two_stage
#print axioms NativeSliceRadiusInterpolation.adjacent_ratio
#print axioms NativeSliceRadiusInterpolation.all_radius_bounds
#print axioms NativeSliceRadiusInterpolation.ballCount
#print axioms NativeSliceRadiusInterpolation.ballCount_mono
#print axioms NativeSliceRadiusInterpolation.bracket_real_radius
#print axioms NativeSliceRadiusInterpolation.radius
#print axioms NativeSliceRadiusInterpolation.radius_pos
