import Theorems.Thm_StickyKakeya4_native_grain_height_projection_transport

#print axioms NativeGrainHeightProjectionTransport.parentDirection
#print axioms NativeGrainHeightProjectionTransport.parentDirection_last
#print axioms NativeGrainHeightProjectionTransport.parentDirection_sub
#print axioms NativeGrainHeightProjectionTransport.parentDirection_slopeVector
#print axioms NativeGrainHeightProjectionTransport.retained_direction_norm
#print axioms NativeGrainHeightProjectionTransport.exists_parent_controlled_direction
#print axioms NativeGrainHeightProjectionTransport.projectToHeight
#print axioms NativeGrainHeightProjectionTransport.projectToHeight_last
#print axioms NativeGrainHeightProjectionTransport.projectToHeight_sub
#print axioms NativeGrainHeightProjectionTransport.physical_projectToHeight
#print axioms NativeGrainHeightProjectionTransport.physical_projection_displacement
#print axioms NativeGrainHeightProjectionTransport.removeHeight_norm_general
#print axioms NativeGrainHeightProjectionTransport.projected_grain_near
