import Theorems.Thm_StickyKakeya4_native_candidate_queried_rank_configuration
import Theorems.Thm_StickyKakeya4_native_conditional_angular_count_transfer
import Theorems.Thm_StickyKakeya4_native_extra_queried_rank_configuration
import Theorems.Thm_StickyKakeya4_native_generic_compatible_stage
import Theorems.Thm_StickyKakeya4_native_nested_parent_physical_menu
import Theorems.Thm_StickyKakeya4_native_parent_angular_coarse_endpoint
import Theorems.Thm_StickyKakeya4_native_reference_parent_complete_angular_upper
import Theorems.Thm_StickyKakeya4_native_third_XY_constant_comparison

set_option autoImplicit false
#print axioms NativeCandidateQueriedRankConfiguration.exists_candidate_queried_rank_configuration
#print axioms NativeConditionalAngularCountTransfer.conditional_angular_count
#print axioms NativeConditionalAngularCountTransfer.nested_angular_count
#print axioms NativeConditionalAngularCountTransfer.nested_parent_power
#print axioms NativeConditionalAngularCountTransfer.nested_relative_width
#print axioms NativeExtraQueriedRankConfiguration.HasCallerUniformities
#print axioms NativeExtraQueriedRankConfiguration.MenuFactory
#print axioms NativeExtraQueriedRankConfiguration.MenuRefl
#print axioms NativeExtraQueriedRankConfiguration.MenuSymm
#print axioms NativeExtraQueriedRankConfiguration.exists_extra_queried_rank_configuration
#print axioms NativeGenericCompatibleStage.HasCompatibleSquaredStage
#print axioms NativeGenericCompatibleStage.compatibleCutoff
#print axioms NativeGenericCompatibleStage.compatibleCutoff_pos
#print axioms NativeGenericCompatibleStage.pairedCount
#print axioms NativeGenericCompatibleStage.select_compatible_squared_stage
#print axioms NativeNestedParentPhysicalMenu.angular_image_global_card
#print axioms NativeNestedParentPhysicalMenu.innerMenu
#print axioms NativeNestedParentPhysicalMenu.innerMenu_card
#print axioms NativeNestedParentPhysicalMenu.nested_angular_image_card
#print axioms NativeNestedParentPhysicalMenu.parent_shear_bound
#print axioms NativeNestedParentPhysicalMenu.physical_cell_mem_innerMenu
#print axioms NativeNestedParentPhysicalMenu.physical_rebase
#print axioms NativeNestedParentPhysicalMenu.rebase
#print axioms NativeNestedParentPhysicalMenu.rebase_coordinate_bound
#print axioms NativeParentAngularCoarseEndpoint.angular_image_box
#print axioms NativeParentAngularCoarseEndpoint.angular_menu_box
#print axioms NativeParentAngularCoarseEndpoint.coarse_endpoint_cost
#print axioms NativeReferenceParentCompleteAngularUpper.exists_reference_parent_upper
#print axioms NativeThirdXYConstantComparison.constant_grid_comparison
#print axioms NativeThirdXYConstantComparison.gap_power_comparison
#print axioms NativeThirdXYConstantComparison.geometryCost
#print axioms NativeThirdXYConstantComparison.geometryCost_one_le
#print axioms NativeThirdXYConstantComparison.xyConstant_le_retained
