import Theorems.Thm_StickyKakeya4_native_compatible_node_directions

#print axioms NativeCompatibleNodeDirections.nodes
#print axioms NativeCompatibleNodeDirections.IsNodeDirectionSystem
#print axioms NativeCompatibleNodeDirections.angular_ofFn_coordinate
#print axioms NativeCompatibleNodeDirections.terminal_fixed_tuple
#print axioms NativeCompatibleNodeDirections.projected_word_global
#print axioms NativeCompatibleNodeDirections.exists_node_word
#print axioms NativeCompatibleNodeDirections.exists_node_direction_system
#print axioms NativeCompatibleNodeDirections.node_direction_system_mono
#print axioms NativeCompatibleNodeDirections.stageDirectionIndex
#print axioms NativeCompatibleNodeDirections.stageAnchorIndex
#print axioms NativeCompatibleNodeDirections.stage_direction_readback
#print axioms NativeCompatibleNodeDirections.stage_anchor_readback
#print axioms NativeCompatibleNodeDirections.stage_direction_bounds
#print axioms NativeCompatibleNodeDirections.stage_index_readback
#print axioms NativeCompatibleNodeDirections.natStageDirectionIndex
#print axioms NativeCompatibleNodeDirections.natStageAnchorIndex
#print axioms NativeCompatibleNodeDirections.nat_stage_index_readback
#print axioms NativeCompatibleNodeDirections.nat_stage_anchor_readback
#print axioms NativeCompatibleNodeDirections.exists_scheduled_node_directions
