import Theorems.Thm_StickyKakeya4_native_height_residue_selection
import Theorems.Thm_StickyKakeya4_native_actual_height_slope_variation
import Theorems.Thm_StickyKakeya4_native_coarse_height_slope_variation
import Theorems.Thm_StickyKakeya4_native_population_parent_selection
import Theorems.Thm_StickyKakeya4_native_grain_quotient_injection
import Theorems.Thm_StickyKakeya4_native_grain_quotient_image

set_option autoImplicit false
#print axioms NativeActualHeightSlopeVariation.horizontalPlane
#print axioms NativeActualHeightSlopeVariation.horizontalPlane_le
#print axioms NativeActualHeightSlopeVariation.matching_height_slope_variation
#print axioms NativeActualHeightSlopeVariation.matching_node_horizontal_gap
#print axioms NativeActualHeightSlopeVariation.matching_node_matrix_variation
#print axioms NativeCoarseHeightSlopeVariation.node_pair_witness
#print axioms NativeCoarseHeightSlopeVariation.same_ancestor_installed_word
#print axioms NativeCoarseHeightSlopeVariation.same_coarse_height_slope_variation
#print axioms NativeGrainQuotientImage.X
#print axioms NativeGrainQuotientImage.X_card
#print axioms NativeGrainQuotientImage.exists_dense_X
#print axioms NativeGrainQuotientImage.full_tangent_image_lower
#print axioms NativeGrainQuotientImage.phase_quotient_loss
#print axioms NativeGrainQuotientImage.rawTangent
#print axioms NativeGrainQuotientImage.tangent_label_injOn
#print axioms NativeGrainQuotientInjection.coordinates_norm_eq_residual
#print axioms NativeGrainQuotientInjection.norm_le_coordinates
#print axioms NativeGrainQuotientInjection.physical_difference_horizontal
#print axioms NativeGrainQuotientInjection.physical_vertex_separated
#print axioms NativeGrainQuotientInjection.residual_mem_normalSpace
#print axioms NativeGrainQuotientInjection.same_coordinate_bins_norm
#print axioms NativeGrainQuotientInjection.same_label_coordinate_bound
#print axioms NativeGrainQuotientInjection.same_label_norm_bound
#print axioms NativeGrainQuotientInjection.tangentCoordinates
#print axioms NativeGrainQuotientInjection.tangentCoordinates_norm
#print axioms NativeHeightResidueSelection.exists_residue_separated_node_cut
#print axioms NativeHeightResidueSelection.same_residue_close_quotient
#print axioms NativeHeightResidueSelection.select_height_residues
#print axioms NativeHeightResidueSelection.selected_close_heights_same_ancestor
#print axioms NativePopulationParentSelection.exists_population_parent
#print axioms NativePopulationParentSelection.population_implies_reference_retention
#print axioms NativePopulationParentSelection.source_population_parent
