import Theorems.Thm_StickyKakeya4_native_original_angular_tuple_menu
import Theorems.Thm_StickyKakeya4_native_transverse_fiber_diameter

set_option autoImplicit false
#print axioms NativeOriginalAngularTupleMenu.angularMenu
#print axioms NativeOriginalAngularTupleMenu.angularMenu_eq_image_coarseMenu
#print axioms NativeOriginalAngularTupleMenu.angularTuple
#print axioms NativeOriginalAngularTupleMenu.angular_member_fine_witness
#print axioms NativeOriginalAngularTupleMenu.coarse_member_labels
#print axioms NativeOriginalAngularTupleMenu.coarse_to_angular_card_lower
#print axioms NativeTransverseFiberDiameter.approximate_fiber_diameter
#print axioms NativeTransverseFiberDiameter.transverse_scalar_bound
