import Theorems.Thm_StickyKakeya4_native_height_metric_power
import Theorems.Thm_StickyKakeya4_native_grain_height_projection_direct

set_option autoImplicit false
#print axioms NativeGrainHeightProjectionDirect.ancestor_height_gap
#print axioms NativeGrainHeightProjectionDirect.coordinates_norm
#print axioms NativeGrainHeightProjectionDirect.infDist_sub_smul_le
#print axioms NativeGrainHeightProjectionDirect.mixed_vertex_ancestor
#print axioms NativeGrainHeightProjectionDirect.physical_difference_decomposition
#print axioms NativeGrainHeightProjectionDirect.raw_mesh_times_ancestor
#print axioms NativeGrainHeightProjectionDirect.unchanged_quotient_difference
#print axioms NativeHeightMetricPower.absorb_normalized_metric
#print axioms NativeHeightMetricPower.actual_metric_constant_paid
#print axioms NativeHeightMetricPower.exists_grain_count
#print axioms NativeHeightMetricPower.exists_uniform_metric_cutoff
#print axioms NativeHeightMetricPower.menu_gap_power
#print axioms NativeHeightMetricPower.metricConstant_small_loss
#print axioms NativeHeightMetricPower.metricConstant_small_loss_of_grain_count
#print axioms NativeHeightMetricPower.normalizationConstant
