import Theorems.Thm_StickyKakeya4_native_scheduled_pair_parent_transfer

#print axioms NativeScheduledPairParentTransfer.diagonal_pair_fiber_eq
#print axioms NativeScheduledPairParentTransfer.diagonal_pair_uniformity
#print axioms NativeScheduledPairParentTransfer.fine_pair_determines_parent
#print axioms NativeScheduledPairParentTransfer.parent_fine_pair_fiber_eq
#print axioms NativeScheduledPairParentTransfer.parent_fine_pair_uniformity
#print axioms NativeScheduledPairParentTransfer.diagonal_parent_uniformity
#print axioms NativeScheduledPairParentTransfer.coarse_pair_over_fine_card_le
