import Theorems.Thm_StickyKakeya4_native_raw_shadow_pair_comparison

#print axioms NativeRawShadowPairComparison.rawPair
#print axioms NativeRawShadowPairComparison.pair_image_card_of_constant
#print axioms NativeRawShadowPairComparison.pair_image_card_le_of_point_comparison
#print axioms NativeRawShadowPairComparison.same_R_pair_image_card_comparison
#print axioms NativeRawShadowPairComparison.image_multiplicity_le_of_card_bounds
#print axioms NativeRawShadowPairComparison.same_R_multiplicity_comparison
#print axioms NativeRawShadowPairComparison.same_R_full_source_multiplicity_comparison
