import Theorems.Thm_StickyKakeya4_native_approximate_fiber_count
import Theorems.Thm_StickyKakeya4_native_global_angular_representatives
import Theorems.Thm_StickyKakeya4_native_refined_global_rows
import Theorems.Thm_StickyKakeya4_native_refined_row_density

set_option autoImplicit false
#print axioms NativeApproximateFiberCount.backward_fiber_step
#print axioms NativeApproximateFiberCount.backward_fiber_sum_bound
#print axioms NativeApproximateFiberCount.backward_fiber_sum_bound_real
#print axioms NativeApproximateFiberCount.capacity_le_transverse_power
#print axioms NativeApproximateFiberCount.card_le_of_approximate_fibers
#print axioms NativeApproximateFiberCount.fiber
#print axioms NativeApproximateFiberCount.infDist_sub_comm
#print axioms NativeApproximateFiberCount.intersection_card_le
#print axioms NativeApproximateFiberCount.intersection_card_le_transverse_power
#print axioms NativeApproximateFiberCount.minimumPredecessor
#print axioms NativeApproximateFiberCount.minimumPredecessor_le
#print axioms NativeApproximateFiberCount.near_sup_of_two
#print axioms NativeGlobalAngularRepresentatives.exists_global_representatives
#print axioms NativeGlobalAngularRepresentatives.exists_global_transverse_packets
#print axioms NativeGlobalAngularRepresentatives.globalAngularMenu
#print axioms NativeGlobalAngularRepresentatives.global_fine_representative
#print axioms NativeRefinedGlobalRows.first_cost_without_radix
#print axioms NativeRefinedGlobalRows.nonrank_row_cost
#print axioms NativeRefinedGlobalRows.nonrank_short_row_cost
#print axioms NativeRefinedGlobalRows.refined_projected_row_lower
#print axioms NativeRefinedGlobalRows.refined_projected_row_lower_absorbed
#print axioms NativeRefinedGlobalRows.retained_richness_coefficient
#print axioms NativeRefinedGlobalRows.retention_radix_six
#print axioms NativeRefinedRowDensity.finest_pair_scale_valid
#print axioms NativeRefinedRowDensity.finest_rich_row_bounds
#print axioms NativeRefinedRowDensity.two_stage_finest_row_bounds
