import Theorems.Thm_StickyKakeya4_native_reference_parent_grain_cleanup
import Theorems.Thm_StickyKakeya4_native_paid_parent_multiplicity_lower

set_option autoImplicit false
#print axioms NativePaidParentMultiplicityLower.parent_conditional_power_lower
#print axioms NativePaidParentMultiplicityLower.parent_full_source_retained_lower
#print axioms NativeReferenceParentGrainCleanup.source_mixed_grain_core
#print axioms NativeReferenceParentGrainCleanup.source_reference_parent_grain_cleanup
