import Theorems.Thm_StickyKakeya4_native_pointwise_trim_preservation
import Theorems.Thm_StickyKakeya4_native_reference_XY_grid_field
import Theorems.Thm_StickyKakeya4_native_saturated_complete_parent_profiles
import Theorems.Thm_StickyKakeya4_native_saturated_population_parent_profiles
import Theorems.Thm_StickyKakeya4_native_two_map_retained_slice_actual_caps

set_option autoImplicit false
#print axioms NativePointwiseTrimPreservation.filtered_point_fiber
#print axioms NativePointwiseTrimPreservation.filtered_point_image
#print axioms NativePointwiseTrimPreservation.point_class_half_retention
#print axioms NativePointwiseTrimPreservation.point_class_image_unchanged
#print axioms NativeReferenceXYGridField.coarseIndex_horizontalCoarsen
#print axioms NativeReferenceXYGridField.fixedField
#print axioms NativeReferenceXYGridField.fixedField_norm
#print axioms NativeReferenceXYGridField.fixedField_readback
#print axioms NativeReferenceXYGridField.fixedField_zero_off
#print axioms NativeReferenceXYGridField.fixed_pxy_readback
#print axioms NativeReferenceXYGridField.pref_squared
#print axioms NativeReferenceXYGridField.slice_horizontal
#print axioms NativeSaturatedCompleteParentProfiles.HasSaturatedCompleteParentProfiles
#print axioms NativeSaturatedCompleteParentProfiles.complete_saturated_selected_parent_profiles
#print axioms NativeSaturatedPopulationParentProfiles.HasSaturatedPopulationParentProfiles
#print axioms NativeSaturatedPopulationParentProfiles.source_saturated_population_parent_profiles
#print axioms NativeTwoMapRetainedSliceActualCaps.dimension_sum
#print axioms NativeTwoMapRetainedSliceActualCaps.encodedPoint
#print axioms NativeTwoMapRetainedSliceActualCaps.encodedPoint_coarse
#print axioms NativeTwoMapRetainedSliceActualCaps.encodedPoint_height
#print axioms NativeTwoMapRetainedSliceActualCaps.encoded_capacities
#print axioms NativeTwoMapRetainedSliceActualCaps.image_composed_encode_card
