import Theorems.Thm_StickyKakeya4_native_literal_reference_angular_cube_source_draft_2214
set_option autoImplicit false
#print axioms NativeLiteralReferenceShadowCubeDraft2150.zero_parent_coordinate_difference
#print axioms NativeLiteralReferenceShadowCubeDraft2150.actual_shadow_support_in_native_ball
#print axioms NativeLiteralReferenceShadowCubeDraft2150.native_ball_parent_count_of_uniformity
#print axioms NativeLiteralReferenceShadowCubeDraft2150.reference_native_ball_parent_upper
#print axioms NativeLiteralReferenceShadowCubeDraft2150.reference_native_ball_conditional_parent_upper
#print axioms NativeLiteralCubeAnglePhaseMenuDraft2159.native_cube_intercept_spread
#print axioms NativeLiteralCubeAnglePhaseMenuDraft2159.native_cube_slope_cell_parent_cap
#print axioms NativeLiteralCubeAnglePhaseMenuDraft2159.native_cube_angle_ball_parent_cap
#print axioms NativeLiteralCubeAnglePhaseMenuDraft2159.reference_native_cube_angle_upper
#print axioms NativeLiteralCubeUnitAngularReadbackDraft2212.literal_angular_readback
#print axioms NativeLiteralCubeUnitAngularReadbackDraft2212.literal_angular_count_le
#print axioms NativeLiteralCubeUnitAngularReadbackDraft2212.reference_native_cube_unit_ball_upper
#print axioms NativeLiteralCubeUnitAngularReadbackDraft2212.reference_off_menu_cube_angular_upper
