import Theorems.Thm_StickyKakeya4_native_slice_class_balls
import Theorems.Thm_StickyKakeya4_native_retained_slice_core
import Theorems.Thm_StickyKakeya4_native_retained_slice_actual
import Theorems.Thm_StickyKakeya4_native_retained_slice_budget
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_selection
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_geometry
import Theorems.Thm_StickyKakeya4_native_weighted_grain_quotient_source
import Theorems.Thm_StickyKakeya4_native_prescribed_grain_history
import Theorems.Thm_StickyKakeya4_native_prescribed_retained_history
import Theorems.Thm_StickyKakeya4_native_prescribed_history_configuration
import Theorems.Thm_StickyKakeya4_native_prescribed_final_configuration

set_option autoImplicit false
#print axioms NativePrescribedFinalConfiguration.HasPrescribedFinalRetainedHistory
#print axioms NativePrescribedFinalConfiguration.HasPrescribedFinalStage
#print axioms NativePrescribedFinalConfiguration.exists_prescribed_final_configuration
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_forget
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_retained_of_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_forget
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_history
#print axioms NativePrescribedFinalConfiguration.prescribed_final_stage_of_history
#print axioms NativePrescribedGrainHistory.IsPrescribedNodeSystem
#print axioms NativePrescribedGrainHistory.construct_prescribed_grain_history
#print axioms NativePrescribedGrainHistory.prescribed_system_forget
#print axioms NativePrescribedGrainHistory.prescribed_system_word
#print axioms NativePrescribedHistoryConfiguration.HasPrescribedHistoryStage
#print axioms NativePrescribedHistoryConfiguration.exists_prescribed_history_configuration
#print axioms NativePrescribedHistoryConfiguration.prescribed_history_stage_forget
#print axioms NativePrescribedHistoryConfiguration.prescribed_history_stage_of_compatible
#print axioms NativePrescribedRetainedHistory.HasPrescribedRetainedHistory
#print axioms NativePrescribedRetainedHistory.construct_prescribed_retained_history
#print axioms NativePrescribedRetainedHistory.prescribed_retained_forget
#print axioms NativeRetainedSliceActual.exists_actual_retained_slice_counts
#print axioms NativeRetainedSliceBudget.exists_retained_slice_budget
#print axioms NativeRetainedSliceCore.exists_retained_slice_core
#print axioms NativeRetainedSliceCore.exists_retained_slice_counts
#print axioms NativeRetainedSliceCore.refinementCost
#print axioms NativeRetainedSliceCore.refinementCost_pos
#print axioms NativeRetainedSliceCore.relations
#print axioms NativeRetainedSliceCore.relations_refl
#print axioms NativeRetainedSliceCore.relations_symm
#print axioms NativeSliceClassBalls.ball_class_card_le
#print axioms NativeSliceClassBalls.ball_class_mem_halo
#print axioms NativeSliceClassBalls.preparedClass
#print axioms NativeSliceClassBalls.preparedClass_subset_ball
#print axioms NativeSliceClassBalls.prepared_ball_upper
#print axioms NativeSliceClassBalls.prepared_real_ball_bounds
#print axioms NativeSliceClassBalls.realized
#print axioms NativeSliceClassBalls.realizedSlice
#print axioms NativeSliceClassBalls.realized_ball_card
#print axioms NativeSliceClassBalls.realized_dist_iff
#print axioms NativeSliceClassBalls.realized_injective_on_height
#print axioms NativeSliceClassBalls.spatialBall
#print axioms NativeWeightedGrainQuotientGeometry.grain_mixed_eq
#print axioms NativeWeightedGrainQuotientGeometry.pick
#print axioms NativeWeightedGrainQuotientGeometry.quotientLabel
#print axioms NativeWeightedGrainQuotientGeometry.quotientLabel_on_mixed
#print axioms NativeWeightedGrainQuotientGeometry.quotient_image_eq
#print axioms NativeWeightedGrainQuotientGeometry.retained
#print axioms NativeWeightedGrainQuotientGeometry.retained_mixed_fiber
#print axioms NativeWeightedGrainQuotientGeometry.retained_mixed_vertices
#print axioms NativeWeightedGrainQuotientGeometry.retained_subset
#print axioms NativeWeightedGrainQuotientGeometry.retained_vertices_le_X
#print axioms NativeWeightedGrainQuotientSelection.card_retention_ceil
#print axioms NativeWeightedGrainQuotientSelection.chosen
#print axioms NativeWeightedGrainQuotientSelection.chosen_spec
#print axioms NativeWeightedGrainQuotientSelection.grain
#print axioms NativeWeightedGrainQuotientSelection.local_card_retention
#print axioms NativeWeightedGrainQuotientSelection.local_mass_retention
#print axioms NativeWeightedGrainQuotientSelection.mass_retention
#print axioms NativeWeightedGrainQuotientSelection.selected
#print axioms NativeWeightedGrainQuotientSelection.selected_grain
#print axioms NativeWeightedGrainQuotientSelection.selected_grain_image
#print axioms NativeWeightedGrainQuotientSelection.selected_grain_nonempty
#print axioms NativeWeightedGrainQuotientSelection.selected_subset
#print axioms NativeWeightedGrainQuotientSource.quotientCap
#print axioms NativeWeightedGrainQuotientSource.quotientCap_pos
#print axioms NativeWeightedGrainQuotientSource.source_quotient_cap
#print axioms NativeWeightedGrainQuotientSource.source_retention
#print axioms NativeWeightedGrainQuotientSource.threshold_transfer
