import Theorems.Thm_StickyKakeya4_four_cycle_contact_frame
import Theorems.Thm_StickyKakeya4_fresh_return_tower_extraction

open Filter MeasureTheory Set Topology
open scoped ENNReal NNReal Topology

noncomputable section

namespace StickyKakeya4

/-- A pruned return tower whose four-probe data are generated by four actual
marked selector lines at every node.  Unlike `PrunedFreshReturnFourProbeTower`,
the matrices and coefficient vectors are not free fields: they are the
anchored contact secant frame and the four canonical cycle-edge coefficients.
-/
structure PrunedMarkedFourCycleReturnTower (selector : Set MarkedLine) where
  Node : ℕ → Type
  nodeFinite : ∀ n, Finite (Node n)
  root : Node 0
  parent : ∀ n, Node (n + 1) → Node n
  hasChild : ∀ n (x : Node n), ∃ y : Node (n + 1), parent n y = x
  line : ∀ n, Node n → Fin 4 → MarkedLine
  line_mem_selector : ∀ n (x : Node n) i, line n x i ∈ selector
  chartNonzero : ∀ n (x : Node n) i,
    direction (line n x i) (3 : Fin 4) ≠ 0
  approxTime : ∀ n, Node n → Fin 4 → ℝ
  timeGap : ℝ
  timeGap_pos : 0 < timeGap
  timeSeparated : ∀ n (x : Node n) i j, i ≠ j →
    timeGap ≤ |approxTime n x i - approxTime n x j|
  capRadius : ℕ → ℝ
  capRadius_nonneg : ∀ n, 0 ≤ capRadius n
  initialRadius : ℝ
  initialRadius_nonneg : 0 ≤ initialRadius
  branchingFactor : ℝ
  branchingFactor_gt_one : 1 < branchingFactor
  capRadius_zero : capRadius 0 ≤ initialRadius
  capRadius_step : ∀ n,
    capRadius (n + 1) ≤ capRadius n / branchingFactor
  motionConstant : ℝ
  motionConstant_nonneg : 0 ≤ motionConstant
  motionA : ∀ n (y : Node (n + 1)) i j,
    dist
        (anchoredCycleA (line n (parent n y)) i j)
        (anchoredCycleA (line (n + 1) y) i j) ≤
      motionConstant * capRadius n
  motionB : ∀ n (y : Node (n + 1)) i j,
    dist
        (anchoredCycleB (line n (parent n y)) i j)
        (anchoredCycleB (line (n + 1) y) i j) ≤
      motionConstant * capRadius n
  motionTime : ∀ n (y : Node (n + 1)) i,
    dist (approxTime n (parent n y) i) (approxTime (n + 1) y i) ≤
      motionConstant * capRadius n
  residualBound : ℕ → ℝ
  residualBound_nonneg : ∀ n, 0 ≤ residualBound n
  residualBound_tendsto_zero : Tendsto residualBound atTop (nhds 0)
  physicalCycleResidual : ∀ n (x : Node n) i,
    ‖(‖rawFourCycleCoeff i‖⁻¹ •
        ((fourCycleEdgeSecant (line n x) i).2 +
          approxTime n x i • (fourCycleEdgeSecant (line n x) i).1)).ofLp‖ ≤
      residualBound n
  noncollapseConstant : ℝ
  noncollapseConstant_pos : 0 < noncollapseConstant
  horizontalNoncollapse : ∀ n (x : Node n) (c : E3),
    noncollapseConstant * ‖c‖ ≤
      ‖horizontalFrameVector (anchoredCycleA (line n x)) c‖

/-- Forget only the fact that the frame came from actual selector lines.  The
four-probe tower fields are filled by the exact cycle-frame identities. -/
def PrunedMarkedFourCycleReturnTower.toFreshReturnTower
    {selector : Set MarkedLine}
    (tower : PrunedMarkedFourCycleReturnTower selector) :
    PrunedFreshReturnFourProbeTower where
  Node := tower.Node
  nodeFinite := tower.nodeFinite
  root := tower.root
  parent := tower.parent
  hasChild := tower.hasChild
  approxA := fun n x => anchoredCycleA (tower.line n x)
  approxB := fun n x => anchoredCycleB (tower.line n x)
  approxTime := tower.approxTime
  approxCoeff := fun _n _x i => fourCycleCoeff i
  timeGap := tower.timeGap
  timeGap_pos := tower.timeGap_pos
  timeSeparated := tower.timeSeparated
  capRadius := tower.capRadius
  initialRadius := tower.initialRadius
  initialRadius_nonneg := tower.initialRadius_nonneg
  branchingFactor := tower.branchingFactor
  branchingFactor_gt_one := tower.branchingFactor_gt_one
  capRadius_zero := tower.capRadius_zero
  capRadius_step := tower.capRadius_step
  motionConstant := tower.motionConstant
  motionConstant_nonneg := tower.motionConstant_nonneg
  motionA := tower.motionA
  motionB := tower.motionB
  motionTime := tower.motionTime
  motionCoeff := fun n y i => by
    simp
    exact mul_nonneg tower.motionConstant_nonneg
      (tower.capRadius_nonneg n)
  coeffUnit := fun _n _x i => fourCycleCoeff_norm i
  residualBound := tower.residualBound
  residualBound_nonneg := tower.residualBound_nonneg
  residualBound_tendsto_zero := tower.residualBound_tendsto_zero
  residualNorm := fun n x i => by
    rw [anchoredCycle_pencil_coeff_raw_eq_contactResidual]
    exact tower.physicalCycleResidual n x i
  noncollapseConstant := tower.noncollapseConstant
  noncollapseConstant_pos := tower.noncollapseConstant_pos
  horizontalNoncollapse := tower.horizontalNoncollapse

/-- An infinite pruned tower of actual marked four-cycles is impossible by the
internal four-time Maslov firewall. -/
theorem PrunedMarkedFourCycleReturnTower.impossible
    {selector : Set MarkedLine}
    (tower : PrunedMarkedFourCycleReturnTower selector) : False :=
  tower.toFreshReturnTower.impossible

end StickyKakeya4
