import Theorems.Thm_StickyKakeya4_native_original_padded_cells
import Theorems.Thm_StickyKakeya4_native_original_height_vertices
set_option autoImplicit false
set_option warningAsError true
set_option maxRecDepth 4096
set_option maxHeartbeats 2600000
noncomputable section
namespace NativePaddedCellFiberCount
open Classical Finset MeasureTheory StickyKakeya4 NativeOriginalCellChartGeometry NativeOriginalParentSelection
open NativeCommonCubicalMesh NativeCubicalIncidenceCounts NativeOriginalParentPhysicalData
open NativeOriginalPaddedCells NativeOriginalHeightVertices OriginalWWitnessCounts
open scoped BigOperators ENNReal

def originalChart {n : ℕ} (D : FiniteScaleSource n) (original : Fin n → Finset Index) (a : ℝ) :
    Finset (Fin n × ShearBinFibers.Index) :=
  (incidences original).image (fun z => (z.1,chartIndex (shift D a) z.2))

/-- The already proved28^3 slice occupancy is applied to the original cells
through their injective original chart labels, without selecting a new set. -/
theorem original_row_card_le {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i) ∈ Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (i : Fin n) (row : ℤ) :
    ((original i).filter (fun k => k (3:Fin 4)-shift D a=row)).card ≤ 21952 := by
  let E := originalChart D original a
  let e := mesh D/4
  let S := (original i).filter (fun k => k (3:Fin 4)-shift D a=row)
  have he : 0 < e := by have hd:=h.1.2.1; dsimp [e,mesh]; positivity
  have hres : ∀ t c,(t,c)∈E → ∀j,
      |(ShearBinFibers.oldCenter e c).1 j-shiftedIntercept (D.line t) (mesh D) (shift D a) j-
        slope (D.line t) j*height e c| ≤ 12*e := by
    intro t c htc j
    obtain ⟨⟨t',k⟩,hk,hmap⟩ := mem_image.mp htc
    have ht : t'=t := congrArg Prod.fst hmap
    have hc : chartIndex (shift D a) k=c := congrArg Prod.snd hmap
    subst t'
    subst c
    exact (original_cell_bounds h original horiginal a ha hk).2 j
  have H := pointsAt_bound E he (fun t=>slope (D.line t))
    (fun t=>shiftedIntercept (D.line t) (mesh D) (shift D a)) hres i (e*((row:ℝ)+1/2))
  have hs : S.image (chartIndex (shift D a)) ⊆
      pointsAt (pointTube E) (height e) i (e*((row:ℝ)+1/2)) := by
    intro c hc
    obtain ⟨k,hk,rfl⟩ := mem_image.mp hc
    apply (mem_pointsAt _ _ _ _ _).mpr
    constructor
    · apply (mem_pointTube E _ i).mpr
      exact mem_image.mpr ⟨(i,k),(mem_incidences original i k).mpr (mem_filter.mp hk).1,rfl⟩
    · change e*(((k (3:Fin 4)-shift D a:ℤ):ℝ)+1/2)=e*((row:ℝ)+1/2)
      rw [(mem_filter.mp hk).2]
  have hc : (S.card:ℝ) ≤ (pointsAt (pointTube E) (height e) i (e*((row:ℝ)+1/2))).card := by
    rw [←card_image_of_injective S (chartIndex_injective (shift D a))]
    exact_mod_cast card_le_card hs
  exact_mod_cast hc.trans H

/-- One actual output cube receives at most eight original height rows, each
with the actual28^3 original per-tube occupancy. -/
theorem output_cell_fiber_card_le {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i) ∈ Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (p : Parent) (i : Fin n) (q : Index) :
    ((original i).filter (fun k=>cellLabel D a p i k=q)).card ≤ 175616 := by
  let S := (original i).filter (fun k=>cellLabel D a p i k=q)
  let rows := Icc (8*q (3:Fin 4)) (8*q (3:Fin 4)+7)
  have hm : ∀k∈S,k (3:Fin 4)-shift D a∈rows := by
    intro k hk
    have he := congrFun (mem_filter.mp hk).2 (3:Fin 4)
    rw [cellLabel_height h.1.2.1] at he
    apply mem_Icc.mpr
    omega
  have hb : ∀r∈rows,(S.filter (fun k=>k (3:Fin 4)-shift D a=r)).card ≤ 21952 := by
    intro r _hr
    exact (card_le_card (filter_subset_filter _ (filter_subset _ _))).trans
      (original_row_card_le h original horiginal ha i r)
  have hc := card_le_mul_card_image_of_maps_to hm 21952 hb
  have hr : rows.card=8 := by
    have hh : (rows.card:ℤ)=8 := by
      dsimp [rows]
      rw [Int.card_Icc_of_le _ _ (by omega)]
      omega
    exact_mod_cast hh
  rw [hr] at hc
  exact hc

/-- Every output cell is generated by an original cell, and each has the
proved fixed original preimage bound. Hence actual original shading mass
survives cubical replacement with an explicit count loss. -/
theorem original_card_le_output_card {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i) ∈ Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (p : Parent) (i : Fin n) :
    (original i).card ≤ 175616*(cells D original a p i).card := by
  exact card_le_mul_card_image (original i) 175616
    (fun q _ => output_cell_fiber_card_le h original horiginal ha p i q)

/-- Actual original and new cubical volumes, including the fixed64 mesh ratio. -/
theorem original_shading_volume_le {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i) ∈ Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (p : Parent) (i : Fin n) :
    volume (D.shading i) ≤ (175616:ℝ≥0∞)*64^4*
      volume (wzCellShading (D.thickness/128) (cells D original a p) i) := by
  have hd:=h.1.2.1
  have hm : 0 < mesh D := half_pos hd
  have he : 0 < D.thickness/128 := by positivity
  rw [horiginal i,volume_wzCellShading hm,volume_wzCellShading he]
  have hc : ((original i).card:ℝ≥0∞) ≤ 175616*(cells D original a p i).card := by
    exact_mod_cast original_card_le_output_card h original horiginal ha p i
  have hm64 : ENNReal.ofReal (mesh D)=64*ENNReal.ofReal (D.thickness/128) := by
    have hh : mesh D=64*(D.thickness/128) := by dsimp [mesh]; ring
    rw [hh,ENNReal.ofReal_mul (by norm_num : (0:ℝ) ≤ 64),ENNReal.ofReal_ofNat]
  rw [hm64]
  calc
    _ ≤ (175616*(cells D original a p i).card)*(64*ENNReal.ofReal (D.thickness/128))^4 :=
      mul_le_mul' hc le_rfl
    _ = _ := by ring
end NativePaddedCellFiberCount
