import Theorems.Thm_StickyKakeya4_native_original_padded_cells
set_option autoImplicit false
set_option warningAsError true
set_option maxRecDepth 4096
set_option maxHeartbeats 2200000
noncomputable section
namespace NativePaddedCellSource
open Classical Finset StickyKakeya4 NativeOriginalParentSelection NativeCommonCubicalMesh
open NativeOriginalPaddedCells NativeContractedUnitParent NativeUnitParentNormalization

/-- Enumerate exactly the retained ORIGINAL labels; removed rows are not restored. -/
def originalLabel {n : ℕ} (R : Finset (Fin n)) (i : Fin R.card) : Fin n :=
  (R.equivFin.symm i).val
lemma originalLabel_mem {n : ℕ} (R : Finset (Fin n)) (i : Fin R.card) : originalLabel R i∈R :=
  (R.equivFin.symm i).property
lemma originalLabel_injective {n : ℕ} (R : Finset (Fin n)) : Function.Injective (originalLabel R) := by
  intro i j hij
  exact R.equivFin.symm.injective (Subtype.ext hij)
lemma originalLabel_range {n : ℕ} (R : Finset (Fin n)) : Set.range (originalLabel R)=(R:Set (Fin n)) := by
  ext i
  constructor
  · rintro ⟨j,rfl⟩
    exact originalLabel_mem R j
  · intro hi
    exact ⟨R.equivFin ⟨i,hi⟩,by simp [originalLabel]⟩

/-- A genuine finite source with actual new marked tubes and actual dyadic
cube shadings generated by original cells. Only retained original labels occur. -/
def source {n : ℕ} {D : FiniteScaleSource n} {eta : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (R : Finset (Fin n)) (a : ℝ) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) :
    FiniteScaleSource R.card :=
  directionSeparatedWZCellSourceAtScales (D.thickness/64) (D.thickness/128)
    (fun i => NativeContractedUnitParent.line D a p (originalLabel R i))
    (fun i => cells D original a p (originalLabel R i))
    (by have hd:=h.1.2.1; positivity)
    (by
      intro i j hij
      exact contracted_direction_separation h p _ _
        (hp _ (originalLabel_mem R i)) (hp _ (originalLabel_mem R j))
        (fun he => hij (originalLabel_injective R he)))

lemma source_thickness {n : ℕ} {D : FiniteScaleSource n} {eta : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (R : Finset (Fin n)) (a : ℝ) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) :
    (source h original R a p hp).thickness=D.thickness/64 := rfl

lemma source_line {n : ℕ} {D : FiniteScaleSource n} {eta : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (R : Finset (Fin n)) (a : ℝ) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) (i : Fin R.card) :
    (source h original R a p hp).line i=NativeContractedUnitParent.line D a p (originalLabel R i) := rfl

lemma source_shading {n : ℕ} {D : FiniteScaleSource n} {eta : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (R : Finset (Fin n)) (a : ℝ) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) (i : Fin R.card) :
    (source h original R a p hp).shading i=
      wzCellShading (D.thickness/128) (cells D original a p) (originalLabel R i) := rfl

lemma source_weights {n : ℕ} {D : FiniteScaleSource n} {eta : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (R : Finset (Fin n)) (a : ℝ) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) (i : Fin R.card) :
    (source h original R a p hp).weight i=1 ∧
      (source h original R a p hp).fibreMark i=mark ((source h original R a p hp).line i) := ⟨rfl,rfl⟩

lemma dyadic_div_power {delta : ℝ} (h : IsWZDyadicScale delta) (k : ℕ) :
    IsWZDyadicScale (delta/(2:ℝ)^k) := by
  obtain ⟨level,rfl⟩ := h
  exact ⟨level+k,by simp only [pow_add,inv_pow,div_eq_mul_inv]⟩

/-- All geometric and cubical source fields are constructed from the original
input. AD, CW and density are deliberately proved separately from this data object. -/
theorem source_geometric_fields {n : ℕ} {D : FiniteScaleSource n} {eta a : ℝ}
    (h : IsWangZakharovNativeFiniteInput D eta) (original : Fin n → Finset Index)
    (horiginal : ∀i,D.shading i=wzCellShading (mesh D) original i)
    (ha : ∀i,wzGraphTime (D.line i) a-mark (D.line i) ∈ Set.Icc (-(1/2:ℝ)) (1/2:ℝ))
    (R : Finset (Fin n)) (p : Parent) (hp : ∀i∈R,parentLabel D a 1 i=p) :
    let S := source h original R a p hp
    0 < S.thickness ∧ S.thickness ≤ 1 ∧ IsWZDyadicScale S.thickness ∧
      (∀i,IsValidLine (S.line i)) ∧
      (∀i,S.line i∈fixedCompactClass) ∧
      (∀i,MeasurableSet (S.shading i)) ∧
      (∀i,IsWZComparableCubicalShading S.thickness (S.shading i)) ∧
      (∀i,S.shading i⊆markedUnitTube (S.line i) S.thickness) ∧
      (∀i j,i≠j → S.thickness ≤ dist (direction (S.line i)) (direction (S.line j))) ∧
      HasNormalizedWZGraphSlab S ∧ HasFixedWZGraphNormalization S := by
  let S := source h original R a p hp
  have hd:=h.1.2.1
  have hdp : 0 < D.thickness/64 := by positivity
  have hmp : 0 < D.thickness/128 := by positivity
  have htd : IsWZDyadicScale (D.thickness/64) := by
    simpa only [show (2:ℝ)^6=64 by norm_num] using dyadic_div_power h.1.2.2.2.1 6
  have hmd : IsWZDyadicScale (D.thickness/128) := by
    simpa only [show (2:ℝ)^7=128 by norm_num] using dyadic_div_power h.1.2.2.2.1 7
  have hline (i : Fin R.card) := contracted_line_common_slab D a p (originalLabel R i) (hp _ (originalLabel_mem R i))
  have hvalid : ∀i,IsValidLine (S.line i) := fun i => (hline i).1
  have hslab : HasNormalizedWZGraphSlab S := by
    refine ⟨fun i => (hline i).2.1,-(1/4:ℝ),(1/4:ℝ),by norm_num,?_,fun i => (hline i).2.2⟩
    exact Set.nonempty_Icc.mpr (by norm_num)
  refine ⟨hdp,by change D.thickness/64 ≤ 1; linarith [h.1.2.2.1],htd,hvalid,?_,?_,?_,?_,?_,hslab,
    hasFixedWZGraphNormalization_of_normalizedSlab S hvalid hslab⟩
  · intro i
    exact contracted_line_compact D a p (originalLabel R i) (hp _ (originalLabel_mem R i))
  · intro i
    exact measurableSet_wzCellShading _ (cells D original a p) (originalLabel R i)
  · intro i
    refine ⟨D.thickness/128,hmp,?_,?_,hmd,?_⟩
    · change D.thickness/128 ≤ D.thickness/64
      linarith
    · change D.thickness/64 ≤ 2*(D.thickness/128)
      linarith
    · exact isWZCubicalShading_wzCellShading _ (cells D original a p) (originalLabel R i)
  · intro i
    exact cell_shading_subset_contracted_tube h original horiginal ha p (originalLabel R i) (hp _ (originalLabel_mem R i))
  · intro i j hij
    exact contracted_direction_separation h p _ _ (hp _ (originalLabel_mem R i)) (hp _ (originalLabel_mem R j))
      (fun he => hij (originalLabel_injective R he))
end NativePaddedCellSource
