import Theorems.Thm_StickyKakeya4_separated_bush_fiber
import Theorems.Thm_StickyKakeya4_spacetime_collision_energy
import Theorems.Thm_StickyKakeya4_actual_slope_source_bounds
import Theorems.Thm_StickyKakeya4_original_residual_criterion

/-!
# The physical ball estimate for the original vector bush-family exit

The vector cap hypothesis keeps the same outer physical point and time across
all bushes. It is not replaced by an unrelated cap choice or an individual
positive-bush mass assumption. This is the quantitative geometric integration
step of original Theorem 8.11; obtaining its vector hypothesis remains a
separate routing obligation.
-/

open MeasureTheory Set Filter
open scoped ENNReal
noncomputable section
namespace StickyKakeya4.VectorBushFrostman

/-- The direction center is generated by the same physical outer point. -/
def vectorCenter (c y : E3) (s₀ s : ℝ) : E3 := (s - s₀)⁻¹ • (y - c)

/-- A physical bush and a physical outer ball force the original slope into
its actual vector cap, with the physical bush error retained. -/
theorem source_mem_vector_cap (a ba c y : E3) (s₀ s ε r g : ℝ)
    (hbush : ‖ba + s₀ • a - c‖ ≤ ε)
    (hball : ‖ba + s • a - y‖ ≤ r)
    (hg : 0 < g) (hgap : g ≤ |s - s₀|) :
    a ∈ Metric.closedBall (vectorCenter c y s₀ s) ((ε + r) / g) := by
  have hc : ‖(ba - y) + s • (a - 0)‖ ≤ r := by
    convert hball using 1 <;> congr 1 <;> module
  have h := SeparatedBushFiber.source_mem_fiber_cap a ba 0 y c s₀ s s ε r 0 ‖a‖ g
    hbush hc (by simp) (by simp) hg hgap
  simpa [SeparatedBushFiber.fiberCenter, vectorCenter] using h

/-- The Euclidean lift covers every physical point, not only a chart subset. -/
theorem spacetimeLift_horizontalProjection (x : E4) :
    spacetimeLift (horizontalProjection x) (x (3 : Fin 4)) = x := by
  ext i
  refine Fin.lastCases ?_ (fun j => ?_) i
  · change x (3 : Fin 4) = x (Fin.last 3)
    rfl
  · simp [spacetimeLift, horizontalProjection]

/-- Every member of one bush contributing to an outer physical ball lies in
its synchronized vector cap. Boundedness of slopes is not needed here. -/
theorem bush_ball_preimage_le_cap
    (σ : Measure E3) (b : E3 → E3) (c y : E3)
    (s₀ s t ε r g : ℝ)
    (hbush : ∀ᵐ a ∂σ, ‖b a + s₀ • a - c‖ ≤ ε)
    (hr : 0 < r) (hg : 0 < g) (hgap : g ≤ |s - s₀|) :
    σ {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r} ≤
      σ (Metric.closedBall (vectorCenter c y s₀ s) ((ε + r) / g)) := by
  apply measure_mono_ae
  filter_upwards [hbush] with a ha
  intro hball
  have hdist : ‖spacetimeLift (b a + s • a) s - spacetimeLift y t‖ ≤ r := by
    exact (show dist (slopeSpacetimePoint b (s, a)) (spacetimeLift y t) < r from hball).le
  have hh := (spacetimeLift_collision_coordinates (b a + s • a) y s t r hr.le hdist).1
  exact source_mem_vector_cap a (b a) c y s₀ s ε r g ha hh hg hgap

/-- The radius enlargement is uniform when the bush error is at most the
physical radius. -/
theorem bush_ball_preimage_le_scaled_cap
    (σ : Measure E3) (b : E3 → E3) (c y : E3)
    (s₀ s t ε r g K : ℝ)
    (hbush : ∀ᵐ a ∂σ, ‖b a + s₀ • a - c‖ ≤ ε)
    (hr : 0 < r) (hε : ε ≤ r) (hg : 0 < g) (hgap : g ≤ |s - s₀|)
    (hK : 2 / g ≤ K) :
    σ {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r} ≤
      σ (Metric.closedBall (vectorCenter c y s₀ s) (K * r)) := by
  apply (bush_ball_preimage_le_cap σ b c y s₀ s t ε r g hbush hr hg hgap).trans
  apply measure_mono
  apply Metric.closedBall_subset_closedBall
  calc
    (ε + r) / g ≤ (r + r) / g := div_le_div_of_nonneg_right (by linarith) hg.le
    _ = (2 / g) * r := by ring
    _ ≤ K * r := mul_le_mul_of_nonneg_right hK hr.le

/-- The vector cap estimate controls the physical pushforward of the entire
family. All components use the same outer point and time; no bush is selected.
The exact extra factor `2r` comes from the fourth-coordinate time fibre. -/
theorem family_physical_ball_mass_le
    {n : ℕ} (σ : Fin n → Measure E3) [∀ i, IsFiniteMeasure (σ i)]
    (b : E3 → E3) (hb : Measurable b) (c : Fin n → E3) (s₀ : Fin n → ℝ)
    (u v ε r g K : ℝ) (y : E3) (t : ℝ) (B : ℝ≥0∞)
    (hbush : ∀ i, ∀ᵐ a ∂σ i, ‖b a + s₀ i • a - c i‖ ≤ ε)
    (hr : 0 < r) (hε : ε ≤ r) (hg : 0 < g) (hK : 2 / g ≤ K)
    (hgap : ∀ i, ∀ s ∈ Icc u v, g ≤ |s - s₀ i|)
    (hvector : ∀ s ∈ Icc u v,
      (∑' i, σ i (Metric.closedBall (vectorCenter (c i) y (s₀ i) s) (K * r))) ≤ B) :
    (((volume.restrict (Icc u v)).prod (Measure.sum σ)).map (slopeSpacetimePoint b))
      (Metric.ball (spacetimeLift y t) r) ≤ ENNReal.ofReal (2 * r) * B := by
  have hF := measurable_slopeSpacetimePoint b hb
  have hrow (s : ℝ) (hs : s ∈ Icc u v) :
      (Measure.sum σ) {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r} ≤
        (Icc (t - r) (t + r)).indicator (fun _ => B) s := by
    by_cases htime : s ∈ Icc (t - r) (t + r)
    · rw [Set.indicator_of_mem htime]
      have hm : MeasurableSet {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r} :=
        Metric.isOpen_ball.measurableSet.preimage (hF.comp (measurable_const.prodMk measurable_id))
      rw [Measure.sum_apply _ hm]
      exact (ENNReal.tsum_le_tsum (fun i =>
        bush_ball_preimage_le_scaled_cap (σ i) b (c i) y (s₀ i) s t ε r g K
          (hbush i) hr hε hg (hgap i s hs) hK)).trans (hvector s hs)
    · rw [Set.indicator_of_notMem htime]
      have he : {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r} = ∅ := by
        apply Set.eq_empty_iff_forall_notMem.mpr
        intro a ha
        have hh : ‖spacetimeLift (b a + s • a) s - spacetimeLift y t‖ ≤ r :=
          (show dist (slopeSpacetimePoint b (s, a)) (spacetimeLift y t) < r from ha).le
        have ht := (spacetimeLift_collision_coordinates (b a + s • a) y s t r hr.le hh).2
        obtain ⟨hlo, hhi⟩ := abs_le.mp ht
        exact htime ⟨by linarith, by linarith⟩
      rw [he, measure_empty]
  rw [Measure.map_apply hF Metric.isOpen_ball.measurableSet,
    Measure.prod_apply (Metric.isOpen_ball.measurableSet.preimage hF)]
  change (∫⁻ s in Icc u v, (Measure.sum σ)
    {a | slopeSpacetimePoint b (s, a) ∈ Metric.ball (spacetimeLift y t) r}) ≤ _
  calc
    _ ≤ ∫⁻ s in Icc u v, (Icc (t - r) (t + r)).indicator (fun _ => B) s := by
      apply lintegral_mono_ae
      filter_upwards [ae_restrict_mem measurableSet_Icc] with s hs
      exact hrow s hs
    _ ≤ ∫⁻ s, (Icc (t - r) (t + r)).indicator (fun _ => B) s :=
      setLIntegral_le_lintegral _ _
    _ = ENNReal.ofReal (2 * r) * B := by
      rw [lintegral_indicator_const measurableSet_Icc, Real.volume_Icc]
      rw [show t + r - (t - r) = 2 * r by ring]
      exact mul_comm _ _

/-- The normalized actual family front, with the source mass and time length
kept as separate explicit factors. -/
def familyFrontProbability {n : ℕ} (σ : Fin n → Measure E3)
    (b : E3 → E3) (u v : ℝ) : Measure E4 :=
  ((ENNReal.ofReal (v - u))⁻¹ * ((Measure.sum σ) univ)⁻¹) •
    (((volume.restrict (Icc u v)).prod (Measure.sum σ)).map (slopeSpacetimePoint b))

theorem familyFrontProbability_isProbability
    {n : ℕ} (σ : Fin n → Measure E3) [∀ i, IsFiniteMeasure (σ i)]
    (hq : 0 < (Measure.sum σ) univ) (b : E3 → E3) (hb : Measurable b)
    (u v : ℝ) (huv : u < v) :
    IsProbabilityMeasure (familyFrontProbability σ b u v) := by
  constructor
  rw [familyFrontProbability, Measure.smul_apply, smul_eq_mul,
    Measure.map_apply (measurable_slopeSpacetimePoint b hb) MeasurableSet.univ,
    preimage_univ, ← univ_prod_univ, Measure.prod_prod,
    Measure.restrict_apply_univ, Real.volume_Icc]
  have hL : ENNReal.ofReal (v - u) ≠ 0 := (ENNReal.ofReal_pos.mpr (sub_pos.mpr huv)).ne'
  calc
    _ = ((ENNReal.ofReal (v - u))⁻¹ * ENNReal.ofReal (v - u)) *
        (((Measure.sum σ) univ)⁻¹ * (Measure.sum σ) univ) := by ring
    _ = 1 := by rw [ENNReal.inv_mul_cancel hL ENNReal.ofReal_ne_top,
      ENNReal.inv_mul_cancel hq.ne' (measure_ne_top _ _), one_mul]

/-- The source mass cancels exactly after normalization. The coefficient is
uniform even when the total mass of the individual family tends to zero. -/
theorem familyFrontProbability_ball_le
    {n : ℕ} (σ : Fin n → Measure E3) [∀ i, IsFiniteMeasure (σ i)]
    (hq : 0 < (Measure.sum σ) univ)
    (b : E3 → E3) (hb : Measurable b) (c : Fin n → E3) (s₀ : Fin n → ℝ)
    (u v ε r g K d : ℝ) (y : E3) (t : ℝ) (C : ℝ≥0∞)
    (hbush : ∀ i, ∀ᵐ a ∂σ i, ‖b a + s₀ i • a - c i‖ ≤ ε)
    (hr : 0 < r) (hε : ε ≤ r) (hg : 0 < g) (hK : 2 / g ≤ K) (hd : 0 ≤ d)
    (hgap : ∀ i, ∀ s ∈ Icc u v, g ≤ |s - s₀ i|)
    (hvector : ∀ s ∈ Icc u v,
      (∑' i, σ i (Metric.closedBall (vectorCenter (c i) y (s₀ i) s) (K * r))) ≤
        C * (Measure.sum σ) univ * ENNReal.ofReal (K * r) ^ d) :
    familyFrontProbability σ b u v (Metric.ball (spacetimeLift y t) r) ≤
      (2 * C * (ENNReal.ofReal (v - u))⁻¹ * (ENNReal.ofReal K) ^ d) *
        (ENNReal.ofReal r) ^ (d + 1) := by
  rw [familyFrontProbability, Measure.smul_apply, smul_eq_mul]
  have hK0 : 0 ≤ K := (div_nonneg (by norm_num) hg.le).trans hK
  have hr0 : ENNReal.ofReal r ≠ 0 := (ENNReal.ofReal_pos.mpr hr).ne'
  calc
    _ ≤ (ENNReal.ofReal (v - u))⁻¹ * ((Measure.sum σ) univ)⁻¹ *
        (ENNReal.ofReal (2 * r) *
          (C * (Measure.sum σ) univ * ENNReal.ofReal (K * r) ^ d)) := by
      gcongr
      exact family_physical_ball_mass_le σ b hb c s₀ u v ε r g K y t _
        hbush hr hε hg hK hgap hvector
    _ = (((Measure.sum σ) univ)⁻¹ * (Measure.sum σ) univ) *
        ((2 * C * (ENNReal.ofReal (v - u))⁻¹ * (ENNReal.ofReal K) ^ d) *
          ((ENNReal.ofReal r) ^ d * ENNReal.ofReal r)) := by
      rw [ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 2),
        ENNReal.ofReal_mul hK0, ENNReal.mul_rpow_of_nonneg _ _ hd]
      norm_num only [ENNReal.ofReal_ofNat]
      ring
    _ = _ := by
      rw [ENNReal.inv_mul_cancel hq.ne' (measure_ne_top _ _), one_mul,
        ENNReal.rpow_add d 1 hr0 ENNReal.ofReal_ne_top, ENNReal.rpow_one]

/-- The normalized family measure remains on the literal original front. -/
theorem familyFrontProbability_supported
    {n : ℕ} (σ : Fin n → Measure E3) [∀ i, IsFiniteMeasure (σ i)]
    (b : E3 → E3) (hb : Measurable b) (u v : ℝ)
    (ambient : Set MarkedLine) (hcompact : IsCompact ambient)
    (hsupport : ∀ i, ∀ᵐ a ∂σ i, ∀ s ∈ Icc u v,
      ActualSlopeSource.heightPoint (b a + s • a) s ∈ unitFront ambient) :
    familyFrontProbability σ b u v (unitFront ambient)ᶜ = 0 := by
  have hs := OriginalResidualCriterion.sourceFrontMeasure_supported
    (Measure.sum σ) b hb u v (unitFront ambient)
    (StickyKakeya4.IsCompact.unitFront hcompact).measurableSet
    (Measure.ae_sum_iff.mpr hsupport)
  rw [familyFrontProbability, Measure.smul_apply, smul_eq_mul]
  change _ * OriginalResidualCriterion.sourceFrontMeasure (Measure.sum σ) b u v
    (unitFront ambient)ᶜ = 0
  rw [hs, mul_zero]

/-- One radius-independent coefficient for all physical radii above the
family's lower scale. It has no dependence on the number of bushes or on q. -/
def familyFrostmanConstant (u v K d : ℝ) (C : ℝ≥0∞) : ℝ≥0∞ :=
  2 * C * (ENNReal.ofReal (v - u))⁻¹ * (ENNReal.ofReal K) ^ d +
    (ENNReal.ofReal K) ^ (d + 1)

theorem familyFrostmanConstant_ne_top (u v K d : ℝ) (C : ℝ≥0∞)
    (huv : u < v) (hd : 0 ≤ d) (hC : C ≠ ∞) :
    familyFrostmanConstant u v K d C ≠ ∞ := by
  have hL : ENNReal.ofReal (v - u) ≠ 0 := (ENNReal.ofReal_pos.mpr (sub_pos.mpr huv)).ne'
  have hd1 : 0 ≤ d + 1 := by linarith
  unfold familyFrostmanConstant
  finiteness

/-- Original vector-family finite-scale Frostman estimate. Small physical
balls use their synchronized moving caps; large balls use probability mass.
The total source mass cancels, so only its positivity is required. -/
theorem familyFrontProbability_finite_scale_bound
    {n : ℕ} (σ : Fin n → Measure E3) [∀ i, IsFiniteMeasure (σ i)]
    (hq : 0 < (Measure.sum σ) univ)
    (b : E3 → E3) (hb : Measurable b) (c : Fin n → E3) (s₀ : Fin n → ℝ)
    (u v ε ρ g K d : ℝ) (C : ℝ≥0∞)
    (huv : u < v) (hε : ε ≤ ρ) (hg : 0 < g) (hK : 2 / g ≤ K) (hK1 : 1 ≤ K)
    (hd : 0 ≤ d)
    (hbush : ∀ i, ∀ᵐ a ∂σ i, ‖b a + s₀ i • a - c i‖ ≤ ε)
    (hgap : ∀ i, ∀ s ∈ Icc u v, g ≤ |s - s₀ i|)
    (hvector : ∀ (y : E3) (s : ℝ), s ∈ Icc u v → ∀ R : ℝ, ρ ≤ R → R ≤ 1 →
      (∑' i, σ i (Metric.closedBall (vectorCenter (c i) y (s₀ i) s) R)) ≤
        C * (Measure.sum σ) univ * ENNReal.ofReal R ^ d)
    (x : E4) (r : ℝ) (hr : 0 < r) (hρr : ρ ≤ r) :
    familyFrontProbability σ b u v (Metric.ball x r) ≤
      familyFrostmanConstant u v K d C * (ENNReal.ofReal r) ^ (d + 1) := by
  have hK0 : 0 ≤ K := zero_le_one.trans hK1
  have hrr : r ≤ K * r := by nlinarith
  by_cases hsmall : K * r ≤ 1
  · rw [← spacetimeLift_horizontalProjection x]
    have hbound := familyFrontProbability_ball_le σ hq b hb c s₀
      u v ε r g K d (horizontalProjection x) (x (3 : Fin 4)) C
      hbush hr (hε.trans hρr) hg hK hd hgap
      (fun s hs => hvector (horizontalProjection x) s hs (K * r) (hρr.trans hrr) hsmall)
    apply hbound.trans
    unfold familyFrostmanConstant
    rw [add_mul]
    exact le_add_right le_rfl
  · letI := familyFrontProbability_isProbability σ hq b hb u v huv
    have hkr : (1 : ℝ≥0∞) ≤ ENNReal.ofReal K * ENNReal.ofReal r := by
      rw [← ENNReal.ofReal_mul hK0, ← ENNReal.ofReal_one]
      exact ENNReal.ofReal_le_ofReal (le_of_lt (lt_of_not_ge hsmall))
    have hp : (1 : ℝ≥0∞) ≤ (ENNReal.ofReal K * ENNReal.ofReal r) ^ (d + 1) := by
      simpa using (ENNReal.rpow_le_rpow hkr (by linarith : 0 ≤ d + 1))
    calc
      _ ≤ 1 := (measure_mono (subset_univ _)).trans_eq (measure_univ)
      _ ≤ (ENNReal.ofReal K) ^ (d + 1) * (ENNReal.ofReal r) ^ (d + 1) := by
        simpa [ENNReal.mul_rpow_of_nonneg _ _ (by linarith : 0 ≤ d + 1)] using hp
      _ ≤ _ := by
        unfold familyFrostmanConstant
        rw [add_mul]
        exact le_add_left le_rfl

end StickyKakeya4.VectorBushFrostman
