import Theorems.Thm_StickyKakeya4_native_endpoint_parent_bounds

#print axioms NativeEndpointParentBounds.one_le_multiplicity
#print axioms NativeEndpointParentBounds.multiplicity_le_tube_card
#print axioms NativeEndpointParentBounds.active_descendants_card_le
#print axioms NativeEndpointParentBounds.old_parent_upper_from_children
#print axioms NativeEndpointParentBounds.localScale_mono
#print axioms NativeEndpointParentBounds.old_parent_power_upper_from_children
#print axioms NativeEndpointParentBounds.old_parent_geometric_upper
#print axioms NativeEndpointParentBounds.inverse_relative_scale
#print axioms NativeEndpointParentBounds.localScale_inverse_remaining
#print axioms NativeEndpointParentBounds.localScale_le_one
#print axioms NativeEndpointParentBounds.local_negative_power_le_remaining
#print axioms NativeEndpointParentBounds.old_parent_dyadic_upper
#print axioms NativeEndpointParentBounds.one_le_full_multiplicity
