import Theorems.Thm_StickyKakeya4_native_last_menu_shading_size
import Theorems.Thm_StickyKakeya4_native_two_stage_transverse_tuples
import Theorems.Thm_StickyKakeya4_native_two_stage_plane_rank
import Theorems.Thm_StickyKakeya4_native_middle_two_scale_balance
import Theorems.Thm_StickyKakeya4_native_two_scale_boundary_balance
import Theorems.Thm_StickyKakeya4_native_rank_one_source_cutoff

set_option autoImplicit false
#print axioms NativeLastMenuShadingSize.absorb_global_count_and_volume
#print axioms NativeLastMenuShadingSize.coefficient_power_lower
#print axioms NativeLastMenuShadingSize.rowCells_eq_rows
#print axioms NativeLastMenuShadingSize.rowCells_volume
#print axioms NativeLastMenuShadingSize.row_volume_bounds_of_global_count
#print axioms NativeLastMenuShadingSize.upperDepth_scale_lower
#print axioms NativeLastMenuShadingSize.window_core_global_row_bounds
#print axioms NativeMiddleTwoScaleBalance.middle_pair_bounds
#print axioms NativeRankOneSourceCutoff.exists_source_cutoff
#print axioms NativeTwoScaleBoundaryBalance.all_pair_bounds
#print axioms NativeTwoScaleBoundaryBalance.boundary_pair_bounds
#print axioms NativeTwoScaleBoundaryBalance.depthPower_mono
#print axioms NativeTwoStagePlaneRank.point_plane_rank_eq
#print axioms NativeTwoStagePlaneRank.previous_rank_menu_plane_rank
#print axioms NativeTwoStageTransverseTuples.point_near_le_half
#print axioms NativeTwoStageTransverseTuples.point_transverse_chains
#print axioms NativeTwoStageTransverseTuples.previous_rank_menu_transverse_chains
#print axioms NativeTwoStageTransverseTuples.unit_chainMass_eq_card
#print axioms NativeTwoStageTransverseTuples.unit_mass_eq_card
