import Theorems.Thm_StickyKakeya4_native_joint_spatial_geometry
import Theorems.Thm_StickyKakeya4_native_matched_shadow_configured_source
import Theorems.Thm_StickyKakeya4_native_matched_shadow_configured_output
import Theorems.Thm_StickyKakeya4_native_matched_shadow_mass
import Theorems.Thm_StickyKakeya4_native_actual_fine_weighted_source_selection
set_option autoImplicit false
#print axioms NativeJointSpatialGeometry.coarse_xy_old_dist
#print axioms NativeJointSpatialGeometry.physical_neighbor
#print axioms NativeJointSpatialGeometry.physical_fiber_card
#print axioms NativeJointSpatialGeometry.physical_image_card
#print axioms NativeMatchedShadowConfiguredSource.actual_inverse_image_bounds
#print axioms NativeMatchedShadowConfiguredSource.actual_image_bounds
#print axioms NativeMatchedShadowConfiguredOutput.actual_inverse_output_image_bounds
#print axioms NativeMatchedShadowConfiguredOutput.actual_output_image_bounds
#print axioms NativeMatchedShadowMass.core_mass_le_full
#print axioms NativeMatchedShadowMass.full_pair_mass
#print axioms NativeMatchedShadowMass.mixed_full_pair_mass
#print axioms NativeActualFineWeightedSourceSelection.exists_same_Q_source
