import Theorems.Thm_StickyKakeya4_native_same_fine_parent_packet
import Theorems.Thm_StickyKakeya4_native_actual_query_rank_configuration
import Theorems.Thm_StickyKakeya4_native_refined_short_row_density

set_option autoImplicit false
#print axioms NativeActualQueryRankConfiguration.HasQuerySecondStageCore
#print axioms NativeActualQueryRankConfiguration.decode_second_stage_queries
#print axioms NativeActualQueryRankConfiguration.exists_actual_query_rank_configuration
#print axioms NativeActualQueryRankConfiguration.grainDepth_strict_step
#print axioms NativeActualQueryRankConfiguration.select_grain_second_stage
#print axioms NativeActualQueryRankConfiguration.stopping_depth_ge
#print axioms NativeActualQueryRankConfiguration.stopping_depth_six
#print axioms NativeActualQueryRankConfiguration.stopping_physical_scale
#print axioms NativeRefinedShortRowDensity.count_lower_of_partition
#print axioms NativeRefinedShortRowDensity.installed_children_card_bound
#print axioms NativeRefinedShortRowDensity.installed_rowChildren_comparable
#print axioms NativeRefinedShortRowDensity.queried_children_card_bound
#print axioms NativeRefinedShortRowDensity.queried_rowChildren_comparable
#print axioms NativeRefinedShortRowDensity.queried_short_row_lower
#print axioms NativeRefinedShortRowDensity.rowChildren_card_sum
#print axioms NativeRefinedShortRowDensity.row_card_le_children
#print axioms NativeRefinedShortRowDensity.short_cell_cost
#print axioms NativeRefinedShortRowDensity.volume_constant_bound
#print axioms NativeSameFineParentPacket.same_fine_parent_cell_packet
#print axioms NativeSameFineParentPacket.same_fine_parent_quadratic_packet
#print axioms NativeSameFineParentPacket.same_parent_displacement_error
#print axioms NativeSameFineParentPacket.tube_height_from_chart_shift
