import Theorems.Thm_StickyKakeya4_native_actual_query_rank_configuration

#print axioms NativeActualQueryRankConfiguration.HasQuerySecondStageCore
#print axioms NativeActualQueryRankConfiguration.decode_second_stage_queries
#print axioms NativeActualQueryRankConfiguration.stopping_depth_ge
#print axioms NativeActualQueryRankConfiguration.grainDepth_strict_step
#print axioms NativeActualQueryRankConfiguration.stopping_depth_six
#print axioms NativeActualQueryRankConfiguration.stopping_physical_scale
#print axioms NativeActualQueryRankConfiguration.exists_actual_query_rank_configuration
#print axioms NativeActualQueryRankConfiguration.select_grain_second_stage
