import Theorems.Thm_StickyKakeya4_native_intermediate_parent_population
set_option autoImplicit false
#print axioms NativeIntermediateParentPopulation.parent_from_ancestor
#print axioms NativeIntermediateParentPopulation.old_fiber_card_le_current
#print axioms NativeIntermediateParentPopulation.intermediate_dyadic
#print axioms NativeIntermediateParentPopulation.actual_population_lower
#print axioms NativeIntermediateParentPopulation.actual_population_upper
#print axioms NativeIntermediateParentPopulation.intermediateCells
#print axioms NativeIntermediateParentPopulation.intermediate_common_mesh
#print axioms NativeIntermediateParentPopulation.intermediate_common_height
#print axioms NativeIntermediateParentPopulation.second_source_AD
#print axioms NativeIntermediateParentPopulation.second_source_CW
#print axioms NativeIntermediateParentPopulation.second_source_geometry
#print axioms NativeIntermediateParentPopulation.second_parent_normalized_count
#print axioms NativeIntermediateParentPopulation.second_source_density_from_count
