import Theorems.Thm_StickyKakeya4_native_shading_independent_representatives

#print axioms NativeShadingIndependentRepresentatives.chooseRepresentative
#print axioms NativeShadingIndependentRepresentatives.chooseRepresentative_eq_canonical
#print axioms NativeShadingIndependentRepresentatives.chooseRepresentative_eq_of_geometry
#print axioms NativeShadingIndependentRepresentatives.relativeRepresentative
#print axioms NativeShadingIndependentRepresentatives.relativeRepresentative_eq_canonical
