import Theorems.Thm_StickyKakeya4_native_relative_parent_profiles
#print axioms NativeRelativeParentProfiles.relativeAtom
#print axioms NativeRelativeParentProfiles.relativeParents
#print axioms NativeRelativeParentProfiles.original_atom_in_parent
#print axioms NativeRelativeParentProfiles.relative_population_bounds
#print axioms NativeRelativeParentProfiles.dyadic_relative_population
#print axioms NativeRelativeParentProfiles.source_parentLabel
#print axioms NativeRelativeParentProfiles.source_parent_population
#print axioms NativeRelativeParentProfiles.source_parents_eq
#print axioms NativeRelativeParentProfiles.relative_population_sum
#print axioms NativeRelativeParentProfiles.dyadic_relative_parent_count
#print axioms NativeRelativeParentProfiles.source_dyadic_population
#print axioms NativeRelativeParentProfiles.source_dyadic_population_power
#print axioms NativeRelativeParentProfiles.HasRelativeProfile
#print axioms NativeRelativeParentProfiles.source_relative_profile
#print axioms NativeRelativeParentProfiles.compact_original_scheduled_native_relative_profiles
