import Theorems.Thm_StickyKakeya4_native_fixed_menu_slice_ad
import Theorems.Thm_StickyKakeya4_native_horizontal_menu_scale_cost
import Theorems.Thm_StickyKakeya4_native_realized_slice_geometry
import Theorems.Thm_StickyKakeya4_native_slice_ad_constant
import Theorems.Thm_StickyKakeya4_native_reference_slice_ad
import Theorems.Thm_StickyKakeya4_native_translated_grain_height_overlap
import Theorems.Thm_StickyKakeya4_native_translated_grain_height_selection
import Theorems.Thm_StickyKakeya4_native_translated_grain_height_fibers
import Theorems.Thm_StickyKakeya4_native_translated_grain_height_metric
import Theorems.Thm_StickyKakeya4_native_translated_grain_height_chart

set_option autoImplicit false
#print axioms NativeFixedMenuSliceAD.fixed_menu_reference_all_radius_bounds
#print axioms NativeFixedMenuSliceAD.menu_gap_cost
#print axioms NativeFixedMenuSliceAD.menu_gap_power_cost
#print axioms NativeHorizontalMenuScaleCost.intrinsic_gap_cost
#print axioms NativeHorizontalMenuScaleCost.intrinsic_gap_power_cost
#print axioms NativeHorizontalMenuScaleCost.parent_scale_dyadic_span
#print axioms NativeRealizedSliceGeometry.floor_center_error
#print axioms NativeRealizedSliceGeometry.horizontalMesh_le_eighth
#print axioms NativeRealizedSliceGeometry.realized_column_error
#print axioms NativeRealizedSliceGeometry.realized_point_coordinate_bound
#print axioms NativeRealizedSliceGeometry.realized_slice_geometry
#print axioms NativeRealizedSliceGeometry.realized_slice_separated
#print axioms NativeReferenceSliceAD.fixed_menu_reference_slice_AD
#print axioms NativeSliceADConstant.ADBounds_of_asymmetric_counts
#print axioms NativeSliceADConstant.constant
#print axioms NativeSliceADConstant.one_le_constant
#print axioms NativeTranslatedGrainHeightChart.mapped_chart_metric
#print axioms NativeTranslatedGrainHeightChart.raw_chart_distance
#print axioms NativeTranslatedGrainHeightFibers.every_reference_fiber_density_cross
#print axioms NativeTranslatedGrainHeightFibers.mixed_X_subset_referenceX
#print axioms NativeTranslatedGrainHeightFibers.mixed_reference_key_eq
#print axioms NativeTranslatedGrainHeightFibers.referenceKey
#print axioms NativeTranslatedGrainHeightFibers.referenceKey_column
#print axioms NativeTranslatedGrainHeightFibers.referenceX
#print axioms NativeTranslatedGrainHeightMetric.mapped
#print axioms NativeTranslatedGrainHeightMetric.mapped_metric
#print axioms NativeTranslatedGrainHeightMetric.mapped_norm_on_image
#print axioms NativeTranslatedGrainHeightMetric.mapped_readback
#print axioms NativeTranslatedGrainHeightMetric.rawAt
#print axioms NativeTranslatedGrainHeightMetric.rawAt_readback
#print axioms NativeTranslatedGrainHeightMetric.referenceHeight
#print axioms NativeTranslatedGrainHeightMetric.referenceHeight_distance
#print axioms NativeTranslatedGrainHeightOverlap.actual_height_distance
#print axioms NativeTranslatedGrainHeightOverlap.actual_height_metric
#print axioms NativeTranslatedGrainHeightOverlap.actual_raw_cell_card
#print axioms NativeTranslatedGrainHeightOverlap.actual_translated_cell_card
#print axioms NativeTranslatedGrainHeightOverlap.floor_shift_carry
#print axioms NativeTranslatedGrainHeightOverlap.floor_shift_distance
#print axioms NativeTranslatedGrainHeightOverlap.rawHeight
#print axioms NativeTranslatedGrainHeightOverlap.rawHeight_readback
#print axioms NativeTranslatedGrainHeightOverlap.raw_cell_translated_card
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight_column
#print axioms NativeTranslatedGrainHeightOverlap.translatedHeight_readback
#print axioms NativeTranslatedGrainHeightOverlap.translated_cell_raw_card
#print axioms NativeTranslatedGrainHeightOverlap.two_integer_card
#print axioms NativeTranslatedGrainHeightSelection.card_retention_four
#print axioms NativeTranslatedGrainHeightSelection.first
#print axioms NativeTranslatedGrainHeightSelection.first_card_retention
#print axioms NativeTranslatedGrainHeightSelection.first_menu
#print axioms NativeTranslatedGrainHeightSelection.first_subset
#print axioms NativeTranslatedGrainHeightSelection.first_translated_constant
#print axioms NativeTranslatedGrainHeightSelection.hereditary_alignment
#print axioms NativeTranslatedGrainHeightSelection.rawHeight_of_mixed_eq
#print axioms NativeTranslatedGrainHeightSelection.second
#print axioms NativeTranslatedGrainHeightSelection.second_card_retention
#print axioms NativeTranslatedGrainHeightSelection.second_menu
#print axioms NativeTranslatedGrainHeightSelection.second_saturated
#print axioms NativeTranslatedGrainHeightSelection.second_subset
#print axioms NativeTranslatedGrainHeightSelection.second_subset_first
#print axioms NativeTranslatedGrainHeightSelection.selected_uniform
#print axioms NativeTranslatedGrainHeightSelection.surviving_grain_eq
#print axioms NativeTranslatedGrainHeightSelection.surviving_local_retention
#print axioms NativeTranslatedGrainHeightSelection.translated_determines_raw
