import Theorems.Thm_StickyKakeya4_native_anisotropic_slice_labels
import Theorems.Thm_StickyKakeya4_native_combined_parent_profiles
import Theorems.Thm_StickyKakeya4_native_grain_quotient_fibers
import Theorems.Thm_StickyKakeya4_native_active_phase_population

set_option autoImplicit false
#print axioms NativeActivePhasePopulation.activePhases
#print axioms NativeActivePhasePopulation.activePhases_subset
#print axioms NativeActivePhasePopulation.active_phase_population
#print axioms NativeActivePhasePopulation.parent_incidence_capacity
#print axioms NativeActivePhasePopulation.parent_retained_eq
#print axioms NativeActivePhasePopulation.retained_incidence_capacity
#print axioms NativeActivePhasePopulation.rowConstant
#print axioms NativeActivePhasePopulation.rowConstant_pos
#print axioms NativeAnisotropicSliceLabels.caller_column_uniformities
#print axioms NativeAnisotropicSliceLabels.columnLabel_horizontalCoarsen
#print axioms NativeAnisotropicSliceLabels.horizontalCoarsen
#print axioms NativeAnisotropicSliceLabels.horizontalCoarsen_height
#print axioms NativeAnisotropicSliceLabels.sliceClass
#print axioms NativeAnisotropicSliceLabels.sliceClass_height
#print axioms NativeAnisotropicSliceLabels.sliceClass_point_eq_column
#print axioms NativeAnisotropicSliceLabels.slicePoint
#print axioms NativeAnisotropicSliceLabels.sliceRelations
#print axioms NativeAnisotropicSliceLabels.sliceRelations_refl
#print axioms NativeAnisotropicSliceLabels.sliceRelations_symm
#print axioms NativeCombinedParentProfiles.HasParentProfiles
#print axioms NativeCombinedParentProfiles.horizontal_window
#print axioms NativeCombinedParentProfiles.source_parent_profiles
#print axioms NativeGrainQuotientFibers.density_transfer
#print axioms NativeGrainQuotientFibers.diameter_div_physicalMesh
#print axioms NativeGrainQuotientFibers.exists_mixed_dense_fiber
#print axioms NativeGrainQuotientFibers.fiber
#print axioms NativeGrainQuotientFibers.mixed_height_count
#print axioms NativeGrainQuotientFibers.phase_diameter_div_physicalMesh
#print axioms NativeGrainQuotientFibers.physicalMesh
#print axioms NativeGrainQuotientFibers.physicalMesh_pos
