import Theorems.Thm_StickyKakeya4_native_original_parent_density_core
set_option autoImplicit false
#print axioms NativeOriginalParentDensityCore.retained
#print axioms NativeOriginalParentDensityCore.parentEdges
#print axioms NativeOriginalParentDensityCore.retained_card
#print axioms NativeOriginalParentDensityCore.retained_shading_eq
#print axioms NativeOriginalParentDensityCore.original_card_le_twice_retained
#print axioms NativeOriginalParentDensityCore.unit_degree_eq_parentEdges
#print axioms NativeOriginalParentDensityCore.parent_population_product
#print axioms NativeOriginalParentDensityCore.cardinal_le_parent_fiber
#print axioms NativeOriginalParentDensityCore.parent_average_density
#print axioms NativeOriginalParentDensityCore.factor
#print axioms NativeOriginalParentDensityCore.coreRadix
#print axioms NativeOriginalParentDensityCore.IsCore
#print axioms NativeOriginalParentDensityCore.exists_retained_parent_density_core
#print axioms NativeOriginalParentDensityCore.compact_original_scheduled_parent_density_core
