import Theorems.Thm_StickyKakeya4_native_retained_slice_all_radii
import Theorems.Thm_StickyKakeya4_native_retained_slice_grain_ad
import Theorems.Thm_StickyKakeya4_native_prescribed_parent_graph_configuration
import Theorems.Thm_StickyKakeya4_native_prescribed_parent_graph_data
import Theorems.Thm_StickyKakeya4_native_retained_column_pair_core

set_option autoImplicit false
#print axioms NativePrescribedParentGraphConfiguration.CurveParentFinalCleanupData
#print axioms NativePrescribedParentGraphConfiguration.HasCurveParentRetainedHistory
#print axioms NativePrescribedParentGraphConfiguration.HasCurveParentStage
#print axioms NativePrescribedParentGraphConfiguration.exists_prescribed_parent_graph_configuration
#print axioms NativePrescribedParentGraphConfiguration.half_depth_eq_depth
#print axioms NativePrescribedParentGraphConfiguration.middleSelected
#print axioms NativePrescribedParentGraphConfiguration.middle_selected_depth
#print axioms NativePrescribedParentGraphConfiguration.stage_with_parent_graph
#print axioms NativePrescribedParentGraphData.HasCurveParentProfiles
#print axioms NativePrescribedParentGraphData.HasParentHeightCore
#print axioms NativePrescribedParentGraphData.attach_prescribed_parent_graph
#print axioms NativePrescribedParentGraphData.curve_parent_profiles_forget
#print axioms NativeRetainedColumnPairCore.caller_parent_pair_uniformity
#print axioms NativeRetainedColumnPairCore.relations
#print axioms NativeRetainedColumnPairCore.relations_refl
#print axioms NativeRetainedColumnPairCore.relations_symm
#print axioms NativeRetainedColumnPairCore.retained_pair_card
#print axioms NativeRetainedColumnPairCore.retained_pair_multiplicity
#print axioms NativeRetainedColumnPairCore.taggedPair
#print axioms NativeRetainedSliceAllRadii.retained_all_radius_bounds
#print axioms NativeRetainedSliceGrainAD.exists_actual_slice_grain_AD
#print axioms NativeRetainedSliceGrainAD.retained_slice_ADBounds
