import Theorems.Thm_StickyKakeya4_native_cubical_diameter_count
import Theorems.Thm_StickyKakeya4_native_original_tuple_parent_interpolation
import Theorems.Thm_StickyKakeya4_native_reference_hereditary_upper

set_option autoImplicit false
#print axioms NativeCubicalDiameterCount.capacity
#print axioms NativeCubicalDiameterCount.capacity_le_real
#print axioms NativeCubicalDiameterCount.card_le_of_center_diameter
#print axioms NativeCubicalDiameterCount.card_le_real_of_center_diameter
#print axioms NativeCubicalDiameterCount.coordinate_gap_le
#print axioms NativeCubicalDiameterCount.indexBox
#print axioms NativeCubicalDiameterCount.indexBox_card
#print axioms NativeCubicalDiameterCount.mem_indexBox_of_dist
#print axioms NativeOriginalTupleParentInterpolation.coarse_menu_lower_of_ancestor
#print axioms NativeOriginalTupleParentInterpolation.point_parent_fiber_subset_ancestor
#print axioms NativeOriginalTupleParentInterpolation.point_parent_fiber_upper_of_ancestor
#print axioms NativeReferenceHereditaryUpper.from_master_reference
