import Theorems.Thm_StickyKakeya4_native_actual_XY_budget_comparison
import Theorems.Thm_StickyKakeya4_native_actual_post_graph_XY
import Theorems.Thm_StickyKakeya4_native_angular_ball_cell_cover
import Theorems.Thm_StickyKakeya4_native_candidate_graph_configuration
import Theorems.Thm_StickyKakeya4_native_common_phi_source
import Theorems.Thm_StickyKakeya4_native_extra_graph_configuration
import Theorems.Thm_StickyKakeya4_native_generic_graph_rank
import Theorems.Thm_StickyKakeya4_native_rich_angular_image_lower

set_option autoImplicit false
#print axioms NativeActualPostGraphXY.attach_actual_post_graph_XY
#print axioms NativeActualXYBudgetComparison.actualXYConstant
#print axioms NativeActualXYBudgetComparison.base_XY_le_retained
#print axioms NativeAngularBallCellCover.angular_ball_cell_card
#print axioms NativeAngularBallCellCover.angular_ball_count
#print axioms NativeCandidateGraphConfiguration.exists_candidate_graph_configuration
#print axioms NativeCommonPhiSource.angularCell_readback
#print axioms NativeCommonPhiSource.cellThickness
#print axioms NativeCommonPhiSource.cellThickness_le
#print axioms NativeCommonPhiSource.cellThickness_nonneg
#print axioms NativeCommonPhiSource.coherent_cell_projection
#print axioms NativeCommonPhiSource.coherent_cell_residual
#print axioms NativeCommonPhiSource.localSlope_distance
#print axioms NativeExtraGraphConfiguration.exists_extra_graph_configuration
#print axioms NativeGenericGraphRank.graph_rank_of_query
#print axioms NativeRichAngularImageLower.point_fiber_le_angular_image
#print axioms NativeRichAngularImageLower.rich_class_angular_lower
