import Theorems.Thm_StickyKakeya4_native_actual_profile_coarse_admission
import Theorems.Thm_StickyKakeya4_native_actual_configured_cell_selection
import Theorems.Thm_StickyKakeya4_native_configured_output_pairs
import Theorems.Thm_StickyKakeya4_native_actual_configured_height_caps
set_option autoImplicit false
#print axioms NativeActualProfileCoarseAdmission.exists_same_reference_admission_of_actual_profile
#print axioms NativeActualConfiguredCellSelection.select_actual_edges
#print axioms NativeConfiguredIncidenceFibers.localIndex
#print axioms NativeConfiguredIncidenceFibers.localIndex_readback
#print axioms NativeConfiguredIncidenceFibers.outputTube
#print axioms NativeConfiguredIncidenceFibers.outputTube_readback
#print axioms NativeConfiguredIncidenceFibers.outputTube_eq_iff
#print axioms NativeConfiguredIncidenceFibers.outputPair_eq_iff
#print axioms NativeConfiguredIncidenceFibers.outputPair_image_card
#print axioms NativeConfiguredIncidenceFibers.outputPair_fiber_eq
#print axioms NativeConfiguredIncidenceFibers.outputTube_ancestor_readback
#print axioms NativeActualConfiguredHeightCaps.actual_height_image
#print axioms NativeActualConfiguredHeightCaps.actual_height_separation
#print axioms NativeActualConfiguredHeightCaps.actual_height_interval_cap
