import Theorems.Thm_StickyKakeya4_native_parent_horizontal_query_menu
import Theorems.Thm_StickyKakeya4_native_parent_height_alignment
import Theorems.Thm_StickyKakeya4_native_horizontal_graph_coordinates

set_option autoImplicit false
#print axioms NativeHorizontalGraphCoordinates.coordinate_graph_readback
#print axioms NativeHorizontalGraphCoordinates.domainBasis
#print axioms NativeHorizontalGraphCoordinates.horizontalGraph
#print axioms NativeHorizontalGraphCoordinates.horizontalGraph_val
#print axioms NativeHorizontalGraphCoordinates.horizontal_finrank
#print axioms NativeHorizontalGraphCoordinates.normalBasis
#print axioms NativeHorizontalGraphCoordinates.normalSpace
#print axioms NativeHorizontalGraphCoordinates.normalSpace_finrank
#print axioms NativeHorizontalGraphCoordinates.slopeMap
#print axioms NativeHorizontalGraphCoordinates.slopeMap_norm
#print axioms NativeHorizontalGraphCoordinates.slopeMap_variation
#print axioms NativeHorizontalGraphCoordinates.slopeMatrix
#print axioms NativeHorizontalGraphCoordinates.slopeMatrix_action
#print axioms NativeHorizontalGraphCoordinates.slopeMatrix_entry
#print axioms NativeHorizontalGraphCoordinates.slopeMatrix_norm
#print axioms NativeHorizontalGraphCoordinates.slopeMatrix_variation
#print axioms NativeParentHeightAlignment.cut_heightNode_readback
#print axioms NativeParentHeightAlignment.exists_height_aligned_nodes
#print axioms NativeParentHeightAlignment.fineNode
#print axioms NativeParentHeightAlignment.fine_heightNode_readback
#print axioms NativeParentHeightAlignment.heightNode
#print axioms NativeParentHeightAlignment.heightNode_occupied
#print axioms NativeParentHeightAlignment.heightNode_readback
#print axioms NativeParentHeightAlignment.height_plane_readback
#print axioms NativeParentHeightAlignment.mem_nodeCut
#print axioms NativeParentHeightAlignment.nodeCut
#print axioms NativeParentHeightAlignment.nodeCut_card
#print axioms NativeParentHeightAlignment.nodeCut_mixed_fiber_eq
#print axioms NativeParentHeightAlignment.nodeCut_mixed_vertices_eq
#print axioms NativeParentHeightAlignment.nodeCut_saturated
#print axioms NativeParentHeightAlignment.nodeCut_subset
#print axioms NativeParentHeightAlignment.nodeWeight
#print axioms NativeParentHeightAlignment.nodeWeight_total
#print axioms NativeParentHeightAlignment.spatialAncestor_self
#print axioms NativeParentHorizontalQueryMenu.relations
#print axioms NativeParentHorizontalQueryMenu.relations_refl
#print axioms NativeParentHorizontalQueryMenu.relations_symm
#print axioms NativeParentHorizontalQueryMenu.size
#print axioms NativeParentHorizontalQueryMenu.uniformities
