import Theorems.Thm_StickyKakeya4_native_raw_incidence_height_population_draft_2123
set_option autoImplicit false
#print axioms NativeRawIncidenceHeightPopulationDraft2123.original_height_row_card
#print axioms NativeRawIncidenceHeightPopulationDraft2123.rounded_height_readback
#print axioms NativeRawIncidenceHeightPopulationDraft2123.double_label_height
#print axioms NativeRawIncidenceHeightPopulationDraft2123.double_front_time_error
#print axioms NativeRawIncidenceHeightPopulationDraft2123.integer_time_interval_card
#print axioms NativeRawIncidenceHeightPopulationDraft2123.coarse_shadow_original_height_count
#print axioms NativeRawIncidenceHeightPopulationDraft2123.final_time_original_height_count
#print axioms NativeRawIncidenceHeightPopulationDraft2123.relative_atom_population_upper
#print axioms NativeRawIncidenceHeightPopulationDraft2123.original_height_atom_capacity
#print axioms NativeRawIncidenceHeightPopulationDraft2123.coarse_shadow_original_incidence_capacity
#print axioms NativeRawIncidenceHeightPopulationDraft2123.raw_atom_mass_upper
#print axioms NativeRawIncidenceHeightPopulationDraft2123.actual_relative_raw_capacities
