import Theorems.Thm_StickyKakeya4_native_simultaneous_weighted_grain_core

#print axioms NativeSimultaneousWeightedGrainCore.classBudget
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_subset
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_mass
#print axioms NativeSimultaneousWeightedGrainCore.eraseFiber_budget
#print axioms NativeSimultaneousWeightedGrainCore.exists_simultaneous_dense_core
#print axioms NativeSimultaneousWeightedGrainCore.removed_mass_le
#print axioms NativeSimultaneousWeightedGrainCore.exists_simultaneous_dense_core_half
