import Theorems.Thm_StickyKakeya4_native_parent_horizontal_readback
import Theorems.Thm_StickyKakeya4_native_anisotropic_row_count_lower

set_option autoImplicit false
#print axioms NativeAnisotropicRowCountLower.chargeConstant
#print axioms NativeAnisotropicRowCountLower.image_row_count_lower
#print axioms NativeAnisotropicRowCountLower.parent_counts_of_actual_rows
#print axioms NativeAnisotropicRowCountLower.queried_parent_counts_lower
#print axioms NativeAnisotropicRowCountLower.shortEdges_subset_parent
#print axioms NativeParentHorizontalReadback.local_slope_difference
#print axioms NativeParentHorizontalReadback.physical_map_horizontal_difference
#print axioms NativeParentHorizontalReadback.physical_map_horizontal_infDist
